### ISSUE TITLE
Style the "Deploy" button more like a button and add help/description text

### ISSUE THREAD

**Issue by klonos** [uselagoon/lagoon#1013]
**Describe the bug**

It appears this "Deploy" button redoes the last deployment but it doesn't look like a button or has any descriptive text accompanying it.

**Expected behavior**

It would be best to change the style of this button that serves a major function, so people don't accidentally click it.

**Screenshots**

![image](https://user-images.githubusercontent.com/2423362/55367649-ca79fd80-5539-11e9-96d2-933736bf0893.png)

**Comment by rocketeerbkw** [comment]
We have a new design for the button and some descriptive text:

![Deployments](https://user-images.githubusercontent.com/92499/58355556-59b8d880-7e3a-11e9-9031-d423094b0e63.jpg)

Text suggestions are welcome. The button does not "redo the last deploy," it's a way to trigger a new deployment. It triggers the same process as making/pushing a new commit.

I can provide more detailed design files if anyone wants to take this on.

**Comment by Feng-Shui** [comment]
Would be good to prevent the button from being pressed multiple times.

**Comment by rocketeerbkw** [comment]
The backend already has logic to skip/cancel multiple deploys, so hitting the button a bunch of times should result in only one or two builds.

See #932

**Comment by mharley12345** [comment]
@Schnitzel  i would like to work on this issue.

**Comment by rocketeerbkw** [comment]
@mharley12345 thanks! This has already been addressed in #1165 though.

**Comment by Schnitzel** [comment]
@mharley12345 
thank you very much! and sorry I unfortunately didn't realize that there is a PR already... Sorry!
