### ISSUE TITLE
Create Step-by-Step Guide to Install & Maintain Lagoon

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1020]
Currently the Installation Guide of Lagoon is rather small: https://lagoon.readthedocs.io/en/latest/administering_lagoon/install/
Also there is no documentation on how to upgrade an already existing Lagoon.

This project idea covers:
- Creating a better Step-by-Step guide on how to Install a Lagoon, with possible known issues, edge cases, etc.
- Create a Step-by-Step guide on how to upgrade/maintain a previously installed Lagoon, with known issues, possible hurdles, best practices, etc.

**Comment by tobybellwood** [comment]
This is now better covered in the documentation, and being updated.
