### ISSUE TITLE
Create Lagoon Contributor Documentation

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1023]
The Documentation about how to get Lagoon running locally and how to contribute is rather sparse:
https://lagoon.readthedocs.io/en/latest/developing_lagoon/

They are a bit outdated and could overall get a lot of love:
- Step-by-Step Guide on how to get Lagoon running locally
- Common miss-conceptions about running Lagoon locally
- How to run tests locally
- How to create tests

**Comment by tobybellwood** [comment]
This is being updated more frequently in the documentation
