### ISSUE TITLE
Add possibility to define multiple repositories in `REPOSITORY_TO_UPDATE` 

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1025]
Some Lagoon users have custom base images and would like them to be updated in the `update-push-images.sh` of the docker-host as well, but currently this only supports one repo defined in the env variable:
https://github.com/amazeeio/lagoon/blob/67083de13be02fe77cb2bfcde3f38ca3df1411f7/images/docker-host/update-push-images.sh#L12

Therefore we would like to support multiple repositories (separated via a comma?) and then loop of this in the bash script.

**Comment by tobybellwood** [comment]
pipe them in the variable and grep -E should work?

`grep -E "repoA|repoB"`
