### ISSUE TITLE
S3 Link Redirect System

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1030]
This is a follow up for #999

Currently the link shown in the Lagoon UI is directly linking to S3.
With the work done in this ticket, the link will point to a Lagoon UI URL, which will create a redirect to the S3 bucket with a validity of 5 seconds.

**Comment by bomoko** [comment]
After a quick DX chat, we're questioning whether this will work for all cases (without having some kind of fallback functionality). Needs to be discussed in more depth.

The lagoon-cli might also complicate this.

**Comment by shreddedbacon** [comment]
Just because I saw this was recently updated. The ability to do [custom restore locations](https://docs.lagoon.sh/using-lagoon-advanced/environment-variables/#custom-restore-location) could also add some complications to the mix.

**Comment by tobybellwood** [comment]
Current status (for clarification) - the download link in the UI is valid for 5 minutes, is signed by the file host, and is available to anyone who has been shared that link.

**Comment by tobybellwood** [comment]
Proposed solution - reduce the timeout to 1 minute, but start the timer on the click of the download button instead of the page load.

**Comment by seanhamlin** [comment]
Some customers do use the direct S3 link to download the backup into a pod for example. So being able to access the raw signed URL would be ace. Having a 1 minute validity will be OK.

**Comment by rocketeerbkw** [comment]
Created follow up issues https://github.com/uselagoon/lagoon/issues/3367 https://github.com/uselagoon/lagoon-ui/issues/91 https://github.com/uselagoon/lagoon-ui/issues/92
