### ISSUE TITLE
Add documentation how the Drupal core statistic module can be used with the default Nginx-Drupal configuration

### ISSUE THREAD

**Issue by twerthmueller** [uselagoon/lagoon#1032]
We will use the Drupal core statistics module, but with the default Nginx config the request to the tracking endpoint /core/modules/statistics/statistics.php is denied (404).

This is related to the Nginx config (https://github.com/amazeeio/lagoon/blob/master/images/nginx-drupal/drupal.conf):
```
location ~* ^.+\.php$ {
    try_files /dev/null @drupal;
}
```
To solve the problem I defined a specific location rule and inject this as a location prepend config.

```
## Allow access to to the statistics endpoint
location ~* ^(/core/modules/statistics/statistics.php) {
      try_files /dev/null @php;
}
```
location_prepend_allow_statistics.conf: [location_prepend_allow_statistics.conf.txt](https://github.com/amazeeio/lagoon/files/3046717/location_prepend_allow_statistics.conf.txt)

And copy this during the Nginx container build (Dockerfile.nginx):
```
# Add specific drupal statistics module nginx configuration
COPY .lagoon/nginx/location_prepend_allow_statistics.conf /etc/nginx/conf.d/drupal/location_prepend_allow_statistics.conf
```

Dockerfile.nginx: [Dockerfile.nginx.txt](https://github.com/amazeeio/lagoon/files/3046746/Dockerfile.nginx.txt)

Maybe you can add this rule by default to the Drupal Nginx config or add this in the Lagoon documentation as an example how the Nginx config could be modified.

**Comment by tobybellwood** [comment]
@AlannaBurke to add to https://docs.lagoon.sh/lagoon/docker-images/nginx/nginx-drupal

**Comment by AlannaBurke** [comment]
Added to docs.
