### ISSUE TITLE
Lagoon UI deployments not always updating with OpenShift build status

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#1040]
Deployments in the lagoon ui for some environments show as running or new, even though the build in OpenShift may have failed or been cancelled.

**Expected behavior**
UI deployments should match the build status from OpenShift

**Comment by shreddedbacon** [comment]
It looks like the `openshiftbuilddeploymonitor` sometimes is unable to communicate with the api after looking through logs I found this right after a build was complete, so the deployment still displayed as running in the dashboard.
```
message:Could not update deployment <project> lagoon-1. Message: FetchError: network timeout at: http://api:3000/graphql
```
Looking at this block, if it fails to update the api it doesn't try again.
https://github.com/amazeeio/lagoon/blob/master/services/openshiftbuilddeploymonitor/src/index.js#L124-L145
Would it be possible to have it try again a few times before it fails, or put the message back into the queue to be processed again?

**Comment by tobybellwood** [comment]
In one of these situations, it looks like Openshift is sensible enough to ignore multiple repeated deploys via GraphQL - and simply actions the most recent - this will mean the previous builds are effectively skipped (and hence build-id/logs won't be available to return to Lagoon) - a more sensible behaviour for these skipped/superceded builds - where we are seeking an update for a buildid that doesn't exist, would be to mark them as superseded in the UI?

**Comment by shreddedbacon** [comment]
What I found was that the process that should update the dashboard is working as expected. But sometimes when it goes to update the dashboard, if the API is unavailable, it fails and you lose the result. It should re-attempt to update the API a few times, or add it to a queue to be reprocessed.

The build-id/logs are there. If I know the end state of a previous build (failed or complete) and update the API to the correct end state, the logs have typically shown up.

**Comment by tobybellwood** [comment]
This has been resolved with the implementation of lagoon-kbd
