### ISSUE TITLE
Task to create MR from config in an environment.

### ISSUE THREAD

**Issue by simesy** [uselagoon/lagoon#1044]
As a non-developer, I want to merge my config into master.

Scenario: I have a branch and I've edited some config in that environment. Say I create a new view, or a webform, or, whatever. My desire is to merge that config back to master.

This assumes all config changes to master are via deployments. A developer creates an environment for an editor. Then editor logs in and creates a webform. The editor then goes to the Tasks UI for that environment and selects "Create config merge request".

On running this task, a robot:

1. builds an environment from that branch
2. grabs the database
3. exports config
4. commits ./config directory
5. Creates MR back to to master

**Comment by simesy** [comment]
Additionally there could be some lagoon config similar to `config_ignore` syntax, that limits which config is commited. This way it minimises MR conflicts because of changes in other config that is deemed inappropriate to update in this way (would differ per site/platform I expect).

**Comment by tobybellwood** [comment]
Not a core Lagoon feature - but something that may be achievable via an advanced task https://docs.lagoon.sh/using-lagoon-advanced/custom-tasks/
