### ISSUE TITLE
Can't xdebug in php storm

### ISSUE THREAD

**Issue by Dirst** [uselagoon/lagoon#1046]
I can't xdebug in php storm. I run port listening and check a pair of breakpoints - one is on the first line of entry point file. App is stopped On the very first breakpoint, but when I proceed to the next breakpoint or next code line I don't get anything, breakpoints pointer dissapears. 

Any suggestions how to solve it?

**Comment by Schnitzel** [comment]
Hi @Dirst 
this sounds very much like an issue that the IDE has no understanding about the files on the server and in the IDE. In order for the IDE to be able to stop at any specific breakpoints it needs to understand which files are running in the PHP and how they match to the IDE. Usually this is described in the File Mapping, see: https://stackoverflow.com/questions/18315741/phpstorm-debugger-not-stopping-at-certain-breakpoints which explains it further and how to resolve it.

More things around this:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206334759-XDebug-stops-at-first-line-but-ignores-some-breakpoints-in-other-files
https://jasonrikard.com/148/xdebug-breakpoints-not-working-mamp-phpstorm/

**Comment by dasrecht** [comment]
closing due to inactivitiy - feel free to get in touch with us under http://amazeeio.rocket.chat
