### ISSUE TITLE
better docker-host pruning

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1051]

**Comment by dasrecht** [comment]
I'll follow 2 ideas:

- Prune should run with `-a -f` flags
- Making sure all exited pods are removed (they seem sometimes to prevent images from being pruned)

**Comment by dasrecht** [comment]
I wonder if we should do the -a -f pruning once a week
and a daily prune that also takes care of the exited pods.

or even making sure we only prune away images that are older than a week
currently testing:
> docker image prune -a --filter "until=168h"

**Comment by dasrecht** [comment]
The docker image prune with the filter works great. This way we could leverage regular pruning while ensuring caches within a week stay fresh and builds fast.
