### ISSUE TITLE
How to get to the UI

### ISSUE THREAD

**Issue by spuky** [uselagoon/lagoon#1057]
I am playing with lagoon testing a few things... got the development Environment running and started looking around.. taking notes of my pain points on the way to later help with documentation... 

I figured out how to get to the graphql api... and get auth... 

from the code I see there should be the UI I saw in videos... 

but going to.. http://localhost:3000/ gives me 
{"errors":[{"message":"Unauthorized - Bearer Token Required"}]}
when I provide that with a browser extension I still only get a json ok

Questions: 
1. Is there a login url 
2. do I need to have the customer first project stuff done first
3. how do I get to see the UI

Thanks for short answers...

**Comment by shreddedbacon** [comment]
You can access the ui at http://localhost:8888/ which will redirect you to keycloak to log in, you can log in with `lagoonadmin:lagoonadmin`

You do need to either change the ui service in `docker-compose.yaml` from `8888:3003` to `8888:3000` or add an env var for setting the ui to dev mode and restart the ui service
```
    environment:
      - NODE_ENV=dev
```
