### ISSUE TITLE
non-admin user cannot modify user account which is associated to same customer's projects

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#1058]
User A - associated with Customer A (customer has projects A, B, C, D, E)
User B - associated with Projects A, B, D

If User A attempts to modify the account of User B (add SSH key for example), they are presented with an "Unauthorized" error.

**Comment by twardnw** [comment]
Internally, see https://jira.amazeelabs.com/browse/VLAAN-112

This will likely change behavior when the RBAC is complete

**Comment by Schnitzel** [comment]
@twardnw 
Can you check/verify this with Lagoon RBAC again?

**Comment by twardnw** [comment]
Fixed as far as I've tested
