### ISSUE TITLE
Start testing against OpenShift 3.10 and 3.11

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1061]
as we're planning to update our clusters to 3.11 we should start automated testing against all three versions we're currently running:
- 3.9
- 3.10
- 3.11

**Comment by alauzon** [comment]
Can Lagoon work with the OKD version of OpenShift?

**Comment by Schnitzel** [comment]
@alauzon 
yes, that's the version we use for automated testing (via minishift)
