### ISSUE TITLE
Implement Galera Master-Master Replication

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#107]

**Comment by Schnitzel** [comment]
@rtprio 
can you write your current status in here? @desdury would like to help out :)

**Comment by rtprio** [comment]
I was able to get a cluster up in a stateful set following the pattern of: https://github.com/adfinis-sygroup/openshift-mariadb-galera

that's in: https://github.com/amazeeio/lagoon/blob/maria-cluster/docker-images/oc-build-deploy/openshift-templates/mariadb-cluster/template.yml

It had the shortcomings of not being the default password, and based on centos. 
The cluster properly established, but I did not fully test the stack.

To resume this work:

- [ ] adapt config and stateful set options from adfinis-sygroup to our centos7-mariadb10-drupal
- [ ] refactor and reapply #32 .
