### ISSUE TITLE
Timings in build logs

### ISSUE THREAD

**Issue by Leksat** [uselagoon/lagoon#1082]
Sometimes builds get long time. To be able to debug the slow parts, would be great to have some kind of timing in the build logs.

Example from Travis:
<img width="1035" alt="Screenshot_2019-05-14_at_16_34_56" src="https://user-images.githubusercontent.com/989015/57703797-6b93c200-7669-11e9-9086-acc69eb70754.png">

An easy option that can be made without any Lagoon changes is to prefix commands from `Dockerfile` and `.lagoon.yml` with `time `.
But it would be nice to have timings on all Lagoon commands, not just on the ones from projects.

**Comment by dasrecht** [comment]
I shortly looked around a bit how this is actually built : https://github.com/travis-ci/travis-build/pull/263

**Comment by shreddedbacon** [comment]
With the lagoon build deploy controllers, we can get the timestamps from the logs once a build is completed. https://github.com/amazeeio/lagoon-kbd/pull/18 should be able to do this.

It isn't how long each step took to run, but using the timestamps you could easily work that out.

**Comment by luigimannoni** [comment]
Adding a +1 on the request.
We're looking to cut down extra steps from our build process and looking to analyse which ones can be optimised.

It's a bit difficult now without filling `.lagoon.yml` and `Dockerfile`s with date/time commands and rightly getting shouted at from the colleagues :grimacing:
