### ISSUE TITLE
Docker registry failure on minishift

### ISSUE THREAD

**Issue by mikkeschiren** [uselagoon/lagoon#1090]
**Describe the bug**
Running make minishift I get this in the end:

Using project "lagoon".
Error response from daemon: Get https://192.168.99.102:30000/v2/: http: server gave HTTP response to HTTPS client
make: *** [Makefile:738: minishift/login-docker-registry] Error 1

Also seeing this in the Openshift UI:
docker-host-3-mqhcf | Image Pull Back-off

**Comment by vincenzodnp** [comment]
Hello @mikkeschiren the problem is your docker daemon doesn't allow to login to insecure registries.
I'm working on a PR to fix it. In the meanwhile, to fix it, create this file (I suppose you are on Gnu/Linux):
`/etc/docker/daemon.json` with this content:

> {
        "insecure-registries":["192.168.99.102:30000"]
 }

**Comment by vincenzodnp** [comment]
@mikkeschiren according to official documentation https://lagoon.readthedocs.io/en/latest/developing_lagoon/#start-services
you can add the full 192.168.99.0/24 network to insecure-registries like comment above to prevent any registry error.
Thanks
