### ISSUE TITLE
solr7.5 "Unable to create core [drupal]"

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon#1093]
**Describe the bug**
Solr 7.5 cores dump with: "

> Unable to create core [drupal]"

 and 

> "Plugin init failure for [schema.xml] fieldType "collated": Error loading class 'solr.ICUCollationField'"

**To Reproduce**
Set `amazeeio/solr:7.5-drupal` image in docker-compose

**Expected behavior**
`drupal` Solr core availale

**Comment by tobybellwood** [comment]
we had to apply the same fix to solr 6.6 to get search_api_attachments working in govCMS/govcms8lagoon/pull/48
```
	"drupal/core": "8.7.1",
	"drupal/search_api": "1.11",
	"drupal/search_api_solr": "2.2",
	"drupal/search_api_attachments": "1.0-beta13",
```
