### ISSUE TITLE
solr 7.5 config does not work with search_api_solr module v3.x 

### ISSUE THREAD

**Issue by fmuellerprevion** [uselagoon/lagoon#1096]
**Describe the bug**
When using the newest version(s) of the search_api_solr module, a correct setup with solr 7.5 cannot be used when using the standard config provided in this repository.

**To Reproduce**
1. Set up D8 with the module search_api and search_api_solr v3.x 
2. Set up a solr container which builds it using the amazeeio/solr:7.5 image and having the config from https://github.com/amazeeio/lagoon/tree/master/images/solr-drupal/solr7.5/conf 
3. Set up the solr server and an index in the config

**Expected behavior**
On the solr server page under search API, there should be no error and the server should be reachable. Views on the created index should deliver a correct result.

**Actual behavior**
The server page reads the message: 

`You are using outdated Solr configuration files. Please follow the instructions in the INSTALL.md file for setting up Solr.`

When running a query using a view, this error is thrown:

`Error while checking server index status: An error occurred while trying to search with Solr: { "error":{ "metadata":[ "error-class","org.apache.solr.common.SolrException", "root-error-class","org.apache.solr.common.SolrException"], "msg":"can not use FieldCache on multivalued field: boost_document", "code":400}}`

A support request on the module is here, but which seems to be a configuration issue: https://www.drupal.org/project/search_api_solr/issues/3056971

**Additional context**
Downgrading the search_api_solr module version fro 3.x to 2.7 works for Solr 7.5. However I had to remove the volume and build again to get it to work correctly.

**Comment by vincenzodnp** [comment]
Hello @fmuellerprevion are you not able to index content at all?
I was able but still get the error in the admin page.
Thanks
Vincenzo

**Comment by vincenzodnp** [comment]
@fmuellerprevion we are going to update the solr config of our `solr:7.5-drupal` image
Thanks for your support
Vincenzo
