### ISSUE TITLE
Provide Lagoon-specific env vars via a file

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon#1107]
Currently the only way to provide env vars to Lagoon from code is via the .env file.  However, this is also how we provide local env vars - we have a use case to provide variables to Lagoon that may differ from local ones.

We would use .lagoon.env.$BRANCHNAME - but these would have to be created for every branch - does it make more sense to have a single .lagoon.env file to hold all these?

In our case, we can lock this so that clients can't modify prod variables without going through support, but can test locally themselves via the .env file - and still modify and commit their own .env files as required.

**Comment by Feng-Shui** [comment]
Or allow these to be editing (per environment if needed) via the Dashboard.  We'd love to see this as a way to handle secrets (API keys etc) without having to commit that stuff into our repo.

**Comment by Feng-Shui** [comment]
My bad, PR came in just after this was opened and at the same time I commented,  thought it was a suggestion and not a PR issue.

**Comment by tobybellwood** [comment]
ah @Feng-Shui - do you have access to the addRuntimeEnv and addBuildtimeEnv mutations in GraphQL? https://github.com/amazeeio/lagoon/blob/master/docs/using_lagoon/environment_variables.md#environment-variables-lagoon-api

**Comment by Feng-Shui** [comment]
Not yet, AFAIK we were waiting on getting access to that, there were some permission issues with it last I heard.  Ben J mentioned that we could use that to set env variables but at the moment we have to open tickets with the support desk.  All good, will follow that up in the next week or so, don't wan to hijack this thread.
