### ISSUE TITLE
SSMTP deployed without mailhub config

### ISSUE THREAD

**Issue by steveworley** [uselagoon/lagoon#1115]
**Describe the bug**
A container was deployed and it had an invalid SSMTP configuration. `50-ssmtp.sh` looks to inject a valid mailhub host as long as it is reachable during deployment with the following:

```
  if nc -z -w 1 mxout.default.svc 25 &> /dev/null; then
    echo -e "\nmailhub=mxout.default.svc:25" >> /etc/ssmtp/ssmtp.conf
    return
  fi
```

If this doesn't trigger it looks like PHP is unable to send mail as we were seeing errors in the logs

```
WARNING: [pool www] child 1220 said into stderr: "sendmail: Cannot open mailhub:25"
```

**To Reproduce**
1. Remove `mailhub` from SSMTP conf
2. Try to send email via PHP

**Comment by tobybellwood** [comment]
I think this is resolved now
