### ISSUE TITLE
Lagoon UI: Deploy button hover effect missing

### ISSUE THREAD

**Issue by grappler** [uselagoon/lagoon#1116]
**Describe the bug**
The deploy button in Lagoon UI does not have a hover effect making the button look like it is disabled.
![image](https://user-images.githubusercontent.com/1785641/59036182-15ccc700-886f-11e9-8694-1fb674fc76b2.png)

URL: https://ui-lagoon-master.ch.amazee.io/projects/[project]/[environment]/deployments

**Comment by rocketeerbkw** [comment]
Thanks for the report!

We have another issue with the same general complaint, #1013. We have a new design there which includes hover states, so I'll close this as a duplicate.
