### ISSUE TITLE
provide prometheus metrics from lagoon builds

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#1126]
Expose an endpoint for prometheus to scrape to gather information about running builds

**Comment by twardnw** [comment]
https://www.rabbitmq.com/prometheus.html

**Comment by twardnw** [comment]
https://github.com/siimon/prom-client

**Comment by bryangruneberg** [comment]
It would be cool if the build process could be described in stages, and for metrics to be kept on those stages.

**Comment by bryangruneberg** [comment]
It would be very helpful if the container image creation could be tracked somehow. 

With sites that are statically generated, the container build time can get heavy and long, and it would be really helpful to know which steps in the container build are taking the longest.

**Comment by tobybellwood** [comment]
There are now basic metrics in build-deploy-tool
