### ISSUE TITLE
Feature request: Tag images with "prefix-latest" version.

### ISSUE THREAD

**Issue by fago** [uselagoon/lagoon#1129]
**Describe the bug**
At https://github.com/drunomics/devsetup-docker we are using ARGs to build images based upon versioned images. For automated CI runs that are using docker-compose we use fixed versions so tests do not fail over night, e.g. done here: https://github.com/drunomics/contentpool/blob/8.x-1.x/.travis.yml#L68  The same applies to the localdev environment, it should be manually updated, so we know it does not fail after image updates (as we had it before versioned images).

But then, for production hosting we want "latest" images to be used. However, that is currently hard to control by an environment variable like 

>COMPOSE_AMAZEEIO_VERSION=v0.22.1

since an empty variables leads to invalid version strings for images like

>FROM amazeeio/solr:6.6-drupal-${COMPOSE_AMAZEEIO_VERSION}

since "6.6-drupal-" is not defined, only "6.6-drupal" is.

Could you make *latest* image tags available using a pattern that always have a "latest" version instead of the versions string?
e.g. provide solr:6.6-drupal-latest in addition to (or instead of ) solr:6.6-drupal

**Comment by fago** [comment]
It's even worse since empty environment variables are not working with docker-compose - it results in errors during image building. Thus I had to define two additional environment variables to make it work 

```
    COMPOSE_AMAZEEIO_VERSION_DRUPAL=drupal
    COMPOSE_AMAZEEIO_VERSION_FPM=fpm
```

see https://github.com/drunomics/devsetup-docker/pull/4/files

That's a quite a hassle since that additional required variables are a BC change for our devsetup.

**Comment by fago** [comment]
the pushed -latest tags work fine, thank you! I guess we leave this open until the PR is closed.

**Comment by Schnitzel** [comment]
@fago 
yes it will be closed automatically as soon as the PR is merged
