### ISSUE TITLE
openshiftremove fails with undefined messages

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#1132]
**Describe the bug**
Some openshiftremove calls fail with undefined. This seems to happen on rocketchat mostly. I couldn't find any undefined messages on slack by doing a quick search

**Expected behavior**
no undefined errors are shown

**Screenshots**
<img width="584" alt="Screenshot 2019-07-01 15 32 35" src="https://user-images.githubusercontent.com/391732/60440655-8fa96380-9c15-11e9-81a2-261ceef61ff1.png">

Internal reference (due to PII) AMAZEEIO-2020

**Comment by tobybellwood** [comment]
openshiftremove has been deprecated in Lagoon 2
