### ISSUE TITLE
Unable to drush ssh from local into Lagoon (outside of Docker container)

### ISSUE THREAD

**Issue by AlexSkrypnyk** [uselagoon/lagoon#1142]
**Describe the bug**
The drush alias generation uses `aliases.drushrc.php.stub` file, which is downloaded from the cluster.

Once downloaded, the alias generation uses values gathered from the environment where drush runs and caches them in the same environment.

The problem is that the value of the `root` of the generated drush alias is provided as absolute of the **environment where drush runs**, rather than where the project is located in Lagoon.

What this means is that if locally my project is checked out in `/home/alex/www/example`, and i run `drush sa`, `/home/alex/www/example` is going to be a value of the `root` and it will be used in Lagoon environment instead of `/app/docroot`.

Line 278 of `aliases.drushrc.php.stub` file:
```
$alias[$site_name] = [
    'remote-host' => "$ssh_host",
    'remote-user' => "$environment->openshiftProjectName",
    // 'root' => "$drupal_path", <--- This path is using local directory on host when ran on remote.
    'root' => '/app/docroot', <-- This works correctly
    'ssh-options' => "-o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p $ssh_port",
  ] + $defaults;
```

**To Reproduce**
1. Clone https://github.com/amazeeio/drupal-example into ~/testproject
2. Deploy this project to Lagoon in order to get at least a single Lagoon environment
3. Make sure that your SSH key is added to the project in Lagoon
4. Run `drush sa` from `~/testproject` on your local
5. Lagoon environment alias is not available

Note that `drush sa` from CLI inside of the CLI container works correctly, because the path to the docroot within a container is the same locally and in Lagoon.

**Expected behavior**
`drush sa` returns the name of the environment in Lagoon (`@production`, `@master` etc.)

**Additional context**
Please note that this issue prevents from SSHing into Lagoon without project containers built locally, which sometimes takes a long time. Fixing this will improve developer's experience.

**Comment by vincenzodnp** [comment]
Hello @alexdesignworks 
as mentioned in official documentation (and as you alredy reported) (https://lagoon.readthedocs.io/en/latest/using_lagoon/drupal/lagoonize) all `drush` commands are not run on your local environment, but inside the `cli` container.
So, as described above, you have two options:
- run bash into the cli container and then all drush commands you need
- run `docker-compose exec cli drush command` in the project directory

There is already an issue with an "hack" to override it #485
