### ISSUE TITLE
Lagoon environment cleanup based on Github PR

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon#1150]
This script will help to keep Lagoon environments clean, by removing old environments related to Pull Requests in `closed` state.

The script accept 2 parameters: name of the customer and number of months to chec "last update date" of an environment (and PR).
The idea is to develop the script and make it as much "project-wide" as possible

**Comment by tobybellwood** [comment]
Not a core Lagoon feature - maybe a helper script?
