### ISSUE TITLE
Speed up deployments by adding a build cache for npm and composer

### ISSUE THREAD

**Issue by fago** [uselagoon/lagoon#1153]
**Describe the bug**
Deployment takes a long time - mostly due to uncached composer and npm in builds I think. ~30min.

**Expected behavior**
Faster deployments.

**Additional context**
Maybe helpful: We've managed to cache building (in runninng containers) via docker volumes in our CI, what works good. See https://github.com/drunomics/devsetup-docker/blob/2.x/docker-compose.yml#L21

**Comment by dan2k3k4** [comment]
@fago, recently @dasrecht added some changes to an internal project but I duplicated them to an open-source repository, see the [changes](https://github.com/AmazeeLabs/silverback/pull/82/files). Perhaps you could implement similar to the [Dockerfile.cli](https://github.com/drunomics/devsetup-docker/blob/2.x/devsetup-docker/Dockerfile.cli#L3) file?

Or check out the rest of the documentation about [Docker multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/).

**Comment by dasrecht** [comment]
Closing this issue as it is covered by multi-stage builds
