### ISSUE TITLE
Add guidelines for getting started with contribution

### ISSUE THREAD

**Issue by technology-amazeelabs** [uselagoon/lagoon#1154]
To aid first-time contributors, a `CONTRIBUTING.md` file can be created with the documentation on how to contribute to this open-source repository.

For more information, see this github article on [setting guidelines for repository contributors](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors#adding-a-contributing-file).

**Comment by tobybellwood** [comment]
docs are now at  https://docs.lagoon.sh/contributing/
