### ISSUE TITLE
Yarn builds fail on Node version 12

### ISSUE THREAD

**Issue by cdchris12** [uselagoon/lagoon#1157]
**Describe the bug**
When I attempted to run `yarn upgrade <package>`, all the resulting yarn image builds failed using Node version 12. In order to make those tests complete, I had to install Node 10.

**To Reproduce**
1. Install Node Version 12 and Yarn
2. Try to remove a package with `yarn remove git-url-parse`
3. See (many) error(s)

**Expected behavior**
We should either rework these builds to pass with Node versions > 10, or should force yarn to error out on any node version other than 10

**Comment by dasrecht** [comment]
Hi @cdchris12 - During the work on #1215 i saw that we're not having node12 built yet - was that something you tested locally?

**Comment by dasrecht** [comment]
https://github.com/amazeeio/lagoon/compare/node_12?expand=1

**Comment by tobybellwood** [comment]
This is being fixed in main - the mariasql library update was first, then the node update to 14/16
