### ISSUE TITLE
Application error logging platform

### ISSUE THREAD

**Issue by garethhallnz** [uselagoon/lagoon#1164]
I am not sure if this is the right place to start this conversation, please let me know if there is a better place for it.

I am wondering what does everyone think of Kibana as an application logging solution?

For me, when we are talking about infrastructure logging .ie routers, containers and lagoon logs, then Kibana does a fine job.

However, I am not a fan when talking about application logging; by this, I mean Drupal logging. I find it's feature set lacking and cumbersome to use.

I do also realise new relic's APM product can be leveraged, but it's not open-source.

Might I suggest Lagoon adopt Sentry in favour of Kibana for application logs?

I recently started using it; it's fantastic and open source.

For me, Sentry is a proper logging solution with a ton of features and take things to the next level.

See: 
https://sentry.io/welcome/
https://sentry.io/platforms/
https://sentry.io/features/
https://sentry.io/integrations/

**Comment by dasrecht** [comment]
Hi @garethhallnz 

Thanks for bringing that up - This is the right place for this kind of discussion :)

We're currently redoing parts of the logging infrastructure so your input on it is valuable. I'll have a look at it and will come back - What i see is that it's pluggable so theoretically you could add sentry just for the projects you use and send the data to their endpoint.

For the application logging i'm planning on using a few filters that will make the log handling better and more intuitive as they are currently sometimes just strings of text which very hard to work with.

/b

**Comment by dasrecht** [comment]
I shortly looked into sentry - but i feel we would still need to run elasticsearch next to sentry as most of the logging still would go towards elasticsearch/kibana

The logging platform currently is used for several things:
- Request Logging (from loadbalancers)
- Application Logging (from Drupal via the lagoon-logs module)
- Container Logs (outputs directly from containers)
- System Logs (a feature that will come in via #1146 to have 1 Tool that aggregates all logs)

As the ELK Stack is tightly integrated by now to create tenants per customer to safeguard data from each of the users i don't think that our improvement efforts will change much on the current base we run on (Elasticsearch, Logstash, Kibana) 

But i'm keen to learn what's cumbersome to use. As mentioned earlier we'll try to treat the logs better so they can be filtered better tailored to the needs of our customers.

**Comment by garethhallnz** [comment]
It might be easier to do a Zoom meeting, and I'll take you through things?

**Comment by dasrecht** [comment]
Sure let's catch up on this topic next week - will ping you in rocketchat :)

**Comment by tobybellwood** [comment]
This is no longer a core lagoon capability?
