### ISSUE TITLE
Pass in custom --build-args from .env* to a Dockerfile at buildtime

### ISSUE THREAD

**Issue by simesy** [uselagoon/lagoon#1168]
I have tried to use this pattern in lagoon, to allow a dockerfile to build from a specific image version.

```
ARG SOME_VERSION
FROM ourspace/nginx:${SOME_VERSION}
```
This works with docker-compose. The value is originally set in `.env` and passed in dynamically through docker-compose.yml, because it's used multiple times). However in the lagoon build context there seems to be no way to set this as a `--build-arg`.

I think this is a feature request, but workaround suggestions are most welcome.

**Comment by rocketeerbkw** [comment]
@simesy I think the API environment variables can do this, would that work? https://lagoon.readthedocs.io/en/latest/using_lagoon/environment_variables/#buildtime-environment-variables-lagoon-api

**Comment by simesy** [comment]
Great! it looks like I'm not configuring my .env properly. Having a closer look.

**Comment by simesy** [comment]
The docs don't really specify the difference between setting a buildtime vs a runtime variable. I already have an .env file with the desired value set, but this is not available at buildtime, so I assume it's being set as an ENV not an ARG.

**Comment by simesy** [comment]
aha, it's a graphql thing for build variables.

**Comment by rocketeerbkw** [comment]
Ya sorry I wasn't clear. That's a method for setting environment variables dynamically via the API. It has a way to set a "build" env var which gets processed as a `--build-arg`.

I looked around the code and I think all the stuff in your `.env` should be available as environment variables when docker is building the image. My guess is that your example code should work, so maybe there is a bug.

> If you don’t provide a value to expected ARG variables which don’t have a default, you’ll get an error message.

Are you getting an error?

**Comment by simesy** [comment]
Yep the error is "invalid reference format" which I think hints at an empty tag value.
```
...
Step 1/5 : ARG SOME_VERSION
Step 2/5 : FROM ourspace/nginx:${SOME_VERSION}
invalid reference format
```
We just did a test by setting this value as a "build scoped" variable via graphql, and it worked perfectly - we'll go with this solution actually (happy if this ticket is closed). I do suspect that the `.env` variables are only available to runtime ENV as opposed to buildtime ARG, and it might be worth stating this in the docs if that is the case.

**Comment by simesy** [comment]
Since we need to double-handle this value in CI (via .env) and in Lagoon (via graphql) then the idea of setting a build arg via .env (and related files) is compelling, but it feels sensible to be careful about whitelisting what values can be set that way.

**Comment by rocketeerbkw** [comment]
@simesy maybe it's not a problem with the passing, but the syntax. This blog suggests that the whole name should be a variable, not just part of it https://www.jeffgeerling.com/blog/2017/use-arg-dockerfile-dynamic-image-specification

You might try adding a `RUN env` and check the build output to see if the `SOME_VERSION` variable is there.

**Comment by simesy** [comment]
Hmm, since this is working with docker-compose, could it really be about the ARG/FROM syntax? Unless Lagoon is using a different version of docker to my local (and to what we have running in gitlab for that matter).

**Comment by simesy** [comment]
I've doubled checked, `RUN env` won't print ARGs before FROM.

**Comment by rocketeerbkw** [comment]
Well according to [this article](https://vsupalov.com/docker-build-pass-environment-variables/) only docker-compose uses `.env` files natively. Docker doesn't read them at all, but lagoon does and exposes them during the build process.

Having said that, the official docs do have an [example like your code](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact) so maybe that's not the problem.

The reason I thought it might be syntax error is cause the docs say [the error](https://docs.docker.com/engine/reference/builder/#arg) for an unset `ARG` is
>[Warning] One or more build-args [foo] were not consumed.

So perhaps it is a lagoon issue that we don't expose `.env` as build-args.

**Comment by simesy** [comment]
Yeah Docker doesn't use natively. To expose this value with docker-compose.yml I do:
```
  thing:
    build:
      args:
        SOME_VERSION: "1.2.3"
```

**Comment by AlexSkrypnyk** [comment]
@simesy 
You can do this to get variables from `.env` file - docker-compose reads `.env` file by default. 
```
 thing:
    build:
      args:
        SOME_VERSION: "${SOME_VERSION:-1.2.3}"
```

For Lagoon, you can use per-environment files as described here https://lagoon.readthedocs.io/en/stable/using_lagoon/environment_variables/

**Comment by simesy** [comment]
> You can do this to get variables from .env file - docker-compose reads .env file by default.

Yes I am actually doing something like that, but I only gave that example for disambiguation. 

> For Lagoon, you can use per-environment files as described here 

In my testing you can't use these variables to use with ARG before FROM in Lagoon. This has been confirmed by Amazee. But if you have an example of it please share!

**Comment by simesy** [comment]
Talking to different docker people, I see that build args come with caveats. Perhaps this could be solved best by simply allowing LAGOON_IMAGE_VERSION (or _TAG) to be set from .lagoon.yml to enable:

```
ARG LAGOON_IMAGE_VERSION
FROM myimages/nginx:${LAGOON_IMAGE_VERSION}
```

**Comment by simesy** [comment]
Just found https://github.com/amazeeio/lagoon/issues/1130 which is the generic "allow all env variables into the build" solution.

**Comment by bomoko** [comment]
I'm going to close this ticket for now, since we have workarounds for build vars and we have issue 1130 which, I think, covers the use case here. Happy to reopen if not.
