### ISSUE TITLE
mariadb-client 10.2.24-r0 is no longer available

### ISSUE THREAD

**Issue by pandaskii** [uselagoon/lagoon#1169]
**Describe the bug**
mariadb-client 10.2.24-r0 is no longer available, need a version to 10.2.26-r0

**Screenshots**
<img width="638" alt="Screen Shot 2019-08-08 at 2 46 41 pm" src="https://user-images.githubusercontent.com/1326673/62675690-5b327f80-b9eb-11e9-8cb4-1e855f3c0be0.png">

**Comment by cdchris12** [comment]
Closing as this issue has been fixed
