### ISSUE TITLE
Gitlab webhook handler doesn't deleter envs after a merge

### ISSUE THREAD

**Issue by steveworley** [uselagoon/lagoon#1189]
**Describe the bug**
When Gitlab is using the webhook handler service a new pull request creates an environment for that PR, however when the PR is merged the PR environment is not deleted correctly.  Merge request events in gitlab should have a state in the payload which would let us determine if the PR has been merged.

**To Reproduce**
1. Add a new project with gitlab as the source
2. Add a new integration to the webhook-handler service
3. Create a PR
4. Merge the PR

**Expected behavior**
The event for merging a PR is handled by the webhook-handler service and successfully decommissions PR environments.

**Additional context**
https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#merge-request-events

**Comment by rocketeerbkw** [comment]
@steveworley are you getting error messages at all? We do have this case [covered in code](https://github.com/amazeeio/lagoon/blob/develop/services/webhooks2tasks/src/webhooks/projects.js#L253) already and we haven't had error reports from other users.
