### ISSUE TITLE
Make http/2 the default for nginx

### ISSUE THREAD

**Issue by garethhallnz** [uselagoon/lagoon#1193]
I just noticed the default Nginx image still uses http/1.1 Might it time to upgrade to http/2?

**Comment by dan2k3k4** [comment]
I asked internally about this and the response was:
>OpenShift does not yet fully support HTTP/2

So I assume HTTP/2 is planned as soon as OpenShift has full support OR as soon as Lagoon is moved to Kubernetes?

**Comment by Schnitzel** [comment]
yes, with the move to native Kubernetes support with Lagoon we will probably change the http/2 default. Like @dan2k3k4 said, OpenShift's Ingress Controller HAProxy does not support http/2 currently, so we can't switch unfortunately.

**Comment by garethhallnz** [comment]
@Schnitzel It's my understanding that Lagoon uses v1.8.1 of HAProxy which does support http/2
See: https://www.haproxy.com/blog/whats-new-haproxy-1-8/#http-2-protocol-support

Either way, this is fo far beyond my abilities I simply have to take your word for it.

Is there a roadmap planned?

**Comment by Schnitzel** [comment]
HTTP2 is supported in OpenShift 3.11: https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-311-haproxy-enhancements
We are currently upgrading all the clusters to it, as soon as this is upgrade is done (1-2 months) we will check if this is something we should enable (we need to do some more testing)

**Comment by mathieuspil** [comment]
This would explain why my experimenting progressive rendering technique lowers the frontend performance instead of improving it.

Really looking forward to when my site is ran through HTTP2!

**Comment by seanhamlin** [comment]
HTTP2 was rolled out to HAPorxy for a lot of clusters last night (during maintenance).
