### ISSUE TITLE
NPM run fails in 1.0.1

### ISSUE THREAD

**Issue by AlexSkrypnyk** [uselagoon/lagoon#1212]
**Describe the bug**
`RUN npm install` fails with ``Error relocating /usr/bin/node: nghttp2_option_set_max_outbound_ack:`

This issue (https://github.com/amazeeio/lagoon/issues/1208) has addressed the core of the problem in Lagoon version `v1.0.0`. The solution was to upgrade `nghttp2-libs` from `1.38.0-r0` to `1.39.2-r0` and the PR was created and merged.

However, running latest PHP-CLI image still has this problem and `v1.0.1` still  shows that `nghttp2-libs` has version `1.38.0-r0`. Adding `RUN apk upgrade` to the Dockerfile resolves the issue.

Can this be added to the Lagoon images?

**To Reproduce**
Steps to reproduce the behavior of outdated `nghttp2-libs`:
1. Start the PHP CLI image with version `v1.0.1`
2. SSH into container
3. `apk info nghttp2-libs`
4. See outdated version

Steps to reproduce the behavior of broken NPM:
1. Start the PHP CLI image with version `v1.0.1`
2. SSH into container
3. Run any npm command
4. See error `Error relocating /usr/bin/node: nghttp2_option_set_max_outbound_ack: symbol not found` 

**Expected behavior**
No error and `npm` commands work.

**Comment by dasrecht** [comment]
Confirmed - We'll come up with a fix for this issue - Initially thought the forced install should also update it.

**Comment by dasrecht** [comment]
PR is open and testing is underway
