### ISSUE TITLE
End of Life PHP 5.6 / 7.1

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#1214]
PHP 5.6 is is unsupported since beginning of 2019 and we should be more open about sunsetting it by end of this year (e.g.. adding more nag messages and communicating a deadline till when php 5.6 will be discontinued)

PHP 7.1 also ends its security support by 2019-12-01 and we should already add the nag screen - As the PHP 7.1 to PHP 7.2/7.3 move is easier I'd expect less issues and work involved between the 7.x branches of PHP

Reference: 
https://www.php.net/supported-versions.php
https://twitter.com/SaraMG/status/1167593974737133569

**Proposal:**
- Agree on EOLing of PHP 5.6 / 7.1 as of 2019-12-01
- Removing PHP 5.6 / 7.1 docker image tags after an agreed timeframe (ideally 2-4 months)
- PHP 5.6 / 7.1 - Updating Nag message to reflect this decision - https://github.com/amazeeio/lagoon/blob/master/images/php/cli/Dockerfile#L61-L62

**Comment by dasrecht** [comment]
I remember we discussed at some point to send back version information during builds back to lagoon - Not even sure if we ever implemented this, but that could help us identifying customers that still have old versions (and also displaying those notifications on the UI)

**Comment by ChandeepKhosa** [comment]
Do you have an EOL/forced termination date for PHP 5.6 agreed yet?

**Comment by dasrecht** [comment]
Hi @ChandeepKhosa 

> The release of Lagoon 1.2.0 brings the first release of PHP7.4-based images, as well as the last PHP5.6, PHP7.0 and PHP7.1 releases, as they are all now officially end-of-life, and out of security support (https://www.php.net/supported-versions.php). In future Lagoon releases, we will not be creating, testing or publishing images for these EOL releases, so the 1.2.0 tag will remain the “latest” version available.

from https://stories.amazee.io/what-to-expect-in-lagoon-1-2-0-e62d9b3cc51a

While you can still use the old PHP images they won't receive any updates anymore. As for the case of PHP 5.6 this is out of security maintenance of PHP since 2018-12-31 (see https://www.php.net/supported-versions.php).

We didn't yet agree on a date where the PHP images will be fully removed - But updating would be highly encouraged as PHP 5.6 is now fully out of support since a year.

**Comment by ChandeepKhosa** [comment]
Thanks, I'll let "my friend" know ;)
