### ISSUE TITLE
Unable to create a new nginx helper that uses rewrite_by_lua_block

### ISSUE THREAD

**Issue by Feng-Shui** [uselagoon/lagoon#1220]
**Describe the bug**
IPv6 nginx helper contains `rewrite_by_lua_block` which means it can not be re-used in a different helper as it triggers a duplicate error.

**To Reproduce**
1. Within the nginx container
2. `echo "rewrite_by_lua_block {}" > /usr/local/openresty/nginx/conf/helpers/040_test.conf`
3. `nginx -s reload`
4. See error `nginx: [emerg] is duplicate in /etc/nginx/helpers/040_test.conf:1`

**Expected behavior**
I should be able to add code to `rewrite_by_lua_block` within the content that the helpers are being included in `app.conf` without having to add it to a file name specifically for IPv6.  Given that duplicate blocks are not allowed, suggest that this file is renamed to `030_rewrite_by_lua_block.conf` indicating that I can use this file for other code that needs to be executed in this block.

**Screenshots**
N/A

**Additional context**
Happy to put up a MR if the above solution is acceptable.

**Comment by dasrecht** [comment]
Hi @Feng-Shui this sounds like a good idea - If you can send a MR our way that would be fantastic!

**Comment by Feng-Shui** [comment]
Ok, will do 👍

**Comment by poojas16** [comment]
I'm having a similar problem.. I included two conf file in app.conf file. 
And these 2 conf file are having rewrite_by_lua_block and on starting the nginx server, i got the following error- 
2021/12/13 19:02:41 [emerg] 29499#29499: is duplicate in /etc/nginx/redirection_url.conf:3
2021/12/13 19:03:46 [emerg] 30423#30423: is duplicate in /etc/nginx/redirection_url.conf:3
2021/12/13 19:10:35 [emerg] 4237#4237: is duplicate in /etc/nginx/redirection_url.conf:3
@Feng-Shui can you help me in this?

**Comment by Feng-Shui** [comment]
@poojas16 if you add another `rewrite_by_lua_block` anywhere in your custom config files you will get this error.  Any code that needs to be executed with `rewrite_by_lua_block` must be to be added to the following file:

https://github.com/uselagoon/lagoon-images/blob/main/images/nginx/helpers/030_rewrite_by_lua_block.conf
