### ISSUE TITLE
Solr

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#123]
Migrate solr:alpine images from https://github.com/amazeeio/docker-solr into lagoon.
Start a solr within the tests (add to https://github.com/amazeeio/lagoon/blob/master/tests/files/drupal8/docker-compose.yml) but don't worry about actually testing solr yet.

**Comment by twardnw** [comment]
#131

**Comment by twardnw** [comment]
solr comes up and running in it's pod, properly accessible, but the core is not yet creating at startup

**Comment by twardnw** [comment]
Core creates properly, and now has persistent storage. I think this is all ready for review and merge

**Comment by twardnw** [comment]
Merged
