### ISSUE TITLE
ESLint Errors w/ Typescript *.test.ts files

### ISSUE THREAD

**Issue by wintercreative** [uselagoon/lagoon#1249]
**Describe the bug**
Given a typescript test file with the name `*.test.ts` eslint will complain that none of the jest global objects exist. The api image will not build as a result.

```
cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.
Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.
Cannot find name 'expect'.
 ```

**To Reproduce**

1. Create a folder in the `services/api/src/resources/` called `test`. 
2. Create a file in in that folder called `error.test.ts`
3. Copy/Paste the following

```
// Unit Under Test
describe('Calculations', () => {
  describe('TEST', () => {
    // scenarios and expectation
    it('When a thing happens, it should be...', () => {
      expect(1 + 1).toBe(2);
    });
  });
```

**Expected behavior**
I expect eslint to not throw errors in my IDE and I expect the api image to build.

**Screenshots**
![Screen Shot 2019-09-14 at 5 06 08 PM](https://user-images.githubusercontent.com/8481069/64913641-fc5ed500-d711-11e9-9294-7137c81b2e46.jpg)

**Comment by bomoko** [comment]
I can't seem to reproduce on the latest - so I'm closing for now (happy for @wintercreative to repoen)
