### ISSUE TITLE
Default user only has guest access by default

### ISSUE THREAD

**Issue by thom8** [uselagoon/lagoon#1251]
With the update to `1.0.0` the default project user only has the guest role which can no longer can access other environments to sync data.

This is an unexpected change as pre `1.0.0` the default project user had access to all environments in a project.

While users are migrating to the new permission model it would be helpful to keep the default access as close to the original approach, users can still restrict the permissions as needed.

**Comment by Schnitzel** [comment]
With https://github.com/amazeeio/lagoon/issues/1229 each task will run with a Maintainer access token.
Do we think we still need to change the default user? The default user will only be used anymore for SSH access and I think there it is fine that the user is Guest?
