### ISSUE TITLE
REDIS_PORT is defined as a TCP address.

### ISSUE THREAD

**Issue by steveworley** [uselagoon/lagoon#1254]
**Describe the bug**
When the containers are built in Openshift they're given a REDIS_PORT env variable and this looks to be a TCP address not a PORT number.

I couldn't find any reference to this being set by Lagoon but might be something worth investigating, I think it might be being defined by kube service discovery but I'm not 100% sure. Also worth noting that if it's expected to be a TCP address the name is a bit misleading and maybe something we can document to prevent some errors?

I ran into this when defining a redis fallback using:

```
$redis_host = getenv('REDIS_HOST') ?: 'redis';
$redis_port = getenv('REDIS_PORT') ?: 6379;
```

It ended up trying to connect to `redis:tcp://172.30.255.100:6379`.

**To Reproduce**
1. Add `var_duno(getenv('REDIS_PORT'))` 

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/1840912/65003239-f861cb80-d93a-11e9-8f5e-7011fc491eb2.png)

**Comment by Schnitzel** [comment]
yes, unfortunately that's what Kubernetes does out of the box, it doesn't make much sense, but it basically adds an environment variable with `XXX_PORT` where `XXX` is each service defined within kubernetes. 
This is the same reason that we're not using `MARIADB_PORT` here: https://github.com/amazeeio/drupal-example/blob/7f1e4a17556243f7b765bdfd061a6da3ade0c01b/web/sites/default/settings.php#L36

We had once a script that atomatically detected the port weirdness:
https://github.com/amazeeio/drupal-example/commit/332e06c91829ef2514c5a1adbe4f75b827ac59c6

but we removed it as the ports of the services hardly ever change.

**Comment by Schnitzel** [comment]
So I just realized that there is actually an environment variable now existing that could be interesting for use: `REDIS_SERVICE_PORT`, this has been already used by @steveworley, let's update our examples to also use `REDIS_SERVICE_PORT` and the other places where it makes sense.

**Comment by steveworley** [comment]
I thought it was part of the K8s service discovery, while I was trying to find it I found some documentation for it.

Awesome! I noticed `REDIS_SERVICE_PORT` as well and started using that as it seemed more inline with what I was expecting. Thanks!

**Comment by vincenzodnp** [comment]
I have update the examples and documentation to use `REDIS_SERVICE_PORT` instead of `REDIS_PORT`
