### ISSUE TITLE
Mutaion `removeNotificationFromProject` doesn't work

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon#1258]
**Describe the bug**
I tried to remove a SLACK notification from a project, by using the `mutation` _removeNotificationFromProject_ like
```
mutation deletenotification2project {
  removeNotificationFromProject(
    input: {
      notificationType: SLACK
      project: "project"
      notificationName: "notification-name"
    }) {
    id
  }
}
```

The error I've got is:
```
{
  "errors": [
    {
      "message": "Cannot destructure property `projects` of 'undefined' or 'null'.",
      "locations": [
        {
          "line": 26,
          "column": 3
        }
      ],
      "path": [
        "removeNotificationFromProject"
      ]
    }
  ],
  "data": {
    "removeNotificationFromProject": null
  }
}
```

**To Reproduce**

1. Create one or more notification and associate to a project with _addNotificationToProject_ mutation.
2. Try to remove it

**Expected behavior**
Notification should be not  associated anymore to the project

**Comment by Schnitzel** [comment]
@rocketeerbkw 
can you check that one? it failed on Lagoon 0.24.0 so with the newest version this might already be solved.
