### ISSUE TITLE
Use common public key format in JWT user token for sshKey

### ISSUE THREAD

**Issue by ryyppy** [uselagoon/lagoon#126]
Right now, our auth-server creates tokens with an `sshKey` attribute, which only reflects the `keyValue` column in the database... example:

```
{
sshKey: 'AAAAB...==',
sub: 'ansible-test',
iss: 'auth-server.dev',
role: 'user',
aud: 'api.dev',
iat: 1507473953
}
```

It's very hard to remember the format of the `sshKey` attribute, since it is kinda "stringly typed" with certain expectations... without any validation in between. So it would be easier to use a value which is more common in SSH... the full public key string.

Expected output:

```
{
sshKey: 'ssh-rsa AAAAB...==',
...
}
```

Required changes:

- [ ] Change token creation in auth-server / commons jwt module
- [ ] Make sure the `api/auth.js` middleware uses this value correctly for looking up permissions (`WHERE type = 'ssh-rsa' AND value = '...'`)
- [ ] For local dev: Invalidate all apps using wrongly generated tokens

**Comment by Schnitzel** [comment]
I agree, let's do this

**Comment by ryyppy** [comment]
Since I am already working on the auth middleware, I think it's best to just add this as well... I also think I already got all the changes needed to make this happen.

**Comment by ryyppy** [comment]
The proposed changes were introduced in #128 🎉
