### ISSUE TITLE
Multiline environment variables breaks lagoon builds

### ISSUE THREAD

**Issue by thom8** [uselagoon/lagoon#1286]
Docker build fails with `bad flag syntax: -----END` when passing multiline environment variables to `docker build` as build args.

**To Reproduce**
1. Add a mutliline environment variable as a build or global variable in the lagoon API
2. build the project
3. See error at the point of the build failure

**Expected behavior**
Either sanitise the variables before passing them to `docker build` or fail gracefully with an error that multiline environment variables are not supported as build variables.

**Comment by bomoko** [comment]
I've added a multiline string via lagoon cli, it looks like the newlines are replaced with `\n` (which will also be the case in the api) - build proceeded without a hitch. I think this is good.
