### ISSUE TITLE
Add the ability to provide metadata to Lagoon projects/environments

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon#1289]
Currently env variables can be provided to projects or environments - but these can be complex and unwieldy for some purposes.

There could also exist the ability to provide (and maintain) a list of more lightweight tags/topics for projects - potentially similar in scope to GitLab's tag_list implementation (https://docs.gitlab.com/12.3/ee/api/projects.html) or GitHub's topics (https://developer.github.com/v4/object/topic/)

These tags could be implemented as an array - allowing specific tags to be added or removed (and updated), exposed via the GraphQL API and filterable.

For the case of projects synced from GitLab or GitHub - these could be synced from the repos across to the project.  Whether environments could hold different tags to projects is probably a further conversation.

**Comment by seanhamlin** [comment]
This would be useful for a number of usecases that I can think of:

* Knowing whether a project is considered `Real` (and not a `Test` project for instance)
* Knowing what technology a project uses (e.g. `Drupal7`, `Drupal8`, `Laravel`, `NodeJS` or `Static`)
* Knowing whether a project is considered `High profile`
* Knowing is a project is `SaaS`, `SaaS+` or `PaaS` (GovCMS specific)
* Knowing is a site is impacted by `Covid-19` and will receive a lot more traffic then usual.

Having the ability to integrate this into the GraphQL API would be great. Agree with @tobybellwood that being able to synchronise the Gitlab tags would also be marvellous.

Current API feature list

* Add a tag to a namespace
* Remove a tag from a namespace
* Get a list of tags for a namespace
* Get a list of namespaces that are tagged with a tag
* Get a list of namespaces that are not tagged with a tag

The Lagoon UI for now could just display the tag (read only) to make this a bit easier.

Bonus points would allow you to filter the project list by tag.

**Comment by tobybellwood** [comment]
added in #1775
