### ISSUE TITLE
projectByName query including group name fails

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1294]
**Describe the bug**
Adding `group.name` to the `projectByName` query causes the query to fail.

**To Reproduce**
1. Perform a query like this:
```graphql
query projectByName {
  projectByName(name:"my-cool-project"){
    id
    name
    groups{
      id
      name
    }
  }
}
```
2. Observe an error reported in the response:
```graphql
{
  "errors": [
    {
      "message": "Cannot read property 'map' of null",
      "locations": [
        {
          "line": 82,
          "column": 5
        }
      ],
      "path": [
        "projectByName",
        "groups"
      ]
    }
  ],
  "data": {
    "projectByName": {
      "id": 123,
      "name": "my-cool-project",
      "groups": null
    }
  }
}
```

**Expected behavior**
Return successfully, populating the list of groups.

Note that the query _does_ work if you only request `group.id`, not `group.name`.

Successful query:
```graphql
query projectByName {
  projectByName(name:"my-cool-project"){
    id
    name
    groups{
      id
      #name
    }
  }
}
```
Successful response:
```graphql
{
  "data": {
    "projectByName": {
      "id": 123,
      "name": "my-cool-project",
      "groups": [
        {
          "id": "048df24f-5948-4c76-87b7-6203bc78e897"
        },
        {
          "id": "8777dc3c-6062-4221-87d1-80e962ac9b86"
        }
      ]
    }
  }
}
```

**Screenshots**
n/a

**Additional context**
This may not happen with all groups, but seems pretty easily reproducible.

**Comment by bomoko** [comment]
I've tried this with a number of groups and can't seem to reproduce it, I'm going to close this for now.
