### ISSUE TITLE
Add favicon for Lagoon UI

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1305]
**Describe the bug**
Visit the Lagoon UI in your browser, notice no favicon is present

**To Reproduce**
Steps to reproduce the behaviour:
1. Visit https://ui-lagoon-master.ch.amazee.io/favicon.ico
2. See HTTP 404

**Expected behavior**
HTTP 200, and the new Lagoon image present.

**Comment by JohnAlbin** [comment]
It's easy to make a favicon from the new Lagoon logo. https://stories.amazee.io/a-logo-for-lagoon-40e892ec2691

I will create a PR for this. Unless, @seanhamlin, you are already working on it?
