### ISSUE TITLE
Add Lagoon logo to README and docs

### ISSUE THREAD

**Issue by JohnAlbin** [uselagoon/lagoon#1307]
**Describe the bug**
The Lagoon logo is pretty. But we don't use it in this repo's README or in the Lagoon docs.

**To Reproduce**
1. Go to https://lagoon.readthedocs.io/en/latest/ or to https://github.com/amazeeio/lagoon
2. Weep at the lack of beautiful logos.

**Expected behavior**
1. Go to https://lagoon.readthedocs.io/en/latest/ or to https://github.com/amazeeio/lagoon
2. Dance party!
   ![dance party](https://media.giphy.com/media/l0HUqsz2jdQYElRm0/giphy.gif)

**Comment by Feng-Shui** [comment]
I don't know how I feel about that gif, but I can't stop watching it.
