### ISSUE TITLE
Deploy button inoperable on production environments

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1311]
**Describe the bug**
Deploy button on Dashboard doesn't work for production environments with Lagoon RBAC:
```
GraphQL error: Unauthorized: You don't have permission to "deploy:production" on "environment".
```

**To Reproduce**
1. Go to production environment on RBAC-enabled Lagoon.
2. Click on Deploy.
3. See error.

**Expected behavior**
Perhaps the button should be disabled, or otherwise indicate that it is inoperable.

**Screenshots**
n/a

**Additional context**
This came out of a GovCMS request, not sure if it is specific to their installation.

**Comment by seanhamlin** [comment]
This reminds me of https://github.com/amazeeio/lagoon/issues/1642 - in essence they look like the same issue.

**Comment by smlx** [comment]
yep, it's the same thing. closing as a dupe because #1642 has more detail and screenshots
