### ISSUE TITLE
openshiftremove reports error when environment doesn't exist

### ISSUE THREAD

**Issue by kaypro4** [uselagoon/lagoon#1322]
**Describe the bug**
When a branch is deleted in Bitbucket, that was never built on Lagoon, the openshiftremove task attempts to delete the environment but fails due to the environment not existing.

**To Reproduce**
1. Go to a Bitbucket that is connected to a Lagoon project
2. Delete a branch that does not match the "BRANCHES ENABLED" regex in Lagoon
3. Observe that 4 attempts and 1 error message are displayed in Slack for the branch deleted

**Expected behavior**
Lagoon should not attempt to delete environments that don't exist.

**Screenshots**
![image](https://user-images.githubusercontent.com/6536955/67111063-00569a80-f189-11e9-8ea9-5b2fbae7382a.png)

**Additional context**
None

**Comment by tobybellwood** [comment]
openshiftremove has been deprecated in Lagoon 2
