### ISSUE TITLE
Include the GitHub username that created the PR in completed build notifications

### ISSUE THREAD

**Issue by nbaosullivan** [uselagoon/lagoon#1327]
It would be very useful to include the GitHub username that created the PR in completed build notifications, so that devs can be notified directly.

One possible solution would be (from @dan2k3k4):

- Add an option on the Lagoon UI per project to change the Slack Message from standard to advanced, with advanced allowing customisation of what end-result looks like:
`[<project>] <pr-num> Build <build-num> completed by <PR Base Username>`
- Then within Slack, the user would just need to add their Github Name to the Get Notified by these words section inside Slack.

Or more simply, the GitHub username that created the PR could be included globally on all completed build notifications.

cc @Schnitzel

**Comment by dan2k3k4** [comment]
Here's a possible implementation:
![image](https://user-images.githubusercontent.com/158704/67248271-33887a80-f464-11e9-85fa-72201243f315.png)
