### ISSUE TITLE
Script upload for protocol-mappers deprecated in Keycloak 7.0.1+

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1359]
**Describe the bug**

> Until now, administrators were allowed to upload scripts to the server through the Keycloak Administration Console as well as through the RESTful Admin API.
> 
> For now on, this capability is disabled by default and users should prefer to deploy scripts directly to the server. For more details, please take a look at JavaScript Providers.

https://www.keycloak.org/docs/latest/release_notes/index.html#keycloak-7-0-1-final

Our current entrypoint script relies on this functionality in `services/keycloak/start.sh`, in the `configure_opendistro_security_client` function.

#1358 overrides the new default to allow script upload functionality for now, but we should use the new recommended method which involves rolling `.jar` files.

**To Reproduce**
Steps to reproduce the behavior (without the changes in #1358):
1. build lagoon locally completely from scratch (`docker system prune -af` first)
2. run `make up`
3. observe errors on keycloak start

**Expected behavior**
Keycloak should start successfully.

**Screenshots**
n/a

**Additional context**
See the link above for details about what we should be doing instead of uploading scripts.

**Comment by tobybellwood** [comment]
resolved in v2.11.0
