### ISSUE TITLE
Refactor Container Logs Elasticsearch Index Name creation to generate less indexes

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1364]
Currently we just use the Kubernetes Namespace name as the indicator for index names of container logs inside elasticsearch: `container-logs-${record['namespace_name']}-${Time.at(time).strftime("%Y.%m")}`

The problem is that with having many PR environments we create a new index for each PR environment even though they only have a couple of hundred log entries. This makes the elasticsearch slow.

Therefore we would like to change the index name to separate between the environment type (where we currently have `production` and `development`):
- `container-logs-${lagoon-projectname}-${lagoon-environmenttype}-${Time.at(time).strftime("%Y.%m")}`

In order to do this we're missing two essential pieces in the payload of the container logs:
- lagoon project name
- lagoon environment type

Fluentd has the possibility to inject the labels of the namespace into the payload of the container logs, therefore the plan is:

- [ ] Inject the Lagoon ProjectName, EnviornmentName, EnvironmentType as a label into the Kubernetes Namespace when we create the namespace, but also when we redeploy (in order to handle namespaces that don't have the labels yet, but also in case the environment type change)
- [ ] create a script that add/updates the labels in all the namespaces created by lagoon
- [ ] Update the Fluentd config https://github.com/amazeeio/lagoon/blob/master/services/logs-forwarder/.lagoon.multi.yml#L223-L228 to check for these new variables and if they exist use them instead of the current way (but provide a fallback to use the old system, plus also for namespaces that are not created by lagoon - like `default`)

**Comment by tobybellwood** [comment]
possible fluentd plugin for pod/namespace data to container logs - https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter

**Comment by Schnitzel** [comment]
@tobybellwood 
yes, we're using that already, or better: the openshift image we use: https://github.com/amazeeio/lagoon/blob/master/docker-compose.yaml#L394 uses it for us :)

**Comment by tobybellwood** [comment]
heh!  _nothing to see here, carry on_
