### ISSUE TITLE
Pull base images in `make build`?

### ISSUE THREAD

**Issue by blazeyo** [uselagoon/lagoon#1376]
**Describe the bug**
The following error was thrown by `make build`. It was caused by an outdated, cached version of node/10-alpine.
```
docker build --quiet --build-arg LAGOON_VERSION=development --build-arg IMAGE_REPO=lagoon -t lagoon/yarn-workspace-builder -f images/yarn-workspace-builder/Dockerfile .
...
error @lagoon/commons@4.0.0: The engine "node" is incompatible with this module. Expected version ">=10.16.3". Got "10.16.0"
```

**To Reproduce**
Run `make build` with an outdated node/10-alpine image.

**Expected behavior**
Common images are pulled on `make build`.

**Comment by blazeyo** [comment]
Here's a list of candidates for pre-pulling:

- rabbitmq:3-management
- redis:alpine
- bobrik/curator
- alpine:3.7
- alpine:3.7
- golang:alpine
- docker:stable
- docker.elastic.co/kibana/kibana:7.3.0
- docker.elastic.co/kibana/kibana:6.8.2
- docker.elastic.co/kibana/kibana:7.1.1
- docker:stable-dind
- postgres:11-alpine
- arachnysdocker/athenapdf-service:2.13.0
- solr:${SOLR_MAJ_MIN_VERSION}-alpine
- alpine:3.8
- node:${NODE_VERSION}-alpine
- docker.elastic.co/logstash/logstash:7.3.0
- docker.elastic.co/logstash/logstash:6.8.2
- php:${PHP_IMAGE_VERSION}-fpm-alpine
- alpine:3.7
- docker.elastic.co/elasticsearch/elasticsearch:7.3.0
- docker.elastic.co/elasticsearch/elasticsearch:6.8.2
- docker.elastic.co/elasticsearch/elasticsearch:7.1.1
- alpine
- python:${PYTHON_VERSION}-alpine
- alpine:3.8
- openresty/openresty:alpine

The list has been generated with
```shell
grep -rohP '^FROM \K(\w[^\s]+)' images/
```
With this it should be quite easy to automate the process. The only step left if to expand the variables (e.g. `${NODE_VERSION}`) and run a docker pull on the result.

**Comment by tobybellwood** [comment]
We've modified the build process since this issue
