### ISSUE TITLE
Lagoon UI: Add pagination to the project list

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1382]
**Describe the feature**

When you have access to a lot of projects in lagoon (e.g. 400+), there is no pagination, this leads to an incredibly long list of projects. This leads to a lot of work by your browser to render the list, and also your scrollbar gets incredibly small.

**Desired behavior**

It would be great if the list would paginate, to show the user a manageable amount of projects at one time. Perhaps the pagination limit could be an environment variable, that perhaps defaulted to 100.

There is still a filter box, and I would imagine this would still be used as the primary way to filter the projects down.

**Comment by tobybellwood** [comment]
The project list in UIv2 will be paginated :partying_face:
