### ISSUE TITLE
Make Lagoon DBaaS capable of handling multiple database clusters

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon#1397]
For load balancing - could test table/schema counts before allocating secrets to a project
For dedicated database clients - could assign "new" environments to the correct database cluster

**Comment by tobybellwood** [comment]
(technically handled by https://github.com/amazeeio/dbaas-mariadb-apb) - but here for visibility

**Comment by Schnitzel** [comment]
we have now support of mariadb-dbaas in OpenShift and it's coming in k8s as well, closing.
