### ISSUE TITLE
repo config should be case insensitive

### ISSUE THREAD

**Issue by jordotech** [uselagoon/lagoon#1401]
**Describe the bug**
Builds are not triggered if the repo configured for the project does not match the case 

**To Reproduce**
1. Create webhook for repo where the repo has capital letters in it, Ex: https://github.com/Foo/bar
2. Configure lagoon project with repo in lower case Ex: https://github.com/foo/bar
3. Build is not triggered

**Expected behavior**
Lagoon should not care about capitalization of repo name string, should build it.

**Comment by bomoko** [comment]
This seems to have been fixed (tested on a new Lagoon). Closing.
