### ISSUE TITLE
Kibana defaults to global_tenant for some users

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#1409]
**Describe the bug**
If a user has not logged into kibana, the first time they log in they end up in the `global_tenant`.  If a user then creates any index patterns in the `global_tenant`, then any other users that log in for the first time and end up in the `global_tenant` can see those patterns. Users index permissions still apply though so they can only see the indexes they have permission to see.

I would guess that any visualisations/dashboards that are created in this tenant are shared too.

`logs-db-ui` has the `global_tenant` configured to be disabled though.
```
# Disable opendistro_security global tenant\n\
opendistro_security.multitenancy.tenants.enable_global: false\n\
opendistro_security.multitenancy.tenants.enable_private: false\n\
```

This seems to affect any users that have not logged into kibana previously and have not selected a tenant already. 

Once a tenant has been selected, I wasn't able to get back to the `global_tenant`.

**To Reproduce**
1. Create a new user
2. Add user to a project
3. Log in to logs-db-ui
4. Observe no index patterns
5. Go to change tenant observe current tenant is `global_tenant`

**Expected behavior**
User should default to any one of the tenants they have access to, rather than global.

**Screenshots**
![image](https://user-images.githubusercontent.com/9973880/69023393-b6c0d000-0a12-11ea-87f6-a7406844f63e.png)
![image](https://user-images.githubusercontent.com/9973880/69023383-aa3c7780-0a12-11ea-9301-383e1282a121.png)

**Comment by tobybellwood** [comment]
closing - Lagoon itself can't control this?
