### ISSUE TITLE
Clarify details of the PR deployment merges

### ISSUE THREAD

**Issue by Leksat** [uselagoon/lagoon#1425]
According to the current [Lagoon docs](https://lagoon.readthedocs.io/en/latest/using_lagoon/build_deploy_process/#pull-requests), during a PR deployment, Lagoon checkouts base branch and merges the head branch. This is correct in general, but some details are missing.

**Comment by Leksat** [comment]
Also, I was trying to find any Github docs confirming the fact that SHA _may not_ point to the branch HEAD. There was a mention of this [here](https://developer.github.com/v3/activity/events/types/#events-api-payload-41), but this section describes not PRs but something else. So I've found nothing 😕

**Comment by bomoko** [comment]
This issue is massively out of date - I'm closing for now, @Leksat we can reopen if you think we should bring this back into active discussion.
