### ISSUE TITLE
make lagoon-kickstart fails with "Cannot read property 'replace' of null"

### ISSUE THREAD

**Issue by MattBred** [uselagoon/lagoon#144]
When running `make lagoon-kickstart` I get this error before it ever attempts to build in openshift:
```
logs2slack_1                     | ```
logs2slack_1                     | TypeError: Cannot read property 'replace' of null
logs2slack_1                     | ```
logs2slack_1                     | Retrying deployment in 100 secs
```

After debugging, I changed this inside `api-data.gql` 

`KickstartCustomer: addCustomer(input: {name: "kickstart-customer"}) {`
to
`KickstartCustomer: addCustomer(input: {name: "kickstart-customer", private_key: "[ PRIVATE KEY FROM ABOVE IN THE SAME FILE ]"}) {`

This seems to have fixed it, but I am sure this is incorrect?

**Comment by Schnitzel** [comment]
@MattBred 
thats fully correct, thanks a lot! Can you send us a PR for it?
Thansks

**Comment by Schnitzel** [comment]
thanks @MattBred and @RoSk0 <3
