### ISSUE TITLE
Remove left over api-db tables from the RBAC migration

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon#1442]
Now that it's been awhile, it's probably safe to remove the tables in `api-db` that are no longer being used after the RBAC migration:

- `customer`
- `customer_user`
- `user`
- `project_user`
- `user`

**Comment by seanhamlin** [comment]
I'd agree, this is confusing for new people to look into the `api-db` tables and spot users that are no longer valid.
