### ISSUE TITLE
LAGOON_ENVIRONMENT_TYPE incorrectly set on production environments

### ISSUE THREAD

**Issue by stooit** [uselagoon/lagoon#1443]
**Describe the bug**
During buildtime the `LAGOON_ENVIRONMENT_TYPE` env var is incorrectly set to `development` on production environments

**To Reproduce**
1. Deploy a dockerfile with `RUN echo $LAGOON_ENVIRONMENT_TYPE` on a production env
2. Monitor build logs for output
```
Step 8/14 : RUN echo $LAGOON_ENVIRONMENT_TYPE
 ---> Running in 9046db5f4884
development
```

**Expected behavior**
Environment variable should be `production` for prod environments

**Comment by bryangruneberg** [comment]
@tobybellwood @seanhamlin - I'm kinda surprised that this issue hasn't caused more problems for users with production environments 🤔 

Its a bit of a blocker for the Gatsby prototype I'm working on. I need to detect if I'm in a production environment to change what Gatsby does in runtime. I can work around it with checking the environment name, but that's not a great generalized solution.

I'd be up to try help fix this, but I'd need some peer-hand-holding I think. Or maybe a hint on where to start looking.

**Comment by seanhamlin** [comment]
Looks like https://github.com/amazeeio/lagoon/commit/3d9d0cfcdef33297169db5107a9a6ce4116fb5a5 fixes this?

**Comment by tobybellwood** [comment]
yup - fixed in https://github.com/amazeeio/lagoon/pull/2518
