### ISSUE TITLE
Remove `project-` specific tenants in Kibana

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1454]
They seem to create more issues than actually help anything:
- Too many tenants in Kibana can cause issues with too big cookies
- Each tenant creates 2 shards in kibana, which causes elasticsearch to have issues with too many shards
- there are not many developers that only have access to a single project, therefore giving them access to the group tenant should be fine (they still only have permissions to see the actual indexes of their projects they have access to)

**Comment by Schnitzel** [comment]
discussed possible ideas with @smlx 
1. give project only roles access to the global tenant (this would mean any saved searches or visualizations added by a user could be visible by any other lagoon user, not access to the data of that search but see the search itself)
2. create project tenants only if there is an actual user having project only access (need to check with some bigger lagoon installations how many tenants this would create as it could technically end up the same amount of tenants again - short check showed that this probably will end up with the same amount of tenants)
3. give project roles access to the group tenants (this means a user can see other groups project index patterns but not their data)

@smlx and @Schnitzel think that Nr. 3 is probably a reasonable solution as project users will not see the data of any other projects.

therefore remaining work is:
- update lagoon with this new system
- create a migration script that changes the roles in opendistro and also deletes the unused tenants

**Comment by tobybellwood** [comment]
These tenants are no longer created in Opendistro/Opensearch, only the roles
