### ISSUE TITLE
addProject mutation broken

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#1459]
**Describe the bug**
When attempting to add a project via the addProject mutation, an error is returned:

```json
"errors": [
    {
      "message": "Incorrect number of arguments for PROCEDURE infrastructure.CreateProject; expected 17, got 18",
      "locations": [
        {
          "line": 103,
          "column": 3
        }
      ],
      "path": [
        "addProject"
      ]
    }
  ]
```

**To Reproduce**
Via the graphql API, run the addProject mutation
```graphql
  addProject(input:{
    name:"tylerward-testing"
    gitUrl:"git@gitlab.com:twardnw/twardnw_com.git"
    branches:"^(dev|lagoon|prod)$"
    pullrequests:"false"
    productionEnvironment:"prod"
    openshift:104
  }) {
    id
  }
```

**Expected behavior**
The project should be created

**Comment by dasrecht** [comment]
on the api pod i get following error in the logs

``` debug: Keycloak token auth failed: Error decoding token: Grant validation failed. Reason: invalid token (wrong type)```

Are we maybe also running into the issue of too many projects as we saw it with the tenants cookie on elasticsearch?
