### ISSUE TITLE
Download button on backups page displays different

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#1463]
**Describe the bug**
Styling on the `Download` button once a backup has been retrieved is different to the when it is shown as `Retrieve` and `Retrieving`

This results in multiple backups displaying close together when they are ready to download. See attached screenshots

**Screenshots**
![image](https://user-images.githubusercontent.com/9973880/70286566-d718c900-181f-11ea-8134-7107dd1eb648.png)
![image](https://user-images.githubusercontent.com/9973880/70286614-03cce080-1820-11ea-9552-cba78f620e78.png)

**Comment by rocketeerbkw** [comment]
What OS and browser versions are you using?

**Comment by JohnAlbin** [comment]
> What OS and browser versions are you using?

I can confirm this is happening on Chrome. I know how to fix it too; the download button is an `a` tag which defaults to `display: inline`, while the other buttons are `button` tags which defaults to `display: inline-block`. I'll do a quick PR.

**Comment by shreddedbacon** [comment]
Yup, was chrome for me too, sorry should have specified.
