### ISSUE TITLE
Add visual regression tool

### ISSUE THREAD

**Issue by JohnAlbin** [uselagoon/lagoon#1466]
Now that Storybook has been added to the UI service (#1279), we can more easily add visual regression testing to make sure we don't break the existing UI while refactoring a component during bugfix or feature additions.

I'm going to try out the following open-source visual regression tools to see which once work best:
- [BackstopJS](https://github.com/garris/BackstopJS)
- [Loki](https://loki.js.org/)
- [Storybook puppeteer plugin](https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-puppeteer)
- [Cypress + snapshots plugin](https://github.com/meinaart/cypress-plugin-snapshots)

**Comment by tobybellwood** [comment]
We've added Storybook integration now, which supports a visual regression functionality.
