### ISSUE TITLE
Lagoon UI: Hide "Not Authenticated" screen when loading UI the first time

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1469]
Basically now show "Not Authenticated" as we got feedback that people don't like to see this page or it is confusing. Instead just show "logging you in"

**Comment by seanhamlin** [comment]
It also shows in Google etc 

![image](https://user-images.githubusercontent.com/10605846/70461816-5fe47d00-1b1e-11ea-86d0-ae528f56435a.png)

My vote would be for a landing page HTTP 200, to which has some basic information on it, and then if you have a session, a loading animation occurs.

**Comment by dan2k3k4** [comment]
In #2453, I added the title `Login Required` so it would look like this instead:


![image](https://user-images.githubusercontent.com/158704/104483790-cd3bca80-55c8-11eb-987d-8821bf17bd7c.png)
