### ISSUE TITLE
Implement Drush 9/10 Site Aliases Connector for Lagoon

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#147]

**Comment by fubhy** [comment]
I started working on this. So far this seems to be impossible with Drush 9. While it is possible to alter specific site aliases that already exist, it is not possible to dynamically register / inject aliases into the site alias manager. It is also not possible to register additional, custom site alias discovery methods in the site alias manager. The most elegant solution would obviously be to allow the registration of custom discovery strategies but another, very simple solution could be to just add a ``set()`` method to the SiteAliasManager and then call it in a similar fashion to what's already suggested here: https://raw.githubusercontent.com/drush-ops/drush/master/examples/Commands/SiteAliasAlterCommands.php

Let's try to summon @weitzman. Maybe he has an idea / preference for how this should be approached. In any case, this is going to require some work on Drush 9.

**Comment by fubhy** [comment]
After some further investigation I think it might work to just manipulate the SiteAliasFileDiscovery class. Currently, much (all?!) of the code in and around the SiteAlias system in Drush is tightly coupled and very hard to manipulate from the outside. The only way, right now, would be to use Reflection to go from the SiteAliasManager to the SiteAliasFileLoader to the SiteAliasFileDiscovery and then to swap out that class instance with a custom one that also looks up virtual site alias files e.g. by calling a HTTP API. I am not sure why Drush doesn't use a proper service / dependency injection architecture to make it more customizable. /cc @weitzman 

Maybe we can convince the Drush folks to either directly add the ability to add HTTP APIs as potential "search locations" in the FileDiscovery class or by using some sort of composite pattern to allow multiple discovery strategies to be used. However, even if we did that, the FileLoader would still be a problem actually because it does file_exists / file_get_content calls.

I think we are stuck until we get some feedback from the Drush team to find a path forward.

**Comment by fubhy** [comment]
I have one final idea left that might sound crazy at first but would work out of the box. The Drush site alias lookup system relies on the Symfony/Finder class. Now the Symfony finder class is actually a Directory / File system lookup API but it does support FTP/HTTP, etc.! That leaves us with a crafty option. We could provide a dockerized FTP/HTTP/whatever service with a virtual filesystem that provides the site aliases. 

https://secure.php.net/manual/en/wrappers.php

**Comment by greg-1-anderson** [comment]
@fubhy I am open to making the site alias manager hookable. Could you be clear about what you are trying to do?

**Comment by zaporylie** [comment]
@greg-1-anderson I have opened https://github.com/drush-ops/drush/issues/3565 to discuss the possibility of populating an alias list based on a request to the external API.

**Comment by greg-1-anderson** [comment]
I didn't notice this update. I just commented on the issue referenced above.

**Comment by Schnitzel** [comment]
@fubhy 
as the SiteAlias is now it's own repo: https://github.com/consolidation/site-alias does that change anything for us? I'm not sure if during the exporting of the SiteAlias functionality the features we need have been added?

**Comment by greg-1-anderson** [comment]
You also might want to consider the experimental feature [wildcard aliases](https://github.com/consolidation/site-alias#wildcard-environments-experimental).  If your site environments are very regular, then one wildcard alias can be used to define any number of usable remote environments. This is tested and works with Pantheon multidev environments, but we're not using this feature yet.

The upside of using this feature is that you do not need to regenerate your aliases when you make a new site environment.  The disadvantage of this feature is that you never get an error when trying to reference an environment of a valid site using a Drush alias -- Drush will always generate an alias record for the requested environment and then try to use it.

As for hooks in the alias manager, there haven't been any new ones defined. I'm not opposed to adding contributed hooks if desired, but I would caution against doing too much work in any function that is called very frequently, as alias lookup is. The Drush 9 alias manager is way way faster than its Drush 8 counterpart, and we'd like to keep it that way.

**Comment by Feng-Shui** [comment]
I've been looking to do the same thing, dynamic alias generation for remote feature-branch based environments.  Using the wildcard alias as suggested:

```
'*':
  host: ssh-lagoon.govcms.amazee.io
  options: {  }
  root: /app/web
  uri: https://nginx-PROJECTNAME-${env-name}.amazee.io
  user: PROJECTNAME-${env-name}
  ssh:
    options: '-p 30831 -o StrictHostKeyChecking=no'
    tty: false
```

Cons:

1: Assumes entry point is the standard nginx route.
2: Hard codes project name into the alias.

Still, this allows us to target remote environments like this without having to add additional custom entries to the file.

`drush @site.environment-name status`

Things like the project name are available via server vars when drush executes, not sure if they can be injected somehow.

**Comment by greg-1-anderson** [comment]
@Feng-Shui `${env.HOME}` will inject the path to your home directory, and etc. for other environment variables, so this will work for most things. You cannot inject the name of the site, though; there's no wildcard interpolation done on the site alias filename. You will need one alias file per site.

**Comment by tobybellwood** [comment]
Raising importance on this now that Drupal9 isn't compatible with Drush <10

**Comment by tobybellwood** [comment]
Drush 9/10 aliases are now handled best at the drupal layer, using wildcards.  https://www.github.com/amazeeio/drupal-integrations is a good example
