### ISSUE TITLE
Deleting environment variable permission issue

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#1472]
**Describe the bug**
As a maintainer/owner in a group, I am allowed to add environment variables to a specific environment, but when I try to delete this variable it fails with `"Unauthorized: You don't have permission to \"delete\" on \"env_var\"."`

**To Reproduce**
1. Add variable 
```
mutation {
  addEnvVariable(input: {
    type: ENVIRONMENT, 
    typeId: 463, 
    scope: RUNTIME, 
    name: "MYVARIABLENAME", 
    value: "MyVariableValue"}
  ) {
    id
  }
} ## return ID:123
```

2. Note successful variable creation

3. Delete variable 
```
mutation {
  deleteEnvVariable(input: {id: 123})
}
```

4. Get permission denied error
```
"Unauthorized: You don't have permission to \"delete\" on \"env_var\"."
```

**Expected behavior**
I should be able to delete variables I created

**Comment by grahamethompson** [comment]
I have maintainer access and I am experiencing this exact issue.

**Comment by shreddedbacon** [comment]
Bumping priority on this

**Comment by seanhamlin** [comment]
This is now impacting a large customer in Australia. Can we get some more eyeballs on this?

**Comment by grahamethompson** [comment]
^^ yes please

**Comment by Schnitzel** [comment]
@rocketeerbkw can you have a look at this? thanks!

**Comment by shreddedbacon** [comment]
I think this was resolved in #1740

**Comment by grahamethompson** [comment]
sorry to reopen if it's an unrelated issue.

I can still create env vars but not delete them...

```
$ lagoon add variable --project FOO --scope runtime --name BAR --value 'FOOBAR'
Result: success
Project: FOO
Environment: feature/sweet-env
ID: 1234

$ lagoon delete variable --project FOO --name BAR

Error: graphql: Unauthorized: You don't have permission to "delete" on "env_var".
```

**Comment by shreddedbacon** [comment]
@thompsong this is fixed in Lagoon v.1.4.0+

**Comment by grahamethompson** [comment]
Thanks @shreddedbacon. Seems that GovCMS is a bit behind....
