### ISSUE TITLE
environmentByName permission error

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#1473]
**Describe the bug**
As a maintainer/owner in a group, I am unable to view an environment

**To Reproduce**
1. Run `environmentByName` query 
```
query envByName3 {
    environmentByName(name: "branch", project: 100) {
        openshiftProjectName
        name
        envVariables {
          id
          name
          scope
        }
    }
}
```

2. Get permission denied error
```
"Unauthorized: You don't have permission to \"view\" on \"environment\"."
```

**Expected behavior**
I should be able to view environments that I maintain

**Comment by grahamethompson** [comment]
I have maintainer access and I am experiencing this exact issue.

**Comment by timclifford** [comment]
This issue has been resolved.
