### ISSUE TITLE
Deleting a project should delete it's environments

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1475]
**Describe the bug**

At the moment, in order to delete an entire project, you are expected to delete its environments first. Failure to do so will result in orphaned environments in the `api-db` database that you cannot remove with GraphQL. It will also mean that the projects continue to run in OpenShift/Kubernetes with no hope of removing them, except manual intervention with `oc`/`kubectl`.

**To Reproduce**

Steps to reproduce the behaviour:

1. Create project
2. Create environment for above project
3. Delete project
4. Now you cannot delete the environment as the project is deleted

**Expected behaviour**

2 parts

1) If you delete a project, it should loop through all of it's environments and delete them. Potentially, this is just a matter of amending the [stored procedure](https://github.com/amazeeio/lagoon/blob/master/services/api-db/docker-entrypoint-initdb.d/03-procedures.sql#L110-L123).
2) Create a new stored procedure and API endpoint to allow deleting an environment by it's ID (rather than project name and environment name).

**Comment by seanhamlin** [comment]
Bumping priority on this, this is impacting customers all the time, and it means environments are sitting effectively in openshift/kubernetes idle, but running pods.

**Comment by Schnitzel** [comment]
actually we're just talking about not allowing the deletion of projects anymore, as it causes all kind of issues (billing, historical information, etc), but instead implement a "deleted" state of a project (like we already to for environments).

But I think what would be great that we block the deletion of a project if it still has environments?

**Comment by Schnitzel** [comment]
opened https://github.com/amazeeio/lagoon/issues/1817 as a counter solution

**Comment by seanhamlin** [comment]
Ideally there would be a way to automate the deletion of an entire project, and all environments (irrespective of how the data is stored in the database) else you get stuck doing it all manually. Which I am trying to avoid (I am literally doing this as I type).

So if the Lagoon API will not do this, then potentially Lagoon CLI can mask around it. Thoughts @shreddedbacon ?

**Comment by shreddedbacon** [comment]
We could do it in the CLI, but it would mean that people would have to update their CLI to get this feature. 

I proposed the following solution for the API in the CLI issue related to this https://github.com/amazeeio/lagoon-cli/issues/117#issuecomment-611864789

It makes more sense for the API to handle these sorts of things than hacking it into the CLI

**Comment by tobybellwood** [comment]
Enviroinments should be deleted before deleting a project. There are now checks for this.
