### ISSUE TITLE
Unknown Lagoon base image versions

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1482]
**Describe the bug**
For about a week, the `php:7.4-fpm-alpine` image on docker hub has been incompatible with the lagoon php 7.4 Dockerfiles (see the fix in https://github.com/amazeeio/lagoon/pull/1481).

The reason this hasn't been picked up by Lagoon CI, and builds have been successful in the past week, is that the Jenkins nodes have a cached `php:7.4-fpm-alpine` image from _before_ the incompatible change was introduced.

This is a problem because it means that the base images that make up a Lagoon build are of unknown versions. They even differ between Jenkins nodes, so you could get different CI results and build artefacts depending on which node your job runs on.

**To Reproduce**
1. Go and look at all the successful builds of php 7.4 images on Lagoon CI in the last week.
2. Check out latest lagoon/master, and run `docker image pull php:7.4-fpm-alpine && make build/php__7.4-fpm`
3. Watch the build fail.

**Expected behavior**
The CI and/or build scripts should be building in a clean environment by removing all cached images and/or pulling all the base images at the start of a build. Bonus points for storing the hashes of the base images so that the build can be reproduced.

**Screenshots**
n/a

**Additional context**
I've got a partial fix in https://github.com/amazeeio/lagoon/pull/1428, which I will continue working on.

In the meantime maybe it would suffice to `docker system prune -af` at the start of each CI job? Seems like it should work as long as jobs aren't running in parallel on the nodes.

**Comment by tobybellwood** [comment]
partial fixes in place - we now pin to upstream tags
