### ISSUE TITLE
Update elastic images and opendistro to latest release

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1501]
**Describe the bug**
Opendistro `1.2.1` is now available and it now supports ES/Kibana 7.2.1.

https://opendistro.github.io/for-elasticsearch-docs/version-history/

Should we consider upgrading?

Currently we use Opendistro `1.1.0` and ES/Kibana `7.1.?`

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
n/a

**Additional context**
n/a

**Comment by Schnitzel** [comment]
yes we should upgrade, if you want to send a PR I would be happy to merge
