### ISSUE TITLE
Race condition when running tests in parallel

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1506]
**Describe the bug**
https://lagoon-ci.amazeeio.cloud/blue/organizations/jenkins/lagoon/detail/PR-1428/8/pipeline/68/
```
Recreating jenkinslagoonpr14288_logs2rocketchat_1 ... error
ERROR: for jenkinslagoonpr14288_logs2rocketchat_1  Renaming a container with the same name as its current name

ERROR: for logs2rocketchat  Renaming a container with the same name as its current name
Encountered errors while bringing up the project.
Makefile:118: recipe for target 'tests/node' failed
make: *** [tests/node] Error 1
make: *** Waiting for unfinished jobs....
```

**To Reproduce**
It's a race condition, so it doesn't always manifest. However running `make tests -j2` will suffice.

**Expected behavior**
Tests should be able to reliably run in parallel.

**Screenshots**
n/a

**Additional context**
https://github.com/docker/compose/issues/6704 indicates that it happens when running `docker-compose up` on the same container in parallel.

Looking at these targets in the `Makefile`, they run `docker-compose up` on the same containers, and will be run in parallel:
* `$(run-rest-tests)`
* `tests/drupal tests/drupal-postgres tests/drupal-galera`
* `$(run-webhook-tests)`

**Comment by fronbasal** [comment]
I experienced the same issues.
