### ISSUE TITLE
Investigate the feasibility of replacing the lagoon API with a CRDs

### ISSUE THREAD

**Issue by thom8** [uselagoon/lagoon#1509]
As kubernetes gives us a pretty good API out of the box that can easily be extended with custom resource definitions we should look into how we could replace the custom lagoon API.

https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/

This might not make sense for all object of the API and there might be some limitations to the number of objects we can store and query in a reasonable time.

Just a thought to consider when we're looking into native kubernetes support.

**Comment by Schnitzel** [comment]
I think that make sense when we're working on a Lagoon Operator, defining all Project Related things in a CRD instead of the Lagoon API.
Lagoon V2 will be using the existing paradigms to deploy (Lagoon API, etc.) while for Lagoon V3 we definitely could think about using more Kubernetes things. 👍

**Comment by tobybellwood** [comment]
Not a CRD, but still up for a bit of discussion
