### ISSUE TITLE
Python CKAN images use deprecated python version

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1515]
**Describe the bug**

Python CKAN images are 2.7 only, and [that version of python is now EOL](https://pythonclock.org/).

**To Reproduce**

1. View the `Makefile`: https://github.com/amazeeio/lagoon/blob/312dfe719119f93f9293686320d0a083670c2280/Makefile#L223-L227

**Expected behavior**

CKAN images should use a supported version of python, which currently [appears to be 3.7 or 3.8](https://python-release-cycle.glitch.me/).

**Screenshots**

n/a

**Additional context**

#1514 is related.

**Comment by tobybellwood** [comment]
looks like Python2 will have to stick around a bit to support the CKAN images, which don't appear to be python3 ready as yet - https://github.com/ckan/ckan/issues/4681 and https://github.com/ckan/ckan/projects/3

**Comment by tobybellwood** [comment]
Will address elsewhere
