### ISSUE TITLE
CKAN datapusher image fails to build properly

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1518]
**Describe the bug**
Building the python 2.7 CKAN datapusher image results in lots of errors and fails to correctly build `uwsgi`.

**To Reproduce**
1. Build the python 2.7 CKAN datapusher image: `rm -f build/python__2.7-ckandatapusher && make -e DOCKER_BUILD_PARAMS='--no-cache' build/python__2.7-ckandatapusher`
2. Observe the build errors.

**Expected behavior**
The image should build without errors.

**Screenshots**
n/a

**Additional context**
Noticed this when testing #1517

**Comment by tobybellwood** [comment]
now working again
