### ISSUE TITLE
Update New Relic PHP Agent to 9.6.0.255

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#1543]
**Describe the bug**
Newrelic PHP Agent has been released - https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-950252

**Comment by seanhamlin** [comment]
Also noting that `PHP 7.4` was added as supported in the agent version `9.4` (latest version is now `9.6.0.255`)

I might have a stab at this today.
