### ISSUE TITLE
Openshift Rollouts failing builds - watching Daemonsets is broken in 3.11

### ISSUE THREAD

**Issue by justinlevi** [uselagoon/lagoon#1544]
Develop and Master builds are failing on Openshift 'with the following error:
```
oc rollout --insecure-skip-tls-verify -n lagoon-dev-develop status daemonset logs-collector --watch
Waiting for daemon set spec update to be observed...
Waiting for daemon set spec update to be observed...
error: watch closed before Until timeout
```

1. Login to the open shift US cluster and try to build the Develop or Master branches

**Expected behavior**
Builds succeed

**Comment by Schnitzel** [comment]
it looks like there is something broken with `oc` and watching deamonsets. There are some other people having the same problem but on regular deployments:
https://github.com/kubernetes/kubernetes/pull/67817

while for us this only happens for deamonsets, here an example for a regular deployment:

```
oc rollout --insecure-skip-tls-verify -n lagoon-dev-develop status deployment harbor-core --watch
deployment "harbor-core" successfully rolled out
```

as Lagoon itself is the only piece that actually can create DeamonSets (regular Lagoon projects are not allowed to create DeamonSets) I think the easiest right now would be to just disable the rolllout monitoring of Deamonsets (still deploy them, just don't monitor the rollout), the code happens here:
https://github.com/amazeeio/lagoon/blob/7ddbcc247c9bb23b35cd15b182033fda3f2cb098/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L988-L992

**Comment by smlx** [comment]
https://github.com/amazeeio/lagoon-kbd fixes this issue.
