### ISSUE TITLE
Update Solr images (inc Solr 7.7 support)

### ISSUE THREAD

**Issue by janmashat** [uselagoon/lagoon#1557]
Latest available solr image is 7.5 on https://hub.docker.com/r/amazeeio/solr/ - however <7.7 are EOL according to https://lucene.apache.org/solr/downloads.html

**Comment by dasrecht** [comment]
Hi @janmashat we're looking into this 

The current issue is, that the the solr upstream images aren't built on alpine linux anymore and  are not compatible with lagoon currently 

https://github.com/docker-solr/docker-solr/issues/257

We'll be looking into switching over to the newer versions soon but it seems not to be straight forward for now.
