### ISSUE TITLE
API: Introduce Viewer & Edit Roles

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#156]
Currently we have an Admin and User Role and if you have the User Role you can also edit all the Objects you have View Rights too (after #154 has landed)
After talking with some CTOs/TechLeads of our clients, they don't feel comfortable to give all their Developers Edit rights. So we would split up the regular User Role into two different ones:
1. Viewer Role: Has basically Viewing rights to all the Objects that the User has access to already (via customer and project permissions)
2. Edit Role: Has Viewing and update/create/delete Roles for the Objects.

I could Imagine that the setting which role the user has could happen in the SSHKeytoCustomer and SSHKeytoProject Object, with an easy setting if the User/SSHKey is a viewer or editor

**Comment by tobybellwood** [comment]
Now that RBAC is available in 1.0.0 this is superseded
