### ISSUE TITLE
Environment deletion via UI broken when deployment branch config is a regex

### ISSUE THREAD

**Issue by thom8** [uselagoon/lagoon#1560]
**Describe the bug**
Lagoon fails to queue deletion of an environment when a project defines a regex for branch deployment.

**To Reproduce**
1. Go to a project which has a regex defined for deployment
2. Find an environment that can be deleted
3. Try to delete environment via the UI
4. Status will switch to `Delete queued` then an error is thrown - `GraphQL error: configured regex '^[regex]$' does not match branchname 'undefined'`

**Expected behavior**
The environment deletion is queued.

**Screenshots**
![image](https://user-images.githubusercontent.com/331453/72758923-08672000-3c39-11ea-98c4-310441ac84a2.png)

**Additional context**
The same error is thrown when deleting environments via GraphQL.
The deletion is successful if you switch the branch deployment config to `true`.

**Comment by smlx** [comment]
Looks as though 33b41855579a80ab6613ec18903c420625ed51e0 updated the function but not the [call sites](https://github.com/amazeeio/lagoon/blob/a391f6df8c3e04313bf0431a1a4f24fe21fea8fe/services/webhooks2tasks/src/handlers/githubBranchDeleted.js#L24).
