### ISSUE TITLE
Deleted projects aren't cleaned up from groups

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon#1562]
**Describe the bug**
We found a group that still had references to lagoon projects that had since been deleted. Do some discovery to figure out if this was a one-time thing or an actual problem. If it's a bug, fix it!

**To Reproduce**
- We found one group on production and fixed it manually so 🤷

**Expected behavior**
No groups should have references to deleted projects

**Screenshots**

**Additional context**

**Comment by rocketeerbkw** [comment]
The deleteProject API resolver doesn't clean up groups, so this is def reproducible and causing problems.

**Comment by rocketeerbkw** [comment]
We should also add a one-time migration script to clean up all the existing groups. We could also update the group model so that it doesn't throw errors if a project doesn't exist (see https://github.com/amazeeio/lagoon/blob/master/services/api/src/resources/group/resolvers.ts#L488 and https://github.com/amazeeio/lagoon/blob/master/services/api/src/resources/project/helpers.js#L73)

**Comment by shreddedbacon** [comment]
Could #1533 be addressed at the same time as this potentially?

**Comment by tnelson-doghouse** [comment]
Bug found in some of our groups; it's being fixed manually.
