### ISSUE TITLE
Invetigate "task:remove-openshift-resources:" event and remove if necessary

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon#1565]
**Describe the bug**
All of our notification services act on `task:remove-openshift-resources:` events but it looks like none of our services actually trigger it. I think this is a tech-debt leftover. Instead I think the event is `task:remove-openshift:`?

**To Reproduce**
1. grep for task:remove-openshift-resources:
2. See that is only listed in notification services and readme
3. fix?

**Expected behavior**
We don't have this tech debt anymore

**Comment by tobybellwood** [comment]
Lagoon doesn't support Openshift (3) any more, closing
