### ISSUE TITLE
SSH key not set when adding project

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1583]
**Describe the bug**
Use the `addProject` mutation and provide a `privateKey`. This private key is not set on the resulting project - one is auto-generated instead.

**To Reproduce**
1. Add a new project using `addProject`, and provide a `privateKey`.
2. Inspect the project.
3. See that a key has been generated instead.

**Expected behavior**
I expect the provided privateKey to be used for the project.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by timclifford** [comment]
Tested and this no long is an issue
