### ISSUE TITLE
Image - Elasticsearch helm chart - create

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#1589]

**Comment by smlx** [comment]
This can be closed once https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/294 is implemented.

**Comment by twardnw** [comment]
The original intention for this ticket was for use by clients, we'll still need to solve that for clients to deploy ES

**Comment by SyneticDevOps** [comment]
We also need this before we can move one of our customers to lagoon.

**Comment by daamol** [comment]
We also need this before we can move some of our sites to Lagoon.

**Comment by tobybellwood** [comment]
Specifically, this is for single-node Elasticsearch in customer projects, as any cluster-wide ES is provided via a different chart

**Comment by seanhamlin** [comment]
This will be required for a large customer in APAC to move to native kubernetes on Lagoon 2. Flagging as a blocker on that.
