### ISSUE TITLE
Service - Broker/RabbitMQ Helm Chart - create/use upstream

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#1597]
Do we have anyone who uses our RabbitMQ images in their projects, or is it just us in the broker service?

RabbitMQ
https://github.com/amazeeio/lagoon/tree/master/images/rabbitmq
RabbitMQ Cluster
https://github.com/amazeeio/lagoon/tree/master/images/rabbitmq-cluster
Broker
https://github.com/amazeeio/lagoon/tree/master/services/broker

Can we use an existing chart, e.g. https://hub.helm.sh/charts/stable/rabbitmq-ha

**Comment by smlx** [comment]
There's a `lagoon-core` chart now that deploys the Lagoon broker, but we should still look at just using an upstream chart so leaving this open.
