### ISSUE TITLE
custom helmchart in .lagoon.yaml

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#1600]
Currently, in the `.lagoon.yaml`, customers can ship a custom openshift template which is referenced by path. Rather than shipping an extra file, we should modify this pattern to allow custom charts to be shipped in the `.lagoon.yml`, this eliminates the need for the `custom` OpenShift template, as the custom chart can contain it's own CronJob resources

**Comment by xantrix** [comment]
Not sure if #1863 it is strictly related to this but I'm also got an error during deploy of custom service in Kubernetes (custom chart was missing).

**Comment by tobybellwood** [comment]
This is no longer supported in Lagoon
