### ISSUE TITLE
Disable caching of large binary files in Varnish

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1613]
**Describe the bug**

In order to protect the soon to be 500MB of Varnish cache (see #1585), Varnish should avoid caching static files that are > 10MB. This is because they are likely going to be served from nginx very quickly, so the overhead of Varnish storing them is pointless.

**Expected behavior**

Large binary files are not cached in Varnish. Perhaps there could be a new environment variable to make this configurable as well.

**Comment by smlx** [comment]
Another option is to protect the small objects by keeping them in a separate stevedore to the larger objects. E.g. split it maybe something like 200MiB (> 10MiB objects), 300MiB (<10MiB objects)?

Some more details on this type of config here: https://info.varnish-software.com/blog/partitioning-your-varnish-cache

**Comment by seanhamlin** [comment]
A customer was impacted when they tried to serve a 409MB exe file from Drupal's public filesystem

```
/sites/default/files/PetLinx6SetupFull.exe
```

It seemed that the connection to the file would just stop working. A pass in Varnish for `.exe` would be neat.
