### ISSUE TITLE
make k3d has no dependency on local-registry service running

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#1616]
When `make k3d` is run, it should specify that (at minimum) the `local-registry` service in docker-compose is up and running. Additionally, it could extend to start all the services specified for `make k8s-tests`.

**Comment by vincenzodnp** [comment]
I think it's already implemented.
`$(MAKE) local-registry-up` is already part of the recipe

**Comment by tobybellwood** [comment]
closing, as this is the old make/build system
