### ISSUE TITLE
Locking a Drupal environment (content and/or config)

### ISSUE THREAD

**Issue by simesy** [uselagoon/lagoon#1622]
I would like Lagoon to support the idea of locking environments which is independent of production/development flags.

> As a client, I want to make WIP changes in an environments, and be certain that they are protected.

The problem is that Lagoon doesn't have a standardised official notion of a "locked" environment. So if you look at GovCMS, there should be a way of saying "We're about to sync the database" or "we're about to import config" but you should be able to check a value from `.lagoon.yml` (or whatever) to be sure this is allowed.

My proposal is that there is a documented LAGOON_* environment variables for this purpose.

I sketched out how this might look (with GOVCMS name-spacing) here:
https://github.com/govCMS/scaffold-tooling/blob/develop/scripts/govcms-deploy#L8-L12

(__OUT OF SCOPE__ Moving content between environments is not Lagoon's problem - this is solved in various ways, eg with `deploy` or `entity_pilot` modules.)

**Comment by simesy** [comment]
An example of this is when an organisation wants to curate a large set of content/config and code on non-production.

This is related to the blue/green concept. However the blue/green concept is a limited model, as it only ever allows one environment that can be updated.

However a tool like `entity_pilot` is amazing. it allows editors to work on content in any number of environments and then to deploy content from one to another.

Example, a commerce site.

`master` - the production site has ongoing BAU changes -  content and code fixes. "Config import" is currently locked, because the administrator is updating views and other things on a daily basis, and he's not a developer. At some stage a developer will capture these changes back into code.

`feature/xmas-sale` - content and some code changes for the upcoming christmas sale. "Content sync" and "Config import" is locked because you don't want to overwrite the content and views changes being made.

`feature/checkout-improvement` - meanwhile there is a project to fix the UX of the shopping experience, and this is requires some blocks and other content to be created. "Content sync" is locked because you don't want to overwrite the content, but "Config import" in enabled as developers are pushing code and config on a regular basis.

**Comment by seanhamlin** [comment]
So with this request, having fairly generic env vars like

* `LAGOON_CONFIG_LOCKED` - configuration is prevented from being imported (e.g. `drush cim` for Drupal 8).
* `LAGOON_CONTENT_LOCKED` - content imports are prevented from being imported (e.g. `deploy`, `entity_pilot` for Drupal 7 or 8)

There could be base logic in the Lagoon upstream images to support this, but ultimately customer images would need to also enforce this (e.g. if the deployment script is customised).

I think as long as the topics are fairly abstract (e.g. content and config) I am OK with this as a thing in Lagoon. It would mean that potentially in the future this information could be exposed in the API and UI.

I would be keen to gauge how many other people and sites would find this useful.

**Comment by simesy** [comment]
Thanks Sean, yes that's pretty much it.

**Comment by tobybellwood** [comment]
is this another use case for being able to add and expose tags to Lagoon envs... https://github.com/amazeeio/lagoon/issues/1289

**Comment by bomoko** [comment]
Hi all,
So we're going through our (not insubstantial) feature request list at the moment, categorizing and closing what doesn't make sense anymore.

I think that this may have made a lot more sense when Lagoon was more tightly integrated with Drupal, but it feels like with metadata and environment variables this is something that can be enforced by users at a project level.

I'm going to close this for now - but I will raise this in the Dev Experience team - we might want to resurrect this idea as something like a "lagoon recipe" and write up how one might achieve this using Lagoon.
