### ISSUE TITLE
add lagoon-cli to lagoon CLI images

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#1623]

**Comment by shreddedbacon** [comment]
https://github.com/amazeeio/lagoon-cli/issues/45

**Comment by vincenzodnp** [comment]
Added a comment in the lagoon-cli issue above.
Do you think it's better have lagoon-cli in all cli images or just toolbox one?

**Comment by tobybellwood** [comment]
discussed elsewhere
