### ISSUE TITLE
Opendistro SQL plugin to support CSV export

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#1624]
Since CSV is not full supported via Kibana/Opendistro in the UI and using the security plugin for tenants

Can it be done with the SQL plugin? https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#sql

**Comment by tobybellwood** [comment]
the elastic sql plugin does include a format=csv option, so probably? https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-rest-format.html

**Comment by shreddedbacon** [comment]
Was more reference to using it with security plugin for tenants. It does work though, PR coming.
