### ISSUE TITLE
update lagoon/tests image to inherit lagoon/python:3.7 and run Python3

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon#1626]
Currently the lagoon/tests image used to run the ansible used in tests is running alpine3.10/Python2/ansible and built from scratch.  Can we update this image to build from our python:3.7 image and run python3/ansible?

https://github.com/amazeeio/lagoon/blob/master/tests/Dockerfile#L1

**Comment by smlx** [comment]
This is starting to generate lots of warnings in CI.

**Comment by tobybellwood** [comment]
Done!
