### ISSUE TITLE
rename cli from `io` to new name

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#164]
in the process of de-amazeeiofying Lagoon we also need to find a new name for the CLI (currently called `io`).

My own brainstorming came up with these ideas:
- `lagoon` - well, lame :D plus also very long
- `goon` - a bit used by Defcon an it's Goons already
- `lagu` - my most prefeered name so far, short, has similarities to lagoon. Not used by anything really

what do you think?

**Comment by karlhorky** [comment]
Just getting back from the holidays. Options sound interesting! Maybe also different abbreviations like `lgn` or `lag`. Will think about some options and get back to this this week.

**Comment by ryyppy** [comment]
i vouch for `lag` ... sounds like a cool abbreviation

**Comment by Schnitzel** [comment]
let's use `lagu`
