### ISSUE TITLE
Command failed with signal "SIGSEGV"

### ISSUE THREAD

**Issue by fjgarlin** [uselagoon/lagoon#1659]
**Describe the bug**
Some builds stop with `Command failed with signal "SIGSEGV".` with no further information. Re-triggering a new build often fixes the problem and everything builds ok on `docker-compose build`

**To Reproduce**
1. *Fail:* See link in slack channel (not here due to privacy)
2. *Fail:* See link in slack channel
3. Re-trigger deploy via Lagoon UI or empty commit to branch 
4. *Success:* See link in slack channel

**Expected behavior**
Builds are either successful if everything runs correctly on `docker-compose build` or more information is provided about the error.

**Screenshots**
N/A

**Additional context**
This is happening on the `blue-value` project and additional info can be requested on `#blue_value_interal` slack channel in `amazee.slack.com`

Link with full logs in slack message here: https://amazee.slack.com/archives/CMA8229GQ/p1581585737106800

**Comment by dasrecht** [comment]
closing as it's not a lagoon issue
