### ISSUE TITLE
Add support for MariaDB >= 10.3

### ISSUE THREAD

**Issue by twerthmueller** [uselagoon/lagoon#1666]
Currently no MariaDB version > 10.2 is officially supported from Lagoon: https://lagoon.readthedocs.io/en/latest/using_lagoon/#supported-services-base-images-by-lagoon

Would be grate to have the possibility to use version 10.3 to be more equivalent to MySQL 8.

**Comment by tobybellwood** [comment]
Hi - this is being looked at in https://github.com/amazeeio/lagoon/pull/892 - the :latest alpine version packages 10.4, which requires some more configuration.  Will make sure this gets worked on!
