### ISSUE TITLE
Make Lagoon aware of a project type

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1673]
**Describe the feature**

At the moment Lagoon has no concept of the type of application that it is running, just what images it needs to run. It would be a great advantage for Lagoon to know roughly what type of application is running in order to customise the UI more.

**Types of applications**

Broad strokes here, something like

* Drupal 7
* Drupal 8
* NodeJS
* Laravel
* Symfony 5
* Silverstripe 4
* Static

Would be sufficient

**What could we use this information for**

I see a lot of possibilities, but for a start:

* Able to show a logo of the application in the UI (nice)
* Able to remove task buttons that do not apply (e.g. hide the `drush cron` buttons for a Laravel application)
* Able to build a library of tasks for other applications, without fear of them polluting the interface of other applications.
* Being able to filter the project list by application type

**How this could be achieved**

Perhaps Lagoon could make an educated guess based on the files in the containers, or perhaps it could be manually set in `.lagoon.yml`. Open to discussion on this.

**Comment by tobybellwood** [comment]
Lagoon now has both Facts and Metadata to support this, and the UIv2 will expose this to users
