### ISSUE TITLE
Allow users to update environment variables value and scope

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1677]
**Describe the bug**

At the moment with Lagoon, you can create new environment variables. You however can't update the value or scope (e.g. `global` or `runtime`) of the environment variable in the future. If you have the ability to create, surely this would mean you can update as well.

The impact of this bug is that you are forced to:

1. delete the current environment variable
2. create a new environment variable with the same name but with the new value/scope

This however is 2 GraphQL API requests, when 1 would be safer (no messing up the name), atomic (no chance of a build with no environment variable), easier for everyone (1 API request) and less confusing.

This also will mean that customers with heavy use (read - automated) of environment variables will end up hitting the API a lot more than necessary, which could impact scaling in the future.

**Expected behaviour**

If you have the ability to create environment variables, you should also be able to update them. At least the value of the variable and and scope of the variable should be updateable.

**Impacted customers**

At least 2 large customers in APJ are impacted by this.

**Comment by tobybellwood** [comment]
Permissable scope changes would be build>runtime>global etc - but project>environment not possible
