### ISSUE TITLE
Mojibake in Lagoon API JSON

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1681]
**Describe the bug**
The Lagoon API sometimes returns incorrectly encoded JSON.
The specific string I noticed the issue on is this one returned from the Lagoon API (slightly edited):

![moji0](https://user-images.githubusercontent.com/861778/74995549-2f10b480-548c-11ea-836e-95867a12b8d7.png)

**To Reproduce**
To reproduce the issue you can edit a database table directly to add a multibyte utf-8 character to a project title, and then list projects using the lagoon cli.

E.g. add "…" to a project tile:

![moji1](https://user-images.githubusercontent.com/861778/74995585-4a7bbf80-548c-11ea-8163-4ed235f53f98.png)

And then list projects using the `lagoon-cli`:

![moji3](https://user-images.githubusercontent.com/861778/74995605-536c9100-548c-11ea-877a-450907427592.png)

**Expected behavior**
There are two problems with this. The first is the mojibake, and the second is that JSON is defined to be UTF-8 encoded, which the string shown in the first screenshot isn't.

I'd expect:

* Lagoon to handle non-ascii glyphs cleanly, and preferably _only_ UTF-8 throughout.
* the JSON library used by the Lagoon API not to encode invalid JSON.

**Screenshots**
See above.

**Additional context**
https://en.wikipedia.org/wiki/Mojibake

**Comment by rocketeerbkw** [comment]
I couldn't reproduce the error on a new install. Looks like new lagoon installs get a database with [utf8](https://github.com/uselagoon/lagoon/blob/main/services/api-db/Dockerfile#L20-L21) already.
