### ISSUE TITLE
Dark mode support for Lagoon UI

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1687]
**Describe the feature**

It would be great if the CSS of the Lagoon UI was adapted to support dark mode when your OS has enabled this.

**Comment by Schnitzel** [comment]
⬛️⬛️⬛️⬛️⬛️⬛️⬛️⬛️⬛️
⬛️⬛️⬛️⬛️⬛️⬛️⬛️⬛️⬛️
⬛️⬛️⬛️⬛️⬛️⬛️⬛️⬛️⬛️
⬛️⬛️⬛️⬛️⬛️⬛️⬛️⬛️⬛️

**Comment by dan2k3k4** [comment]
Rough idea?

![image](https://user-images.githubusercontent.com/158704/104647348-02701780-56b2-11eb-95e7-5657db170df5.png)

We'll need to use [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

We _could_ potentially migrate to [TailwindCSS](https://tailwindcss.com) and use the [dark-mode](https://tailwindcss.com/docs/dark-mode) setup they have?

**Comment by timclifford** [comment]
We are looking at supporting this for v2, however its not a high priority issue
