### ISSUE TITLE
BASIC_AUTH docs need tweaking

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1697]
**Describe the bug**

The [current docs](https://lagoon.readthedocs.io/en/latest/using_lagoon/docker_images/nginx/#basic-authentication) mention 2 of the 3 variables you can use to control `BASIC_AUTH` in Nginx.

There is another variable that needs documenting `BASIC_AUTH`

The link in that section to environment variables is also broken, and should point to https://lagoon.readthedocs.io/en/latest/using_lagoon/environment_variables/ likely.

**Comment by Schnitzel** [comment]
how I read this code:
https://github.com/amazeeio/lagoon/blob/60eb80e6fc6b808ab44722ebfecd24ac1392877d/images/nginx/docker-entrypoint#L4-L12
the `BASIC_AUTH` is set automatically if `BASIC_AUTH_USERNAME` and `BASIC_AUTH_PASSWORD` are set.

not sure what @seanhamlin you are referring too?

**Comment by seanhamlin** [comment]
At present I think the logic

```
if [ ! "${BASIC_AUTH}" == "off" ]; then 
```

Must be not functioning as people expect it to. I just had a customer mention that by *not* setting `BASIC_AUTH`, basic auth was not enabled. After setting `BASIC_AUTH=1`, it was.

So either this is a docs issue, or code, or both.

---

I wonder if [this has something to do with it](https://linuxize.com/post/how-to-compare-strings-in-bash/):

```
Use the == operator with the [[ command for pattern matching.
```

I use `zsh`, so unsure if this is the same as bash:

```
$ BASIC_AUTH=1; if [ ! "${BASIC_AUTH}" == "off" ]; then echo 'enabled' ; fi
zsh: = not found

$ BASIC_AUTH=1; if [[ ! "${BASIC_AUTH}" == "off" ]]; then echo 'enabled'; fi
enabled

$ export BASIC_AUTH=
$ if [[ ! "${BASIC_AUTH}" == "off" ]]; then echo 'enabled'; fi
enabled

$ export BASIC_AUTH=off
$ if [[ ! "${BASIC_AUTH}" == "off" ]]; then echo 'enabled'; fi
```

---

I will amend my PR to incorporate the desired logic. This however may cause applications that previously did not have basic auth, to now suddenly have it.
