### ISSUE TITLE
Add tests for Lagoon tasks

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon#1702]
We currently have no tests for the lagoon tasks system. As a part of adding vanilla k8s support for tasks, it'd be great to get integration tests working for these.

My idea for how this would work:

- Use the ansible tests infra that already exists
- Since the current "built-in" tasks (like drush cache clear) require a drupal project, create a new project that uses the drupal 8 code
- Deploy the new project as part of the tests but don't remove it automatically
- Use the API to create a couple tasks that can test all the functionality of the system
- Test the tasks by creating a new API ansible script that can "fetch/compare/retry" a graphql query the same way the tests currently do for URLs
- After all task tests pass, then delete the project

At the minimum we should test that a single task get created and "succeeds" but ideally we'd test all possible status and all the task mutations. Also test that the data gets sent back to the API correctly (check that start/end times are correct, remote ids, etc).

**Comment by tobybellwood** [comment]
Lagoon tasks are now tested
