### ISSUE TITLE
make build fail building lagoon/php:7.0-fpm

### ISSUE THREAD

**Issue by aldibier** [uselagoon/lagoon#1706]
When "make build" command  try to create lagoon/php:7.0-fpm lagoon/php:7.0-fpm it's generate an error compiling PHP

checking Check for supported PHP versions... configure: error: not supported. Need a PHP version >= 7.1.0 and < 8.0.0 (found 7.0.33)
ERROR: `/tmp/pear/temp/xdebug/configure --with-php-config=/usr/local/bin/php-config' failed

**To Reproduce**

1. Go to lagoon repository cloned
2. Execute make build
3. Wait until lagoon/php:7.0-fpm build

**Expected behavior**
The expected behaviour is a successfull image created

**Screenshots**

![Screenshot_20200309_123920](https://user-images.githubusercontent.com/908212/76241721-6a88de00-6203-11ea-881b-a9f7864181c3.png)

**Comment by Schnitzel** [comment]
@aldibier thanks for your issue!
We actually don't support PHP 7.0 anymore, support has been removed in the master branch already, and will also be removed in the newest release 1.3.0 which will go out in the next couple of days.

**Comment by aldibier** [comment]
Thank you @Schnitzel , thank you for your clarification, I confirm that execute "make build" from master is working, thanks for the amazing work.

**Comment by tobybellwood** [comment]
PHP7.0 build has now been deprecated - our legacy images are still available, but unmaintained.
