### ISSUE TITLE
Invalid environment variables when a service name contains a dash.

### ISSUE THREAD

**Issue by thom8** [uselagoon/lagoon#1708]
When creating a service in lagoon via docker-compose where the name contains a dash, eg `mariadb-test`, the name is used as the prefix for setting environment variables via the service broker.

This causes issue for the application reading the variables and the backup system as the variables are only expanded up until the dash in the variable name.

**To Reproduce**
1. Create or modify a docker compose service which implements a lagoon type using the service broker.
2. rename the service to include a `-` eg. `mariadb-test`
3. Deploy the project to a lagoon
4. The environment variables in the `lagoon.env` configmap will contain the dash. eg. `MARIADB-TEST_DATABASE`

**Expected behavior**
These are convert to an underscore to be valid environment variables.

**Comment by CGoodwin90** [comment]
Tested with mariadb-test and values were converted to mariadb_test

![Image](https://user-images.githubusercontent.com/40746380/205174419-92fcd923-8adf-4e26-9404-37f6ccc3df9b.png)
