### ISSUE TITLE
userByEmail API

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon#1709]
Similar to https://github.com/amazeeio/lagoon/pull/1104 it might be worth to have a function that returns `user` by querying his email.

**Comment by vincenzodnp** [comment]
@rocketeerbkw @Schnitzel any new about this request?
At the moment, the only way to gather user's info is by ssh key (isn't it?).

**Comment by Schnitzel** [comment]
@vincenzodnp
currently you cannot search for users via email addresses via the graphql api, but this should be an admin only action anyway (privacy and security), if you need it for a one time search (and not via an automated system that needs an API), you can search for email adresses directly in the keycloak UI.
can you elaborate why this feature is important? you mention "might be worth to have", this doesn't sound very urgent.

**Comment by vincenzodnp** [comment]
I agree is not urgent but it's a bit annoying to search for user's info in Keycloak UI or via lagoon cli.
ATM, when I have to check for user's attributes like groups the user belongs to, I get the key via lagoon cli and then I run the `userBySshKey` GraphQL query.

**Comment by tobybellwood** [comment]
This would be handy
