### ISSUE TITLE
Support NodeJS 13

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1711]
the title says it all :)

**Comment by rocketeerbkw** [comment]
or not? https://github.com/amazeeio/lagoon/issues/1668#issuecomment-587812051

**Comment by Schnitzel** [comment]
Oh, wasn't aware that 14 comes out already end of April. @zanettin as you asked for this, how urgent is nodejs 13 for you? and could we maybe wait for nodejs 14 that comes out end april, so we would have the base images ready beginning of may?

**Comment by zanettin** [comment]
@Schnitzel 14 is also okay if you want to skip 13. thx

**Comment by Schnitzel** [comment]
@zanettin cool, closing this and opened #1712
