### ISSUE TITLE
Openshift projects not removed if lagoon project name longer than 60 chars

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon#1714]
**Describe the bug**
`openshiftremove` service is not able to remove Openshift project/namespace if the name of lagoon environment is longer than 60 chars

**To Reproduce**
1. Create a project with an environment with a name longer than 60 chars
2. Delete environment via Lagoon CLI or API
3. Check GraphQL API and environment doesn't exist anymore
4. Check Openshift UI or CLI and see project still exists

**Expected behavior**
After an environment is deleted, it might be deleted from API and Openshift

**Comment by tobybellwood** [comment]
openshiftremove has been deprecated in Lagoon 2
