### ISSUE TITLE
Add mongodb-tools to mongodb base image

### ISSUE THREAD

**Issue by bomoko** [uselagoon/lagoon#1718]
We have some requests for the mongodb-tools apk to be available within the mongodb image, specifically to allow restoring of backups (using the mongorestore tool).

**Comment by tobybellwood** [comment]
yup - the whole mongodb image needs a revisit, because the packages are no longer available on apk, so a base image switch is needed.

**Comment by vincenzodnp** [comment]
I've opened the above PR to include tools in the base image
