### ISSUE TITLE
Self-Service ssh key adds `_` if the ssh key has a comment

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#1725]
**Describe the bug**
Adding an ssh key via self-service `ssh-rsa SSHKEY foo@bar.baz`
Will end up as ssh key `SSHKEY_foo@bar.baz` in the API rendering further access with the key impossible.

**Expected behavior**
I see two ways of solving that.

One would be the way most of the GIT providers do it and basically give only one field to add a key - the stripping of comment and key-type is done behind the scenes afterwards.

This would be easier for the UX as customers might not be aware that they need to only paste the key portion of their key.

Alternatively we could try to be clever on the self-service and strip the comment away

**Comment by rocketeerbkw** [comment]
https://github.com/amazeeio/lagoon/pull/1745
