### ISSUE TITLE
Pre-rollout tasks cause deployments to fail on newly created Lagoon environments.

### ISSUE THREAD

**Issue by cdchris12** [uselagoon/lagoon#1726]
**Describe the bug**
When creating a new environment via the first push, if a `pre-rollout` task is defined, the build will fail. This is due to the fact that pre-rollout tasks are, by their nature, to be executed _before_ the built containers are rolled out. Thus, the attempted command fails with an error message similar to:
```
Error from server (NotFound): pods "null" not found
```

**To Reproduce**
1. Create a new branch of an already existing project, and ensure a `pre-rollout` task is defined in `lagoon.yml`.
2. Push the new branch in order to create a Lagoon build.
3. View logs once build fails.

**Expected behavior**
In the case that any pre-rollout task(s) cannot be completed due to the specified pods not existing because this is the first deploy to a Lagoon environment, the pre-rollout task(s) should simply be skipped.

**Comment by Schnitzel** [comment]
mhh, this should be handled by https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/scripts/exec-pre-tasks-run.sh#L17-L19
but I think https://github.com/amazeeio/lagoon/pull/1529 broke that, as `$POD` is now not empty, but filled with `null`. 
I think @smlx can help us here?

**Comment by rocketeerbkw** [comment]
I fixed this when I merged `master` into `kubernetes` in https://github.com/amazeeio/lagoon/commit/3168fffcb5234e6148dae14ae8ac38a29f32ad15#diff-aa5d30ee04ad43ee9ef99d2befa04f3c
