### ISSUE TITLE
Drush ULI task should inform the user when UID1 is blocked

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1729]
**Describe the bug**

At the moment, if UID1 is blocked, then drush will still generate a one time login link, however when visited, it will yield 'access denied' ([see the s.o question](https://drupal.stackexchange.com/questions/179259/drush-uli-generates-correct-link-but-results-in-access-denied)).

**To Reproduce**

1. Block UID1
2. Generate one time login link
3. Click it

**Expected behavior**

Perhaps drush can check to see if UID1 is blocked as a pre-flight command, and if so, it will present the user with a message informing them of such, and refusing to generate a one time login link.

**Comment by klonos** [comment]
...while at it, perhaps also add a more meaningful error when the user does not have permission to run the task ...here's what's thrown when trying to run the "drush uli" task on master:

![Screen Shot 2020-05-18 at 1 28 30 am](https://user-images.githubusercontent.com/2423362/82163550-a64fbc00-98b4-11ea-9b32-20a3da446e09.png)

...better yet, hide the task in the first place, if the user does not have permission to run it.

**Comment by tobybellwood** [comment]
Drush ULI task to be rewritten anyway
