### ISSUE TITLE
figure out a way to present lagoon documentation 

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#173]
we expect to have two types of lagoon documentation:
- documentation how to run lagoon (admin documentation)
- documentation how to use lagoon (user documentation)

both of it we expect to be part of the lagoon git repo.

This issue is to find a nice way for people to read the documentation

**Comment by twardnw** [comment]
I asked for opinions from a handful of developers I know, they mostly seemed to like some lightweight docs in the code repo, or having comment-generated docs for admin/developers there. Only one person liked the idea of having end-user documentation included in the same repo.

Most agreed that readthedocs was a good place to actually have the docs generated through though.

**Comment by Schnitzel** [comment]
ok, then let's use readthedocs :)

**Comment by twardnw** [comment]
how about a structure of:
```
docs\
  using_lagoon
  administering_lagoon
  developing_lagoon
```

**Comment by Schnitzel** [comment]
seems good to me :)

**Comment by twardnw** [comment]
ok, and are we tied to markdown, or is moving to something like RST to be considered?

http://zverovich.net/2016/06/16/rst-vs-markdown.html

**Comment by Schnitzel** [comment]
Markdown please

**Comment by twardnw** [comment]
http://ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/

**Comment by twardnw** [comment]
oh, ok, markdown it is then
