### ISSUE TITLE
Update PHPRedis to 5.2.0

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1730]
**Describe the request**

We are currently running [PhpRedis 4.3.0](https://github.com/amazeeio/lagoon/blob/master/images/php/fpm/Dockerfile#L71) (released [2019-03-13](https://pecl.php.net/package/redis/4.3.0)). Now that we are no longer supporting PHP 5 images, we should look to run the latest version possible to benefit from new features and bug fixes.

The latest version is [5.2.0](https://github.com/phpredis/phpredis/releases/tag/5.2.0)

This will change the `ping` behaviour, so we will need to be careful to stage the rollout to customers with full information.

**Comment by tobybellwood** [comment]
The Drupal7 version of the redis module is incompatible with PHPRedis 5x without a patch https://www.drupal.org/project/redis/issues/3074189

**Comment by vincenzodnp** [comment]
There are more recent updates in the above drupal.org issue tracking.
Maybe it's ok now to update the phpredis library

**Comment by tobybellwood** [comment]
Closing (a few days) before php7 goes EOL. php8 images use phpredis5
