### ISSUE TITLE
Inconsistent error field type in lagoon logs

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1732]
**Describe the bug**
`harbor-clair` logs an `error` field as a string, while something else in lagoon logs an `error` field as an object.
This causes issues on log ingestion:
```
["org.elasticsearch.index.mapper.MapperParsingException: object mapping for [error] tried to parse field [error] as object, but found a concrete value"
```

And also causes issues in the `logs-forwarder` which gets a `400` back from Elasticsearch.

This occurs on e.g. `container-logs-lagoon-dev-develop-*` indices.

An example event which causes this error looks like this (edited):
```
{"Event":"could not parse package version. skipping","Level":"warning","Location":"ubuntu.go:316","Time":"2020-03-23 11:36:01.416499","error":"invalid version","version":"0.27-1+deb7u1build0.12.04.1, 0.28-1+deb8u1","docker":{},"kubernetes":{"container_name":"harbor-clair","namespace_name":"lagoon-dev-develop","level":"info"}
```

**To Reproduce**
1. Go to an affected elasticsearch node
2. View its logs
3. See error

**Expected behavior**
The fields of an index should be consistently typed, otherwise Elasticsearch can't index them.

**Screenshots**
n/a

**Additional context**
I'm not sure, but maybe this should be fixed by some filtering in logstash?

**Comment by tobybellwood** [comment]
I think this is all handled int he logs-dispatcher/logs-concentrator now?
