### ISSUE TITLE
Handle parallel usage of mariadb-dbaas and mariadb-shared

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1735]
I'm not 100% sure but while looking at the mariadb-dbaas implementation in k8s I think I found an issue int he openshift implementation of mariadb-dbaas.
Basically I think in here: https://github.com/amazeeio/lagoon/blob/1d07b9505b3164564b713513f01f68e9f1e3bc02/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L88-L103

there is a missing check if the project already uses `mariadb-shared` before we check if `mariadb-dbaas` is even existing or not. As it could be that:
1. an environment first has used the `mariadb-shared` because only `mariadb-shared` servicebroker existed on the cluster
2. the cluster admin enables the `mariadb-dbaas` operator
3. on a new deployment the above check sees the existing `mariadb-dbaas` operator and now creates this to create a new `mariadb-dbaas` even though there is an already existing `mariadb-shared` 

Unless the `mariadb-dbaas` and `mariadb-shared` create the exact same DB, Username, password combo?

**Comment by shreddedbacon** [comment]
I'll have a run over it
