### ISSUE TITLE
Varnish Version Updates

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#1741]
Currently we ship Varnish 5.2.1 in our varnish images `amazeeio/varnish` which is the default in alpines 3.7 repos - https://pkgs.alpinelinux.org/packages?name=varnish&branch=v3.7

```
~ > docker run -it amazeeio/varnish:latest varnishd -V
varnishd (varnish-5.2.1 revision 67e562482)
```

Currently the last releases are 6.3 and 6.4 - https://varnish-cache.org/docs/index.html

We should discuss how we move forward with newer varnish versions as the 5.2.x are marked as deprecated by Varnish.

**Comment by tobybellwood** [comment]
Varnish 5 and 6 now available in lagoon-images
