### ISSUE TITLE
Azure git repository names don't validate

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#1743]
**Describe the bug**
Azure Git Repositories don't pass the input validation

`git@ssh.dev.azure.com:v3/ORG/SUBPROJECT/REPONAME`

The regex https://github.com/amazeeio/lagoon/blob/027f9a80cc40699de99c70f43bac1453c478ad7d/services/api/src/resources/project/resolvers.js#L32

Seems not to let the Azure Repositories being added - the graphql mutations fail with `The provided gitUrl is invalid`

**To Reproduce**
1. Update a test project with the repository url `git@ssh.dev.azure.com:v3/ORG/SUBPROJECT/REPONAME`

**Expected behavior**
Regex is passed

**Comment by CGoodwin90** [comment]
Confirmed to not pass input validation if repo url doesn't end with 'git'

With Azure DevOps Services, the format for the project URL is dev.azure.com/{your organization}/{your project}

Potential solution is an additional regex check using something like - /(?:git|https?|dev)(?=.*\bazure\b)(.*)$/

Will need to confirm url structure but the above regex works for the below variations:

https://FabrikamFiber01@dev.azure.com/FabrikamFiber01/FabrikamFiber01-01/_git/FabrikamFiber01-01
git@ssh.dev.azure.com:v3/ORG/SUBPROJECT/REPONAME
dev.azure.com/{your organization}/{your project}

**Comment by christopher-hopper** [comment]
I'm having the same problem. Our organisation has just moved all our code off Atlassian Bitbucket server and onto Azure DevOps. I'm trying to get my Lagoon projects hooked back up to the new repos, but cannot.

Is there a workaround and/or a timeline to address this issue?

**Comment by christopher-hopper** [comment]
Here's the Git URL patterns ChatGPT-4 dug up for GitHub, Bitbucket, GitLab, and Azure DevOps with either SSH or HTTP. 

- `https://github.com/user/repo.git`
- `git://github.com/user/repo.git`
- `git@github.com:user/repo.git`
- `https://bitbucket.org/user/repo.git`
- `git://bitbucket.org/user/repo.git`
- `git@bitbucket.org:user/repo.git`
- `https://gitlab.com/user/repo.git`
- `git://gitlab.com/user/repo.git`
- `git@gitlab.com:user/repo.git`
- `https://dev.azure.com/user/project/_git/repo`
- `git@ssh.dev.azure.com/v3/user/project/repo`

Microsoft is the only one omitting the `.git` suffix. 

I've tried adding a `.git` suffix to see if Microsoft has added their own workaround for customers, but no. Adding `.git` to the end of a working URL just breaks as expected.

**Comment by smlx** [comment]
`.git` is just the conventional suffix for the leaf directory. The canonical examples are here https://git-scm.com/docs/git-clone#_git_urls

**Comment by dasrecht** [comment]
> Is there a workaround and/or a timeline to address this issue?

Hi @christopher-hopper - We have a very small number of customers using Azure Devops - The easiest workaround is to update the URL in the API DB manually. This is a hack but worked for the case we had almost 3 years ago.
