### ISSUE TITLE
UI SSH Key created date seems not to reflect the correct date

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#1747]
**Describe the bug**
When adding a second ssh key to the UI the created date of both keys seems to be the same.

**To Reproduce**
1. Go to https://dashboard.amazeeio.cloud/settings
2. Add a second ssh key
3. Check Created dates

**Expected behavior**
Correct created date is shown

**Screenshots**
![Settings](https://user-images.githubusercontent.com/391732/77851324-dba32c00-71d8-11ea-8c2b-645d86cbc1f5.png)

**Comment by seanhamlin** [comment]
I can confirm it just says the current date and time, kind of like a clock, but just less useful.

My key says

```
10 Apr 2020, 14:26:33 (+12:00)
```

**Comment by jrsouth** [comment]
Just noticed this same behaviour.

Seems likely to be `key.create` returning `undefined` in [services/ui/src/components/SshKeys/index.js#L28](https://github.com/amazeeio/lagoon/blob/47abca41f689f9af7ff5ce2d36dd4b3ec72b2fd5/services/ui/src/components/SshKeys/index.js#L28) 

Looks like it should be `key.created` according to [services/ui/src/lib/query/Me.js#L14](https://github.com/amazeeio/lagoon/blob/47abca41f689f9af7ff5ce2d36dd4b3ec72b2fd5/services/ui/src/lib/query/Me.js#L14)
