### ISSUE TITLE
Warning displayed when trying to download lagoonize zip file

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#1754]
**Describe the bug**
When trying to download the ZIP file that is referenced on the top of this page in the docs https://lagoon.readthedocs.io/en/latest/using_lagoon/drupal/lagoonize/
A warning is displayed saying it may not be safe (see screenshots)

It looks like an issue was raised for this in the main `downgit` repository, but the solution does not really seem ideal https://github.com/MinhasKamal/DownGit/issues/31 

**Expected behavior**
Zip file downloads without issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/9973880/77983700-5eec8b00-735b-11ea-8a2c-c330b979fcdb.png)

**Comment by dan2k3k4** [comment]
I use the `Refined Github` extension and this gives me a `Download` button on folders.

The folder we want is:
https://download-directory.github.io/?url=https://github.com/amazeeio/lagoon/tree/master/docs/using_lagoon/drupal`

The `Refined Github` version requires a Github auth key so it's less susceptible of being used by malware, but it's less user-friendly for just quickly downloading the zip file.

**Comment by shreddedbacon** [comment]
Closing, as this was fixed in a recent PR
