### ISSUE TITLE
Missing Build logs link in Rocketchat message

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon#1777]
**Describe the bug**
openshiftbuilddeploymonitor sends message in Rocketchat without link to build logs file.
This does not happen in Slack and in RocketChat it happens since April 2nd.

**To Reproduce**
1. Set a Rocketchat notification
2. Build a project
3. Check the missing logs

**Expected behavior**
Logs file in Rocketchat message.

**Comment by Schnitzel** [comment]
this will be fixed when https://github.com/amazeeio/lagoon/pull/1765 is released (in 1.4.1)
