### ISSUE TITLE
Flesh out READMEs for services. 

### ISSUE THREAD

**Issue by AlannaBurke** [uselagoon/lagoon#1791]
Services needing READMEs:
https://github.com/amazeeio/lagoon/tree/master/services/logs2microsoftteams
https://github.com/amazeeio/lagoon/tree/master/services/logs2rocketchat
https://github.com/amazeeio/lagoon/tree/master/services/kubernetesdeployqueue
https://github.com/amazeeio/lagoon/tree/master/services/kubernetesbuilddeploymonitor
https://github.com/amazeeio/lagoon/tree/master/services/ssh
https://github.com/amazeeio/lagoon/tree/master/services/openshiftbuilddeploymonitor
https://github.com/amazeeio/lagoon/tree/master/services/logs2slack
https://github.com/amazeeio/lagoon/tree/master/services/kubernetesbuilddeploy
https://github.com/amazeeio/lagoon/tree/master/services/logs2email
https://github.com/amazeeio/lagoon/tree/master/services/openshiftbuilddeploy

**Comment by shreddedbacon** [comment]
I added some words to them, would be good to get a second set of eyes over them though.
