### ISSUE TITLE
Dynatrace support for Nginx/PHP

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1793]
**Describe the feature**

I now have 2 large customers with existing enterprise Dynatrace licenses. To purchase a New Relic subscription is not the easiest thing to get past procurement either.

I am wondering if we can deploy the Dynatrace agent to the Nginx/PHP image, and have it behind environment variables (just like New Relic) to determine if it is enabled or not.

Perhaps environment variables like:

* `DYNATRACE_ENABLED` - boolean
* `DYNATRACE_LICENSE` - string

For features the APM tool has see https://www.dynatrace.com/technologies/php-monitoring/

All supported PHP versions are supported by the agent (even `PHP 7.4`) (so long as you have `v1.179` or later) https://www.dynatrace.com/support/help/technology-support/application-software/php/support/supported-versions/

**Challenges**
It looks like to actually download the OneAgent, you need to have a valid login https://www.dynatrace.com/support/help/technology-support/operating-systems/linux/installation/install-oneagent-on-linux/ - this will make baking the agent into the images a lot harder.

**Comment by seanhamlin** [comment]
By the sounds, the OneAgent binary requires a license in order to download the thing. This sounds like a non-starter for Lagoon.

Customers can still add the agent to their images if they have a license.

**Comment by tobybellwood** [comment]
For anyone looking back at this, there are updated docs for Docker now - still requiring login, but a smoother install process it seems - https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/docker/set-up-oneagent-on-containers-for-application-only-monitoring

**Comment by tobybellwood** [comment]
To clarify here, Dynatrace binaries are provided on a per-customer authenticated registry basis, and not as a generic binary activated by a license key, so we would not be able to include them at the lagoon-images level - and would instead need including in a projects dockerfile as per the instructions
