### ISSUE TITLE
Allow to disable auto generated routes on Branches

### ISSUE THREAD

**Issue by kurtfoster** [uselagoon/lagoon#1807]
Currently, autogenerate is set to false, it blocks generation of routes across the entire project, #505. Would it be possible to block autogeneration on branches defined in the branches field on the project instead? This would allow for our PR branches to continue to get autogenerated routes, whilst not re-adding the routes to defined branches.

 ```
     {
        "name": "governors",
        "branches": "^(master|develop|production)$"
      },
 
```

**Comment by tobybellwood** [comment]
I talked about something similar in #912 - to have an "all branches default" set in .lagoon.yml, that could be overridden by specified branches.  If that override could be a regex, it would be even more flexible

**Comment by kurtfoster** [comment]
#912 would definitely be useful. This requirement would be to either move route:autogenerate into the per branch settings, or to be able to define branch regex for the creation of autogenerate routes. The purpose of this is:

1. to avoid issues where users accidentally use the amazee routes on links etc, thereby going around the CDN and increasing direct Origin traffic. If a person did this accidentally, link checkers would pick it up as the route would fail.
2. Ensure that any security protection (IP restrictions, DDOS protection etc) offered by the CDN/WAF on the manually added routes can not be easily routed around by ensuring only the manually added routes exist.

Is there any interest in making this change? If so, I can look at adding it to our internal backlog to PR back to lagoon.
