### ISSUE TITLE
Show average deploy duration on lagoon UI

### ISSUE THREAD

**Issue by fmuellerprevion** [uselagoon/lagoon#1815]
We have deployment times ranging from 6 to 20 minutes, and for some clients, we would like to tell them how long they need to calculate the site could be down (maximum).

Therefore it would be really nice to see the average duration per environment on the lagoon UI under "Deployments".

![avg_duration](https://user-images.githubusercontent.com/26752987/80202445-ee691f00-8625-11ea-8721-74e71a12cf23.png)

**Comment by timclifford** [comment]
Thanks for the suggestion but we are not planning to integrate this kind metrics into the UI at present
