### ISSUE TITLE
Block deletion of projects if it still has environments

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1817]
this is a counter suggestion to https://github.com/amazeeio/lagoon/issues/1475

Currently you can delete a project while it still has environments, this causes problems with environments still on k8s clusters which are abandoned.

Therefore in order to prevent this, we would add a check during the deleteProject API call that checks if the current project has no active environments attached, and only allows the deletion of the project if all environments are also deleted.

This ensures:

1. that we don't have any abandoned environments on the k8s cluster
2. that a user wanting to delete a project actually needs to check each of the environments to be really sure that they want to remove them
3. automation still is capable via the lagoon-cli to implement a `--cleanup` flag to automatically delete all environments at the same time

**Comment by rocketeerbkw** [comment]
Done in #3261
