### ISSUE TITLE
Rewrite the SSH service image to decouple from api-db

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1820]
**Describe the bug**
SSH service image uses Ubuntu as a base. For consistency, easier maintenance etc. it might be a good idea to switch to alpine.

**To Reproduce**
n/a

**Expected behavior**
SSH image no longer relies on Ubuntu.

**Screenshots**
n/a

**Additional context**
https://github.com/amazeeio/lagoon/issues/1818 is related

**Comment by tobybellwood** [comment]
If we do need to use Ubuntu/Debian for some reason - we can at least align versions with other image upstreams :-)

**Comment by smlx** [comment]
I did some investigation on this.

The main issue seems to be that `openssh-server` doesn't allow login unless the user exists in the name-service database.

Lagoon ssh access uses commands like:
```
ssh -p [PORT] -t [PROJECT-ENVIRONMENT-NAME]@[HOST]
```
So the system needs to synthesize `getpwnam()` values matching `PROJECT-ENVIRONMENT-NAME` from Lagoon to be consumed by `openssh-server`. It does this by accessing the `api-db` directly via `libnss-mysql`.

`libnss-mysql` is unmaintained upstream (for ~15 years!) and doesn't compile with the mariadb libraries available in alpine 3.11. Distros (Debian, Fedora) are carrying patches but at this point the `libnss-mysql`-on-alpine road started looking rocky.

I can see a couple of alternatives to get Alpine working:
* Get rid of the `PROJECT-ENVIRONMENT-NAME@HOST` syntax, and instead require users to use `ssh lagoon@HOST project=... environment=...`, much like the existing `service=...` and `container=...` options. This means we don't need `libnss-mysql`, but isn't very user-friendly :-1: 
* avoid `openssh-server` by implementing our own simple ssh server that can use the Lagoon GraphQL API to get project and environment information. This would be more effort but would probably add some flexibility to the SSH service and might not be too difficult using libraries like:
  * https://godoc.org/github.com/gliderlabs/ssh#Server
  * https://godoc.org/k8s.io/client-go/tools/remotecommand

**Comment by Schnitzel** [comment]
btw, the `PROJECT-ENVIRONMENT-NAME@HOST` was specifically built because of Drush, as I could not find a way to teach Drush to use the `lagoon@host project=PROJECT-ENVIRONMENT-NAME` form (this might have changed with Drush 9/10).

I think the best way would be to implement our own SSH Server, as IMHO we're need to disable a LOT of the features of openssh-server already.
Just another thing: we're also offering SFTP support, which basically is just a binary `openssh-sftp-server` executed on inside the destination container, so it probably should be possible also with our own ssh server, but just to remember :)

**Comment by smlx** [comment]
If we decided to go the NSS route, these might also be helpful:
https://github.com/protosam/go-libnss
https://github.com/osallou/nss-external

**Comment by tobybellwood** [comment]
SInce this discussion, there is now a fork of libnss-mysql that may have more joy with alpine - https://github.com/saknopper/libnss-mysql

**Comment by smlx** [comment]
I think fundamentally that the SSH service hitting the api-db directly makes it too closely coupled to the current Lagoon architecture.

If the SSH service simply consumed the Lagoon API then it would be much easier to e.g. deploy to the cluster closest to the target workload instead of the same cluster running api-db.
