### ISSUE TITLE
Disable wiki feature for this repo

### ISSUE THREAD

**Issue by dan2k3k4** [uselagoon/lagoon#1824]
It looks like we don't use the wiki feature for this repository so we could potentially disable it in favour of using our official documentation.

I'm not sure if we have already ported the few pages in the wiki to our docs, so we'll also need to verify that.

**Comment by tobybellwood** [comment]
@AlannaBurke - are these in your sights?

**Comment by AlannaBurke** [comment]
All wiki articles moved and deleted, but i no longer seem to have access to repo settings, so i can't disable the wiki.

**Comment by tobybellwood** [comment]
aaaand done!
