### ISSUE TITLE
Tasks on dashboard should be configurable in which service they are ran

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#1825]
**Describe the bug**
Currently we assume that the `cli` pod is the pod where commands should run - In more complicated applications this might not be true.

Code example for a `drush cache-clear` - https://github.com/amazeeio/lagoon/blob/1386194da63bd267c47a3534a3d375fe474caa3b/services/api/src/resources/task/resolvers.js#L339-L345

If we could overwrite the `cli` pods name in the .lagoon.yml that would open up the possibility for more complex Drupal applications.

**Comment by dasrecht** [comment]
As discussed with @shreddedbacon there's a possibility to run a custom task via `lagoon run custom` which already helps getting around the current limitation.

**Comment by tobybellwood** [comment]
The new task system allows you to specify which service the task runs in
