### ISSUE TITLE
Feature request: respect Github pull request drafts

### ISSUE THREAD

**Issue by pmelab** [uselagoon/lagoon#1851]
When using pull request environments for a feature branch driven workflow, we often end up creating environments for pull requests that don't yet need one, since the PR's are just opened for collaboration. We can use the ["Draft mode" feature](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to mark pull requests that are not ready for testing/review yet and Lagoon could respect that by *not* building environments for them

**Comment by tobybellwood** [comment]
That's a nice idea. We can certainly look to see what the webhook passed to see if there is a flag - but it may be worth a discussion to see if this is "expected behaviour"?

**Comment by dan2k3k4** [comment]
`isDraft` boolean field should be available:
https://developer.github.com/v4/object/pullrequest/

I presume we can just not build anything if that returns true, then when the PR is updated - we would still receive the object content and `isDraft` would then be false, so we could trigger the build process.

**Comment by zanettin** [comment]
+1 from our side. would love to get this 👍
but also a valid input from @tobybellwood . maybe the pr is still in draft state but we would need a working pod for final tests. what about a combination of `isDraft` and `labels` combo to enforce a build even in `draft` state?

**Comment by ChandeepKhosa** [comment]
That sounds like a good idea. 
FYI there will be some people who are using GitHub Free for their organisations accounts (I am), and Pull Request Drafts are only available for paid plans. 

If there's not already a related task, it might be nice to simply respect the prefix of "WIP:" if it's in the PR name across all git hosts including GitHub, BitBucket & GitLab too?

**Comment by dan2k3k4** [comment]
You can already customise branches with a regex such as:
`^(?!WIP:).+`

Which states that the branch name **does not** start with `WIP:`

I'm not sure if this works for pull-request titles though, but the same concept could be applied there.

You can set that via a GraphQL Mutation with the API https://api.lagoon.amazeeio.cloud/graphql

Such as:

```
mutation {
  updateProject(input: {
    id: 1,
    patch: {
      branches: "^(?!WIP).+"
    }
  }) {
    id
    name
    branches
  }
}
```

That would build all branches that do not start with `WIP`.

**Comment by ChandeepKhosa** [comment]
Oh brilliant thanks, good to know 👍

**Comment by tobybellwood** [comment]
Closed as workaround exists.
