### ISSUE TITLE
Document the auto idler

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1868]
There is a service in Lagoon called the `autoidler` however this service has no real documentation even though it is fairly critical to managing large clusters.

## The ask

Can we create a page in the docs around the `autoidler` service, what it's purpose in life is, and how it works. 

## Example docs content

**Background**

The `autoidler` service runs continuously in the background of Lagoon, and looks to spin down pods for _non-production_ environments (production environments are exempt) when certain criteria is met. This means that dormant projects do not consume resources in the cluster, and more projects can be accommodated as a result.

It is important to note that this at the moment only works on OpenShift, and has not been ported to Native Kubernetes.

An idled pod will be started again if traffic is received that is intended for it. This pod scheduling process can take a minute, so it is expected that the first request might time out (subsequent requests will succeed).

**Determine auto idling is enabled for a given environment**

Use Lagoon CLI

```bash
lagoon get environment $ENVIRONMENT_NAME -p $PROJECT_NAME --output-json | jq -r '.data[].autoidle'
```

A value of `1` indicates that auto idling is active, `0` for inactive.

**CLI pods**

A check is run every 15 minutes to see if there is

* running processes (e.g. `rsync`, `drush`, `top`)
* cronjobs defined (e.g. `drush cron`)
* running builds

If no to all 3, then the CLI pod is idled down.

**Nginx/php and Varnish pods**

A check is run every 30 minutes to see it there is:

* running builds
* pods are younger than 4 hours
* traffic being received for the routes for the project in Kibana

If no to all 3, then the Nginx/PHP and Varnish pods are idled down.

**Comment by shreddedbacon** [comment]
CLI idler is adjustable interval too, default is 1 hour, but some Lagoons can get away with a more frequent interval.

> **Nginx/php and Varnish pods**
> 
> A check is run every 30 minutes to see it there is:
> 
> * running builds
> * pods are younger than 4 hours
> * traffic being received for the routes for the project in Kibana
> 
> If no to all 3, then the Nginx/PHP and Varnish pods are idled down.

It isn't just nginx/php/varnish here, it is anything that has a `service notin (mariadb,postgres)`

The default for service idler check interval is varied across Lagoons, smaller or single Lagoons can run more frequently. Normally it is 4 hours, but some can run more frequently without issue (30mins for example)

Otherwise this explains the idling process accurately.

**Comment by tobybellwood** [comment]
The auto-idler has been replaced in Lagoon 2 with the https://github.com/amazeeio/aergia-controller
