### ISSUE TITLE
Add es-curl in base elasticsearch images

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon#1877]
es-curl is a wrapper of elasticsearch `curl` commands more useful and easy to use.
The elasticsearch base images don't include it.

**Comment by Schnitzel** [comment]
the regular elasticsearch image does not use any authentication, which is the main reason that `es-curl` exists, see https://github.com/amazeeio/lagoon/blob/master/services/logs-db/es-curl

if we want to add es-curl to the base elasticsearch images, we need to adapt the code to not do any authentication.

But overall I think the idea is a good one.

**Comment by vincenzodnp** [comment]
> if we want to add es-curl to the base elasticsearch images, we need to adapt the code to not do any authentication.

Ok going to adapt the PR.
BTW, I've tested the image on my local, and despite it doesn't use any authentication, `es-curl` worked as well.
 
> But overall I think the idea is a good one.

:) thanks
