### ISSUE TITLE
Ability to add a security.txt to Lagoon projects, which can be customised per-site

### ISSUE THREAD

**Issue by thom8** [uselagoon/lagoon#1879]
We should consider being able to add the files needed for `security.txt` compatibility to lagoon projects to allow vulnerabilities to be disclosed securely.

https://securitytxt.org/

“When security risks in web services are discovered by independent security researchers who understand the severity of the risk, they often lack the channels to disclose them properly. As a result, security issues may be left unreported. security.txt defines a standard to help organizations define the process for security researchers to disclose security vulnerabilities securely.”

**Comment by tobybellwood** [comment]
I'd envisage a customer being able to add a folder to their git repo that held their files (security.txt as a minimum, and any PGP key) and then Lagoon can make that file available via /.well-known/security.txt (or /security.txt if /.well-known poses an issue)

Whilst there are Drupal modules available, it'd be good to have a generic approach that works for all sites.  Having the file history auditable in code is a positive too.

Maybe the file should be specified in the .lagoon.yml for an environment (usually prod, but maybe it should be on all?)

**Comment by tobybellwood** [comment]
If customers want this, they can add the files themselves.
