### ISSUE TITLE
Add labels to lagoon managed openshift projects

### ISSUE THREAD

**Issue by nicksantamaria** [uselagoon/lagoon#1888]
Currently finding the namespaces for a project and/or environment requires assuming the pattern is `[project]-[environment]`. This might not work when environments are derived from branches with slashes in them, or if the `--openshiftProjectPattern` was non-standard.

### Desired solution

Add the following labels to openshift projects/namespaces.

- `lagoon/project` - project machine name
- `lagoon/environment` - environment name
- `lagoon/branch` - branch (if available)

You could then use these labels in queries using the `oc` binary.

```
$ oc get ns --selector=lagoon/project=foo
NAME                     STATUS    AGE
foo-develop      Active    1y
foo-master       Active    2y
foo-pr-736       Active    191d
foo-production   Active    2y
```

```
$ oc get ns --selector=lagoon/project=foo,lagoon/environment=production
NAME                     STATUS    AGE
foo-production   Active    2y
```

**Comment by smlx** [comment]
This already exists for Kubernetes. https://github.com/amazeeio/lagoon/blob/fc05af1dade22a3cca236f9c6da8bbccad9ccd5a/services/kubernetesbuilddeploy/src/index.js#L319-L322 So this feature request would be for adding the same thing to Openshift.

**Comment by Schnitzel** [comment]
also I'm not sure if we want to inject the branch name into the namespace as a label. Currently we inject the environment name, which is generated from the branch name (for environments created from branches) but the environment name is also used for PRs and promotion deployments.

@nicksantamaria are you specifically interested in the branch name or would the environment also be ok?

**Comment by nicksantamaria** [comment]
Both would be best. The branch name would be useful, otherwise you have to transform the branch name into the format used by environments.

**Comment by nicksantamaria** [comment]
Turns out there are no labels being added to openshift projects currently. I've updated the issue description accordingly.
