### ISSUE TITLE
Auto-idler takes too long to run

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#1893]
**Describe the bug**
On a Lagoon with a lot of projects, environments, or clusters, it can take a long time for the auto-idler to run through, this can lead to the idler process running for a long time and continues to run even after another idler process has started. Resulting in pods running longer than they need to be, or not being idled fast enough when required.

**Expected behavior**
The idler should smarter in this process. Ideally each cluster should be in charge of its own idling process rather than relying on the upstream lagoon to tell it when to idle.

This could be done with a few simple changes to the Lagoon API, and building a new service that would run in each cluster that knows what to look for.

Process would be:
* label or annotate namespaces with the auto-idle value of the project (or if the environment has the value defined, use it instead)
  * this could be done when an environment is created, or updated in the lagoon API (a new mutation even that just does the label/annotation instantly when run so no need to re-deploy?)
* new service in cluster would periodically check environments that have the label to see if they need to be idled based on the existing conditions the auto-idler already uses

This would result in the idler running much faster, without the latency from having to reach out to other clusters to perform the pre-checks, then the eventual idling steps.

The only problem to solve would be checking for router-logs, or if there is a way to check these without leaving the cluster that would be even better.

**Comment by shreddedbacon** [comment]
This needs more attention, bumping priority. 
Will work on an implementation.

**Comment by tobybellwood** [comment]
fixed in https://github.com/amazeeio/aergia-controller
