### ISSUE TITLE
Better UX when adding keys via the UI

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#1894]
**Describe the bug**
When adding an SSH key via the UI it feels quite clunky and can be error prone.

**To Reproduce**
Scenario 1:
1. Log in to the UI
2. Go to settings
3. Begin to add an SSH key
4. Copy and paste the wrong section or an incomplete key by missing a character/characters from the key.
5. Key gets added successfully, but the API now has a bad key

Scenario 2:
1. Log in to the UI
2. Go to settings
3. Begin to add an SSH key
4. Copy and paste the the key, but the key being pasted has new lines in it for some reason
5. Key gets added successfully, but the API now has a bad key with new lines

**Expected behavior**
A more github/gitlab like approach to adding a key to my account, and any validation be done by the API.

If a user tries to add a key that is not ssh-rsa or ssh-ed25519, it should fail or warn on screen rather than having them select from the drop down box like it is currently, even having the placeholder text similar to github with `Begins with ssh-rsa or ssh-ed25519`

Scanning for new lines in the key should also be performed, and perhaps a warning is shown on screen advising the user.

**Screenshots**
Lagoon:
![image](https://user-images.githubusercontent.com/9973880/82182425-a046f300-9927-11ea-9961-832a16a03f2a.png)

Github:
![image](https://user-images.githubusercontent.com/9973880/82182594-dc7a5380-9927-11ea-9ce4-bcdf0c308311.png)

**Additional context**
This is solved in the lagoon CLI by allowing a few methods of adding a public key, but the first 2 examples are ones that would be how a user would add their key in github directly from the public key file they have.

The CLI handles the splitting up and validating the key to make sure it is supported by lagoon if it is given a full public key path.
```
Examples:
Add key from public key file:
  lagoon add user-sshkey --email test@example.com --pubkey /path/to/id_rsa.pub

Add key by defining full key value:
  lagoon add user-sshkey --email test@example.com --keyvalue "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINA0ITV2gbDc6noYeWaqfxTYpaEKq7HzU3+F71XGhSL/ my-computer@example"

Add key by defining full key value, but a specific key name:
  lagoon add user-sshkey --email test@example.com --keyname my-computer@example --keyvalue "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINA0ITV2gbDc6noYeWaqfxTYpaEKq7HzU3+F71XGhSL/"

Add key by defining key value, but not specifying a key name (will default to try using the email address as key name):
  lagoon add user-sshkey --email test@example.com --keyvalue "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINA0ITV2gbDc6noYeWaqfxTYpaEKq7HzU3+F71XGhSL/"
```

**Comment by anthony-malkoun** [comment]
Hey @shreddedbacon according to the current placeholder text you should have to add the e.g. `ssh-rsa` part of the public key. If this was the case you don't actually need the drop down to select the key type.

Interestingly too, I entered the same key in GitHub (which works) so it must actually strip out newlines which might be a nicer user experience.

**Comment by twardnw** [comment]
We should also check for the trailing comment and any associated whitespace and remove that
