### ISSUE TITLE
error from openshiftdeploy when running intial deploy of a branch

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#19]
While moving slackin over to lagoon, the first push of master w/ the lagoon changes failed to deploy, showing this error in the openshiftdeploy log

```
2017-08-31T22:23:29.633Z - silly: Error from server (Forbidden): User "system:serviceaccount:amze-amazeeio:jenkins" cannot list rolebindings in project "amze-amazeeio-slackin-master"
```

I saw similar behavior when pushing the develop branch for the first time as well. A subsequent push had the deployment succeed each time.

**Comment by Schnitzel** [comment]
This is probably a race condition with Appuio. For the hosting in ZRH we're using Appuio which needs us to use their api to create new projects in openshift (https://github.com/amazeeio/lagoon/blob/master/docker-images/oc-build-deploy/build-deploy.sh#L18)
and then a couple of lines later we try to do changes via `oc` to this created project:
https://github.com/amazeeio/lagoon/blob/master/docker-images/oc-build-deploy/build-deploy.sh#L32
Their API had no possibility to add serviceaccounts as admins to a new project, but this should be possible now.

This should fix this:
https://github.com/amazeeio/lagoon/pull/20

Let's get that in and then we can test again @twardnw

**Comment by twardnw** [comment]
I haven't seen this error since #20 was merged. Closing.
