### ISSUE TITLE
Add project count to the Lagoon Dashboard

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1909]
This is a pure nice to have, but knowing how many projects you have access to would be handy at a glance.

Example mockup

![image](https://user-images.githubusercontent.com/10605846/82769888-9a529400-9e8a-11ea-93ad-9e6a1484ab4b.png)

**Comment by CGoodwin90** [comment]
PR created in the UI Repo - https://github.com/uselagoon/lagoon-ui/pull/24
