### ISSUE TITLE
Investigate using a service mesh

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#1910]
A service mesh like [Istio](https://istio.io/docs/concepts/what-is-istio/#why-use-istio) would provide immediate benefits to Lagoon, in particular:
* [Enforcing mutual TLS](https://istio.io/docs/tasks/security/authentication/mtls-migration/) between components would provide hardening against Lagoon service access from outside the service mesh.
* [Visualise traffic](https://istio.io/docs/tasks/observability/metrics/using-istio-dashboard/) between Lagoon components to assist Ops teams with troubleshooting.

There's an operator available: https://istio.io/docs/setup/install/standalone-operator/

**Comment by cdchris12** [comment]
@vincenzodnp looked into this when we were first looking at the move to k8s from openshift; maybe he'd know how feasible this is currently?

**Comment by tobybellwood** [comment]
We're not currently looking at implementing a service mesh
