### ISSUE TITLE
internal-registry-secret in k8s doesn't update when lagoon API variables are updated

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#1936]
**Describe the bug**
When the `internal_container_registry` variables in the API are created initially, the `lagoon-internal-registry-secret` in kubernetes is created with these variables.
If the variables in the API are updated, it doesn't also update the secret in kubernetes.
This could result in images encountering `imagepullbackoff` condition.

**Expected behavior**
If the variables in the API are updated, the kubernetes secret should be updated too.

**Comment by shreddedbacon** [comment]
Further investigation, this does update the secret, but only when a deployment occurs. 

This is still a problem for environments that have not had a deployment and the registry changes.

Maybe there needs to be another mechanism that can update the kubernetes secret without having to do a deployment?

**Comment by tobybellwood** [comment]
the remote-controller now handles secret creation and rotation on a schedule
