### ISSUE TITLE
Use environment Variable to disable NewRelic Browser

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#1951]
Currently we only allow the enable/disable of NewRelic via an environment variable.

Enabling NewRelic also enables the Browser Instrumentation which could in some cases be an unwanted additional request sites do (Also as those scripts need to be referred to in the GDPR and Cookie Management Solutions)

As there's a low number of customers actively using the Browser Instrumentation on lagoon (as far as i can tell) we could go 2 ways.

- Leaving it Enabled by default and have an environment variable that allows easy disabling of the 
- Disabling it by default and needing the environment variable to allow it (this would also lead to less requests sites do whereas the impact should be minimal - but it will follow good privacy-first guidelines to not enable the feature by default)

**Comment by seanhamlin** [comment]
This page looks relevant https://docs.newrelic.com/docs/browser/new-relic-browser/page-load-timing-resources/new-relic-cookies-used-browser

So it looks like by default, Browser is enabled when you enable APM.

You can turn it off in the UI of Browser, in the settings tab:

![image](https://user-images.githubusercontent.com/10605846/84564903-70213180-adb9-11ea-8e8a-5ee995788f3b.png)

From reading https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-configuration there is a setting `newrelic.browser_monitoring.auto_instrument` which can be set to `false` to disable the insertion of the JS snippets used by Browser.

So this feature request is possible 🎉
