### ISSUE TITLE
Service Idler should not scale pods on Kubernetes Clusters

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1952]
**Describe the bug**
The Lagoon Service Idler is scaling pods in force mode on Kubernetes Clusters even though we don't have support for auto unidling on Kubernetes Clusters yet.
Also we actually use `oc idle` and it seems running this against a Kubernetes cluster will just scale the Deployment to 0 even though Kubernetes should not support `oc idle` (it's an OpenShift command)

**To Reproduce**
run https://github.com/amazeeio/lagoon/blob/master/services/auto-idler/idle-services.sh with `force`, see deployments on Kubernetes cluster scaled to 0.

**Expected behavior**
Kubernetes clusters are skipped.

**Comment by tobybellwood** [comment]
this is now handled by aergia
