### ISSUE TITLE
Long running builds not always updating the UI

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#1956]
**Describe the bug**
When a build runs for a long time, once it completes or fails, it does not always update the status in the UI.

**To Reproduce**
1. Start a build that takes longer than 1 hour to complete
2. Wait for it to complete
3. See that the status in the UI is still running.

**Expected behavior**
Should update the UI with the build status

**Screenshots**

**Additional context**
It seems to only be builds that run longer than 1 hour, have seen it happen on builds that have run for 1.5hrs and on ones that have run for 2+hrs. Not sure if it is a hard line at 1 hour as I couldn't find anything timing specific in code.

**Comment by tobybellwood** [comment]
Fixed in the controller
