### ISSUE TITLE
Consolidate *remove and *misc Lagoon services

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon#1965]
The `openshiftremove` and `kubernetesremove` services exist to do just one thing, delete cluster resources when a Lagoon environment is deleted. I think we can move these tasks into the `*misc` services and reduce the complexity/overhead of running Lagoon. We probably should've just gotten rid of the `*remove` service back when we added the `*misc` service to begin with.

**Comment by rocketeerbkw** [comment]
Or, make sure we do this when/if we start using Kubernetes operators instead of Lagoon services for this feature.

**Comment by tobybellwood** [comment]
it is done
