### ISSUE TITLE
Document EOL Status of components

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#1993]
**Describe the bug**
We've started to end of life some images with the last lagoon versions - This made it into blogposts but never into documentation - We should find a way to show which image versions are supported and which are not

We started EOLing some containers in lagoon 1.2.0 - https://www.amazee.io/blog/post/what-to-expect-in-lagoon-1-2-0

**Comment by tobybellwood** [comment]
This is now documented in the docs and the release notes
