### ISSUE TITLE
Create allow list for tasks

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#2003]
At the moment, there is a block list for tasks, and this is great if you want to remove 1 or 2 tasks from the list. However you do need to update this every single time a new task is added (else you risk exposing new tasks to your users).

## Proposed solution

Just like we have `LAGOON_UI_TASK_BLOCKLIST`, let's also have a `LAGOON_UI_TASK_ALLOWLIST` to which if defined will take precedence over the blocklist.

**Comment by tobybellwood** [comment]
We won't be creating any new tasks this way - in future they will be more controllable.
