### ISSUE TITLE
Allow post-rollout-tasks on containers without bash.

### ISSUE THREAD

**Issue by thom8** [uselagoon/lagoon#201]
Currently, `exec-post-rollout-tasks-run.sh` assumes bash is available in the service container.

https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/scripts/exec-post-rollout-tasks-run.sh#L3

And for example it's not available by default in the `redis` container - `docker run amazeeio/redis bash`

Perhaps we could add another option to allow `sh` but default to using `bash`.

**Comment by Schnitzel** [comment]
this has been implemented
