### ISSUE TITLE
GitHub PR Link in Lagoon UI is incorrect.

### ISSUE THREAD

**Issue by AlannaBurke** [uselagoon/lagoon#2040]
**Describe the bug**
Link to GitHub PR ("source" field) in Lagoon UI is incorrect. The link (in this example) is `github.com/amazeeio/drupal-example-simple/tree/pr-6` and it should be `https://github.com/amazeeio/drupal-example-simple/pull/6`

**To Reproduce**
1. Create a PR branch in an environment with PR branches enabled. 
2. Visit the PR environment Overview in the Lagoon UI. 
3. Click on the "source" link. It will take you to a "Page not Found" in GitHub. 

Example here:
https://ui-lagoon-master.ch.amazee.io/projects/drupal9-example-simple/drupal9-example-simple-pr-6

**Screenshots**
<img width="1395" alt="drupal9-example-simple-pr-6 | Environment 2020-07-06 21-22-08" src="https://user-images.githubusercontent.com/1540998/86682686-d111e300-bfce-11ea-86c9-ecf2e6aa208d.png">

**Comment by daanmolenaar** [comment]
It looks like we have the same issue for GitLab. The Merge request links to gitlab.com/[PATH]/tree/pr-1234567 in the lagoon interface.

**Comment by daanmolenaar** [comment]
https://github.com/amazeeio/lagoon/blob/main/services/ui/src/components/Environment/index.js#L18 There is a new url build up here based on the branch name. In case of a PR is that pr-xxx.

There should be a switch if its a PR then to show the PR url saved in deploydata: https://github.com/amazeeio/lagoon/blob/0e51f7b74d0b24473ca21d22fb7c0a1aa3029d8d/services/webhooks2tasks/src/handlers/gitlabPullRequestOpened.ts#L45

**Comment by dan2k3k4** [comment]
The above PR #2456 tries to address the issue for the UI but not for the messages sent in logs or Slack.

I am not certain of the Gitlab URL. I currently just replace `tree/` with `pull/` and remove the `pr-` if it's not a `branch` environment.
