### ISSUE TITLE
Development environments labelled with production incorrectly

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#2041]
I was checking namespace labels and noticed that some development environments are being labelled as production

Checking here https://github.com/amazeeio/lagoon/blob/9131889183e252f8a214b1b7037a0568841a22a1/services/kubernetesbuilddeploy/src/index.ts#L363 we are using `lagoonEnvironmentType` to label the environment, but this variable is actually pulled from the running `kubernetesbuilddeploy` pods, see here
https://github.com/amazeeio/lagoon/blob/9131889183e252f8a214b1b7037a0568841a22a1/services/kubernetesbuilddeploy/src/index.ts#L22

I think the label needs to be updated to use `environmentType`

The same issue is in openshiftbuilddeploy using the wrong variable.

**Comment by Schnitzel** [comment]
+1, this is a bug.
