### ISSUE TITLE
The mariadb image will not start a second time

### ISSUE THREAD

**Issue by Neo-Oli** [uselagoon/lagoon#2042]
**Describe the bug**
The mariadb image will not start a second time

**To Reproduce**
1. Start a lagoon docker environment with `docker-compose up`
2. Stop it again with  `docker-compose stop`
3. Start it again

**Expected behavior**
The mariadb container should start again.

**Error**
```
mariadb_1  | ln: /home/.my.cnf: File exists
project_mariadb_1 exited with code 1
```

**Context**
The Problem is this change: e73e239f326274565daf38b7a4b0f5b1176bc35b
`ln -s ${MARIADB_DATA_DIR:-/var/lib/mysql}/.my.cnf /home/.my.cnf` will fail if the symlink already exists. Previously this was the very last step and the docker container started anyway, but now it will fail and break much earlier. It should probably check if the file already exists before trying to symlink it.

**Comment by vincenzodnp** [comment]
@Neo-Oli I think it might be overridden with a `-f` to force the re-creation of symlink.
I will try on my local.
Thanks for the feedback

**Comment by rocketeerbkw** [comment]
From https://arslan.io/2019/07/03/how-to-write-idempotent-bash-scripts/ the suggestion is

> So to be safe, always use `ln -sfn source target`.
