### ISSUE TITLE
Deployment duration does not stop incrementing for failed kubernetes deployments

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#2046]
**Describe the bug**
Deployment duration does not stop incrementing for failed kubernetes deployments.

**Screenshots**
![image](https://user-images.githubusercontent.com/9973880/86877632-9a50df80-c12a-11ea-9668-a7ec5685dd04.png)
Wait a minute and refresh
![image](https://user-images.githubusercontent.com/9973880/86877676-accb1900-c12a-11ea-9fd7-6f1faa97fa86.png)

**Comment by tobybellwood** [comment]
This has been "fixed" for most use cases.
