### ISSUE TITLE
environmentByOpenshiftProjectName returns deleted environment

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon#2050]
**Describe the bug**
The `environmentByOpenshiftProjectName` API query always [returns the first environment](https://github.com/amazeeio/lagoon/blob/master/services/api/src/resources/environment/resolvers.ts#L269), which may be deleted.

This causes some issues:
* The UI to show old data, like deployments/tasks/backups for the deleted environment instead of the active one.
* The deployment check in #2033 will always requeue and never build
* The restic backup code uses this query so probably a bug there
* A number of functions in `@lagoon/commons` use it, so probably bugs there

**To Reproduce**
1. Run the tests
2. Run the tests again
3. Run the query and compare with the database, you'll see it loads the wrong data

**Expected behavior**
It shouldn't return deleted data when an active environment exists

**Comment by tobybellwood** [comment]
The SQL may have been updated to resolve this?

**Comment by bomoko** [comment]
I think this was solved in this commit https://github.com/uselagoon/lagoon/commit/2596947226dd579482a17cdb3f6ecef3745071c2
