### ISSUE TITLE
Feature request - list routes in lagoon PR deployments UI

### ISSUE THREAD

**Issue by jordotech** [uselagoon/lagoon#2053]
Currently PR environments do not list their routes like the dedicated environments do on the overview tab in lagoon

example url https://ui-lagoon-master.ch.amazee.io/projects/ipsum/ipsum-pr-58

![image](https://user-images.githubusercontent.com/485972/87056325-113db500-c1cb-11ea-9100-f9dd19cc8e29.png)

**Comment by shreddedbacon** [comment]
This usually happens when there hasn't been a successful completed deployment yet.
The routes only get updated once a deployment has completed.

**Comment by jordotech** [comment]
Ah you are correct.  However, (maybe this is a separate subject) when there is an error in post-rollout the deployment is marked as failed and the route is not shown even though the route exists and it did deploy.

**Comment by jordotech** [comment]
I would print the route if the route exists, regardless of what happened in post-rollout.

**Comment by Schnitzel** [comment]
> However, (maybe this is a separate subject) when there is an error in post-rollout the deployment is marked as failed and the route is not shown even though the route exists and it did deploy.

@jordotech you are correct, there is a case were the routes and pods/containers are created but the post-rollout fail.
Lagoon only checks if the routes exist or not if the build is fully successful. We could change that code though that Lagoon checks the routes no matter if the build fails or not and then the routes would appear in the UI for a failed build.

**Comment by jordotech** [comment]
That would be very helpful.  On a larger subject, I think many would benefit by there being a 3rd result that reflects reality - "Deployed with issues" or something like that.  We'll get a slack notification that the deployment failed which isn't true, it did deploy in reality.  Take this example - on production there are new Drupal modules being added in a deployment but in post-rollout `drush cim` fails.  We all get notified that the deployment didn't go through but in reality, production is running with the new code.

**Comment by tobybellwood** [comment]
This has been resolved in a more recent release
