### ISSUE TITLE
lagoon UI is constantly signing you in

### ISSUE THREAD

**Issue by jordotech** [uselagoon/lagoon#2054]
Even after you login to the lagoon UI every page starts by "signing you in".  It should keep you signed in, this adds a few seconds to every page load.  

![Screen Shot 2020-07-09 at 10 11 36 AM](https://user-images.githubusercontent.com/485972/87058335-932edd80-c1cd-11ea-848e-eb90519e2b7d.png)

**Comment by tobybellwood** [comment]
UIv2 will support SSR to remove this imposition
