### ISSUE TITLE
Create and manage Networkpolicies automatically inside Lagoon

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#2058]
As of right now Lagoon depends on OpenShift to create Networkpolicies automatically on namespace creation.
In Kubernetes such an automated system does not exist and therefore it is on Lagoons responsibility to create the Networkpolicies and manage them.

With this ticket we would like to achieve that:
- k8s Networkpolicies (if supported by the target cluster) are automatically created by Lagoon when a new namespace is created by Lagoon
- These Networkpolicies focus on Ingress protection right now, Egress are not in scape
- Ingress protects from access from any other namespace in the cluster except the ones that are needed (like the ingress controller namespace)

Stretch goals:
- Additional namespaces that permit Ingress access can be defined within `.lagoon.yml`

**Comment by tobybellwood** [comment]
Lagoon 2.0 introduced NetworkPolicies to protect ingress
