### ISSUE TITLE
k8s build canceling non functional

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#2062]
**Describe the bug**
Cancelling a build in k8s is not working

**To Reproduce**
1. Trigger two builds
2. Cancel the newer build of the two
3. Build is never canceled 

**Expected behavior**
Build is canceled after cancelling it via the Lagoon API

**Additional context**
Looks like cancelling build has actually not been implemented yet:

https://github.com/amazeeio/lagoon/blob/68a2d95e7ac19ccc11e627453ce10bc96af14aa5/services/kubernetesmisc/src/handlers/kubernetesBuildCancel.ts#L100-L109

also there is some code that checks if the build exists at all, but in my tests the `jobInfo` always is existing:
https://github.com/amazeeio/lagoon/blob/68a2d95e7ac19ccc11e627453ce10bc96af14aa5/services/kubernetesmisc/src/handlers/kubernetesBuildCancel.ts#L89-L97

and therefore the if is never reached

**Comment by tobybellwood** [comment]
This is now implemented, aside from occasional edge cases.
