### ISSUE TITLE
Duplicate OpenDistro security roles for Lagoon groups

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#2074]
**Describe the bug**
Duplicate OpenDistro security roles for Lagoon groups with differing index permissions created in OpenDistro Security.

**To Reproduce**
Steps to reproduce the behavior (as a user):
1. Impersonate as an affected user.
2. Log in to Kibana and view a problematic index pattern.
3. See error

Steps to reproduce the behaviour (as an admin):
1. In Kibana, search for a security role associated with a given Lagoon group.
2. See that there are multiple roles returned.
3. See that the roles may also have different index permissions.

**Expected behavior**
I would expect that there is a single tenant role for a Lagoon group with all the required index permissions.

**Screenshots**
n/a

**Additional context**

From the naming of the duplicate roles, they appear to be associated with Lagoon billing groups. Should billing groups have any OpenDistro Security roles associated with them? I would guess they shouldn't?

**Comment by tobybellwood** [comment]
This has been tightened up
