### ISSUE TITLE
API requests failing due to cached permissions

### ISSUE THREAD

**Issue by thom8** [uselagoon/lagoon#2078]
Today we've run into an interesting issue in which a project's default user is unable to list drush aliases.
While testing we were able to fix by forcing an update of the default users permissions by adding them to the default group as a maintainer. This fix was replicated on a few other projects.

As keycloak showed the users in the correct groups and updating the users groups didn't actually make any change I flushed the lagoon redis cache which has resolved the issue across all other project.

The following error was returned from `drush sa` in the affected projects.
```
Using https://api.lagoon.amazeeio.cloud/graphql as lagoon API endpoint [6.59 sec, 10.61 MB]                                                                                         [notice]
Curl request didn't return any environments for the given project '[lagoon-project-name]'. [7.87 sec, 10.61 MB]
```

**To Reproduce**
Not easy to reproduce as it looked to be a caching issue and now that the cache has been flushed the issue can't be replicated.

**Comment by tobybellwood** [comment]
My suspicion is that somehow the Redis cache isn't properly populated (maybe services coming up in the wrong order), or incorrectly formed cachekeys - and this is triggering one of the Redis KeycloakUnauthorizedErrors

**Comment by Schnitzel** [comment]
interesting, running the Drupal Drush tests https://github.com/amazeeio/lagoon/blob/master/tests/tests/drupal.yaml#L57-L65  a couple of times locally might help reproduce the bug and then help to resolve the issue.

@thom8 @tobybellwood 
do we know if this happened on a brand new project created or was this an already existing project?
I could imagine that as the default user is added right when the project is created, there might be a race condition were the user is given permissions to fast?

**Comment by Schnitzel** [comment]
by @tobybellwood 
> was this an already existing project?
it was existing projects

**Comment by smlx** [comment]
@tobybellwood this is fixed I think?

**Comment by tobybellwood** [comment]
Yes, I think so
