### ISSUE TITLE
Dashboard UI - "up" button

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon#2090]
When you check a long page like a build's log one, if you want to jump on the top of the page, you need to scroll up.

It'might be useful to have a sort of "jump on top" or "up" button to jump and the beginning of the page instead of scroll up.

**Comment by dan2k3k4** [comment]
What do you need from the top of the page @vincenzodnp?

What if we used a fixed header or moved some things to a sidebar that's always visible?

![fixed-header](https://user-images.githubusercontent.com/158704/104963632-40837900-59db-11eb-84a1-5fb0e02eaca3.gif)

![scroll-window](https://user-images.githubusercontent.com/158704/104965839-d91bf800-59df-11eb-8789-4a3cad5a1547.gif)

**Comment by timclifford** [comment]
Added to deployment logs
