### ISSUE TITLE
InvalidAccessKeyId when downloading backup

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#2098]
**Describe the bug**
If an external cluster has different backup restore bucket and credentials configured in the BaaS, any generated download links for these backups will fail because the wrong key is used to sign the download link.

**To Reproduce**
1. Go to the `Downloads` tab for an environment using different restore bucket/credentials
2. Click on 'Retrieve'
3. Once retrieved, click 'Download'
4. See error from AWS stating `InvalidAccessKeyId`
```
<Error>
<Code>InvalidAccessKeyId</Code>
..snip..
</Error>
```

**Expected behavior**
Download should succeed.

**Additional context**
The API is hardcoded to use what is provided to it
https://github.com/amazeeio/lagoon/blob/master/services/api/src/resources/backup/helpers.js#L13-L22

It might be good to have the `deployment target` or `openshift` object in the API configureable to store the AWS credentials that the BaaS uses for restoring backups into, so the correct key is used to sign the generated link.

**Comment by tobybellwood** [comment]
part of a wider issue with Backups/restore credentials and how they're stored.
