### ISSUE TITLE
Be able to provide alternative providers for hits

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#2104]
At the moment the billing system assumes the hit data will be stored in [Elasticsearch in the router-logs index](https://github.com/amazeeio/lagoon/blob/master/services/api/src/models/environment.ts#L254). With the advent of CDNs, it would be good to be able to pull hit data from an external API endpoint, or even from another index in Elasticsearch (if we end up exporting the raw logs to there).

**Comment by tobybellwood** [comment]
The billing system is no longer part of Lagoon
