### ISSUE TITLE
Helpers script to remove old .kibana indexes

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon#2118]
Kibana every time it restarts, creates a new `.kibana_` index and update the alias.
For example the index `.kibana_4` is the index which alias is `.kibana`.

Those indexes are used to keep the kibana configuration and are kept in case of a configuration rollback/restore.
It might be the case to keep just the latest index and delete the old ones.

**Comment by tobybellwood** [comment]
Opensearch/Opendistro maintenance is now outside of the scope of Lagoon
