### ISSUE TITLE
lagoon docs, malformed link

### ISSUE THREAD

**Issue by jordotech** [uselagoon/lagoon#2131]
**Describe the bug**
There's a link to the environment variables page at the bottom of this page https://lagoon.readthedocs.io/en/latest/using_lagoon/docker_images/nginx/#basic-authentication

It links to https://lagoon.readthedocs.io/en/using_lagoon/environment_variables/ instead of https://lagoon.readthedocs.io/en/latest/using_lagoon/environment_variables/

resulting in 404

**To Reproduce**
Click this link

![image](https://user-images.githubusercontent.com/485972/89307615-e82c0b00-d636-11ea-8ac6-240db3c7b6c6.png)

you'll land on unstyled 404 page 

![image](https://user-images.githubusercontent.com/485972/89307695-fe39cb80-d636-11ea-882e-67ca15e90513.png)

**Comment by tobybellwood** [comment]
fixed in our latest docs - https://docs.lagoon.sh/lagoon/docker-images/nginx#basic-authentication
