### ISSUE TITLE
Avoid exclusive language `master`

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon#2139]
There has already been discussion and agreement internally to no longer use `master` as the name of our default branch. This issue is to announce our intention publicly and hold us accountable for the change (since it's already been ~2 months from our last discussion).

TODO:
- Determine what processes are needed to make the change
- Make the change

**Comment by smlx** [comment]
I found a couple of things while looking into this:

There's a nice procedure [here](https://github.com/chancancode/branch-rename#gradual-migration) which will allow you to gradually migrate by using github actions to mirror commits between `main` and `master` branches during a transition phase.

There was also [a change in git 2.28](https://github.blog/2020-07-27-highlights-from-git-2-28/#introducing-init-defaultbranch) to make the default branch name configurable in `git init`.

**Comment by tobybellwood** [comment]
as per https://github.com/github/renaming/ - there are already some protections in place - missing branches now redirect to the default.

After renaming, we'd need to modify any PRs to point to main, and look at the configuration of the release drafter Action.

**Comment by smlx** [comment]
On the PR retargeting, there's a script here https://github.com/ethomson/retarget_prs

**Comment by dan2k3k4** [comment]
Hey @AlannaBurke, I've created PR #2446 and updated as much usage of `master` as possible.

There are still various links to 3rd party repositories but those still use `master` branch as their default branch.

I am not 100% sure on the `tests/` directory, I updated it but if those should be ignored then I can remove the commit for that.

Each commit refers to a different set of root directories (e.g. update to all `docs/` is done in one commit).

**Comment by dan2k3k4** [comment]
We may need to also update [Pygmy](https://github.com/amazeeio/pygmy) to use `main` branch as default, if so, we will need to update all of the links to the current documentation for Pygmy which is https://pygmy.readthedocs.io/

**Comment by rocketeerbkw** [comment]
We still have a `master` branch until we release lagoon 2 (on `main`) and the potential work for pygmy too, so reopening.

**Comment by rocketeerbkw** [comment]
I can only find a few remaining issues in legacy repos that will eventually be archived so I think we've completed this.
