### ISSUE TITLE
Deployments page can have so many deployments that the page fails to load

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#2158]
**Describe the bug**

If you have a lot of deployments on a given environment, then loading the deployments page will take a long time. This can exceed 90 seconds, and thus the page will fail to load entirely.

On an active project 1,193 deployments are on the page. This is far too many to be useful.

**To Reproduce**
1. Create a new environment
2. Trigger 1,000 deployments
3. Notice how the page takes a long time to load

**Expected behavior**

Either A):

Pagination showing the last 20 deployments by default, with the option to go to the next page. The page should load in a reasonable time as well (sub 5 seconds) for a customer

or B):

Just limit the list of the last X entries, and don't do pagination. There should be no need to go back past 100 deployments (as an example) ever.

**Screenshots**

![image](https://user-images.githubusercontent.com/10605846/90697770-3d247e00-e2d3-11ea-968d-82de0ec3e9f7.png)

**Comment by chandanatk** [comment]
Related to [#1382](https://github.com/uselagoon/lagoon/issues/1382)

**Comment by rocketeerbkw** [comment]
We did option b in #2763
