### ISSUE TITLE
Active/Standby button doesn't work

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#2167]
**Describe the bug**
When attempting to trigger an active/standby action, the button in the UI does not work as previously.

**To Reproduce**
1. Open Chrome/Firefox
2. Go to an environment that is running Active/Standby
3. Click the button to trigger the action
4. Nothing happens

**Expected behavior**
The button should pop up a confirmation box asking the user to verify their action.

**Comment by shreddedbacon** [comment]
I did some quick digging, I think the following were reverted when problems were added

https://github.com/amazeeio/lagoon/blame/master/services/ui/src/components/ActiveStandbyConfirm/index.js#L6
This line should actually be uncommented

https://github.com/amazeeio/lagoon/blame/master/services/ui/src/components/ActiveStandbyConfirm/index.js#L69
And this line should be changed back to
```
export default withLogic(ActiveStandbyConfirm);
```

**Comment by rocketeerbkw** [comment]
Fixed in 2.x with #2387
