### ISSUE TITLE
Active/Standby routes do not update correctly in the API

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#2168]
**Describe the bug**
When deploying an active/standby environment, the build and deploy process does not update the active/standby routes back into the API for kubernetes based deployments

**To Reproduce**
1. Trigger a deployment for an active/standby environment
2. Watch the logs and see that ACTIVE_ROUTES and STANDBY_ROUTES are correctly populated
3. Once the build completes, the routes do not get updated into the API

**Expected behavior**
The routes should be added in the API

**Comment by shreddedbacon** [comment]
~Resolved in #2172~
Edit: sorry, not related to that issue.

**Comment by tobybellwood** [comment]
This has been solved (now)
