### ISSUE TITLE
lagoon UI - scalability problem with deployments list

### ISSUE THREAD

**Issue by jordotech** [uselagoon/lagoon#2174]
Hello, we have reached 250 deployments for our dev branch and the lagoon UI is taking ~1min to load the list of deployments.  As time goes on it will continue to get slower until the page is unusable.

Solution- add pagination to the list of deployments

https://ui-lagoon-master.ch.amazee.io/projects/ipsum-front/ipsum-front-dev/deployments

**Comment by seanhamlin** [comment]
Duplicate of #2158
