### ISSUE TITLE
Run SSH pod in each lagoon-remote

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#2177]
Currently, all SSH connections run via the SSH pod in the same location that all other Lagoon services run. While this simplifies the auto-generation of Drush aliases, the experience of customers using SSH from locations distant from the main cluster is impacted by this.

Each cluster should have it's own SSH pod running, and the auto-generated drush aliases should prefer this endpoint for any SSH interaction.

**Comment by tobybellwood** [comment]
There's discussion over in #1820 about this

**Comment by nicksantamaria** [comment]
Adding my vote for a solution along these lines. Our team is often frustrated by how long it takes to establish a ssh connection, and the latency involved with the Australia -> Switzerland -> Australia round trip.

**Comment by tobybellwood** [comment]
Been implemented, awaiting wider rollout
