### ISSUE TITLE
Drush archive-dump saves file with wrong extension

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#2180]
**Describe the bug**
When running a `drush archive-dump` task against a site, the task is hardcoded to name the file `*.tar` where drush actually compresses it. This can cause some confusion for users when attempting to extract the file.

See code here: https://github.com/amazeeio/lagoon/blob/32e4b7e5b21f55af6132bd811c1c11a4863d3497/services/api/src/resources/task/resolvers.ts#L257

**To Reproduce**
1. Go to 'tasks'
2. Click on 'drush archive-dump'
3. Wait for task to complete, and check the file result
4. See file is of `gzip compressed data` but the extension is just `.tar`

**Expected behavior**
Extension should reflect the file type of `.tar.gz`

**Comment by tobybellwood** [comment]
no further modifications to legacy hardcoded tasks.
