### ISSUE TITLE
Support ECDSA SSH keys and FIDO/U2F key types in Lagoon

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#2189]
> The YubiKey 5 Series supports the following algorithms on the PIV smart card application.
>
>    RSA 1024
>    RSA 2048
>    ECC P-256
>    ECC P-384

https://support.yubico.com/support/solutions/articles/15000014219-yubikey-5-series-technical-manual

I'd like to use my Yubikey to interact with Lagoon via SSH, but only RSA and Ed25519 keys are supported by Lagoon. For various reasons RSA 2048-bit keys aren't great so it would be nice to add support for at least `ecdsa-sha2-nistp256`, and possibly `ecdsa-sha2-nistp384`.

**Comment by smlx** [comment]
Lagoon should also support the FIDO/U2F key types `ecdsa-sk` and `ed25519-sk`.
https://www.openssh.com/txt/release-8.2

**Comment by tobybellwood** [comment]
As long as the key type is parsable by [sshpk](https://github.com/joyent/node-sshpk) - it should be easyish to add in.

I'm not sure that the *-sk are supported by sshpk, so we may need to look to validate somehow else?

**Comment by smlx** [comment]
Looks like it isn't supported https://github.com/joyent/node-sshpk/issues/72

**Comment by smlx** [comment]
Even the non `sk` versions will make it easier to use Yubikeys.

**Comment by tobybellwood** [comment]
ECDSA key support is now in Lagoon

**Comment by tobybellwood** [comment]
Going to reopen this to track the -sk key types
