### ISSUE TITLE
Allow admins to add a new project (based on MariaDB)

### ISSUE THREAD

**Issue by ryyppy** [uselagoon/lagoon#22]
AC:
- GraphQL query which will add given project to the database
- Only users with a valid admin token can do the mutation

**Comment by Schnitzel** [comment]
actually, adding a site to a sitegroup should be allowed to all users that their ssh key is part of the sitegroup or the client of this sitegroup :)

**Comment by ryyppy** [comment]
@Schnitzel so far we don't have a proper R/W credential separation and we decided on starting with the admins and slowly integrate the common users as well :-)

**Comment by Schnitzel** [comment]
okay, it's just that we would like soon to allow a beta test :)

**Comment by ryyppy** [comment]
I would say we create a new ticket for users specifically ASAP 👍

**Comment by ryyppy** [comment]
This issue is suspended in favor of #35
