### ISSUE TITLE
MariaDB image ship with functions not available in AWS RDS Aurora

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#2204]
**Describe the bug**

At the moment, Alpine Linux 3.11 ships with [MariaDB 10.4.13-r0](https://pkgs.alpinelinux.org/package/v3.11/main/x86/mariadb). 

MariaDB introduced a new function `REGEXP_SUBSTR` in [10.0.5](https://mariadb.com/kb/en/regexp_substr/) (around 2013).

This function is available in MySQL 8.0. However is your Lagoon cluster is backed with AWS Aurora RDS, then you are currently capped to MySQL 5.7 and this function is not available.

If you use Azure Managed MySQL, then [MySQL 8.0 is available](https://docs.microsoft.com/en-us/azure/mysql/concepts-supported-versions).

**To Reproduce**

1. Write an SQL query that uses `REGEXP_SUBSTR`
2. Query will run locally using docker container
3. Query will fail on production using RDS Aurora

**Expected behavior**

There is consistency between local and production in terms of the version of MySQL available.

**Logs**

Seen in the application when running the query

```
REGEXP_SUBSTR does not exist
```

**Comment by tobybellwood** [comment]
This is one of the known incompatibilities between Aurora/RDS and MySQL/MariaDB
