### ISSUE TITLE
`add_metadata_to_project` cannot run a second time

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#2208]
unfortunately this code:
https://github.com/amazeeio/lagoon/blob/5045fc57ae9f498c87f67af0622a0c1a86b8f5bc/services/api-db/docker-entrypoint-initdb.d/01-migrations.sql#L1140-L1149

is not built like the other scripts in the `api-db` migrations. It throws an error if you try to run it twice (like it happens when we rollout lagoon), therefore stopping the script at an unexpected point.

We would need to make the code more clever that it realizes that the script already ran once before.

**Comment by smlx** [comment]
Could we start using migrations for the DB schema? There's a nice CLI tool [here](https://github.com/golang-migrate/migrate).

**Comment by rocketeerbkw** [comment]
Fixed in 2.x with #2387
