### ISSUE TITLE
Add Sumologic exporter for the logs-dispatcher

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#2210]
**Describe the bug**
`logs-dispatcher` doesn't currently have the sumologic exporter installed, it should: https://github.com/SumoLogic/fluentd-output-sumologic

**To Reproduce**
n/a

**Expected behavior**
Able to export to sumologic from `logs-dispatcher`.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by tobybellwood** [comment]
this has been implemented
