### ISSUE TITLE
mark unmanaged custom routes with annotation so they can be removed

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#2224]
currently we don't remove previously created k8s objects by lagoon, this can lead into issues, especially for objects that are unique across the whole k8s cluster (like openshift routes where only exactly one route in the whole openshift can claim a specific host).

But at the same time we also have some customers that added some routes manually by hand into openshift, which was regular practice at the beginning of Lagoon, while this doesn't happen anymore in kubernetes we need to find a good way to handle this in openshift, as just removing non-existing routes in the `.lagoon.yml` will cause crazy amount of havoc.
(sidenote: or Lagoon 2.0 and k8s we will implement the removal of any service, see https://github.com/amazeeio/lagoon/issues/1678)

therefore I suggest that in oc-build-deploy-dind we setup a system that annotates all existing routes that are not part of `.lagoon.yml` with something like `lagoon.sh/status=unmanaged`, we then can create a cronjob per cluster that removes the routes automatically (as we know that some clusters have never added manual routes).

**Comment by seanhamlin** [comment]
We were discussing this at standup, as this has real impacts for clusters, e.g.:

* Customer removes route from `.lagoon.yml` and releases to production. Say the site is no longer hosted on Lagoon, or is defunct and the domain is no longer active.
* Lagoon does not remove the dead route upon next deploy, it just chills.
* When the Let's Encrypt certificate expires next, it will not auto-renew as the domain does not exist or point at Lagoon. Thus exposer pods will live on indefinitely unless manually killed.

## Proposed solution

* For clusters that have manually managed routes outside of Lagoon, they get the label like you mention `lagoon.sh/status=unmanaged`. We would need to give some sort of grace period to notify customers to do this.
* Upon Openshift build and deploy, we do a difference set between what is in `.lagoon.yml` and what is currently deployed to the cluster that are **not** labeled `lagoon.sh/status=unmanaged`. We delete any routes that are in the difference set.

**Comment by shreddedbacon** [comment]
Closed by https://github.com/uselagoon/build-deploy-tool/pull/238
