### ISSUE TITLE
Compatibility of Lagoon with Harbor 2

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#2231]
Seems that Harbor 2 has breaking api changes which Lagoon is not aware yet. 
As we are installing Harbor 2 with our lagoon charts: https://github.com/uselagoon/lagoon-charts/compare/add_harbor#diff-4f3175c54d7aa8d5027622b86f693066R5 we should make sure that Lagoon has compatibility to Harbor

Depending on the changes in Harbor2 it would be great if there is maybe a way to tell Lagoon if the API is v2 or v1, as we might not be able to update all Harbors to v2 when we migrate to Lagoon 2.

**Comment by tobybellwood** [comment]
Lagoon is fully compatible with the latest Harbor releases :partying_face:
