### ISSUE TITLE
api service does api calls to itself

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#2233]
while working on lagoon-core in lagoon-charts (https://github.com/uselagoon/lagoon-charts/issues/97) we realized that the api actually does api calls to itself. This was probably not realized so far as the default api endpiong (`http://api:3000`) worked everywhere, but with helm in the mix this can now be something like `http://lagoon-core-api:3000` and so we had to specifically set `API_HOST` on the api pods.
This seems a bit strange, it's probably because the api consumes shared code from `node-packages/commons/src/api.ts` which was more thought for the case that other services need to talk to the api.
it's not a huge problem, but I think it would just be more efficient if the api uses the code already itself to talk to the api-db instead of making another api call to itself?

**Comment by tobybellwood** [comment]
Will be readdressed as part of a larger service consideration
