### ISSUE TITLE
Lagoon API lists `bytesUsed` when it is actually `kiloBytesUsed`

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#2245]
# Describe the bug

The storage calculator incorrectly (and confusingly) captures KB instead of Bytes. It looks like this was introduced in https://github.com/amazeeio/lagoon/commit/e59e3a05985de4ac4bacaf3a508904204a98ab2f but never reflected in the API.

## To Reproduce

Install the latest version of `du`, on Mac, this is GNU `gdu`. The command used to count the storage space is [listed in the code](https://github.com/amazeeio/lagoon/blob/main/services/storage-calculator/calculate-storage.sh#L122).

```
du -s /storage/${PVC} | cut -f1
```

Reading up on the `-s` switch

>        -s, --summarize
>             display only a total for each argument

Here is an example from my local laptop of a large directory of log files:

1. Current command

```
$ gdu -s ~/largedir/ | cut -f1
109611500
```

2. Forcing Bytes

```
$ gdu -b ~/largedir/ | cut -f1
111982025079
```

3. Forcing KB

```
$ gdu -sk ~/largedir/ | cut -f1
109611500
```

4. Human readable

```
$ gdu -h ~/largedir/ | cut -f1
105G
```

## Expected behavior

One of 2 options:

1. That the `bytesUsed` matches up to actual bytes used. 
2. The API is changed to `kiloBytesUsed` and the `-k` flag added for clarity

Either way, this is likely a breaking API change, and possibly better suited to Lagoon 2.0.

**Comment by shreddedbacon** [comment]
The [storage calculator is being updated](https://github.com/uselagoon/storage-calculator/pull/11) to include the kilobyte field, while retaining the old one for backwards compatability. The data in both fields remains the same though, just simply making it clear that the data is kilobytes not bytes. We will need to update the actions-handler to consume the new field if it is present, and announce a deprecation of the old one (minimum lagoon-remote chart version required to get the new field)

The API is a different story, we can expose the data in a new field that just displays the same data with `kiloBytesUsed` and deprecate `bytesUsed`
