### ISSUE TITLE
inject build argument that is unique for every single time we run a build

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#2246]
can be used to invalidate the caching of layer caches in order to force a specific set of docker layers to run even if the code itself did not change.

**Comment by Schnitzel** [comment]
until this lands, here a way to work around with this:

```
FROM amazeeio/node:10-builder as builder
COPY . /app/

RUN yarn install

# make sure we skip the layer caching every single time, see https://stackoverflow.com/questions/35134713/disable-cache-for-specific-run-commands
# 
# `yarn build` runs the gatsby build which reaches out to an external service to load content, as this content might has changed
# we need to make sure `yarn build` runs every single time. As the code of the git repo did not change and this is the only thing that is used
# for docker builds to decide if it should use the cache or not. Therefore we force the layer cache to be invalid (with downloading a random string)
# a bit hacky, but works. can be refactored when https://github.com/amazeeio/lagoon/issues/2246 lands.
ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
RUN yarn build && rm -rf /app/node_modules

FROM amazeeio/nginx
COPY lagoon/redirects-map.conf /etc/nginx/redirects-map.conf
COPY --from=builder /app/public /app
```

**Comment by bryangruneberg** [comment]
As we're getting more and more Gatsby projects, this is becoming more important to avoid the reliance on the random.org website service. It would be great to remove this dependency. On Sunday passed random.org went down, and Workshop Orange couldn't deploy or build Gatsby projects using this approach.

In the meantime here's an alternative URL that works as well: 
``` 
Dockerfile:
ADD "https://onlinerandomtools.com/generate-random-bytes" skipcache
```

**Comment by bryangruneberg** [comment]
Just a poke on this thread that online randomtools.com went down today as well.

We're changing all our build files to get a random string over https from a Lagoon project that we control, but maybe there is a better way in Lagoon already?

@bomoko - I think I recall you talking about this sometime in the last few months? Is this still an open topic, or is there already a solution?

**Comment by bomoko** [comment]
@bryangruneberg see above PR :)
