### ISSUE TITLE
ROUTE_TLS_ACME is set to 'True', instead of 'true'

### ISSUE THREAD

**Issue by jaimed-amazee** [uselagoon/lagoon#2249]
# Describe the bug

ROUTE_TLS_ACME is set to True and not true, which causes LE to not generate certs.

## To Reproduce

1. tls_acme set to true in .lagoon.yml file
2. We see this in the build logs: 

```
+++ cat .lagoon.yml
+++ shyaml get-value 'environments.master.routes.0.nginx.1.stellenwerk-berlin\.de.tls-acme' true
++ ROUTE_TLS_ACME=True
```

## Expected behavior

Validation should run to change the True to true.

## Additional context

I think this is where we get that from: images/oc-build-deploy-dind/build-deploy-docker-compose.sh

`ROUTE_TLS_ACME=$(cat .lagoon.yml | shyaml get-value production_routes.active.routes.$ROUTES_SERVICE_COUNTER.$ROUTES_SERVICE.$ROUTE_DOMAIN_COUNTER.$ROUTE_DOMAIN_ESCAPED.tls-acme true)`

**Comment by cdchris12** [comment]
According to our testing, this can be resolved by adding the `-y` flag to the `shyaml` command. It seems `shyaml` is interpreting this as a boolean value no matter how it's quoted.

**Comment by rocketeerbkw** [comment]
Fixed in 2.x with #2494
