### ISSUE TITLE
Error loading solr config from /opt/solr/server/solr/mycores/drupal/conf/solrconfig.xml

### ISSUE THREAD

**Issue by yusufhm** [uselagoon/lagoon#2261]
# Describe the bug

I'm getting the following error when running the `solr` service with OOTB configuration:

> An error occurred while trying to retrieve additional information from the Solr server: Solr endpoint http://solr:8983/ internal Solr server error (500). { "error":{ "metadata":[ "error-class","org.apache.solr.core.SolrCoreInitializationException", "root-error-class","org.xml.sax.SAXParseException"], "msg":"SolrCore 'drupal' is not available due to init failure: Could not load conf for core drupal: Error loading solr config from /opt/solr/server/solr/mycores/drupal/conf/solrconfig.xml", "trace":"org.apache.solr.core.SolrCoreInitializationException: SolrCore 'drupal' is not available due to init failure: Could not load conf for core drupal: Error loading solr config from /opt/solr/server/solr/mycores/drupal/conf/solrconfig.xml\n\tat org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:1644)\n\tat org.apache.solr.servlet.HttpSolrCall.init(HttpSolrCall.java:249)\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:469)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:395)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:341)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:502)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)\n\tat org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)\n\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.solr.common.SolrException: Could not load conf for core drupal: Error loading solr config from /opt/solr/server/solr/mycores/drupal/conf/solrconfig.xml\n\tat org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:97)\n\tat org.apache.solr.core.CoreContainer.getConfigSet(CoreContainer.java:1227)\n\tat org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1174)\n\tat org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:690)\n\tat com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:197)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:209)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\t... 1 more\nCaused by: org.apache.solr.common.SolrException: Error loading solr config from /opt/solr/server/solr/mycores/drupal/conf/solrconfig.xml\n\tat org.apache.solr.core.SolrConfig.readFromResourceLoader(SolrConfig.java:190)\n\tat org.apache.solr.core.ConfigSetService.createSolrConfig(ConfigSetService.java:109)\n\tat org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:91)\n\t... 9 more\nCaused by: org.apache.solr.common.SolrException: org.xml.sax.SAXParseException; systemId: solrres:/solrconfig.xml; lineNumber: 109; columnNumber: 7; The string \"--\" is not permitted within comments.\n\tat org.apache.solr.core.Config.<init>(Config.java:154)\n\tat org.apache.solr.core.Config.<init>(Config.java:90)\n\tat org.apache.solr.core.SolrConfig.<init>(SolrConfig.java:205)\n\tat org.apache.solr.core.SolrConfig.readFromResourceLoader(SolrConfig.java:182)\n\t... 11 more\nCaused by: org.xml.sax.SAXParseException; systemId: solrres:/solrconfig.xml; lineNumber: 109; columnNumber: 7; The string \"--\" is not permitted within comments.\n\tat com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)\n\tat com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)\n\tat com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)\n\tat com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)\n\tat com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)\n\tat com.sun.org.apache.xerces.internal.impl.XMLScanner.scanComment(XMLScanner.java:819)\n\tat com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanComment(XMLDocumentFragmentScannerImpl.java:1034)\n\tat com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2982)\n\tat com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)\n\tat com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)\n\tat com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)\n\tat com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)\n\tat com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)\n\tat com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)\n\tat com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)\n\tat com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)\n\tat org.apache.solr.core.Config.<init>(Config.java:143)\n\t... 14 more\n", "code":500}}

## To Reproduce

1. Start with a fresh solr container:
```
docker-compose stop solr && docker-compose rm -fv solr
docker-compose up -d solr
```
2. Check the value of the dataDir config:
```
docker-compose exec solr grep "<dataDir>" /opt/solr/server/solr/mycores/drupal/conf/solrconfig.xml
```
The value should be correct:
```
<!--<dataDir>${solr.data.dir:}</dataDir>-->
<dataDir>/var/solr/${solr.core.name}</dataDir>
```
3. Restart the container:
```
docker-compose restart solr
```
4. Check the value of the dataDir config again:
```
docker-compose exec solr grep "<dataDir>" /opt/solr/server/solr/mycores/drupal/conf/solrconfig.xml
```
The value is incorrect (**the closing comment tag is gone**):
```
<!--<dataDir>/var/solr/${solr.core.name}</dataDir>
<dataDir>/var/solr/${solr.core.name}</dataDir>
```
5. In the Drupal site, go to `/admin/config/search/search-api/server/solr` and confirm the Solr core is not accessible and the error shown above can be seen.

## Expected behavior

1. The `dataDir` config value should remain the same.
2. Solr core should be accessible.

## Additional context

I believe the issue is coming from the script `/images/solr/20-solr-datadir.sh`, [line 102](https://github.com/amazeeio/lagoon/blob/master/images/solr/20-solr-datadir.sh#L102) where `sed` is being used to replace lines, and the comment tag has not been ignored:
```
sed -ibak "s/<dataDir>.*/<dataDir>$SOLR_DATA_DIR_ESCAPED\/\${solr.core.name}<\/dataDir>/" $1/solrconfig.xml
```
I did a test locally and can confirm that if we replace it with
```
sed -ibak "/<\!\-\-/!s/<dataDir>.*/<dataDir>$SOLR_DATA_DIR_ESCAPED\/\${solr.core.name}<\/dataDir>/" $1/solrconfig.xml
```
then it works fine.

**Comment by tobybellwood** [comment]
Thanks @yusufhm - I'll keep trying to reproduce, but never seen this issue myself?

Are you just using the built-in solrconfig, or getting fresh from the Drupal module?

**Comment by yusufhm** [comment]
Hey @tobybellwood, I was using the built-in solrconfig, with the `amazeeio/solr:7.7-drupal` image.

So you followed the steps above and could not reproduce it? I'll try again later in a different VM and a completely new project to see if it still happens.
