### ISSUE TITLE
Error in Harbor Scanner matcher regex fallbacks

### ISSUE THREAD

**Issue by bomoko** [uselagoon/lagoon#2279]
# Describe the bug

When testing harbor scanner matcher regexes where there are _no_ regex capture groups (i.e. Project, Environment, and Service _all_ get pulled from the default fields) - I found a few errors.

First, the field names were incorrect in some places.

Second, where there are no match groups at all, the match extractor was not returning an object, which lead to a runtime error.

**Comment by rocketeerbkw** [comment]
Fixed in 2.x with #2394
