### ISSUE TITLE
lagoon-core does not overwrite LAGOON_VERSION in all service images, leading to different issues

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#2287]
lagoon-core service images should overwrite LAGOON_VERSION for all images as currently we have some strange issues:

- lagoon UI shows base image version in footer, while not a bug it's confusing for people that use lagoon
- openshiftbuilddeploy and kubernetesbuilddeploy want to use `amazeeio/oc-build-deploy-dind:20.10.0` which doesn't exist, the version number is derived from `LAGOON_VERSION`

**Comment by tobybellwood** [comment]
The builddeploys could probably look for :latest images.  There is a new PR to master to ensure master branch pushes :latest to amazeeio dockerhub.

Overwriting LAGOON_VERSION is more sensible though all round

**Comment by rocketeerbkw** [comment]
Fixed in 2.x with #2494
