### ISSUE TITLE
Add documentation for nodejs images

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#2295]
I got asked today which node containers we support currently and stumbled over the fact that we don't have those containers documented currently.

**Comment by AlannaBurke** [comment]
Where would i find this info or from whom would i obtain it?

**Comment by AlannaBurke** [comment]
also, is this a duplicate of https://github.com/amazeeio/lagoon/issues/1433?

**Comment by dasrecht** [comment]
🙈 ok let's close this and continue with 1433 - need to talk to the OP about that...
