### ISSUE TITLE
Dedicated clusters to define their own k8up backup schedule

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#2303]
A customer has requested that _all_ projects on their dedicated cluster are backed up on a set schedule that differs from the defaults.

**Default schedule:**

• 7 daily backups
• 6 weekly backups

**Desired schedule:**

• 7 daily backups
• 4 weekly backups
• 12 monthly backups

**Comment by Schnitzel** [comment]
I think this would be best implemented in the build controller: https://github.com/amazeeio/lagoon-kbd
as we overall are moving cluster level settings into the build controller.
Can you create a sister ticket in the build controller to track this?

**Comment by seanhamlin** [comment]
done

**Comment by cdchris12** [comment]
Closed by #2721
