### ISSUE TITLE
openshiftbuilddeploymonitor sometimes fails silently

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#2318]
There seems to be some times where the openshiftbuilddeploymonitor will just stop processing messages in the queue. At minimum it would be good to add some monitoring so this might alert, but a better goal is to find out what causes these stoppages. Unfortunately, I do not know how to reproduce this issue. The last known time this happened was Nov 10 at approx 10:05 PDT

**Comment by tobybellwood** [comment]
not any more
