### ISSUE TITLE
Unable to update activeSystemsPromote on a project

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#2321]
# Describe the bug

The `activeSystemsPromote` field is missing from `UpdateProjectPatchInput`.

## To Reproduce

1. View the schema for `UpdateProjectPatchInput`.
2. See that `activeSystemsPromote` is missing.

## Expected behavior

`activeSystemsPromote` should be a field in `UpdateProjectPatchInput` so that it can be updated on an existing project.

## Screenshots

n/a

## Additional context

This is going to become more important as projects start migrating more often.

**Comment by rocketeerbkw** [comment]
Fixed in lagoon 1.x #2432. Fixed in lagoon 2.x #2494.
