### ISSUE TITLE
Tenant switch in Kibana does not stay permanent or default to user's tennant

### ISSUE THREAD

**Issue by chandanatk** [uselagoon/lagoon#2327]
For some users, the tenant switch in Kibana seems not to stick and keeps changing. The two possibilities currently known are:
1. Although the global tenant is disabled in the Open Distro configuration, somehow it still appears for some users
2. Global tenant does not appear but the tenant is empty before switching

**Comment by shreddedbacon** [comment]
I've had a look into this and done a quick test locally.

Our `logs-db-ui` uses opendistro-1.6 (https://github.com/amazeeio/lagoon/blob/main/services/logs-db-ui/Dockerfile#L62)

I checked where the default tenant gets sourced from, and it happens here in the `getTenantByPreference` function https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/opendistro-1.6/lib/backend/opendistro_security.js

There appear to be some checks that check for the global tenant being enabled etc, but then it falls back to this check https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/blob/opendistro-1.6/lib/backend/opendistro_security.js#L389-L393

The `tenants` array that is iterated over contains `global_tenant` in it still, so when it comes time to `tenantkeys.sort()` it does so alphabetically, then returns the first item in the array. This means anyone with a tenant that is alphabetically behind `global_tenant` will use global.

There isn't anyway to set a specific default tenant though from what I can find, so it will still use alphabetical sorting. But quick testing of this block of code works. But it isn't perfect, if the length of tenants is 1 (being just the global_tenant) this will probably fail. But I think you can't actually log in unless you are in a tenant anyway.
```
for (k in tenants) {
    if (globalEnabled === false && k == "global_tenant") {
        continue;
    }
    tenantkeys.push(k);
}
tenantkeys.sort();
return tenantkeys[0];
```

We could, for now, in the `logs-db-ui` service create a file `backend.js` with the above code change. Then in the Dockerfile add a COPY just after adding the `RUN bin/kibana-plugin`
```
COPY backend.js /usr/share/kibana/plugins/opendistro_security/lib/backend/opendistro_security.js
```

**Comment by chandanatk** [comment]
Only thing I could find for setting a default tenant
https://discuss.opendistrocommunity.dev/t/default-tenant-kibana/889

**Comment by tobybellwood** [comment]
Kibana is no longer managed by Lagoon
