### ISSUE TITLE
inject Fastly annotations if Fastly operator is present on the cluster

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#2335]
We have the Fastly Operator now available on k8s clusters. When it is present, all client domains should route via the CDN, so we need to inject the necessary annotations to ingresses for this.

`fastly.amazee.io/watch`
`fastly.amazee.io/service-id`

We would need to store the service-id along with the cluster information in the API. Also these settings need to be able to be overridden at the project or environment level too, pulling in a customer provided api-secret-key from a BUILDTIME env var

**Comment by shreddedbacon** [comment]
The first part of this is merged in #2457 

The lagoon-builddeploy controller has had the addition merged https://github.com/amazeeio/lagoon-kbd/pull/32, but hasn't been released yet.

**Comment by rocketeerbkw** [comment]
Fixed in 2.x with #2494
