### ISSUE TITLE
Private container registry incorrectly sets login password

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#2338]
When using the private container registry setup in Lagoon, if you define a password in the lagoon API at the project level, but you have environment level variables defined. The check used will prioritise the environment level variable first, but if there is one not defined, it will set it to an empty value.

https://github.com/amazeeio/lagoon/blob/f2fe153eab7da3c932f8b66b5c7136115a8c1bdc/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L263-L268

The logic needs to be updated to check if the value is not empty before setting it.

**Comment by rocketeerbkw** [comment]
Fixed in 2.x with #2387
