### ISSUE TITLE
MariaDB: reduce the amount of restarts needed at cold boot

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#234]
currently mariadb starts 5 (!) times with a complete empty datadir, see:
https://gist.github.com/Schnitzel/1095caddc50905b8ffd571ac7e8963c9
would be awesome to get that down.

also there is a lot of verbosity, because of 
https://github.com/amazeeio/lagoon/blob/04276da48db74e8969a493c7ceaf2a7886244e1c/images/mariadb/docker-entrypoint.sh#L3-L5

let's remove that :)

**Comment by rtprio** [comment]
I can try to integrate `mysql_install_db.sh`  which sets up the system tables into the docker entrypoint. that could bring it from 5 to maybe 2.
