### ISSUE TITLE
Service type override environment variable not working

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#2340]
# Describe the bug

When setting a `LAGOON_SERVICE_TYPES` override variable at the project level. If any environment variables are defined at the environment level, then the `LAGOON_SERVICE_TYPES` override is ignored, unless it is also set at the environment level.

## To Reproduce

Set the `LAGOON_SERVICE_TYPES` variable at the project level, make sure no environment level variables are defined.
Deploy an environment and see that the service type override works.

Add any environment level variable that isn't `LAGOON_SERVICE_TYPES` and see that the service type override no longer works

## Expected behavior

It should only use a `LAGOON_SERVICE_TYPES` override if one is found in the project or environment level variables.

## Additional context

This is similar issue to #2338 where the environment level variables set empty values if there are any variables defined.

**Comment by rocketeerbkw** [comment]
Fixed in 2.x with #2387
