### ISSUE TITLE
Problems DB error logs very verbose

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#2357]
# Describe the bug

We are seeing some errors from elasticsearch when indexing `lagoon-logs`:
```
error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch [error type]: illegal_argument_exception [reason]: 'Limit of total fields [1000] in index [lagoon-logs--_-all_environments-_-2020.12] has been exceeded'"
```

The error message concerned appears to be generated by the problems DB system when it encounters an error inserting duplicate records:
```
"event"=>"problems:drutiny:resultset:problem_insert_error"
```

The log message itself appears to contain a full result set and is >91KB in size.

A contributing factor is that `lagoon-logs` is expected to contain a `project` field containing the name of the project concerned. Because this field is missing, errors for all projects are ending up in a single index.

## To Reproduce

1. Run Lagoon at scale in production :smiley: 
2. Occasionally see these error messages in logs-concentrator.

## Expected behavior

There might be a way to pare down the log message a bit to avoid sending so many logs and hitting the elasticsearch limit.

In addition, maybe the `project` field of the log message should be populated with the name of the project concerned? That way the logs will end up in the `lagoon-logs-<project>-*` index and the customer/tenant will be able to see the logs in Kibana. However I'm not sure if this behaviour is desirable.. should customers be able to view these error logs?

## Screenshots

n/a

## Additional context

n/a

**Comment by tobybellwood** [comment]
We're deprecating large single packet problems (eg drutiny), so this shouldn't be occurring any more
