### ISSUE TITLE
activeSystemsPromote not defined by UpdateProjectPatchInput

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon#2358]
# Describe the bug

Currently unable to update the `activeSystemsPromote` by using `updateProject` function
The error is:
```"message": "Field \"activeSystemsPromote\" is not defined by type UpdateProjectPatchInput. Did you mean activeSystemsRemove, activeSystemsDeploy, activeSystemsMisc, or activeSystemsTask?"```

## To Reproduce

1. Run a query like ```mutation updateProject {   
updateProject(input: {id: 1, patch: {
activeSystemsPromote: "lagoon_kubernetesBuildDeploy"}}) {
    id
  }
}```
3. See error

## Expected behavior

By querying the project, the `activeSystemsPromote` field must be updated

**Comment by smlx** [comment]
I think this is a duplicate: https://github.com/amazeeio/lagoon/issues/2321

**Comment by vincenzodnp** [comment]
Yep it is. Going to close
