### ISSUE TITLE
No default storage class for node-persistent template in openshift

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#2376]
The default storage class is not set on `node-persistent` service types. This results in the PVC sitting in a pending state.
https://github.com/amazeeio/lagoon/blob/main/images/oc-build-deploy-dind/openshift-templates/node-persistent/pvc.yml#L39

But in `nginx-php-persistent` we set `bulk` as the default: https://github.com/amazeeio/lagoon/blob/main/images/oc-build-deploy-dind/openshift-templates/nginx-php-persistent/pvc.yml#L39 (edited) 

Workaround is to add `lagoon.persistent.class: bulk` in the docker-compose.yml file

**Comment by tobybellwood** [comment]
Lagoon doesn't support Openshift (3) any more
