### ISSUE TITLE
main branch ci: also test against openshift 3

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#2382]
with https://github.com/amazeeio/lagoon/pull/2367 we're adding back ci into the main branch, which roughly works like this:
- kind cluster that runs lagoon-core
- same kind cluster as target for lagoon kubernetes tests

now we would also like to:
- still have kind cluster that runs lagoon-core (we don't expect Lagoon 2 to run on an OpenShift 3)
- start an OpenShift 3 minishift beside the kind cluster
- use openshift 3 as target for lagoon openshift tests

**Comment by tobybellwood** [comment]
no longer required
