### ISSUE TITLE
Undersized pod resources

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#2392]
# Describe the bug

We currently define unrealistically small resources on pods in our kubernetes helm charts. This causes issues with pod scheduling, cluster autoscaling etc.

## To Reproduce

1. Deploy a lagoon project. 
2. Observe that it is using much more than 10m CPU and 10Mi memory.

1. Deploy lots of lagoon projects.
2. Observe that the k8s scheduler can sometimes pack too many pods on a node (without other scheduling limitations such as max pods per node).

## Expected behavior

Workloads will of course vary in resource usage, but our "estimate" can be improved.

## Screenshots

n/a

## Additional context

This probably requires a workload survey to determine an approximate median value.

This change will also affect HPAs, which will have to be adjusted to retain current behaviour.

**Comment by seanhamlin** [comment]
Agree with this issue, more accurate estimates can be done. Looking at an example live Drupal 8 project running in native kubernetes now:

* `Nginx/PHP`: 200MiB RAM, 0.11 CPU
* `Solr`: 600MiB RAM, 0.005 CPU
* `CLI`: 8 MiB RAM, 0.008 CPU

Checking on another busy Drupal 8 project:

* `Nginx/PHP`: 256MiB RAM, 0.12 CPU
* `CLI`: 1200 MiB RAM, 0.03 CPU

**Comment by nicksantamaria** [comment]
Perhaps this should be configurable in .lagoon.yml as it will be highly dependent on how heavy an application is.

**Comment by smlx** [comment]
I think this was fixed in https://github.com/uselagoon/build-deploy-tool/pull/162 ?
