### ISSUE TITLE
Occasional failures on main branch CI

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon#2393]
Generally CI is much faster and reliable on main branch.  Occasionally we get deploy failures - I'd guess they're load related - there's a lot of parallel builds on a single node
https://lagoon-ci.amazeeio.cloud/blue/rest/organizations/jenkins/pipelines/lagoon/branches/PR-2387/runs/4/nodes/45/steps/46/log/?start=0
https://lagoon-ci.amazeeio.cloud/blue/rest/organizations/jenkins/pipelines/lagoon/branches/PR-2311/runs/14/nodes/45/steps/46/log/?start=0
Both occurred in the same place, but retries got them through.

Notwithstanding, we should probably have stopped the tests once the API responded with a fail `"api response: {u'errors': [{u'path': [u'deployEnvironmentBranch'], u'message': u'Unauthorized: You don\\'t have permission to \"deploy:development\" on \"environment\".', u'locations': [{u'column': 56, u'line': 1}]}], u'data': {u'deployEnvironmentBranch': None}}"`

**Comment by smlx** [comment]
Agree that this should fail faster.

I think this is less to do with the parallel builds, and more related to the way that the API takes a while to process all the fixtures we pump in via the `data-watcher-pusher`.

Probably the best fix for now would be to check the response and retry a few times to trigger a deploy before eventually failing.
