### ISSUE TITLE
DBaaS Timeout SERVICE_BROKER_COUNTER is not triggered

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#2485]
# Describe the bug

If the DBaaS Service does not provision a service the deployment is running indefinitely

https://github.com/amazeeio/lagoon/blob/main/images/kubectl-build-deploy-dind/scripts/exec-kubectl-mariadb-dbaas.sh#L10-L13

```+++ '[' 1 -lt 180 ']'
+++ let SERVICE_BROKER_COUNTER=SERVICE_BROKER_COUNTER+1
+++ echo 'Service for mariadb not available yet, waiting for 5 secs'
+++ sleep 5
```

SERVICE_BROKER_COUNTER is increased but OPERATOR_COUNTER is used in the if statement leading to the condition never reaching the else portion

**Comment by tobybellwood** [comment]
SERVICE_BROKER_COUNTER has been removed now
