### ISSUE TITLE
API does not allow authentications if one SSH Key is wrong

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#250]
To reproduce:
Add an SSH Key that is not valid (like do not add the last character of the Key via `addSshKey`

Outcome:
Whole API does not work anymore and fails with 
```
(node:33) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 37): KeyParseError: Failed to parse (unnamed) as a valid ssh format key: length out of bounds at +0x16 (data truncated?)
```

Expected Outcome:
API still works and just ignores the not valid SSH Key

**Comment by ryyppy** [comment]
Bug is produced by `api/routes/keys.js` -> prevent single wrong sshkeys to break all keys
also add validation for addKey / updateKey before inserting in database (see #249)
