### ISSUE TITLE
Links to logs and routes not showing up in Slack CI integration

### ISSUE THREAD

**Issue by jaimed-amazee** [uselagoon/lagoon#2507]
# Describe the bug

The Slack CI integration is no longer displaying links to logs and routes on successful deploy complete messages.  The links are visible on the RocketChat integration.

## To Reproduce

1.  Start a new build on a project that has notifications going to a Slack channel
2. Once the build completes, there should be a messages stating that the build completed successfully and it should provide links to Logs and routes.

## Expected behavior

Links to the logs for the build and routes should be displayed, but are not.

## Screenshots

<img width="513" alt="New Slack Integration" src="https://user-images.githubusercontent.com/54284907/107712752-93c1b200-6c8f-11eb-8bc5-90f3e23ec810.png">
<img width="622" alt="Old Slack Integration" src="https://user-images.githubusercontent.com/54284907/107712755-945a4880-6c8f-11eb-9f99-8cd097e0a744.png">

**Comment by rocketeerbkw** [comment]
Duplicate of #2511
