### ISSUE TITLE
Deploy Messages miss the Ingress URLS and the link to the Logs

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#2511]
# Describe the bug

The `openshiftbuilddeploymonitor` service put the Log Link as well as the Ingress URLs into a successful Deploy Message. Currently the `builddeploymonitor` seems not to do this towards Slack (but for Rocketchat).
## Expected behavior

Messages on all notification streams include the link to the deploy logs as well as the ingress URLs

## Screenshots

![Bildschirmfoto 2021-02-15 um 11 51 16](https://user-images.githubusercontent.com/391732/107937467-3de95480-6f84-11eb-9bbd-906170a69f41.png)

**Comment by Schnitzel** [comment]
@shreddedbacon I think you looked at this already? How hard is this to fix?

**Comment by shreddedbacon** [comment]
> @shreddedbacon I think you looked at this already? How hard is this to fix?

I looked at it briefly. I think it is mainly because the logs2slack is looking for something that the other notification services don't use.

I'll have another look shortly and see if it will be a relatively simple fix.

**Comment by BrianGilbert** [comment]
![Station 2021-03-18 09-34-07](https://user-images.githubusercontent.com/114017/111548670-272a5d80-87cf-11eb-842b-1d8074b1ebec.png)

This is what we are getting using webhook with Discord, would also love for the routes to be echoed out in the success message, and logs link would be sublime too

**Comment by shreddedbacon** [comment]
This PR https://github.com/amazeeio/lagoon-kbd/pull/42 adds the support for slack messages that was missing.

I noted in that PR that the entire notification service needs to be re-written so that we have a more consistent messaging experience across all the notification services though.

**Comment by tim-yao** [comment]
Have same issue in DPC SDP slack. Look forward to a fix.

**Comment by shreddedbacon** [comment]
The latest build deploy controller release includes fixes for this, my understanding is this was recently rolled out.

@tim-yao are you able to confirm if slack messages are now as expected?
