### ISSUE TITLE
Support ClamAV as a Service Type

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#2528]
A lot of customers require the use of ClamAV within their cluster. This is better to be run as a dedicated service over TCP/IP then building into the `Nginx/PHP` images (in executable mode). 

Advantages of running a single service in the cluster:

* Only a single virus database to update (with FreshClam)
* Consumes less resources overall (only 1 deployment in the cluster)
* TCP/IP scanning is much quicker than executable mode

It would be excellent if we could support this as a dedicated Lagoon service type, running on port `3310` (default port). Custom `livenessProbe` and `readinessProbe` configuration can be made to ensure we cater for the initial launch time (which can be several minutes while ClamAV initialises it's database). 

At the moment, we are seeing customers create ClamAV deployments using the `node` service type, this has many disadvantages, mainly:

* Runs on port `3000`, so you need to edit the default configuration, this is confusing
* The `livenessProbe` and `readinessProbe` are not tuned to ClamAV
* The CPU and RAM resources are not tuned to ClamAV

**Comment by tobybellwood** [comment]
I think this can be considered in two parts:

* Creation of a standard, optimized ClamAV image for use in Lagoon
* Creation of a helm chart with the correct configurations for running in a lagoon-remote installation

**Comment by Schnitzel** [comment]
yea, for me clamav doesn't belong into lagoon, this should be deployed as a cluster level tool via helm.
Deploying it via lagoon doesn't really have any advantages and its also not a web-application like everything else in Lagoon.

Therefore to not add too many complicated things I would suggest to just deploy this via helm into the cluster and not worry about it in lagoon.

**Comment by nicksantamaria** [comment]
I agree with @Schnitzel  - theres no value for us to run clamav as a lagoon project (beyond it currently being the simplest way to deploy it). 

If it came as part of the cluster, deployed with helm or whatever, I'd drop ours in a heartbeat.

**Comment by tobybellwood** [comment]
yah - clamav in cluster is preferred. There are now more lagoon service types that could be used for clam though - basic or worker?
