### ISSUE TITLE
Monitoring cannot be disabled for ingresses on kubernetes

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#2555]
# Describe the bug

For a new site being developed on Lagoon, sometimes DNS is not set up yet. That means that monitoring will fail for any custom domains added to the site.

## To Reproduce

1. Deploy a site on Lagoon k8s with a domain that you own, but have not set up any A/AAAA records for.
2. Monitoring is configured but fails immediately

## Expected behavior

Maybe monitoring should be configurable via `.lagoon.yml`. One way it could work is like the existing `tls-acme: true/false`. We could also have `monitor: true/false` that defaults to true but can be disabled.

## Screenshots

n/a

## Additional context

Does `monitoring_urls` do anything on kubernetes?

**Comment by tobybellwood** [comment]
Actual monitoring to be implemented outside Lagoon - Lagoon only provides minimal config to support it..
