### ISSUE TITLE
API updates not happening when environments with special characters complete.

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#2568]
# Describe the bug

There is currently an issue where if an environment that has special characters in it, eg `/`, are handled by the controller. 

Currently Lagoon will make safe (dns compliant) environment names before sending to the controller. This is fine, but any time an update or entry is returned to Lagoon to be handled by the controllerhandler, the API check for the environment fails as lagoon is expecting to see the environment name before it was made safe.

## To Reproduce

1. Deploy an environment like `feature/my-cool-feature`
2. On completion check the API/UI for the existence of any `ROUTES`
3. See there are no routes

## Expected behavior

Routes and/or other updates should be in the API

## Additional context

Checking the controllerhandler logs shows that the updates failed because of the environment not being found, further investigation shows that this is because of the environment name being made dns-compliant before being sent to the controller.

**Comment by shreddedbacon** [comment]
Just adding this to make sure the issue was known and that #2565 is raised is to fix this issue specifically

It does **NOT** attempt to solve #2322

**Comment by rocketeerbkw** [comment]
Fixed in 2.x with #2596
