### ISSUE TITLE
API container sync:opendistro-security fails to create tenants

### ISSUE THREAD

**Issue by KorvinSzanto** [uselagoon/lagoon#2577]
# Description
Running `yarn sync:opendistro-security` in a running API container leads to a 400 bad request error when creating tenants:
```
2021-03-16T18:36:55.432Z - info: Syncing 3 groups
2021-03-16T18:36:55.433Z - debug: Processing lagoonadmin
debug: lagoonadmin: Created OpendistroSecurity role "lagoonadmin"
error: Opendistro-Security create tenant error: HTTPError: Response code 400 (Bad Request)
debug: lagoonadmin: Created index-pattern "application-logs-*"
...
```

This error [is thrown here](https://github.com/amazeeio/lagoon/blob/main/services/api/src/resources/group/opendistroSecurity.ts#L66) when opendistro-security api endpoints don't behave.

The reason this request is leading to a 400 is because it doesn't include the required `description` json body key, I can't find when this changed in opendistro-security but it seems like it's required now.

## To Reproduce

Firstly make sure you have an up to date opendistro-es install

1. Exec into a running api container with `k exec -n lagoon-core -it deployment/lagoon-core-api -- sh`
2. Run `yarn sync:opendistro-security` in the continaer
3. See the error

## Expected behavior

No error, expect the tenant to be created

## Additional context

I've tested this with postman and can create the tenants successfully only when the description is included. So I've opened a PR that adds a generic description.

**Comment by tobybellwood** [comment]
fixed in #2578
