### ISSUE TITLE
Lagoon UI: Add pagination to the backup list

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#2595]
At the moment, for projects that have existed for a long time, it is not uncommon to have many hundreds, if not thousands of backups to be listed on the environment backup page. Here is an example of a project with a lot of backups:

```js
document.getElementsByClassName('data-row').length
1438
```

I would say the 99% use case is to get a recent backup, and not to scroll down the page and hunt for the backup.

## Feature request

Can we add pagination to the backup list screen, and show perhaps the last 7 days worth of backups, or the most recent 20 or something?

Related to #1382

**Comment by rocketeerbkw** [comment]
Display limits were added in #2771. Pagination is a feature that'd we like to add in the future for the entire schema.
