### ISSUE TITLE
Running `deleteAllProjects` resets the project table autoincrement leading to oddly linked data

### ISSUE THREAD

**Issue by KorvinSzanto** [uselagoon/lagoon#2616]
# Describe the bug
Running `deleteAllProjects` will reset the autoincrement ID, this wouldn't matter but there are orphaned resources left around when `deleteAllProjects` runs and so creating a new project with ID `1` leads to those orphaned resources being errantly linked with the new project.

## To Reproduce

1. Create a project with a "main" environment, deploy it, run some kind of task
2. Run `deleteAllProjects` and if you'd like `deleteAllEnvironments`
3. Create a new project with a new "main" environment
4. Observe the deployments and tasks from step 1 associated with the envrionment created in step 3.

## Expected behavior

A new project should never be associated with resources it did not create.

**Comment by KorvinSzanto** [comment]
The two ways I see to avoid this are:
1. Use `delete from projects` instead of `truncate projects` which means defining a query and [using it here](https://github.com/amazeeio/lagoon/blob/42bf55050d1bd1ddfd5b92cc6e3dafa3f31b0420/services/api/src/resources/project/resolvers.ts#L702)
2. Delete deployments and tasks when deleting environments

I'd definitely prefer #2, but I'd guess #1 would be easier to implement

**Comment by rocketeerbkw** [comment]
Thanks for reporting.

The `deleteAll` mutations are in there for testing infrastructure and local development support only, and not designed to be used in production. If you run that, you should run all `deleteAllX` mutations. Even if you do that there will still be left over stuff in the api-db. We've reworked a bit to not require those mutations being the the API and have an [issue to retire those mutations](https://github.com/amazeeio/lagoon/issues/2101) and also an [issue for cleaning up related resources](https://github.com/amazeeio/lagoon/issues/1475) on project deletion.
