### ISSUE TITLE
support: How to use Branch specific `env` file in Dockerfile during Build?

### ISSUE THREAD

**Issue by Decipher** [uselagoon/lagoon#2622]
As per https://docs.lagoon.sh/lagoon/using-lagoon-advanced/environment-variables#lagoon-env-usdbranchname, I have a couple of Branch specific env files:
- https://github.com/druxt/demo.druxtjs.org/blob/develop/.lagoon.env.develop
- https://github.com/druxt/demo.druxtjs.org/blob/develop/.lagoon.env.main

The files are loaded in correctly during runtime, but I also need the variables to be available during build in my Dockerfile:
- https://github.com/druxt/demo.druxtjs.org/blob/develop/Dockerfile

While I could use the Lagoon CLI to add the variables, this is a demonstration repository and I wish to have as much transparency as possible.

**Comment by rocketeerbkw** [comment]
@Decipher we don't support build time variables defined in environment files, the only way to add them is via the API.

We do have an open issue for that: https://github.com/amazeeio/lagoon/issues/574.
