### ISSUE TITLE
Consider compressing DB backups

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#2649]
# Describe the bug

I don't think we currently compress DB backups.

## To Reproduce

1. Inspect mysqldump commands in prebackuppods.

## Expected behavior

Lagoon compresses DB dumps if it results in more efficient use of space.

## Screenshots

n/a

## Additional context

DB dumps are highly compressible. However we have to be a bit careful about how we do it because `restic` uses a rolling checksum to "chunk" the data it backs up. A small change in one area of the DB backup can cause large changes in the compressed file when using straight up `gzip` or `zstd`.

Fortunately these commands already have an `--rsyncable` flag to work around this and make the compression friendlier to rolling checksums.

I don't know if the space saved is worth the extra complexity. For example this change in backup logic would also require changes in restore logic. Probably needs some experimentation to generate numbers to see if this is worth doing.

**Comment by tobybellwood** [comment]
of relevance - https://github.com/restic/restic/issues/790

**Comment by smlx** [comment]
AFAIK restic now does compression by default, including deduplication. So this will be fixed for new backup respositories by simply upgrading k8up.

https://restic.readthedocs.io/en/stable/047_tuning_backup_parameters.html#compression

So I think we can close this issue?
