### ISSUE TITLE
skopeo commands (and others?) during builds should retry

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#2657]
# Describe the bug

A transient network issue with `skopeo` failed a whole Lagoon deploy.

## To Reproduce

1. Run a build.
2. It fails.
3. Check logs.
4. Run again, maybe it succeeds.

Failed build 1:
```
...
time="2021-05-17T12:36:12Z" level=fatal msg="Error reading blob sha256:4c1c7b9ec858d96f034adb39c39658fef06a007dfe7e6ea6ecc4c8c55c612e1d: Get https://<>/v2/amazeeio/redis/blobs/sha256:4c1c7b9ec858d96f034adb39c39658fef06a007dfe7e6ea6ecc4c8c55c612e1d: read tcp 10.244.3.149:53444->34.206.115.145:443: read: connection timed out"
```
Failed build 2:
```
...
time="2021-05-17T12:20:37Z" level=fatal msg="Error reading blob sha256:4c1c7b9ec858d96f034adb39c39658fef06a007dfe7e6ea6ecc4c8c55c612e1d: Get https://<>/v2/amazeeio/redis/blobs/sha256:4c1c7b9ec858d96f034adb39c39658fef06a007dfe7e6ea6ecc4c8c55c612e1d: read tcp 10.244.3.147:40282->34.206.115.145:443: read: connection reset by peer"
```

This deploy succeeded the third time.

## Expected behavior

Any network operation such as copying blobs around has the possibility to encounter network errors.
Instead of failing the build immediately Lagoon should at least retry a couple of times to make the build process more robust.

## Screenshots

n/a

## Additional context

n/a

**Comment by chandanatk** [comment]
Had another deployment failing with a similar error and succeeded in 3rd attempt

`time="2021-11-18T06:26:42Z" level=fatal msg="Error writing blob: Patch \"https://harbor.ch3.amazee.io/v2/XXX/production/varnish/blobs/uploads/395e2aa2-954d-4f2b-938b-cf8717291635?_state=0_74pJY6sVhdWgIv8624EJj6I1Ab9X3SoiQ8d8bHltR7Ik5hbWUiOiJhZHlheC1pbmZvcHJvL3Byb2R1Y3Rpb24vdmFybmlzaCIsIlVVSUQiOiIzOTVlMmFhMi05NTRkLTRmMmItOTM4Yi1jZjg3MTcyOTE2MzUiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjEtMTEtMThUMDY6MjY6MTIuMjkzODQ1ODQ3WiJ9\": dial tcp 34.65.41.217:443: i/o timeout"`

**Comment by tobybellwood** [comment]
Just had another similar report - this time pulling from imagecache.amazee.io - also redis and varnish images, and on an Azure cluster.

**Comment by chandanatk** [comment]
+1 
on an Azure cluster
`time="2022-01-17T23:51:46Z" level=fatal msg="Error trying to reuse blob sha256:adb259581afb1e6d7dd7595bcee919b632310d6a4eea312c56bc335c6e7ff92f at destination: Head \"-storage//docker/registry/v2/blobs/sha256/ad/adb259581afb1e6d7dd7595bcee919b632310d6a4eea312c56bc335c6e7ff92f/data?se=2022-01-18T00%3A11%3A45Z&sig=Icv5WcmgOIPcHDQPbL%2BfEYKUeY0uOmwH608JOD7s4KY%3D&sp=r&sr=b&sv=2016-05-31\": read tcp 10.244.2.44:32858->52.239.131.36:443: read: connection reset by peer"`
