### ISSUE TITLE
autogenerate `.my.cnf` in CLI container

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#267]
it would be very cool if the CLI container autogenerates an `.my.cnf` so the users can just run `mysql` in the cli.

As the CLI container itself doesn't really ahead if there is a mariadb or other service existing, we probably need to do some clever autodiscovery if `mariadb` is resolveable and based on that create the `.my.cnf`.

For User/Pass inside `.my.cnf` we can use the global env variables  `MARIADB_DATABASE` `MARIADB_USER` `MARIADB_PASSWORD`

Important: for the `mariadb-drupal` Image they are `drupal` where for `mariadb` they are `lagoon`, but we have a `cli-drupal` Image so we can overwrite that there

**Comment by rtprio** [comment]
From what I've seen so far, intra-pod communication for this sort of metadata seems like it would be extremely tricky, add starting dependancies, and so forth. Could something like this benefit from a central secrets controller, such as #65. 

Would it make sense for `oc-build-deploy-dind` to generate some passwords, which could then be pulled out of the environment and in multiple pods, such as `MARIADB_USER`? maraidb root password and maxscale password could also make use of this, perhaps via templates?

It could also be a prototype for other resources such as generating a key that is used for encrypting files in git.

**Comment by Schnitzel** [comment]
this has been implemented
