### ISSUE TITLE
How to start using it?

### ISSUE THREAD

**Issue by hanoii** [uselagoon/lagoon#27]
Is there any document or a best way to start using it?

Let's say I want to set up a new drupal site to work on and have it deployed somewhere, say digital ocean, linode or whatever. 

Thanks.. I am very curious to give this a try.

**Comment by Schnitzel** [comment]
@hanoii 
thanks for your interest! Currently all documentation is focused on how to develop locally and how the testing framework works. But we are working on documentation on how to install and use Lagoon on your own server.

Just a heads up:
Lagoon works together with OpenShift (which is a Docker Orchestration system based on Kubernetes). So the first step is to install OpenShift on a server of you choice and then install Lagoon inside of it.

There are many tutorials out there to install OpenShift on a server, like DigitalOcean or Linode. Just make sure that you choose a tutorial for OpenShift Origin (version numbers 1.5 or 3.6 and bigger), there is an older version of OpenShift (mostly referred as version 2) which will not work together with Lagoon.

**Comment by hanoii** [comment]
Hi @Schnitzel ,

When you say develop locally, you mean *a project* or develop locally on laggon? Because the former wasn't too intuitive for me either.

I mean.. say that I want to start a new drupal project (or whatever, but being drupal what I do the most).. what should I do locally?

Download docker, openshift, clone this, then do what?

Maybe I missed something but laying out some bare quickstart guide will really make onboarding/testing much more easier.

I see https://github.com/amazeeio/drupal-example and spotted the lagoonize branch which I guess it's meant to something like this.. but.. a recipe, even if bare, would be awesome.

I will follow your heads up and install those things on a digital ocean and then clone this, although not sure what to do next :) I guess I am just anxious

**Comment by n1ru4l** [comment]
@hanoii https://github.com/amazeeio/lagoon/pull/23/files#diff-f785e9e46b9afd2567df7a658338db17
I found this. I am also curious about trying out lagoon 🤗

**Comment by Schnitzel** [comment]
@hanoii 
Let me try to remove some confusion here :)

If you just like to develop Drupal locally, you don't need Lagoon, you should look at https://docs.amazee.io/local_docker_development/local_docker_development.html which will explain you how to run the amazee.io local docker environment and how to run Drupal in there.

If you like to host that local developed Drupal Site on an amazee.io server (I understand that you don't want that, but just for the purpose of explaining), you don't need Lagoon, as we already have Lagoon running and also OpenShift running. All you need to do is give us access to your github repository where you have your Drupal hosted and we will then deploy this for you.

If you like to host that local developed Drupal Site on your own server, then you need Lagoon. But currently all the documentation there is is about developing Lagoon locally, and there is no documentation yet how to start your own Lagoon inside an existing OpenShift. We're working on that and will probably have something this week :)

Will keep you updated as soon as we have something :)

Michael

**Comment by Schnitzel** [comment]
also regarding installation, I started https://github.com/amazeeio/lagoon/blob/develop/docs/INSTALL.md which will explain how to install it. It's in no place complete yet as I'm realizing that installing it on another OpenShift with no knowledge is a bit harder than I thought. So we are refactoring some parts of the system in order to make it easier (like https://github.com/amazeeio/lagoon/issues/47)

So we are working on this, it will take a couple of days more, sorry.

**Comment by jonathanjfshaw** [comment]
Thanks for your work on docs @Schnitzel, I see you did a big chunk yesterday. A developer of mine will be looking at Lagoon for us in a few days, so I'm hoping you'll get time to fill in those last @todo's ...

**Comment by Schnitzel** [comment]
It's here! It's finally here!

We just launched [v0.6.0](https://github.com/amazeeio/lagoon/releases/tag/v0.6.0) and with that much better documentation:
https://github.com/amazeeio/lagoon/blob/master/docs/INSTALL.md

Sorry for all the wait, but we really wanted to get everything of 0.6.0 in it so you don't have to work with weird Hiera Git Repos and stuff :)

**Comment by hanoii** [comment]
Wow, I am truly curious. I have to admit the INSTALL docs was a bit jaw dropping at first, but it could be the time of night. Just double checking, I should install openshift on a server (would a DigitalOcean droplet work? Any minimum requirements?) and then follow that doc?

From there one, what should I use locally to deploy to the lagoon server? your own local developer?

Thanks!!! And Happy to see this moving forward.

**Comment by dgtlmoon** [comment]
@Schnitzel your link to the documentation give a 404

**Comment by rtprio** [comment]
A lot has changed since November; The install guide is in the administering_lagoon directory of the docs.

https://github.com/amazeeio/lagoon/tree/master/docs
