### ISSUE TITLE
udpate default activeSystems* values

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#2701]
The current values for the `activeSystems*` config of projects is still set to `lagoon_openshift*` settings, this should be updated to the `lagoon_controller*` varieties.

**Comment by tobybellwood** [comment]
I presume it's set in here as default fallbacks if not specified - https://github.com/uselagoon/lagoon-one/blob/master/services/api/src/resources/project/resolvers.ts#L307-L331

**Comment by twardnw** [comment]
The defaults were changed in Lagoon 2 RC1
