### ISSUE TITLE
Move activeSystems* to the cluster, and out of the project

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#2702]
As a follow up to #2701, we should normalise the data in the API database to refer to the active systems at a cluster level. This way we avoid the situation entirely of having out of date, or inaccurate active systems for a given project on a given cluster.

It also means that moving to newer systems is a trivial tasks that is done once for all projects on a given cluster.

If you want to test a given active system on a given project (and not cluster wide), you can always create a new cluster, assign the appropriate active systems, and copy the other settings from the previous cluster.

## Current schema

```
project
 - cluster (int)
 - active_systems_deploy
 - active_systems_promote
 - active_systems_remove
 - active_systems_misc
 - active_systems_task
 - ...

openshift
 - id
```

## Proposed schema

```
project
 - cluster (int)
 - ...

openshift
 - id
 - active_systems_deploy
 - active_systems_promote
 - active_systems_remove
 - active_systems_misc
 - active_systems_task
```

Also related to #2285 in which we proposed changing the name of the table from `openshift` to `kubernetes`.

**Comment by tobybellwood** [comment]
This behaviour has been fixed now, and you no longer need to specify the active_sytems
