### ISSUE TITLE
Users added to a group via Gitlab are not getting correct project access in Lagoon

### ISSUE THREAD

**Issue by chandanatk** [uselagoon/lagoon#2703]
# Describe the bug

One of our customers using Gitlab to manage projects, users etc: recently experiencing an issue with Lagoon access. When users are added to a group, they do not get access to the projects in that group on Lagoon. This used to work before and hard to say when it stopped working. When added to a project-specific group, that still works correctly as expected.

## To Reproduce

Steps to reproduce the behaviour:

1. Go to a user on 'Gitlab'
2. Add to a group or remove from an existing group and add again
3. Check the user on keycloak. This change does not show in Keycloak -> user -> groups 
4. Below error can be seen on webhooks2tasks logs
`2021-06-16T23:25:46.024Z - info: Handling gitlab:user_add_to_group uuid=97f87616-fc87-4190-b5d7-04383103605b
2021-06-16T23:25:46.269Z - error: lagoon-logs: Send to lagoon-logs: Could not add user to group , reason: TypeError: async_retry_1.retry is not a function`

5. Now do the same but with a project-specific group this time
6. See that works correctly as reflected on Keycloak

## Expected behaviour

Users getting added correctly to groups similar to project-specific groups when managed using Gitlab

## Additional context

The current workaround to this issue is adding the user to the group again using Lagoon cli since that works as expected.

**Comment by bomoko** [comment]
It seems as though `async-retry` is being pulled in incorrectly here

https://github.com/uselagoon/lagoon/blob/de9a20c02a165c3976ca24cce586e676c3d83330/services/webhooks2tasks/src/handlers/gitlabUserGroupAdd.ts#L1

we shouldn't be destructuring the import.

**Comment by tobybellwood** [comment]
@bomoko - do we have a quick PR for this - is it just removing the curly braces?

**Comment by bomoko** [comment]
indeed there is @tobybellwood - ^^ this should do it.
