### ISSUE TITLE
As a developer I'd like to have links/buttons on Slack's builddeploymonitor integration messages so that I can swiftly halt or inspect unwanted builds and deploys

### ISSUE THREAD

**Issue by luigimannoni** [uselagoon/lagoon#2712]
Titled into an user story if that's more helpful to convey the message, I'll rephrase if requested.

This is a very welcome touch that would help a lot teams with a bunch of different projects running/building on Lagoon, often during a code review we face the possibility to merge two or more pull requests in a short timeframe or even have back-to-back merges spawning a quite high number of unwanted builds like in the screenshot below:

![Screenshot from 2021-06-23 15-35-41](https://user-images.githubusercontent.com/1405327/123124033-3c063500-d43f-11eb-8f53-9c75cca39adc.png)

The current workaround we're adopting for now is to disable the webhooks temporarily from the repositories and re-enabling these back before merging the last pull request, however that requires a developer with repository admin access to be present on code review and not everyone has access to that. In that case we're forced to log in into the project pages and halt the deploys one by one, which works if we're dealing with one single project and a couple of clicks to reach one build, a little bit less if we're dealing with 5 different projects and trying to halt 5 to 20 builds.

A lot of different app integrations on Slack offer a quick button to trigger an action remotely without logging into or navigating through the lagoon projects web interface, wondering if the same can be added to the current builddeploymonitor integration? 

Or a simple link that points to the `https://ui-lagoon-master.ch.amazee.io/projects/[project]/[env]/deployments/lagoon-build-[hash]` URL could do also the job?

See below some examples of quick action buttons on Slack messages:

![Screenshot from 2021-06-23 15-50-08](https://user-images.githubusercontent.com/1405327/123126665-7b358580-d441-11eb-972c-9c005e861b61.png)
![Screenshot from 2021-06-23 15-52-10](https://user-images.githubusercontent.com/1405327/123126860-a91aca00-d441-11eb-8400-ee2a704c5ed3.png)

**Comment by tobybellwood** [comment]
The newer build systems will compress consecutive builds for any environment, cancelling any builds that are superseded before starting.

The screenshot show a polysite, which is one of the downsides of polysites.

As for a greater interaction via slackbots, they're not really in scope at the moment for us, but happy to hear if this is still a use case for you
