### ISSUE TITLE
Slack builddeploymonitor duplicates ingress URLs

### ISSUE THREAD

**Issue by janmashat** [uselagoon/lagoon#2736]
# Describe the bug

Slack notifications contain duplicate URLs

## Expected behavior

Ingress URLs should not be duplicated.

## Screenshots

<img width="550" alt="Screenshot 2021-06-30 at 11 21 53" src="https://user-images.githubusercontent.com/12157479/123936917-edecb680-d995-11eb-9e9b-fea9e0d0c6b8.png">

**Comment by tobybellwood** [comment]
no longer occurring
