### ISSUE TITLE
built-in layer caching to speed builds

### ISSUE THREAD

**Issue by rtprio** [uselagoon/lagoon#274]

**Comment by Schnitzel** [comment]
During Lagoon Builds this already exist (with the fact that there is docker-host that keeps the caches).

I assume you are referring to builds that happen during development of lagoon on local computers?

**Comment by rtprio** [comment]
Correct; a `make docker-safe` and `make docker-load` functionality.

**Comment by rtprio** [comment]
This is done with the `make s3-load` behavior.
