### ISSUE TITLE
send audit log to lagoon-logs rabbitmq queue for storing in lagoon-logging elasticsearch

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#2740]
right now the api just outputs the audit-log as console log. While this is captured by lagoon-logging container log system, it's not parsed and cannot easily be analyzed as it's just raw text logs.

If we send the audit log to the lagoon-logs rabbitmq queue, they would be picked up by lagoon-logging collector and put into the elasticsearch fully parsed, also if we provide the projectname in the logs, they will be indexed to the lagoon-logs of the project and the customers will be able to see the logs of their projects.

here an example on how we send these logs currently:
https://github.com/uselagoon/lagoon/blob/f9fb6852040416c16c7c5a5af60a10608784d404/services/api/src/resources/deployment/resolvers.ts#L556-L563

**Comment by timclifford** [comment]
WIP: https://github.com/uselagoon/lagoon/pull/2800

**Comment by smlx** [comment]
Since the existing `lagoon-logs` are already used for another purpose, should we maybe create a new `audit-logs-` prefix instead?

**Comment by Schnitzel** [comment]
@smlx 
I would really like to prevent to create another index in elasticsearch, we already have way too many indexes on our elasticsearch clusters.
also for me these are lagoon-logs, no? like who created a project in lagoon would be a log of lagoon?

**Comment by smlx** [comment]
I guess they are, but the problem is that the fields do not match. Elasticsearch is designed around homogenous logs with the same set of fields in each record, but the existing fields in lagoon-logs will not match audit-logs. lagoon-logs currently just contain build logs, don't they?

**Comment by tobybellwood** [comment]
There may also be a requirement to keep audit logs for a different retention period, which may be easier in ILM with a different index?

**Comment by Schnitzel** [comment]
> lagoon-logs currently just contain build logs, don't they?

no, they include much more, basically every time `sendToLagoonLogs` is called in the services it creates a lagoon-log entry: https://github.com/uselagoon/lagoon/search?q=sendToLagoonLogs
so for example every deployment success/failure, every webhook, etc is logged. The problem is that in the past they have not been logged with the userID that triggered the action.

So for me the "audit-logs" are just additional and more detailed lagoon-logs which specifically call out who has made the api call.

> but the existing fields in lagoon-logs will not match audit-logs.

if we use the existing lagoon-logs logging infrastructure the fields will match :)

> There may also be a requirement to keep audit logs for a different retention period, which may be easier in ILM with a different index?

Like mentioned above, for me I don't see any difference in an audit log or a lagoon log, maybe a customer wants to know when exactly a deployment has been finished, while another customer wants to know who logged in.

I think the easiest right now is to use the existing lagoon-logs infrastructure and we can  refactor the whole lagoon logs logging infrastructure in the future when we switch the api and services to be build with another programming language

**Comment by tobybellwood** [comment]
audit logs now go to a dedicated single index outside customer namespaces, for admin only
