### ISSUE TITLE
Old $LAGOON_SAFE_PROJECT in task command

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon#2741]
# Describe the bug

In here https://github.com/uselagoon/lagoon/blob/ea0583e3d6cac186fe83d6fc17126da5be8c7228/services/api/src/resources/task/resolvers.ts#L303 and here https://github.com/uselagoon/lagoon/blob/ea0583e3d6cac186fe83d6fc17126da5be8c7228/services/api/src/resources/task/resolvers.ts#L348 the `command` uses the old `$LAGOON_SAFE_PROJECT` variable that doesn't exist anymore.
It should use `$LAGOON_PROJECT` instead.
The resulting file is something like `/tmp/-dev-2021-07-01T10:09:07+00:00.sql.gz`

Here the full log of a task pod
```
> mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation> ' when trying to dump tablespaces
 [success] Database dump saved to /tmp/-prod-2021-07-01T10:09:07+00:00.sql.gz
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added '[ssh.lagoon.amazeeio.cloud]:32222,[34.65.70.251]:32222' (ECDSA) to the list of known hosts.
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

## To Reproduce

1. Login into the UI (dashboard)
2. Select a project and an environment
3. Run a task like `drush sql-dump`
4. The tasks completed successfully but no link to download file

## Expected behavior

UI should show a link to download file

**Comment by Schnitzel** [comment]
this is just a missing environment variable, the error in the log is an nginx error. They most probably have nothing to do with each other.

we definitely should fix the usage of `$LAGOON_SAFE_PROJECT`, but it will just make the filename nicer and not actually fix the upload issue.
