### ISSUE TITLE
api fails requests while refreshing keycloak admin token

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#2744]
I'm not sure if this is really an issue or if it's maybe something else.

But we are seeing in the amazee.io lagoon some api errors here and there, looking at the logs of all api pods I can find this behavior:
As soon as in the logs we have
```
lagoon-core-api-8b58b44fd-57dqk api [2021-07-01 14:49:58] [debug]: keycloakAdminClient: refreshing expired token
lagoon-core-api-8b58b44fd-57dqk api [2021-07-01 14:49:58] [debug]: keycloakAdminClient: refreshing expired token
lagoon-core-api-8b58b44fd-57dqk api [2021-07-01 14:49:58] [debug]: keycloakAdminClient: refreshing expired token
lagoon-core-api-8b58b44fd-57dqk api [2021-07-01 14:49:58] [debug]: keycloakAdminClient: refreshing expired token
```

right after that we have many failed requests:

```
lagoon-core-api-8b58b44fd-57dqk api [2021-07-01 14:49:58] [error]: Could not submit project (2345) claims for authz request: User not found: d414bb26-1211-4045-998a-3138378c1042
lagoon-core-api-8b58b44fd-57dqk api [2021-07-01 14:49:58] [error]: Could not submit project (2345) claims for authz request: User not found: ecebfcff-2fd5-483b-9ec1-c74ae06a9ebc
lagoon-core-api-8b58b44fd-57dqk api [2021-07-01 14:49:58] [error]: Could not submit project (2345) claims for authz request: Request failed with status code 404
lagoon-core-api-8b58b44fd-57dqk api [2021-07-01 14:49:58] [error]: Could not submit project (2345) claims for authz request: Request failed with status code 404
lagoon-core-api-8b58b44fd-57dqk api [2021-07-01 14:49:58] [error]: Could not submit project (2345) claims for authz request: Request failed with status code 404
lagoon-core-api-8b58b44fd-57dqk api [2021-07-01 14:49:58] [error]: Could not submit project (2345) claims for authz request: Request failed with status code 404
lagoon-core-api-8b58b44fd-57dqk api [2021-07-01 14:49:58] [error]: Could not submit project (2345) claims for authz request: User not found: 17cda1c1-e9b6-47b0-8c24-f995636318b3
```

this is how it looks in the error log:
![stern_--tail_10_lagoon-core-api_and_Lens_and_Slack_____aio-agency-finalist-internal___Amazee___6_new_items](https://user-images.githubusercontent.com/750999/124145086-7df43400-da5a-11eb-8dec-216480e0860f.jpg)

Now I'm not sure if this is the source of the api errors, but maybe while the tokens are refreshed every request that comes in at the same time fails because the token is not refreshed yet?

**Comment by rocketeerbkw** [comment]
I'm testing another issue, but locally I'm seeing these same "User not found: [valid UUID]" errors except I don't see any "refreshing expired token" messages before hand.

**Comment by tobybellwood** [comment]
We've implemented some changes that reduce the incidence of this, but it still requires some updates to upstream keycloak libraries that can't progress.

**Comment by smlx** [comment]
This is closely related to #3217 since if client auth was used, token refresh would not be required.
