### ISSUE TITLE
Lagoon Drush sql-dump task sometimes truncates the DB dump file

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#2751]
# Describe the bug

Lagoon Drush sql-dump task sometimes truncates the DB dump file.

## To Reproduce

1. Run a drush sql-dump task.
2. See it complete successfully.
3. Download the file.
4. See gzip report that the file is truncated:

```
$ zcat example-master-2021-07-05T08\ 16\ 35+00\ 00.sql.gz | tail -c 128

gzip: example-master-2021-07-05T08 16 35+00 00.sql.gz: unexpected end of file
-XXXXXXXXXXX-xxxxxxxxxxxxxxxxx','i:1555555555;',2111111111),('honeypot_time_restriction','XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

Downloading the file multiple times results in the same truncated file with the same `sha256sum`.

## Expected behavior

I expected the file not to be truncated.

## Screenshots

n/a

## Additional context

Here are the logs of the task pod:

```
[pod/lagoon-task-12345-mnopqr/cli] 2021-07-05T08:17:47.982553919Z  [success] Database dump saved to /tmp/example-master-2021-07-05T08:16:35+00:00.sql.gz
[pod/lagoon-task-12345-mnopqr/cli] 2021-07-05T08:17:48.186664335Z Pseudo-terminal will not be allocated because stdin is not a terminal.
[pod/lagoon-task-12345-mnopqr/cli] 2021-07-05T08:17:48.255605119Z Warning: Permanently added '[ssh.lagoon.amazeeio.cloud]:32222,[34.65.70.251]:32222' (ECDSA) to the list of known hosts.
[pod/lagoon-task-12345-mnopqr/cli] 2021-07-05T08:17:52.222333598Z {"data":{"uploadFilesForTask":{"id":12345,"files":[{"filename":"example-master-2021-07-05T08:16:35+00:00.sql.gz"}]}}}
```

The dump is successful, and then the Lagoon API returns a successful response payload.

So either:
* `drush sql-dump` is truncating the file, and the truncated file is being uploaded.
* Lagoon API is truncating the file during `uploadFilesForTask` and storing the file truncated.

**Comment by smlx** [comment]
Is this issue just https://github.com/uselagoon/lagoon/issues/2746?

**Comment by rocketeerbkw** [comment]
I can verify locally that with some file sizes, the API is truncating the file, so it's probably not a problem with drush. It seems likely to be related to #2746
