### ISSUE TITLE
Lagoon UI: Add pagination to the tasks list

### ISSUE THREAD

**Issue by chandanatk** [uselagoon/lagoon#2758]
For one of the projects of our customers in AU, which have been around for a while (since 2019), the tasks list has been gone up to nearly 400 and this causes a considerable amount of delay to render the page.

Feature request

Can we add pagination to the tasks list screen, and show perhaps only the most recent ones or a fixed count from the recent ones?

Related to [#1382](https://github.com/uselagoon/lagoon/issues/1382)

**Comment by rocketeerbkw** [comment]
Display limits were added in #2771. Pagination is a feature that'd we like to add in the future for the entire schema.
