### ISSUE TITLE
Executing remote shell command over ssh not working as expected

### ISSUE THREAD

**Issue by rackberg** [uselagoon/lagoon#276]
When trying to remotely executing a terminal command over ssh, eg:
    `ssh -p <portnumber> <lagoon-user>@ssh.lagoon.amazeeio.cloud /bin/bash -c "cd /app && pwd"`

The directory change did not happen. The reponse is:
`/app/web`

But when removing the "/bin/bash -c" part, it works. Is that the correct behavior?
     `ssh -p <portnumber> <lagoon-user>@ssh.lagoon.amazeeio.cloud "cd /app && pwd"`

Response:
`/app`

**Comment by twardnw** [comment]
The behavior between providing a command and the interactive shell _is_ slightly different. When a command is provided, it is wrapped in `sh -c`, so the multiple layers of command_string are not going to behave exactly like you expect.

https://github.com/amazeeio/lagoon/blob/master/services/ssh/home/rsh.sh#L136-L140
