### ISSUE TITLE
Drush file sync task fails on Drush version 10

### ISSUE THREAD

**Issue by cdchris12** [uselagoon/lagoon#2761]
# Describe the bug

When a project using Drush version 10 (and probably Drush version 9, but this is unconfirmed) attempts to run a file sync task from the Lagoon UI, this task can fail with an error like the following:

```
> rsync: failed to set times on "/app/docroot/sites/default/files/.": Operation not permitted (1)
> rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1659) [generator=3.1.3]
```

This is caused by an upstream change in how Drush' newer versions handle options passed to that rsync command. Namely, only two options are supported there to be configurable in a site alias. More info on this issue can be found here: https://github.com/drush-ops/drush/issues/3491

## To Reproduce

1. Go to a project still hosted on an Openshift 3.x cluster which uses Drush version 9 or 10
2. Run a files sync task between any two targets

## Expected behavior

The rsync command completes successfully

## Additional context

A valid hot fix for this behavior would be to add drush version detection logic to the Lagoon tasks system. If a project is using a Drush version >= 9.x.x, the the Lagoon tasks system would add the required flags to the `drush` command itself, like so:

```
drush rsync @source:%files @target:%files -- --omit-dir-times --no-perms --no-group --no-owner --chmod ugo=rwX
```

**Comment by timclifford** [comment]
[Lagoon-sync](https://github.com/amazeeio/lagoon-sync) is also a potential tool you could use to sync files as a workaround for now.

**Comment by bomoko** [comment]
closing for now, replaced by #3134
