### ISSUE TITLE
Update Slack notification's channel graphql not working

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon#2773]
# Describe the bug

Calling the `updateNotificationSlack` fails with error.

## To Reproduce

1. Set a GraphQL query like: 
```
mutation modifyslack {
  updateNotificationSlack (input: {
    name: "drupal-example" 
    patch: {
      channel: "new-channel"
      }
    }
  ) {
    id
  }
}
```
2. See error: ```Unknown column 'channel' in 'field list'\nsql: update `notification_email` set `channel` = 'new-channel' where `name` = 'drupal-example' - parameters:{}",```

## Expected behavior

Slack Notification should have the new channel set for notifications

**Comment by dan2k3k4** [comment]
It should be updating the `notification_slack` table and not the `notification_email` table.
