### ISSUE TITLE
implement a project-level router pattern

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#2791]
It would be super handy for some clients that have a managed CDN to be able to set up a project level router pattern. This would ideally live as a project level setting in the API.

**Comment by shreddedbacon** [comment]
Currently we inject the openshift/kubernetes scoped `routerPattern` into the build spec here: https://github.com/uselagoon/lagoon/blob/main/node-packages/commons/src/tasks.ts#L303

What you could do is add a new field to the project type that is `routerPattern`. Then just update the logic in `tasks.ts` to check if a project `routerPattern` has been defined, and inject that instead.

EDIT: The build-deploy controller turns that into the `ROUTER_URL` that kubectl-build-deploy-dind uses here https://github.com/amazeeio/lagoon-kbd/blob/main/controllers/lagoonbuild_controller.go#L355-L370

**Comment by tobybellwood** [comment]
ALso #2573 #2574 and #2666 probably relevant here if we're looking at router patterns

**Comment by smlx** [comment]
~What if we just have `router-logs-*` as the only pattern, and then you can filter by `lagoon.sh/project` label?~

edit: wrong thing, sorry for the noise

**Comment by shreddedbacon** [comment]
> What if we just have `router-logs-*` as the only pattern, and then you can filter by `lagoon.sh/project` label?

I think that is a different issue, this pattern is for customising autogenerated routes router patterns that are used when creating the ingress.
