### ISSUE TITLE
API request logs should include audit information

### ISSUE THREAD

**Issue by cdchris12** [uselagoon/lagoon#2807]
In order to be able to better understand where every Lagoon request comes from and support future auditing efforts, we should add the following data to each request log wherever possible:

- IP the request originated from
- ~Lagoon user which made the request (or a value which can be uniquely mapped to a single user)~ Already completed in #2690

**Comment by Schnitzel** [comment]
there is https://github.com/uselagoon/lagoon/pull/2690 which has been merged and https://github.com/uselagoon/lagoon/pull/2800 which improves on this.
Does this satisfy the requested features of this ticket?

**Comment by cdchris12** [comment]
#2690 Does indeed cover the user identification portion of this requirement. I do not see any inbound IP information being recorded there or in #2800, though.

**Comment by timclifford** [comment]
@cdchris12 I think I can try detect the request ip address inside the express middleware - will take a look

**Comment by timclifford** [comment]
@cdchris12 added ip address to user logs, which will look for http headers from 'x-forwarded-for,
x-forwarded, x-client-ip, fastly-client-ip' and also the 'request.connection'

![image](https://user-images.githubusercontent.com/2339381/129757608-4ce900e9-047d-4d95-9bab-daf010fcc013.png)

**Comment by timclifford** [comment]
https://github.com/uselagoon/lagoon/pull/2800/commits/1ced821270df379afec941f743c8bd8928f2daf8

**Comment by cdchris12** [comment]
@timclifford That looks good for this issue. Feel free to mark your PR as closing this issue :)
