### ISSUE TITLE
Lagoon API reporting environment services that aren't running.

### ISSUE THREAD

**Issue by KorvinSzanto** [uselagoon/lagoon#2809]
# Describe the bug

The graphql API will sometimes report services that aren't running.

## To Reproduce

Not sure how to reliably replicate but I have a deployed environment that shows the issue on my lagoon remote.

## Expected behavior

A query like
```gql
query {
  environmentByName(project: $projectId name: $environment) {
    services {
      id
      name
    }
  }
}
```
should only return services that are actually running.

## Screenshots
Note that the API reports 2 CLI processes with different IDs

![Screenshot from 2021-08-18 13-21-05](https://user-images.githubusercontent.com/1007419/129966763-fa000c1f-0200-4709-a60a-d33814d345fd.png)

Whereas kubernetes only has one cli running.

![Screenshot from 2021-08-18 13-21-35](https://user-images.githubusercontent.com/1007419/129966841-9b433331-a690-41f0-8b3a-d4b21c55401a.png)

## Additional context

The development environment using the same launch configuration does not show the extra CLI service, I can only guess that redeploying the project would make the extra cli go away.

**Comment by rocketeerbkw** [comment]
The `services` is not a realtime list of running services, only a list of services types that have been deployed. The list is only [updated when a deployment finishes](https://github.com/uselagoon/lagoon-one/blob/85d36a24d3bb82fb327a82c822e5cd8b80543537/services/controllerhandler/src/index.ts#L197-L198). It's only purpose (at the moment) is to allow the task system to [show/hide tasks that can/can't run](https://github.com/uselagoon/lagoon/blob/main/services/ui/src/components/AddTask/logic.js#L53-L59) if a specific service is likely to exist.

It's possible that at the time of update there were two cli services running.
