### ISSUE TITLE
Lagoon API doesn't return IDs for added deploys

### ISSUE THREAD

**Issue by KorvinSzanto** [uselagoon/lagoon#2810]
# Describe the bug
The API provides several different methods to add a deploy but they each have their faults.

- `deployEnvironmentLatest`: Works great for starting deploys and is actually nicely versatile when it comes to specifying which environment to deploy. Only issue is it gives no output beyond a string `"success"` so you have no way to track /which/ deployment was created.
- `deployEnvironmentBranch`: See `deployEnvironmentLatest`
- `deployEnvironmentPromote`: See `deployEnvironmentLatest`
- `deployEnvironmentPullrequest`: See `deployEnvironmentLatest` 
- `addDeployment`: This gives output that you can use to determine which deploy was added, but unfortunately doesn't actually deploy anything, it will just leave deploys in pending state forever. An added issue is that it expects more input than it should need like expecting a name and a created date.

## To Reproduce

Attempt to add a deploy, you won't be able to add one that runs and get the ID from it.

1. Try `deployEnvironmentLatest`, observe that input/output doesn't give you a way to determine which deploy was added
2. Try `addDeployment`, observe the deploy not leading to a build instance and remaining in `pending` state.

## Expected behavior
It'd be better to always output the added deployment, even if the deploy name isn't available yet. Just being able to get the deploy ID would make it so that I can track the record when I create it rather than having to guess which deploy maps to which local record using the AMQP deploy updated exchange.

**Comment by rocketeerbkw** [comment]
I think this is a duplicate of #2652?

**Comment by KorvinSzanto** [comment]
Totally forgot I opened an issue for this earlier. Should've searched harder sorry!
