### ISSUE TITLE
Support Kubernetes 1.22

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon#2816]
To fully support Kubernetes 1.22, a number of services across Lagoon will need to be updated to adopt the deprecations in 1.22 (https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22)

Kubernetes API Docs 1.22 (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22)

We should also update all these charts to run on Kubernetes 1.19 minimum for compatibility.

At this stage, we will not attempt the 1.25 deprecations (as they are only available once on 1.22)

- [ ] uselagoon/lagoon (https://github.com/uselagoon/lagoon/pull/2815)
- [ ] uselagoon/lagoon-charts/lagoon-build
- [ ] uselagoon/lagoon-charts/lagoon-core
- [ ] uselagoon/lagoon-charts/lagoon-logs-concentrator
- [ ] uselagoon/lagoon-charts/lagoon-remote
- [ ] amazeeio/charts/dbaas-operator (https://github.com/amazeeio/charts/pull/27)
- [ ] amazeeio/charts/dioscuri (https://github.com/amazeeio/charts/pull/27)
- [ ] amazeeio/aergia-controller (https://github.com/amazeeio/aergia-controller/pull/7)
- [ ] amazeeio/dbaas-operator (https://github.com/amazeeio/dbaas-operator/pull/47)
- [ ] amazeeio/dioscuri (https://github.com/amazeeio/dioscuri/pull/20)
- [ ] amazeeio/lagoon-kbd (https://github.com/amazeeio/lagoon-kbd/pull/76)
- [ ] amazeeio/lagoon-idler (https://github.com/amazeeio/lagoon-idler/pull/14)

Where Lagoon is required to support k8s < 1.19, we should consider either freezing that operator/controller/chart version or creating an explicit fork

```
uselagoon/lagoon
    1.19/1.22
    apiVersion: networking.k8s.io/v1
    kind: Ingress
        change `serviceName` -> `service.name` and `servicePort` -> `service.port.number`
        set `path`,`pathType` and `backend` correctly

uselagoon/lagoon-charts/lagoon-build
    1.16/1.22
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
        change `spec.validation`->`spec.versions[*].schema` and remove `spec.version`

uselagoon/lagoon-charts/lagoon-core
    1.19/1.22
    apiVersion: networking.k8s.io/v1
    kind: Ingress
        change `serviceName` -> `service.name` and `servicePort` -> `service.port.number`

uselagoon/lagoon-charts/lagoon-logs-concentrator
    1.19/1.22
    apiVersion: networking.k8s.io/v1
    kind: Ingress
        change `serviceName` -> `service.name` and `servicePort` -> `service.port.number`

uselagoon/lagoon-charts/lagoon-remote
    1.14/1.22
    apiVersion: scheduling.k8s.io/v1
    kind: PriorityClass
        change apiVersion only, no code change

amazeeio/dbaas-operator
    1.16/1.22
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
        change `spec.validation`->`spec.versions[*].schema` and remove `spec.version`
        change `webhookClientConfig` -> `webhook.clientConfig`
    
    1.16/1.22
    apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
        change apiVersion only, no code change

amazeeio/charts/dioscuri
    1.16/1.22
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
        change `spec.validation`->`spec.versions[*].schema` and remove `spec.version`

amazeeio/charts/dbaas-operator
    1.16/1.22
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
        change `spec.validation`->`spec.versions[*].schema` and remove `spec.version`

amazeeio/aergia-controller
    1.16/1.22
    apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
        change apiVersion only, no code change

    1.19/1.22
    apiVersion: networking.k8s.io/v1
    kind: Ingress
        update `networkv1beta1` and `networkv1beta1.IngressList` in main.go

amazeeio/lagoon-idler
    1.16/1.22
    apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
        change apiVersion only, no code change

    1.19/1.22
    apiVersion: networking.k8s.io/v1
    kind: Ingress
        review `networkv1beta1` and `networkv1beta1.IngressList` in service-kubernetes.go

amazeeio/lagoon-kbd
    1.16/1.22
    apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
        change apiVersion only, no code change

    1.16/1.22
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
        change `spec.validation`->`spec.versions[*].schema` and remove `spec.version`

amazeeio/dioscuri
    1.16/1.22
    apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
        change apiVersion only, no code change

    1.16/1.22
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
        change `spec.validation`->`spec.versions[*].schema` and remove `spec.version`

    1.19/1.22
    apiVersion: networking.k8s.io/v1
    kind: Ingress
        change `serviceName` -> `service.name` and `servicePort` -> `service.port.number`
```

**Comment by serhat-ozkara** [comment]
Is there any progress on this? We can't use lagoon & there are no warnings about incompatibility  with K8S >1.22. At least it should be documented as not compatible and K8S <1.22 is required to install Lagoon. @tobybellwood

**Comment by tobybellwood** [comment]
Hi @serhat-ozkara - we're actively working on this right now, and have made some good progress. As you can see from the linked tickets in this issue, there are a lot of moving parts that we are bringing together.

We have them all testing together sucessfully now, and we're aiming to make Lagoon Kubernetes 1.22 compatible in the next month or so, ready for when 1.22 is generally available on AWS EKS (and in the Regular Channel for GKE).

The PR/branch we're testing on (with heavy use of helm-git) is at https://github.com/uselagoon/lagoon-charts/pull/395

We haven't (to date) elected to place the kubeVersion semver constraint on our charts, but as we start to make 1.22 compatible versions, we will have to.

I have (just now) updated the install docs with the constraint.

Many apologies for the lack of clarity here - we are working on this, and trying to make the upgrade process as smooth as possible.

**Comment by serhat-ozkara** [comment]
Thank you for prompt reply @tobybellwood
