### ISSUE TITLE
CI: service images are cached from previous builds?

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#2823]
something strange is happening on our CI system, I'm not sure if this is an edge case or an actual issue.

The situation is this:
- we merged https://github.com/uselagoon/lagoon/pull/2797 11 days ago
- since then the ci tests all where able to install lagoon-core
- running it locally with a complete fresh build cache, we had an error:
```
❯ rm build/keycloak-db

❯ make build/keycloak-db
DOCKER_SCAN_SUGGEST=false docker build --quiet --build-arg LAGOON_VERSION=development --build-arg IMAGE_REPO=lagoon --build-arg UPSTREAM_REPO=uselagoon --build-arg UPSTREAM_TAG=latest -t lagoon/keycloak-db -f services/keycloak-db/Dockerfile services/keycloak-db
sha256:27fd999bd60473b16c1b3c308b44dd980d1e2cb7c1878fe56c62958a8438738e
touch build/keycloak-db

❯ docker run --rm -it --user 10000 lagoon/keycloak-db
2021/08/30 15:47:45 [ ERROR ] Error while parsing '/etc/mysql/conf.d/my_query-cache.cnf': open /etc/mysql/conf.d/my_query-cache.cnf: permission denied
```
- but running the latest `testlagoon/keycloak-db:main` (which was pushed the last time main was built, therefore including this code), it ran though:
```
❯ docker run --rm -it --user 10000 testlagoon/keycloak-db:main
MySQL data directory not found, creating initial DBs
Installing MariaDB/MySQL system tables in '/var/lib/mysql' ...
````

so this leads me to believe that a CI run is not actually rebuilding the images? I see that we only clear the build cache when we build a tag:
https://github.com/uselagoon/lagoon/blob/54ebf7f0285643573620b70d9c09efab88fad121/Jenkinsfile#L26-L29
which I think is fine, but even as the Dockerfile has a new content it should rebuild the images, leading me to believe that there is maybe just an edge case where the docker host has something strangely cached?

**Comment by tobybellwood** [comment]
I've looked at this a little bit, and still trying to get my head around the best way.

obviously adding `--pull` into the docker build command would always refresh from the upstream, but `docker build --pull` errors with local-only images :cry: 

The other way would be to clear out all images ahead of a build (as we do for tag builds) - but I'm still not entirely clear that this actually removes all images (currently looking at this).

I'l have a bit more of a think.

**Comment by tobybellwood** [comment]
I also looked at containrrr/watchtower but that only worked on running containers.

We can maybe repurpose the script used in docker-host to refresh the non-Jenkins ones.

**Comment by smlx** [comment]
here's a hack, maybe we can put something like this into the Jenkinsfile?
```
bash -c "echo \"$(awk '/^FROM ..UPSTREAM_REPO/ { print $2 }' $(find . -type f -name Dockerfile))\"" | xargs -tn1 -P8 docker pull -q
```

**Comment by tobybellwood** [comment]
of course, we could probably mitigate this by pinning the images - I hear there are some wise words in https://dev.to/uselagoon/automating-updates-from-upstream-source-images-20ee :grinning:

**Comment by tobybellwood** [comment]
I fixed this!
