### ISSUE TITLE
Drush connections to remotes broken

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#284]
It looks like there is an issue with the entry point.

`drush @staging ssh ` gives following error

```
[example]cli-drupal:/app$ drush @staging ssh
sh: /app/web: Permission denied
command terminated with exit code 126
Connection to ssh.lagoon.amazeeio.cloud closed.
An error 126 occurred while running the command `ssh -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 32222 -t example-staging@ssh.lagoon.amazeeio.cloud 'cd /app/web && bash -l'`                                                                                                   [error]
```

whereas connecting directly without changing the webdirectory and executing bash works.

```
ssh -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 32222 -t example-staging@ssh.lagoon.amazeeio.cloud```

I'm not sure if that is related to the issue we were seeing yesterday - https://github.com/amazeeio/lagoon/commit/b122bda814fc7d0a55f2c7d068d9183792e517ee

**Comment by Schnitzel** [comment]
@dasrecht 
what is the `WEBROOT` env variable set too in the cli container? 
it is used by drushrc.php:
https://github.com/amazeeio/lagoon/blob/f8fa6a724b4159c8ff12f8d54fed5a24b95af02b/images/php/cli-drupal/drushrc.php#L10
to automatically find the drupal webroot and is also used during remote connections to automatically cd into the right directory

**Comment by Schnitzel** [comment]
mhh actually, testing this looks like it's some other problem, looking into this

**Comment by Schnitzel** [comment]
looks like the culprit is here:
https://github.com/amazeeio/lagoon/commit/dca2158214b4ca3a2da9f80594405c468a17f1ba

this works when using direct ssh connections (which I tested) but not via the weird drush way it uses (cd and then running bash)
rolled back production and now figuring out how to fix this.
