### ISSUE TITLE
Improve Notifications related graphql queries

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#285]
The current set of queries relating to notifications requires that you know and specify the type. Either refactor or add a query which allows you to discover all notifications on a project, without needing to know the type.

**Comment by Schnitzel** [comment]
this is done now, we have an ENUM for the notificationtype

**Comment by twardnw** [comment]
The problem is that when running a query for the data about a project, you cannot access info about it's notifications, the only thing you can get back is the type.
```
query {
  projectByName(name:"ci-github") {
    name
    notifications{
      __typename
    }
  }
}
```
returns
```
{
  "data": {
    "projectByName": {
      "name": "ci-github",
      "notifications": [
        {
          "__typename": "NotificationRocketChat"
        }
      ]
    }
  }
}
```

**Comment by twardnw** [comment]
There is also no query to look up a notification by any method, it currently requires manually inspecting the DB to get the name
