### ISSUE TITLE
Broken hyperlink to Kibana on Logging page

### ISSUE THREAD

**Issue by christopher-hopper** [uselagoon/lagoon#2853]
# Describe the bug

The Kibana hyperlink markdown on the Logging page is malformed. I can see that someone was trying to escape the brackets but this must've been URL encoded incorrectly.

## To Reproduce

1. Go to https://docs.lagoon.sh/lagoon/logging/logging
2. Click on https://logs.amazeeio.cloud/
4. See error `{"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}`

## Expected behavior

The Amazee.io Logs Kibana service is opened.

## Screenshots

N/A

## Additional context

N/A

**Comment by tobybellwood** [comment]
fixed in #2852
