### ISSUE TITLE
Prevent long running (failed) deployments where practical

### ISSUE THREAD

**Issue by brett-sargeant** [uselagoon/lagoon#2861]
It would be useful if there was a way to be notified of long running deployments once they reach a certain time limit. Or for a central service desk to to be notified (for example GovCMS)

![image](https://user-images.githubusercontent.com/42017163/136726875-45bd6c53-00b8-44cd-8d64-f577b194c48e.png)

**Comment by tobybellwood** [comment]
We're looking at this currently - one of the things we're aiming to implement is a periodic status update (likely with attached logs) - so at least you'd know where it was stuck/broken.  They very rarely run >1h long without a configuration/build error.

**Comment by seanhamlin** [comment]
Further to the above, we witnessed an issue where a `solr` pod got stuck in the `Terminating` phase, and never actually let the new pod come in. The build as a result never progressed passed this phase.

Final container logs of the stuck build:

```
+++ set  +x
+++ kubectl rollout --insecure-skip-tls-verify -n ns-dev status deployment solr --watch

Waiting for deployment "solr" rollout to finish: 0 out of 1 new replicas have been updated...
```

Confirmation of the pod statuses

```
$ kubectl get pods -n ns-dev
NAME                    READY   STATUS        RESTARTS   AGE
cli-7c79869fbb-dns69    1/1     Running       0          12d
lagoon-build-fu1ptf     1/1     Running       0          12d
nginx-d6f89d8dd-6w5bm   2/2     Running       0          12d
solr-59ffd65748-xbq7m   0/1     Terminating   0          13d
```

The net result is a build that has persisted for 12 days. Not ideal.

## Proposed solution

Add a timeout to the `rollout status` command of **20 minutes**. The pods have a `.spec.progressDeadlineSeconds` of 10 minutes, so this seems fair.

```
kubectl -n ns-dev rollout status deployment solr --watch --timeout=20m
```
