### ISSUE TITLE
detect incompatible Solr config during build

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#2887]
Currently an incompatible Solr configuration will only fail at pod startup, effectively causing a failed build, but the logs go into Kibana in the container-logs index. Rather than completing the build and burying that error, Lagoon should detect this incompatible configuration during the build and add the error to the build log directly.

**Comment by tobybellwood** [comment]
The user can also check that their config is incompatible _before_ they push to Lagoon.
