### ISSUE TITLE
validate nginx configuration during build

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#2890]
Currently there is no validation done during Lagoon builds to verify the nginx configuration. This can result in code being pushed which immediately sends the nginx into a crashloop. A simple `nginx -t -f /etc/nginx/nginx.conf` could be run during the build to validate the configuration, as well as show the error in the build log to make it more immediately visible.

**Comment by tobybellwood** [comment]
This can be tested locally before pushing to Lagoon
