### ISSUE TITLE
Deployment of branches not configured for deployment on project

### ISSUE THREAD

**Issue by xantrix** [uselagoon/lagoon#2904]
# Describe the bug
Few customers reported that branches not configured for deployment (not present in the `branches` regex string) are deployed anyway

## Expected behavior

honor the `branches` string regex for deployments

**Comment by Schnitzel** [comment]
after some research it seems this only happens for environments that have been created in the past and then deleted. The new DeployTarget Logic doesn't check that the environment has already been deleted and just creates it again.
I think this happens here: https://github.com/uselagoon/lagoon/blob/e08be8e274e3fd093f7a103b2cd00a46075b763c/node-packages/commons/src/deploy-tasks.ts#L210

**Comment by vincenzodnp** [comment]
@shreddedbacon the same happens with the PR regex.
For example, setting it to `false` allows the creation of environments based on a PR regardless of the PR regex.
ps: the regex envs didn't exist before, so they are brand-new envs
