### ISSUE TITLE
Creating group should add the user to the group

### ISSUE THREAD

**Issue by steveworley** [uselagoon/lagoon#2916]
I think this is more a Lagoon concern than the CLI tool - so thought it would be best to create here. Currently when you create a new group it does not assign the user who created the group to the group and as a result they are not able to add any other users to the group.

They can however add the group to projects that they have access to, which makes the process for creating users and groups slightly awkward as I would need to raise a ticket to add my user to the new group.

For example:
```
$ lagoon add group -N new-group 
Result: success
id: 61b571ee-1ae5-406e-b42d-e311ad11682b

$ lagoon add project-group -p my-project -N new-group 
Result: success
id: 1

$ lagoon add user-group --email developer@test.com -N new-group -R maintainer 
Error: graphql: Unauthorized: You don't have permission to "addUser" on "group".
```
In this example:
- My user is part of org-group
- My project is included in org-group
- My user can add the new group
- My user can add the new group to the project (based on RBAC of org-group)
- My user cannot add users to the new group

The use case for this is:
- Providing scoped maintainer access to targeted projects via a new group

Currently - to provide a developer maintainer access for projects managed by Lagoon I would have to give them maintainer access to the broad group that all projects are part of.

**Comment by seanhamlin** [comment]
+1 to this issue. When you create a group, you should immediately be added as an `OWNER` IMO.

**Comment by tobybellwood** [comment]
The current work on Organizations should provide a framework to define who can create groups/projects within an existing boundary.

Hopefully, we can straighten this out a bit

**Comment by shreddedbacon** [comment]
> The current work on Organizations should provide a framework to define who can create groups/projects within an existing boundary.
> 
> Hopefully, we can straighten this out a bit

Organizations is transitional though, in that Lagoon can still operate without orgs being utilized. I've put a PR up that resolves this for non-org usage.
