### ISSUE TITLE
Reduce debug noise in API pod logs

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#2930]
# Describe the bug

There is a lot of log noise in the `api` container logs of  `lagoon-core`:

```
[2021-11-14 20:19:50] [debug]: Keycloak legacy auth failed: Error decoding token: invalid algorithm
[2021-11-14 20:19:50] [debug]: Keycloak token auth failed: Error decoding token: Grant validation failed. Reason: invalid token (expired)
```

I roughly guess 99% is the above debug noise, and < 1% is actual useful log information

## To Reproduce

1. Tail `api` container logs
2. Notice log noise

## Expected behavior

No debug information emitted

**Comment by shreddedbacon** [comment]
This is becoming a problem when trying to actually debug issues

**Comment by smlx** [comment]
Fixing this will also make it practical to increase Lagoon logs retention.

**Comment by tobybellwood** [comment]
closing on #3164 - will address specific logging later
