### ISSUE TITLE
Command "ard" is not defined

### ISSUE THREAD

**Issue by fjgarlin** [uselagoon/lagoon#2937]
# Describe the bug

When running the `drush archive-dump` default UI task, the task appears as `Succeeded` but the info message indicates otherwise: `Command "ard" is not defined.`

This happens on Drupal 9 projects with drush 10 as the command is no longer available for that version of `drush`.

## To Reproduce

1. Go to any project with drush 10 and any environment, then choose the `Tasks` tab
2. Click on `Generate database and files backup (Drush 8 only) [drush archive-dump]`
3. Wait and see the task as succeeded
4. See error message and no link to the archive dump

## Expected behavior

As it is a default command from the UI, it should either work as expected or not be there if the project has `drush 10`.

**Comment by dan2k3k4** [comment]
It seems that there is no archive-dump for Drush 9+
https://github.com/drush-ops/drush/issues/1779

But [this comment](https://github.com/drush-ops/drush/issues/1779#issuecomment-521991645) sounds interesting, maybe it can be ported to Lagoon instead of waiting for Drush to have this feature added back?

**Comment by tobybellwood** [comment]
Looks like ard isn't coming back anytime soon - we're rewriting tasks to support these situations

**Comment by tobybellwood** [comment]
and with the benefit of hindsight, maybe it is coming back sometime soon - https://github.com/drush-ops/drush/pull/5148

`ard` and `arr` are in Drush [11.1.1](https://github.com/drush-ops/drush/releases/tag/11.1.1) - h/t to @AlexSkrypnyk for the pointer
