### ISSUE TITLE
Allow optional configurable limits on RAM for pods

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#2957]
In a recent event, we saw the PHP max memory limit raised to 800MB. Due to application related issues, we were still seeing PHP OOMs even with this extremely high number. As FPM has 50 threads (by default), this is quite a lot of RAM for just 1 pod. We observed pods regularly trying to use > 20 GB RAM.

This had flow on effects to impact nodes in the cluster. Nodes becoming not-ready. And a lot of pod flapping.

## Ideal solution

There is someway to enforce a maximum RAM allocation per pod, that is configurable on a per cluster level. This would apply to only projects deployed by Lagoon.

For example, one could optionally set a maximum RAM allocation of 8GB per pod. This would have really helped our situation described above.

**Comment by tobybellwood** [comment]
close in favour of https://github.com/uselagoon/lagoon/issues/3122
