### ISSUE TITLE
allow users to export reports from OpenSearch

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#2965]
OpenSearch has the ability for users to exports their reports in various formats, but the roles which are created are missing the necessary permissions. It would be fantastic if Lagoon users could run these exports :)

**Comment by smlx** [comment]
Closely related to #2844

**Comment by twardnw** [comment]
I spent some time doing a one-off for a client today, and found that in OpenDistro 1.13.2, you must add the `indices:monitor/settings/get` permission at the Index Permissions level. Adding this at the Cluster Permissions level does _not_ allow this permission on the indices a role has access to

**Comment by twardnw** [comment]
We will also need the Cluster level permission `cluster:admin/opendistro/reports/menu/download` on each role
