### ISSUE TITLE
Invalid site aliases when environments/branches contain slashes

### ISSUE THREAD

**Issue by elistone** [uselagoon/lagoon#2978]
# Describe the bug

We tend to create environments based off branches that might contain forward slashes `/`, however doing this seems to break aliases. 
For example if you have an environment called `example/test` and you try to copy it's database to another environment you would get the following error:

> Error: no alias record could be found for source @example/test

But example/test is not a valid alias.

## To Reproduce

1. Create two environments based upon Drupal from branches one with & one with out a forward slash e.g. `test` & `example/test`
1. Configure drush aliases 
1. Using lagoon UI try and sync database or files from `example/test` to `test`
1. See error

## Expected behavior

Database / files should sync successfully.

## Additional context

I think this could be solved by replacing the slashes with something else or removing them, but it might be helpful to have this details of what the would be on the UI.

**Comment by rocketeerbkw** [comment]
It should [already be replacing `/` with `-`](https://github.com/uselagoon/lagoon/blob/main/services/drush-alias/web/aliases.drushrc.php.stub#L308), you can run `drush @sa` to see how lagoon set the alias.

Please re-open if this is not working though!

**Comment by elistone** [comment]
Hi thanks for the update, maybe it is just the error message is incorrect then?
I have not had chance to fully confirm this yet but if you do a sync via the UI you see the following error message:

> Logs on pod lagoon-task
> 
> In SqlSyncCommands.php line 77:
>                                                                             
>   Error: no alias record could be found for source @example/test

Which implied to me that the alias it was looking for was `@example/test`

**Comment by rocketeerbkw** [comment]
@elistone ah, I didn't understand that it was the UI specifically you were having issues with. The slash is only replaced when the alias is generated, but lagoon only "knows" the original environment name. This is also an issue with `.` in the environment name, so you can follow #2911 for updates.
