### ISSUE TITLE
Add ability to define specific IngressClass in Lagoon ingresses

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon#2998]
With changes in https://kubernetes.github.io/ingress-nginx/#what-is-an-ingressclass-and-why-is-it-important-for-users-of-ingress-nginx-controller-now we should consider how best to support multiple ingress-nginx controllers inside a Lagoon cluster

In order to upgrade a Lagoon cluster to Kubernetes 1.22, ingress-nginx 1.x will be needed, which forces this change. The fix identified in https://github.com/amazeeio/aergia-controller/issues/8#issuecomment-908825821 only works for single ingress-nginx clusters

To fully support the possibility of multiple controllers:

- [ ] Lagoon service ingresses should have a IngressClass defined
- [ ] An ingressClassName field will need to be added to the ingress spec for all templates
- [ ] A helper added to each service to support a variable
- [ ] Addition of a new lagoon label to a route to provide the value for the variable
- [ ] The ability to set this variable via the API (as per API routes in PR #2940)
- [ ] Document where/when this is to be used
- [ ] Update Lagoon documentation to configure ingress-nginx 1.x correctly

**Comment by Schnitzel** [comment]
nice found! yea that would make sense as we already start to  have clusters with multiple ingress controllers.
The default ingressClassName of the ingress-nginx controller is `nginx`: https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L106

So I think we should use `nginx` as the default?

Also I think it would be good to define the variable in the build controller for the whole cluster, this way we don't push the responsibility of choosing the correct ingressClassName to the developer (which is responsible for the .lagoon.yml) and instead to the operations people (which managed the controller).

one question:
> Addition of a new lagoon label to a route to provide the value for the variable
what do you mean with "lagoon label" ?

**Comment by twardnw** [comment]
It would also be very handy to have different class names for autogenerated vs. custom domains. This would mean the build controller needs to understand if multiple ingress controllers are present, and only assign different class names when there are multiple controllers, it does not appear from the docs that a single controller can watch for multiple class names

**Comment by shreddedbacon** [comment]
This has been added to the build-deploy-tool https://github.com/uselagoon/build-deploy-tool/pull/71 but there is no support for having autogenerated on a different ingressclass without some minor hacks. Is this something we need to support too?

**Comment by tobybellwood** [comment]
no!
