### ISSUE TITLE
Deployment Logfiles are overwritten instead of recreated under a new name

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#305]
Deployment logfiles of of the same _buildname - projectname and branchname_ combination end up in the same logfile. The expectation would be that older deployment logs can still be acessed after another deployment to the same environment.

Code: https://github.com/amazeeio/lagoon/blob/master/services/openshiftbuilddeploymonitor/src/index.js#L208

We would need to adapt the hash function to include the gith-sha to generate unique logs per commit.

**Comment by twardnw** [comment]
rather than trying to pull a single sha out of the deploy message, adding a timestamp to the generated log name should suffice.
