### ISSUE TITLE
Realtime Build Logs

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#307]

**Comment by rthideaway** [comment]
That would be amazingly helpful. For us not having the realtime logs is quite a big problem. From time to time the deployment takes unexpectedly long and we have no info what's going on in the background. We are hopeless without any chance to react. Usually the deployment fails in the end, but it it's too late, too much time was wasted, and most of the time with no helpful info in the end how to prevent this again.

**Comment by ChandeepKhosa** [comment]
Super excited to see this!

**Comment by luigimannoni** [comment]
Also +1 from our side. 
Wish I had a streaming log today, very looking forward into that for time-critical deployments.

**Comment by bryangruneberg** [comment]
+1 from me closes #2537

**Comment by tobybellwood** [comment]
This is 75% complete - closing here.

**Comment by Leksat** [comment]
@tobybellwood where to find the last 25%? 😅
