### ISSUE TITLE
Not able to deploy using Azure git

### ISSUE THREAD

**Issue by vincenzodnp** [uselagoon/lagoon#3072]
# Describe the bug

Azure git doesn't support SHA2 algorithm for Open SSH 8.8 as mentioned by several users here: https://developercommunity.visualstudio.com/t/Missing-Support-of-SHA-2-algorithm-for-O/1562711

Azure reported there are no plans to support SHA2 despite in this blog it seems to be supported https://devblogs.microsoft.com/devops/supporting-sha-2-algorithm-in-ssh-on-azure-devops/

One of the suggested things is to add this config in the ~/.ssh/config file
`Host ssh.dev.azure.com
HostkeyAlgorithms +ssh-rsa
PubkeyAcceptedAlgorithms +ssh-rsa`

The same result I was able to get by using, `GIT_SSH_COMMAND='ssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa'` before pull from git

## To Reproduce

1. Set a project with azure git
2. Deploy
3. See error
`Unable to negotiate with 40.74.28.12 port 22: no matching host key type found. Their offer: ssh-rsa
fatal: Could not read from remote repository.
`

**Comment by smlx** [comment]
This issue is also reported more recently (October 2021) here: https://developercommunity.visualstudio.com/t/Git-SSH-access-offers-weak-algorithms-r/1547526

And the state of the Azure SSH service is still the same today:
```
$ ssh -V
OpenSSH_8.8p1 Debian-1, OpenSSL 1.1.1m  14 Dec 2021
$ ssh -vvv ssh.dev.azure.com 2>&1 | grep -A16 'KEXINIT proposal'
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256
debug2: host key algorithms: ssh-rsa
debug2: ciphers ctos: aes256-cbc,aes192-cbc,aes128-cbc,aes128-ctr,aes256-ctr
debug2: ciphers stoc: aes256-cbc,aes192-cbc,aes128-cbc,aes128-ctr,aes256-ctr
debug2: MACs ctos: hmac-sha2-256,hmac-sha2-512
debug2: MACs stoc: hmac-sha2-256,hmac-sha2-512
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: diffie-hellman-group-exchange-sha256
debug1: kex: host key algorithm: (no match)
Unable to negotiate with 20.37.194.13 port 22: no matching host key type found. Their offer: ssh-rsa
```

Technically it might be possible to re-enable SHA1 for the host-key algorithm but it is known to be insecure and we also have requirements from customers to ensure SHA1 is disabled everywhere in Lagoon for security reasons.

So therefore I don't know if there's anything we can do in Lagoon to fix this. On the Azure side they need to either add a non-RSA host key, or enable an RSA SHA2 host key algorithm.

**Comment by rocketeerbkw** [comment]
The solution some customers have come up with is to run an ssh-proxy, there is a write up at https://www.cando-image.com/de/setting-azure-git-ssh-proxy
