### ISSUE TITLE
Different backup/prune schedule for development environments

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#3073]
Currently all production and development environments share the same backup and prune schedule.

It may be good to have a different schedule available for development environments

**Comment by smlx** [comment]
This is causing heavy load on clusters with many development environments combined with a short custom interval between backups.

**Comment by tobybellwood** [comment]
ah, so digging in, there is a feature shortfall here. The remote-controller allows for the setting of a cluster-wide [default schedule/retention,](https://github.com/uselagoon/lagoon/blob/main/images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh#L197-L219) and the build-deploy scripts allow this to be overridden for [production only](https://github.com/uselagoon/lagoon/blob/main/images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh#L1143-L1147) on a per-project basis.

So we will need to add functionality in two places:
* in the remote-controller to allow for the addition of additional production and development-specific [overrides](https://github.com/uselagoon/remote-controller/blob/main/controllers/v1beta1/lagoonbuild_controller.go#L67-L71). 
* in the build-deploy script to check for the existence of any of these variables before determining the backup schedule for any given environment. Maybe we take the opportunity to factor out the backup schedule into a separate script, as we did for route processing.

Is the order of precedence:
Lagoon-defined prod specific > Cluster-defined prod/dev specific > cluster default?

**Comment by Schnitzel** [comment]
we should probably meet about this, as k8up v2 has a couple of improvements (like a `@daily` schedule) which automatically will spread out the backups for you.

We have not upgraded yet to v2 because of timing issues, but I think a lot of the issues we are describing here could be solved with v2.

**Comment by shreddedbacon** [comment]
I think k8up will solve part of the problem.

**Comment by shreddedbacon** [comment]
I think k8up will solve part of the problem, but not all of it.

If a customer has changed the default backup schedule at the cluster level to be, say, every 6 hours. And there are many projects that have more than 10 environments configured, you have the potential for a large number of unnecessary backup pods for environments that probably don't need backups every 6 hours, with or without k8up configured correctly.
