### ISSUE TITLE
Investigate new method for populating api with test data for UI development

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon#3101]
We currently use `api-data-watcher-pusher` to add a bunch of fake data to the api so that the UI will not be completely empty. Since we want to deprecate that service and there's no need to inject data when not developing the UI we should find another way to accomplish this.

Initial suggestions:

- Use the lagoon cli export/import functionality
- Write a custom script that lives in the `api` (e.g `yarn install-ui-data`)
- A db container image that's prefilled with test data
- Other?

The end result would be moving all the "High Cotton" related info from `api-data-watcher-pusher` to something else.

**Comment by tobybellwood** [comment]
IIRC the CLI has a bulk import function we could use, but I don't think it can handle adding lagoon-remotes at the moment

**Comment by rocketeerbkw** [comment]
> IIRC the CLI has a bulk import function we could use, but I don't think it can handle adding lagoon-remotes at the moment

Same for users/groups I think. We can add new import/export features since it's just making api calls under the hood.
