### ISSUE TITLE
Route generation takes a LONG time for environments with many routes

### ISSUE THREAD

**Issue by cdchris12** [uselagoon/lagoon#3118]
# Describe the bug

After updating an Openshift cluster to using the `v2.5.0` version `kubectl-build-deploy-dind` image from a much older version of this image, it was noticed that a specific project with multiple hundreds of routes was now taking multiple hours to build, where it took ~20 minutes previously.  The overwhelming majority of this time is spent with the build pod sitting at ~100% CPU usage (1 core) churning through executing the `exec-routes-generation.sh` script. 

## To Reproduce

1. Create an example project with multiple hundred routes in its `.lagoon.yml`
2. Deploy the project
3. See build take multiple hours
4. ????
5. PROFIT

## Expected behavior

Deployments should not take multiple hours, regardless of the number of domains present in a project/environment.

## Screenshots

N/A

## Additional context

Given the massive amounts of domains in this project, it seems to me that what we're seeing here is simply handling/processing a substantial amount of data numerous times. I would assume it would be better to store this data somehow once accessed, so that we don't need to read the `.lagoon.yml` file, pipe that to `shyaml`, then filter for the specific bit we need; multiple times. Maybe this routes generation activity is better suited to a higher programming language like Python?

**Comment by seanhamlin** [comment]
This is fixed by https://github.com/uselagoon/lagoon/pull/3133 right?

**Comment by cdchris12** [comment]
This would've been resolved by #3133, but that functionality was reverted as part of the work done in #3181 to resolve issues we saw with badly formatted docker-compose.yml files. For now, this issue remains unresolved as of Lagoon release 2.8.4

**Comment by shreddedbacon** [comment]
This has been fixed now that routes are handled in the `build-deploy-tool`
