### ISSUE TITLE
Some Unicode Characters (e.g. en-dash) in Filenames in Backups (tar.gz) are not detected on Windows Zip software (e.g. 7-zip)

### ISSUE THREAD

**Issue by silverham** [uselagoon/lagoon#3132]
# Describe the bug

Some Unicode Characters in Filenames in Backups (tar.gz) are not detected on Windows Zip software (e.g. 7-zip)

We use with software over at GovCMS to create backups (.tar.gz) of uploaded files which is a shared path folder by all docker containers.

However when using a windows Zip software which the 7zip, some unicode characters get removed. e.g. "en dash'.

Example correct filename: 
files\2022-02\Air quality – Philip Wolfhagen.png

Filename when views or extracted in 7-zip or PeaZip.
files\2022-02\Air quality Philip Wolfhagen.png

The filename in the archive can extracted correctly when using:
- Windows - bandizip
- Windows - ConEmu's tar program.
- Linux tar program

Note: i can manually rename the file to the correct filename without issue.

Manually making similar archive using docker (linux) and centos 7 did not re-produce the issue.

## To Reproduce

1. Download backup file with the filename "Air quality Philip Wolfhagen.png".
(in GovCMS this is https://dashboard.govcms.gov.au/projects/myproject/myproject-master/backups)
2. extract or view in 7-zip (windows) - see filename is missing en-dash.
@see https://docs.lagoon.sh/using-lagoon-advanced/backups/

## Expected behavior

Correct filename should be extracted.

## Additional context

Suggested fix, is to use 'tar --format=posix -cf' or similar for this software's.
@see https://superuser.com/a/487289/658383

Debug outputs in cmder (con emu):
[note that 'Characteristics ' seems different')

Zip archive info of backup tar from lagoon.
<pre>
===========================
"C:\Program Files\7-Zip\7z.exe" l ~/Downloads/backup-myproject-master-nginx-2022-04-27T12_53_51Z.tar | head -n 20

7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

Scanning the drive for archives:
1 file, 4647312896 bytes (4433 MiB)

Listing archive: C:\Users\myusername\Downloads\backup-myproject-master-nginx-2022-04-27T12_53_51Z.tar

--
Path = C:\Users\myusername\Downloads\backup-myproject-master-nginx-2022-04-27T12_53_51Z.tar
Type = tar
Physical Size = 4647312896
Headers Size = 5644800
Code Page = UTF-8
Characteristics = ASCII

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2021-11-29 12:03:26 .....          487          512  data\nginx\.htaccess
[...]
===========================
</pre>

Zip archive info of backup from a linux Docker OR Cent OS 7:
<pre>
===========================
 "C:\Program Files\7-Zip\7z.exe" l ~/Downloads/temp.tar | head -n 20

7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

Scanning the drive for archives:
1 file, 5166305280 bytes (4927 MiB)

Listing archive: C:\Users\myusername\Downloads\temp.tar

--
Path = C:\Users\myusername\Downloads\temp.tar
Type = tar
Physical Size = 5166305280
Headers Size = 2144256
Code Page = UTF-8
Characteristics = UTF8 MaxUnicode=8211

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2022-05-06 14:02:24 D....            0            0  .
2021-11-29 12:03:26 .....          487          512  .\.htaccess
[...]
=======================
</pre>

**Comment by rocketeerbkw** [comment]
We use an [upstream tool](https://github.com/k8up-io/k8up) to do backups. After looking into this issue on a call for ~10 mins we weren't able to determine if the problem is in there or in an upstream tool that our upstream tool uses....

Since it's only broken on 7-zip on windows and you really shouldn't use en-dash in web based file names, we think this doesn't effect very many users.

For those reasons I'm afraid we won't be spending any additional time fixing this issue. Thank you for reporting it.
