### ISSUE TITLE
Lagoon UI file sync task fails on environments using Drush version 8

### ISSUE THREAD

**Issue by cdchris12** [uselagoon/lagoon#3134]
# Describe the bug

The hard-coded Lagoon Task definition for file syncs (https://github.com/uselagoon/lagoon/blob/main/services/api/src/resources/task/resolvers.ts#L709) has the correct syntax to be used with Drush versions 9 and 10, but is not syntactically correct for Drush version 8 due to the lone `--` after `@self:%files` which is needed by Drush versions 9 and 10.

The task fails with an error similar to the following:

```
You will delete files in /app/web/sites/default/files and replace with data from <project>@ssh.lagoon.amazeeio.cloud:/app/web/sites/default/files/
Do you really want to continue? (y/n): y
Unexpected remote arg: <project>@ssh.lagoon.amazeeio.cloud:/app/web/sites/default/files/
rsync error: syntax or usage error (code 1) at main.c(1354) [sender=3.1.3]
Could not rsync from                                                     [error]
<project>@ssh.lagoon.amazeeio.cloud:/app/web/sites/default/files/
to /app/web/sites/default/files
```

## To Reproduce

1. Setup a Lagoon env with Drupal and Drush version 8
2. Attempt a file sync task from the UI
3. See error

## Expected behavior

The files sync should complete successfully.

## Additional context

It seems easy enough to add logic here which can detect the Drush version and add/remove that errant `--` accordingly for older versions (<=8.x) of Drush. We already have logic such as this for other commands: https://github.com/uselagoon/lagoon/blob/main/services/api/src/resources/task/resolvers.ts#L456

**Comment by tobybellwood** [comment]
We're not planning on making any changes to the built-in tasks if we can help it - plus Drush 8 is suuuuper old now
