### ISSUE TITLE
sync:opendistro-security runs with regular 60s pauses

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#3150]
# Describe the bug

When syncing Lagoon roles to Opensearch using the `sync:opendistro-security` task the sync often seems to pause at certain points for exactly 60s. When syncing a large Lagoon installation this makes the the task take a very long time.

## To Reproduce

1. Run `yarn sync:opendistro-security` in the `api` pod of your large Lagoon installation.
2. Watch the sync process pause regularly for exactly 60s at a time.

## Expected behavior

The sync process should run continuously and not pause.

## Screenshots

n/a

## Additional context

n/a

**Comment by smlx** [comment]
This may be related to #2844

**Comment by tobybellwood** [comment]
THis script is planned for deprecation
