### ISSUE TITLE
Provide ability to delete selected custom tasks

### ISSUE THREAD

**Issue by ivangrynenko** [uselagoon/lagoon#3162]
Custom tasks in Lagoon environments are tailored for Drupal and rely on Drush. However, when hosting a non-Drupal application, there are several issues with those:
1. They don't apply to a custom web application
2. They clutter the interface.

Because [custom tasks can be added](https://docs.lagoon.sh/using-lagoon-advanced/custom-tasks) to Lagoon projects, we can define custom tasks to facilitate non-Drupal CMS, such as WordPress (using WP-CLI), however, the Drupal tasks are still present in the Lagoon Tasks interface. In fact, custom tasks are added to the bottom of the list and a user must scroll down to see them.

It would be good to have one of those (or a combination of) features available:
1. Ability to delete custom tasks by project ID and task ID/name
2. Ability to reorder tasks by specifying their weight, for example:
```
mutation runClearWpCache {
 addAdvancedTaskDefinition(input:{
    name: "Clear WordPress Cache",
    project:{project_id},
    type: COMMAND,
    **weight: "-100",**
    permission: DEVELOPER,
    description: "Clear WordPress Cache",
    service: "cli",
    command: "wp cache flush all --allow-root --path=/app/web"})
    {
        __typename
    }
}
```

**Comment by bomoko** [comment]
Thanks for the issue @ivangrynenko 

So we've been speaking about this internally for a while - and one of the features we have discussed, is using metadata and facts to determine whether a task should be shown for a project or not.
This would allow you to maintain group level tasks, but only have them show up on certain projects.

I really like the idea of a weight. That should be super simple to implement.
As it stands, the ordering of the tasks is a bit of an issue with the way some of the tasks are hardcoded in the ui - @timclifford, any thoughts on how we should proceed here?

Deleting advanced task definitions is actually already possible using the mutation 
```
deleteTask {
  deleteAdvancedTaskDefinition(advancedTaskDefinition:ID_HERE)
}
```

**Comment by tobybellwood** [comment]
core tasks will be deprecated in favour of custom tasks
