### ISSUE TITLE
Ability to have a different backup schedule for standby production environments

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#3178]
We are seeing excess database load that is at least partially driven by the fact that both production environments are backing up the database every 6 hours.

There is no business need for this particular customer to backup the standby database, only the active database. 

It would be handy to have the ability to define a backup schedule for active, and another for standby.

**Comment by steveworley** [comment]
I think to help with implementation, rather than opening up backup patterns to Lagoon yaml - the standby environment could be treated as a non-prod and inherit the non-prod backup schedule.

**Comment by tobybellwood** [comment]
technically, this isn't possible, as backup schedules are only generated on deploy. We could look at wiring more A/S tasks into dioscuiri.
