### ISSUE TITLE
Support unset/empty environment variables via graphql

### ISSUE THREAD

**Issue by tnelson-doghouse** [uselagoon/lagoon#3208]
**Is your feature request related to a problem? Please describe.**

We sometimes (currently for testing purposes) want to override an environment variable from the codebase with an empty OR unset value (eg. to temporarily turn off basic auth).  

**Describe the solution you'd like**

I'd like the Lagoon API to support unsetting environment variables (with the assumption that this would also become available via the lagoon-cli, where `--value ''` would set the empty value, and maybe `--unset` would unset the value, but that's a separate issue).  

In discussions with Ben Jackson surrounding this, it seems like, if we also made the unsetting of environment variables also delete the configmap entry, that would solve problems for some other people.  

**Describe alternatives you've considered**
The current workaround is to unset these in the codebase.

**Comment by shreddedbacon** [comment]
There is already a bug uselagoon/build-deploy-tool#136 in which deleting a variable from the Lagoon API, it is not cleaned up from the configmap, this is part of the issue. Normally this has been done the opposite way, people set these variables in the API and then remove them from the environment when required. You're doing it the opposite way, which to me 

The [docs](https://docs.lagoon.sh/using-lagoon-advanced/environment-variables/#environment-variables) show the hierarchy of variables, so the empty value in the API should be made available in the pod if you're using the `.lagoon.x`, `.env`, or `.env.x` files see the [entrypoint script](https://github.com/uselagoon/lagoon-images/blob/main/images/commons/lagoon/entrypoints/50-dotenv.sh), and it should overwrite what is in the local files. Currently the API seems to allow for empty variables to be set (but the CLI does not allow this, we can fix the CLI to allow empty values then).
```
        "id": 30,
        "envVariables": [
          {
            "name": "EMPTY_VARIABLE",
            "value": ""
          }
        ]
```
One concern would be that setting the value to empty may not solve this for all cases, and if we were to implement some sort of `unset` feature, this would need to then dig into the entrypoint script to be able to unset values that are defined in there. So only users of newer images would be able to leverage this.

**Comment by shreddedbacon** [comment]
@tnelson-doghouse I released lagoon-cli v0.13.0 which allows for empty variables to be set in the API now.

Will leave this open though to discuss the `unset` functionality though

**Comment by tobybellwood** [comment]
A combintaion of allowing '' and the CLI/UI updates should resolve this more easily

**Comment by tnelson-doghouse** [comment]
Great, thanks!  

Just so I have a clear picture of what's going on:
- I see that I can set a variable to '' in the CLI, and it shows it as '-', which I assume means that it's empty and the CLI is just representing it that way.  
- I'm not seeing a way of overriding it to be just unset

I'm currently happy either way, but just wanted to be sure where we're at.

**Comment by shreddedbacon** [comment]
Yes `-` showing in the output of the cli is just a symptom of the way the table output works, it shouldn't actually show `-` so we should fix that. (https://github.com/uselagoon/lagoon-cli/pull/299)

We're working on fixing the bug in Lagoon that deletes removed variables from the configmap, but there is still some work on that front.

As for `unset`, I don't really see any value in this once the delete from configmap is resolved. Unless you have better information about what you think it would solve?

**Comment by tnelson-doghouse** [comment]
Only to override variables from the codebase to not exist in Lagoon, but not a high priority at all.  Setting them as blank should be sufficient in most cases :) .

**Comment by shreddedbacon** [comment]
Right, that was in case you had something in a `.env` file that you specifically wanted undefined, iirc?

**Comment by tnelson-doghouse** [comment]
Yes, but it's not something I've seen a need for since I submitted the original ticket, so nice to have, but not at all a high priority.
