### ISSUE TITLE
addProject should validate the Kubernetes cluster ID is valid

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#3215]
# Describe the bug

At present it is possible to add a project to a Lagoon core, with a cluster ID that does not exist.

## To Reproduce

```
lagoon add project \
  --branches '^(main|dev)$' \
  --gitUrl 'git@github.com:seanhamlin/drupal9-base.git' \
  --openshift 990099 \
  --productionEnvironment 'main' \
  --project 'banana' \
  --developmentEnvironmentsLimit 1
```

The cluster ID `990099` is made up.

## Expected behavior

Error returned from the API indicating that the request was not successful

**Comment by CGoodwin90** [comment]
Hey Sean - just tested this locally and got back the expected response from the API, are you still able to reproduce the issue?

![image](https://user-images.githubusercontent.com/40746380/185499660-38720bee-78d1-4d67-902a-9c791c51354d.png)

**Comment by seanhamlin** [comment]
Just tried again, and I am not able to reproduce. Thanks @CGoodwin90 !
