### ISSUE TITLE
Remove defunct billing groups from Keycloak database

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#3216]
# Describe the bug

In https://github.com/uselagoon/lagoon/pull/2837 the billing code was removed from the Lagoon API, but this failed to clean up the data left behind in the Keycloak database. This left-behind data in turn caused issues for the Lagoon 2.9.0 upgrade (which upgraded Keycloak).

## To Reproduce

* Create a billing group of `Banana`
* Create a user group of `banana`
* Upgrade Lagoon to 2.9.0

## Expected behavior

No billing groups in the Keycloak database (only user groups)

**Comment by shreddedbacon** [comment]
There is a script to clean these up https://github.com/uselagoon/lagoon/blob/main/services/api/src/migrations/3-remove-billing-data/billing-groups.ts
