### ISSUE TITLE
Use service account for Keycloak admin API access

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon#3217]
Lagoon currently uses Keycloak's built-in `admin-cli` client and a username/password to authenticate against the Keycloak Admin API. One problem with this is that the token obtained has to be repeatedly refreshed since it is intended for the admin CLI tool and has a very short expiration.

Instead, could Lagoon use an administrative [service-account client](https://www.keycloak.org/docs/16.1/server_development/#authenticate-with-a-service-account)? This would avoid the repeated refreshing of admin tokens.

There would need to be some bootstrap logic to create this service-account client on initial install of Lagoon. The built-in `admin-cli` username/password can still be used for that. I guess this would go into the Keycloak [startup script](https://github.com/uselagoon/lagoon/blob/main/services/keycloak/startup-scripts/00-configure-lagoon.sh).

This might help with #2930.

**Comment by rocketeerbkw** [comment]
I don't think this will work to prevent expirations altogether. I doesn't matter if you provide a user/pass or if you provide a client-id/client-secret, at the end of the day keycloak is returning a JWT token that will have an expiration date.

If we switch to a dedicated admin service account, it would allow us to add 2fa to the admin account though. And we could possibly bump the expiration time? So could still be worth it.
