### ISSUE TITLE
Support spot instances for Lagoon workloads

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon#3219]
To better allow optimal cluster configurations, Lagoon should be configurable to place certain defined workloads onto spot instances.

It is proposed to do this via:
* a label on the deployments
```
 "lagoon.sh/spot" = "true"
 ```
 * a taint on the nodes (and a matching toleration to be added to deployments)
 ```
       {
        key    = "lagoon.sh/spot"
        value  = "true"
        effect = "NO_SCHEDULE"
      }
```
* setting a min replica count=2 for any production service using spot
* a set of Lagoon feature flags, configurable in environment variables at the environment, project, and cluster level
```
LAGOON_FEATURE_FLAG_DEFAULT_SPOT_PRODUCTION={comma separated service-types list}
LAGOON_FEATURE_FLAG_DEFAULT_SPOT_DEVELOPMENT={comma separated service-types list}
LAGOON_FEATURE_FLAG_SPOT_PRODUCTION=false
```

The variables would take a list of the lagoon.types that spot is to be enabled for - and be able to be set at the controller/cluster level as a DEFAULT (which could be overridden at the proj/env level).

## to do:
* Identify which services are spot-suitable - initially anything that is stateless, or uses the `bulk` storageclass (node, PHP, cli, nginx) 
* Identify which services **are not** spot-suitable - database-singles, solr, elasticsearch, redis
* decide whether to handle cronjobs and backups via these variables or separately
* decide on variable naming
* write docs on configuring clusters and setting variables

The majority of this work will happen in uselagoon/build-deploy-tool - but keeping ticket here for reference

**Comment by shreddedbacon** [comment]
For backups and spot, I think this would have to be handled in k8up, as it starts the pods. It isn't clear from the docs of k8up if this is possible though.

EDIT: Looking at the code of k8up, when it creates the job that handles the backup, there is no where that it appears that tolerations can be injected. So would need to feature request to k8up for this support.
