### ISSUE TITLE
disable opensearch integration if no opensearch defined

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#3262]
When running locally or in tests with no opensearch configured, the API still attempts to reach out to an opensearch (that doesn't exist) to create roles and index patterns etc.

It would be nice to be able to disable this integration if there is no opensearch configured.

**Comment by smlx** [comment]
Is there any update on this issue?

**Comment by shreddedbacon** [comment]
https://github.com/uselagoon/lagoon/blob/f519a90cb4b2ec28ec1f6c7283ba4a24951e7e60/services/api/src/resources/group/opendistroSecurity.ts#L16 there is this envvar that can disable the integration
