### ISSUE TITLE
Broken anchor links to 'Set up SSL certificates' in docs

### ISSUE THREAD

**Issue by christopher-hopper** [uselagoon/lagoon#3281]
# Describe the bug

There are a few broken links in the docs for help on how to "Set up SSL certificates"

## To Reproduce

Steps to reproduce the behaviour:

1. Search Google for "Lagoon SSL"
2. Click on the FAQ link at the top of the results - https://github.com/uselagoon/lagoon/blob/main/docs/resources/faq.md
4. Find the section for "I'm getting an invalid SSL certificate error"
5. Click on the link to "our documentation about SSL." 
6. Observe that the page anchor isn't found and we end up at the top of a very long page.

## Expected behavior

We are taken to the SSL documentation anchor within the markdown page.

The anchor behaves the same when clicked from the [markdown file](https://github.com/uselagoon/lagoon/blob/main/docs/resources/faq.md) as it does on [docs.lagoon.sh](https://docs.lagoon.sh/resources/faq/).

## Screenshots

> If applicable, add screenshots to help explain your problem.

Google "Lagoon SSL"
<img width="1147" alt="Screen Shot 2022-09-06 google lagoon ssl" src="https://user-images.githubusercontent.com/452515/188532492-da4c2e46-2da2-42c9-923b-eba734d1151d.png">

Lagoon FAQ SSL - Fig.01
<img width="1147" alt="Screen Shot 2022-09-06 lagoon faq fig 01" src="https://user-images.githubusercontent.com/452515/188532542-30140780-41aa-4e7f-9277-d05781e60051.png">

Lagoon FAQ SSL - Fig.02
<img width="1147" alt="Screen Shot 2022-09-06 lagoon faq fig 02" src="https://user-images.githubusercontent.com/452515/188532551-a713fdb2-2e94-4f30-8ac3-7faf9312547d.png">

## Additional context

> Add any other context about the problem here.

This anchor is used in other places within the markdown pages. For instance it is seen at the top of this page also

https://github.com/uselagoon/lagoon/blob/main/docs/using-lagoon-the-basics/lagoon-yml.md 

Fixing the markdown anchor should not require updates to all the links in all the pages where it appears.

**Comment by tobybellwood** [comment]
Thanks, @christopher-hopper - if you've got docs PRs - we're happy to take them as a PR only - just include a bit of info in the text - no need to create a separate issue!

Thanks so much for your continued contribution, much appreciated!

**Comment by christopher-hopper** [comment]
Thank you. That'd be easier. I guess I was trying to follow the process to the letter, just to be safe. Good to know
