### ISSUE TITLE
Building of master crashes on lagoon/auth-ssh with `OPENSSL_1.0.2' not found (required by ssh-keygen)

### ISSUE THREAD

**Issue by renebakx** [uselagoon/lagoon#33]
Running make build on macos 10.12.6 crashes with the error "ssh-keygen: /lib64/libcrypto.so.10: version `OPENSSL_1.0.2' not found (required by ssh-keygen)"

Steps to reproduce :

Clone lagoon repo and run make build
Wait a while and on building the auth-ssl the process stops 

`docker build --quiet --build-arg IMAGE_REPO=lagoon -t lagoon/auth-ssh -f services/auth-ssh/Dockerfile .`
steps 12 in the process is the crash.

See attached console log

[crash.log.txt](https://github.com/amazeeio/lagoon/files/1301864/crash.log.txt)

it looks like an upstream issue with "${IMAGE_REPO:-amazeeiolagoon}/centos7:" upstream.

Trying to figure out how to fix it, because I do think it happened on a 'regular' Centos 7 server I have in production to, but that was when installing apache 2.4.27 on a clean install.

**Comment by Schnitzel** [comment]
Thanks for this @renebakx :)

I did some debugging as well and saw that we're missing the openssl-libs package:
https://github.com/amazeeio/lagoon/commit/811aef02679608434ab1884aedfee2b8be301210

Can you try to build it with that?

**Comment by renebakx** [comment]
Will do that later today 👍

**Comment by renebakx** [comment]
Did a rebuild with the fix, and the errors are gone.   

The entire make build now runs perfectly.

**Comment by Schnitzel** [comment]
Merged: https://github.com/amazeeio/lagoon/pull/36 thanks @renebakx
