### ISSUE TITLE
`docker image prune` should run as a cronjob on the docker-host / docker-host on seperate node

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#330]
We saw a few times that the docker-host uses a lot of disk space. 

The `docker image prune` should run as cronjob every once in a while

Also we should figure out if we want to run a separate host where the docker-host is running on so we would be able to size the storage accordingly without running into storage limitations of the compute nodes.

**Comment by dasrecht** [comment]
The idea to have the docker-host on a separate compute node would solve the occasional disk usage issues we see. Apart form this we saw that the pushes to the registry could be a bit faster.

I'm not sure if the registry also would need to be scheduled on the same compute node or not. 

The basic idea is to tag the additional compute node in a way that we can have an affinity set to schedule the docker-host on that machine. Most of the remaining work will be documentation to get this going as this is a feature that can be enabled if it's needed.

**Comment by Schnitzel** [comment]
this is done
