### ISSUE TITLE
Lagoon can't sync Gitlab users when they don't have public email addresses

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon#3306]
# Describe the bug

Lagoon fails to sync gitlab data when a gitlab user doesn't have a public email address.

## To Reproduce

1. Create a user in gitlab with no public email
2. Add that user to a group/project
3. See that lagoon doesn't reflect the change in it's internal groups representation
4. See logs similar to `[error]: lagoon-logs: Send to lagoon-logs: Could not add user to group , reason: Error: GraphQL Error: User not found: [REDACTED]`

## Expected behavior

All gitlab system hooks are handled correctly (i.e., lagoon syncs gitlab data in all situations).

## Additional context

A [security release in gitlab 14.4.1, 14.3.4, and 14.2.6](https://about.gitlab.com/releases/2021/10/28/security-release-gitlab-14-4-1-released/#webhook-data-exposes-assignees-private-email-address) changed the payload data of some system hooks by replacing user email addresses with `REDACTED`. This causes some lagoon sync actions to fail. We know that the `user_add_to_group`, `user_remove_from_team`, and `user_remove_from_group` are affected. Additional research is required to check all the system hooks.

One solution is to require all users in gitlab to have a public email address. We'll have to check if gitlab can handle this or if it has to be a soft organization policy.

Another solution is to change our system hook handlers to load the necessary data from the gitlab API instead of relying on data from the system hook payload. As long as we get the gitlab user id in all payload this should be feasible.

**Comment by shreddedbacon** [comment]
I think we need to go down the path of having the webhooks2tasks service reach out to the gitlab api when it receives these hooks and use the user ID to retrieve the user email address for subsequent requests

Updating users profiles using some form of automation is not guaranteed as the users could go in and change their profile back at any time, and getting gitlab to add some enterprise/global override seems difficult based on the referenced issue
