### ISSUE TITLE
Auto-cancel deployments that take longer than X hours

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#3308]
Spotted in a cluster are builds that Lagoon thinks are running, but clearly have not been running for 3 years

<img width="535" alt="image" src="https://user-images.githubusercontent.com/10605846/195016706-9f27801e-5444-4fce-878d-5a5ab96d014e.png">

It would be great if there was a way to auto-cancel deployments that take longer than X hours, perhaps configurable per remote, but allow a default of 3 hours or something.

**Comment by tobybellwood** [comment]
those ones are veeery special indeed - but agree checking a suitable runtime and reporting makes sense

**Comment by shreddedbacon** [comment]
Some sort of reconcile loop for core could be neat to have in the future, and could call these out if they aren't immediately fixable.

But these ones definitely are a special case, this problem isn't so much of a problem these days.

**Comment by shreddedbacon** [comment]
https://github.com/uselagoon/remote-controller/pull/183 was merged today, next version of the remote-controller will be able to handle cancelling builds AND tasks that run too long, this timeout is adjustable.

**Comment by shreddedbacon** [comment]
This is resolved now, the remote-controller has had this functionality for a few releases.
