### ISSUE TITLE
When a build fails, include the text from the last step in the lagoon UI along with the notification payload

### ISSUE THREAD

**Issue by bryangruneberg** [uselagoon/lagoon#3320]
The new Lagoon UI accordion gives a nice indication of where a build might have failed. From a developer perspective, it would be really great to have the text from the last failed section included with the build-failed notification payload.

In slack this could be a thread on the failed message containing the text, or perhaps included in a text file.

![image](https://user-images.githubusercontent.com/383346/199091968-0fc461c9-b8e4-44a4-bd8a-38fb06543c77.png)

Some considerations however... 
1. Does this log information contain potentially sensitive details such as keys - those would need to be redacted
2. Is the information actually available when the notification runs?
3. Do all the notifications (Slack, email, webhook) have a good way to display this info

So there could be reasons not to do this - then we should kill this feature request!

**Comment by shreddedbacon** [comment]
2) The information is not currently available when the notification fires, we would need to ship this information into the notification event.
3) Some build step failures could produce significant logs. Displaying it may not be very useful at all considering we dump the link to the build in the notification too. Our slack notifier doesn't support threading. Not sure about other notifiers, but they might not support it either (webhook doesn't even do the range of notifications, it just does build success/failures)

**Comment by tobybellwood** [comment]
There is now a build step indicating a failure in the UI
