### ISSUE TITLE
Deleting environments on clusters that no longer exist

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon#3324]
Sometimes when a cluster is decommissioned, any environments that are still marked as being on this cluster are unable to be deleted. This is because the API tries to send a message to the remote cluster (which obviously doesn't exist), and then nothing happens.

It would be nice if there was a way to flag a cluster in the API as deleted/decomissioned when they are removed. This issue may still occur even when the cluster is deleted from the API too, but it would probably error silently.

This would allow the API to just mark the environment as deleted, rather than try send a message to a non-existing cluster and hope for a response.

**Comment by seanhamlin** [comment]
Also, potentially if a new build is triggered for an environment to which is on a cluster that is deleted/decomissioned, perhaps it can be rejected up front, rather than just making the API think there is a build in progress forever.
