### ISSUE TITLE
Change QoS/Bulk deployments "status" from "New" to "Queued"

### ISSUE THREAD

**Issue by BKAmazee** [uselagoon/lagoon#3352]
Change QoS/Bulk deployments "status" from "New" to "Queued", so that Qos/Bulk deploys can be easily identified from standard "new" deployments.

<img width="1452" alt="image__11__png" src="https://user-images.githubusercontent.com/102367505/204297931-544d1f89-7d6d-4db5-9611-edbd6aeccaaf.png">

**Comment by shreddedbacon** [comment]
This needs to be done in the API and in the `remote-controller`, I'm going to transfer this to `uselagoon/lagoon` because I've put a PR in to add the required ENUM status (https://github.com/uselagoon/lagoon/pull/3351)
