### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by RoSk0** [uselagoon/lagoon#337]
Here is a deployment log https://gist.github.com/RoSk0/4792b85c1e5beb3cdd802947679d5655
Repository of project being deployed https://github.com/RoSk0/lagoon-test.
This is simple Drupal 8 project created to test custom Lagoon installation.

I wasn't able to understand the reason of fail so asking for help and recommendations...

**Comment by Schnitzel** [comment]
can you remove these two lines? 
https://github.com/RoSk0/lagoon-test/blob/master/.lagoon.yml#L27-L28

I think this causes oc-build-deploy to think that the cli should not be deployed (see https://gist.github.com/RoSk0/4792b85c1e5beb3cdd802947679d5655#file-lagoon-deploy-log-L212 it declares it as `SERVICE_TYPE=None`)

**Comment by RoSk0** [comment]
Hi @Schnitzel ,

Thanks for quick response. I have added those 2 lines to mitigate bug fixed in #335 :D

Can you please take a look at that.

**Comment by Schnitzel** [comment]
can you explain me why you have `environments.master.types.cli` defined in `.lagoon.yml`?

**Comment by RoSk0** [comment]
Because it was failing with `Error: invalid path 'environments.master.types.cli', can't query subvalue 'types' of a leaf (leaf value is None)` described in #335 with attempt to fix in #336

**Comment by Schnitzel** [comment]
okay, let's try with then removing all these lines:
https://github.com/RoSk0/lagoon-test/blob/master/.lagoon.yml#L20-L28
:)

**Comment by RoSk0** [comment]
Actually a was able to pass that issue with cli service by adding `lagoon.rollout: 'false'` to lables of cli service in docker compose https://github.com/RoSk0/lagoon-test/commit/9f28a84228c0a0ff2324676fe8ed4d66ad469755.

Nginx deployment is still running so i will report tomorrow.

**Comment by RoSk0** [comment]
So  I removed those lines 20-28, commented out my workaround (`lagoon.rollout: 'false'`) and pushed (commit https://github.com/RoSk0/lagoon-test/commit/2a6326e1473df5f07d5c61f0acb621b0120d98e9 ).
Deploy failed but now in a new way. Deploy log https://gist.github.com/RoSk0/60c73089f2d49c252aff217f1e075728

**Comment by Schnitzel** [comment]
okay, are you running on openshift 3.7? there is an issue right now, that we are trying to fix

**Comment by RoSk0** [comment]
v3.9

**Comment by Schnitzel** [comment]
@RoSk0 
We upgraded to OpenShift 3.7+ support
It should work now without any modifications. Happy to also help in our slack channels! http://slack.amazee.io/
