### ISSUE TITLE
Static arguments for custom tasks

### ISSUE THREAD

**Issue by bomoko** [uselagoon/lagoon#3371]
Currently, all custom task arguments require a user to either select or provide a value.

What I would like to see is the ability to have argument types that behave like standard arguments, but are not manipulable by the person invoking them.

There are multiple uses for this functionality - but, as a simple example, if we are running a task in an image pod, we may want to inject _specific_ environment variables for the task run, but not have those controlled at invocation time (rather, it is set at task creation time).

**Comment by tobybellwood** [comment]
custom tasks now support default arguments that should cover most use cases
