### ISSUE TITLE
[feature] Support for DDEV

### ISSUE THREAD

**Issue by ElijahLynn** [uselagoon/lagoon#3374]
Mosty a stub for now for others to add comments onto since I didn't see any existing issues. Our team recently switched from Lando to DDEV, and they like the convenience of it, so I want to explore what it would take to create the DDEV abstraction layer for Lagoon. 

**Is your feature request related to a problem? Please describe.**
Add support for DDEV. 

* https://github.com/drud/ddev
* https://ddev.readthedocs.io/

**Describe the solution you'd like**
TODO

**Describe alternatives you've considered**
TODO

**Additional context**
TODO

**Comment by rocketeerbkw** [comment]
I think it's more correct to request that DDEV add support for Lagoon, not the other way around. Lagoon provides a set of docker images and a specific `docker-compose.yml` and `.lagoon.yml` schema that are built into a valid (hosted) Lagoon environment.

Lagoon itself can't create local environments, but the [pygmy](https://github.com/pygmystack) project ingests those resources and produces a valid local environment. [Lando](https://docs.lando.dev/lagoon/) does the same thing. There is an open issue for [DDEV to implement Lagoon](https://github.com/drud/ddev/issues/3188).

We'd be happy to collaborate further with DDEV but at the moment I'd say the ball is in their court. It's certainly possible that Lagoon would need to make changes to support DDEV, so any further/specific issues are welcome.

**Comment by ElijahLynn** [comment]
Ahh, that makes sense that it would be the other way around, thanks for chiming in here and linking that issue! I'll pop over there and leave a comment too!

**Comment by tobybellwood** [comment]
DDev Lagoon support released in https://github.com/ddev/ddev/releases/tag/v1.22.4
