### ISSUE TITLE
Special characters in build logs are not properly displayed

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#3398]
# Describe the bug

Any special characters printed in the build logs of a deployment are not properly displayed in the Lagoon API or UI.

## To Reproduce

1. Create a post rollout tasks that outputs umlauts https://github.com/amazeeio-demos/drupal-example-8/blob/main/.lagoon.yml#L13-L16
2. Run a deployment
3. Look at build logs, the special characters are broken: https://dashboard.amazeeio.cloud/projects/drupal-example-8/drupal-example-8-main/deployments/lagoon-build-pk3kyr
```
*** Task STDOUT ***
 C$C6C<
```

## Expected behavior

Umlauts are correctly shown, like when looking at the build logs directly via `kubectl logs`

```
*** Task STDOUT ***
 äöü
```

## Additional context
This doesn't seem to be a problem specifically to the post rollout tasks but anything that outputs special characters in the build logs, it's just that usually the other logs don't really have any umlauts, etc.

**Comment by smlx** [comment]
Oh this is a fun one! It looks like somewhere between the terminal output and the web page the output stream is being converted from UTF-8 to [7-bit ASCII](https://en.wikipedia.org/wiki/ASCII#Bit_width) (most likely?), which is zeroing the high bit.

```ruby
$ ruby -e "p 'äöü'.unpack('C*').map{|c| c & 0b01111111}.pack('C*')"
"C$C6C<"
```
