### ISSUE TITLE
Passing extra command-line flags to mysqld startup

### ISSUE THREAD

**Issue by igayoso** [uselagoon/lagoon#341]
Add the possibility to add extra flags when mysqld startup, could be something like:

```
$ docker run --name mariadb -e MARIADB_EXTRA_FLAGS='--max-connect-errors=1000 --max_connections=155' bitnami/mariadb:latest
```

**Comment by rtprio** [comment]
Thank you for your feedback.  We've designed our images to allow extra configuration; in this case you can add your desired configs  with your dockerfile. 

```
FROM amazeeio/mariadb
RUN echo max-connect-errors=1000 >> /etc/mysql/conf.d/extra.cnf
...
```
And update `docker-compose.yaml` 
from `image` to `build`
