### ISSUE TITLE
Cannot restart CLI once docker-compose stop has been executed

### ISSUE THREAD

**Issue by agence104** [uselagoon/lagoon#343]
Hi,

I'm running under Windows 10.

If you have done a `docker compose up -d` and you execute `docker-compose stop` , then you try doing `docker compose up -d` you will get an error:

`failed to create symbolic link '/tmp/ssh-agent': File exists`

Thanks

**Comment by twardnw** [comment]
use `docker-compose up --force -d` instead, it will recreate the ssh-agent volume mount.
