### ISSUE TITLE
Remove SHA-1 from SSH key exchange

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#3431]
This has been brought up as a way to increase security for the current SSH service within Lagoon. SHA-1 key exchange algorithms are considered weaker compared to newer SHA-2, SHA-256, or SHA-512.

It has [come up in the past as a blocker for PCI compliance](https://serverfault.com/questions/758673/how-to-disable-diffie-hellman-group1-sha1-for-ssh) as well.

## Current key exchange algorithms

Here are the current key exchange algorithms:

```
ssh:/$ ssh -Q kex
diffie-hellman-group1-sha1
diffie-hellman-group14-sha1
diffie-hellman-group14-sha256
diffie-hellman-group16-sha512
diffie-hellman-group18-sha512
diffie-hellman-group-exchange-sha1
diffie-hellman-group-exchange-sha256
ecdh-sha2-nistp256
ecdh-sha2-nistp384
ecdh-sha2-nistp521
curve25519-sha256
curve25519-sha256@libssh.org
sntrup4591761x25519-sha512@tinyssh.org
```

Perhaps we could look at removing all the SHA-1 based algorithms?

```
diffie-hellman-group1-sha1
diffie-hellman-group14-sha1
diffie-hellman-group-exchange-sha1
```

## Proposed change

This is detailed further in man `sshd_config` under `KexAlgorithms`:

```
KexAlgorithms -diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
```

**Comment by smlx** [comment]
`ssh -Q kex` queries the _supported_ algorithms in the ssh _client_. By default, the ssh client will not be configured to use all those algorithms. On my machine the default according to `man ssh_config` is:

```
                  sntrup761x25519-sha512@openssh.com,
                   curve25519-sha256,curve25519-sha256@libssh.org,
                   ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,
                   diffie-hellman-group-exchange-sha256,
                   diffie-hellman-group16-sha512,
                   diffie-hellman-group18-sha512,
                   diffie-hellman-group14-sha256
```

You can see what the client is actually sending via `ssh -vv`:

```
debug2: local client KEXINIT proposal
debug2: KEX algorithms: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
```

On the _server_ side you can see the configuration by connecting using `ssh -vv` and looking for these lines:

```
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
```

The output above is from the Lagoon `ssh` service, so it doesn't appear to be configured to use any SHA1 KEX algorithms.

The `ssh-portal` unfortunately _does_ present a SHA1 KEX algorithm. I've ticketed that here: https://github.com/uselagoon/lagoon-ssh-portal/issues/206
