### ISSUE TITLE
Versions in Lagoon Information

### ISSUE THREAD

**Issue by tnelson-doghouse** [uselagoon/lagoon#3480]
It would be nice if the Lagoon API supported the querying of versions.  Specifically, grab "env | grep VERSION" and attach it to the environment or deployment or something, and then allow querying of it via the Lagoon interface.  

At this point, both Sean and I have made scripts that do essentially this across all projects (which requires a SSH into each environment) -- it'd be nice if this could happen:
- Without requiring maintainer-level permissions on each environment, and
- Without requiring firing up a CLI pod on each project

The purpose is so that we can see which projects have out-of-date versions of Lagoon images, and also out-of-date versions of our own software.  

HTH!

**Comment by shreddedbacon** [comment]
What versions are you talking about here? This is probably exactly what the insights system aims to expose?

**Comment by tnelson-doghouse** [comment]
Versions for:
- PHP
- Lagoon
- New Relic
- Versions of our software (we have environment variables for this too, also called <BLAH>_VERSION)

Duplication of Insights sounds plausible.  Please either close this as a duplicate of whichever insights ticket is appropriate, or turn this into an insights ticket (whichever is suitable).

**Comment by shreddedbacon** [comment]
Yeah, this sounds like insights. Ticket covering insights #3082
