### ISSUE TITLE
run `oc get istag` with parallel and --retries

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#349]
It looks that if we have `oc tag --source=docker` and immediately `oc get istag` afterwards this runs into some race conditions, where the openshift registry has not resolved the image tag yet, so `oc get istag` fails.

In order to prevent this, I think a save way would be to run `oc get istag` inside a gnu parallel with `--retries` so it automatically retries for 2-3 times (probably preferred also with a sleep in there)

The complexity is a bit that currently the output of `oc get istag` is saved in an bash array:
https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L351

which does not work anymore with parallel. Instead I think we could save the output in a file per image.

**Comment by rtprio** [comment]
merged into master on e7545ce2b25a3484ba0aff62a2653fc4e42fb57d
