### ISSUE TITLE
Implement new Storage for API Objects

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#35]
As discussed in https://github.com/amazeeio/lagoon/issues/29 we want to rebuild the Storage of the API

At the same time we also create new Objects, in this hierarchy:
- customer (the current client, stores information about the customer)
  - project (each project, like each git repository)
     - openshift (information about the openshift that the project is pushed too)

ssh keys can be referenced from customer and from project

## customer

| key | type | description | example value |
| :--- | :--- | :--- | :--- |
| name | String | Unique. name of the customer. | amazeeio |
| ssh\_keys | reference to ssh\_keys object | can be referencing to multiple ssh keys, this ssh key will have access to all projects of this customer |  |
| comment | free text | some comment about the client |  |
| created | date | time of creation date of customer. Date format tbd. |  |
| private\_key | SSH Private key | ssh private key for this specific user, will be used during the deployment to access the git repositories that should be deployed |  |

## project

| key | type | description | example value |
| :--- | :--- | :--- | :--- |
| name | string | Unique. name of the project | awesomewebsite |
| client | reference to client | reference to the client of this project |  |
| ssh\_keys | reference to ssh\_keys object | can be referencing to multiple ssh keys, used to allow specific ssh keys only access to a single project |  |
| git\_url | string | git url of the project, needs to be in ssh format | git@github.com:amazeeio/awesomewebsite.git |
| slack | reference to slack object | can be either existing (if slack enabled) or not (no slack notifications) |  |
| active\_systems\_deploy | String | Name of the active system for deployment | lagoon\_openshiftDeploy |
| active\_systems\_remove | String | Name of the active system for removals | lagoon\_openshiftRemove |
| branches | String | Regex of branches to be deployed, default is all branches | ^\(master\|staging\)$ or .\* |
| pullrequests | Bool | Enable or disable pull request builds, default: false | true, false |
| openshift | Reference to OpenShift Object | Used to define to which OpenShift this project should be deployed too |  |

## openshift

| key | type | description | example value |
| :--- | :--- | :--- | :--- |
| name | string | unique, name of the openshift server |  |
| console\_url | URL | URL of the console to connect to | https://console.appuio.ch |
| registry | Domain String | Domain \(not full URL\) of the docker registry to push to | registry.appuio.ch |
| token | JSON Web Token | token of the service account to use to create openshift resources.  |  |
| username | String | Username of the OpenShift User that should be used to create openshift resources | foo |
| password | String | Password of the OpenShift user that should be used to create openshift resources | bar |
| router\_pattern | String | String with the router pattern that will be used on that specific OpenShift server, has two substitutions: ${project}, ${environment} that will be subsituted automatically | ${project}.${environment}.appuio.amazee.io |
| project\_user | String | OpenShift Username that should also be given access too when creating a new project | technology@amazeelabs.com |

## SSH Key

| key | type | description | example value |
| :--- | :--- | :--- | :--- |
| name | String | Unique. name of the ssh key, most probably an email address, but can be any string. | michael.schmid@amazee.io |
| key | ssh key | the actual ssh key, with no type or email address at the end | AAAAC3NzaC1lZDI1NTE5AAAAICtH4WLYkj55uZ/cLtTjnb0QbutYX1xBJbUzpRhBXeq3 |
| type | ssh key type | the type of the ssh key, by default ssh-rsa  | ssh-rsa, ssh-ed25519 |

## slack

| key | type | description | example value |
| :--- | :--- | :--- | :--- |
| webhook | URL | URL of the Slack Incomming Webhook | https://hooks.slack.com/services/AAAAAAA/BBBBBBBB/CCCCCCCC |
| channel | String | Name of the Slack Channel to send notifications to | mychannel |

**Comment by rtprio** [comment]
Do we want to be chat system agnostic? Is it worth replacing slack_webhook / slack_channel with a foreign key to chat platform table?

**Comment by Schnitzel** [comment]
@rtprio 
good idea, I think that would make sense and also be more ready for the future.
I updated the table above
