### ISSUE TITLE
Error on make build

### ISSUE THREAD

**Issue by JeffVeit** [uselagoon/lagoon#357]
I'm testing Lagoon and running my first make build. 
During build/ssh I'm getting:

> Step 14/32 : RUN rm -f /bin/sh && ln -s /bin/bash /bin/sh
>  ---> Using cache
>  ---> a0ca59ab9950
> Step 15/32 : RUN npm -g install jwtgen
>  ---> Running in c3c4aa98b6b3
> npm http GET https://registry.npmjs.org/jwtgen
> npm http GET https://registry.npmjs.org/jwtgen
> npm http GET https://registry.npmjs.org/jwtgen
> npm ERR! Error: CERT_UNTRUSTED
> npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
> npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
> npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
> npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
> npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
> npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
> npm ERR!     at doWrite (_stream_writable.js:223:10)
> npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
> npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
> npm ERR!     at write (_stream_readable.js:583:24)
> npm ERR! If you need help, you may report this log at:
> npm ERR!     <http://github.com/isaacs/npm/issues>
> npm ERR! or email it to:
> npm ERR!     <npm-@googlegroups.com>
> 
> npm ERR! System Linux 4.4.0-119-generic
> npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "-g" "install" "jwtgen"
> npm ERR! cwd /
> npm ERR! node -v v0.10.25
> npm ERR! npm -v 1.3.10
> npm ERR! 
> npm ERR! Additional logging details can be found in:
> npm ERR!     /npm-debug.log
> npm ERR! not ok code 0
> The command '/bin/sh -c npm -g install jwtgen' returned a non-zero code: 1
> Makefile:338: recipe for target 'build/ssh' failed
> make: *** [build/ssh] Error 1
> 

Running make clean and trying again does not help. I've tried this outside of the build, and npm -g install jwtgen runs just fine. I imagine it's to do with certificates - but I would have expected Digicert, who signs github.com to be recognised.

Any ideas?

**Comment by rtprio** [comment]
It looks like quite a few people are having a similar issue; https://github.com/npm/npm/issues/20191 
`npm config set strict-ssl false` could be a brief workaround until a better solution of getting updated CA certificates fixes the problem.

**Comment by Schnitzel** [comment]
or use our lagoon image cache:
`make s3-load`
and then build again, this time it should see the Docker Image layer caches and right go through

**Comment by JeffVeit** [comment]
You were exactly right! The pull ubuntu:latest worked. I was silly not to think of that.

Perhaps that should go at the beginning of the instructions.

**Comment by JeffVeit** [comment]
Thanks!
