### ISSUE TITLE
Make imagemagick available on lagoon

### ISSUE THREAD

**Issue by chindris** [uselagoon/lagoon#361]
There will be many cases when we will use imagemagick (convert) as the image toolkit in Drupal, instead of the old PHP GD. We should have this package also available.

**Comment by dasrecht** [comment]
Workaround: 

Adding imagemagick to Dockerfile.php and Dockerfile.cli

> RUN apk add --no-cache imagemagick

**Comment by Schnitzel** [comment]
+1 from another client that would like to have that.
