### ISSUE TITLE
API uses `Int` for backup restore sizes which can be larger than `Int` size

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon#3629]
# Describe the bug

The GraphQL type for the `restoreSize` field is set as `Int` which [only allows signed 32-bit integers](https://graphql.org/learn/schema/#scalar-types). Since the size is recorded in bytes, this can be larger than the `Int` type. In this case the api will error with: `Int cannot represent non 32-bit signed integer value`

## To Reproduce

1. Restore a backup larger than 2.2GB
2. Attempt to retrieve restore info from the api (or view the backups page in the UI)

## Expected behavior

The api stores and retrieves restore size without errors.

## Additional context

Introduced in https://github.com/uselagoon/lagoon/pull/3599.

**Comment by shreddedbacon** [comment]
Is Float the better one to use, since we use it for storage bytes?
https://github.com/uselagoon/lagoon/blob/main/services/api/src/typeDefs.js#L947

**Comment by rocketeerbkw** [comment]
> Is Float the better one to use, since we use it for storage bytes? https://github.com/uselagoon/lagoon/blob/main/services/api/src/typeDefs.js#L947

I checked the graphql spec and it doesn't specify what the max size of a float is. There's a random comment on a SO question that says it's 52 or 128 bits.... but no source was provided.

I would expect the storage calculator and restore sizes to be mostly equivalent, so if it works for storage I suppose it should be fine for restores.
