### ISSUE TITLE
Add support for OpenSSH FIDO SSH keys `-sk` keys

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#3694]
These `-sk` variants can only be created with a YubiKey or compatible FIDO/U2F token and the token is required to use the private key.

It would be great if Lagoon had support for these keys.

I think these are the following public key types

```
ecdsa-sk
ed25519-sk
```

See https://www.openssh.com/txt/release-8.2 under the heading "FIDO/U2F Support" for more information on OpenSSH.

**Comment by rocketeerbkw** [comment]
Duplicate of #2189
