### ISSUE TITLE
Imagebuild of centos7-mariadb10 stalls with error

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#37]
When building the centos7-mariadb10

```
warning: /var/cache/yum/x86_64/7/mariadb/packages/MariaDB-10.2.8-centos7-x86_64-common.rpm: Header V4 DSA/SHA1 Signature, key ID 1bb943db: NOKEY
Public key for MariaDB-10.2.8-centos7-x86_64-common.rpm is not installed
```

I solved the build locally by adding

```
RUN rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
```

Will push a MR to fix that issue in a bit

/bastian

**Comment by Schnitzel** [comment]
after testing we learned that the stalling is not coming from this issue, but rather just a very slow download of MariaDB.
As we are planning to migrate all Images to Alpine bases I think we don't need to worry about this too muach
