### ISSUE TITLE
Settings file permissions.

### ISSUE THREAD

**Issue by yaroslav-lu** [uselagoon/lagoon#370]
Hello,

during build of container, settings.php file and sites/default folder gets wrong permissions and Drupal shows error on status report page.

sites/default gets 775
settings.php gets 664

Thank you.

**Comment by thom8** [comment]
@yariklutsiuk add the following to your Dockerfile --

```
# Config directory should be non-writable.
RUN chmod 755 /app/docroot/sites/default
```

Just needs to be run after the code has been added to the image.
