### ISSUE TITLE
Header mislabeling: 'Project variables' incorrectly displayed above 'Environment variables' section in Lagoon dashboard

### ISSUE THREAD

**Issue by Ahmedjabar** [uselagoon/lagoon#3717]
## Describe the bug

`Project variables` is shown as the header above `Environment Variables` section. The correct heading appears briefly before it is replaced by Project variables. This was observed on Lagoon core version `2.18.0+fa25b3e9`.

## To Reproduce

1. Go to the Variables section
2. Observe `Project variables` header above the `Environment variables` section. See the attached screenshot.

## Expected behavior

The header should be correct (i.e. `Environment variables`).

## Screenshots
<img width="1985" alt="Screenshot 2024-05-02 at 3 37 34 pm" src="https://github.com/uselagoon/lagoon/assets/5373793/99b6e63e-9dde-43a1-ab3c-6f364b54b926">

## Additional context

N/A.

**Comment by shreddedbacon** [comment]
Closing, issue already exists in the lagoon-ui: https://github.com/uselagoon/lagoon-ui/issues/244
