### ISSUE TITLE
Feature Request: Ability to create lower scoped access for a given user/SSH key

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#3780]
Along the same veins as GitHub's PAT system [[link](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens)], it would be great if there was a way to be able to attach a given SSH key to a given scope within your Lagoon user.

e.g.

* Have an SSH key that is read-only access
* Have an SSH key that is for developer only access
* Have an SSH key that is full access to everything you can do (current status quo)

This is the principle of least privilege.

As a developer, you can use your 'development SSH key' and add this to your SSH agent, and use this most of the time. You might reserve access to production systems to another SSH key, that is FIDO backed.

At present, the only way to achieve something similar to this, is creating multiple Lagoon user accounts for the same human, and granting different roles to each Lagoon user.

**Comment by tobybellwood** [comment]
Closing here, but tracking internally as part of other long-term feature requests. 

Implementation of this will become a consideration for a full users&permissions systems overhaul, which itself is still only at the idea stage.
