### ISSUE TITLE
Add "Completed with Warnings" to CLI and Notification output

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon#3819]
Currently users who don't use the CLI will have no idea (without looking at the logs) that their successful build has failed with warnings. +1 if we could include "why the build failed"

**Comment by shreddedbacon** [comment]
> +1 if we could include "why the build failed"

This is only currently possible by parsing the build log, as there are no stages saved against the API, just the final stage/step

Also small clarification around the wording used. `completed with warnings` are not failures. The build step can show which step builds failed at though, but not which warnings were collected, this would require changes to the API to store this information better. CLI and Logs2Notifications would need to parse the log to extract this information, which would be duplicated processes, want to avoid that.
