### ISSUE TITLE
Update drupal7 example $base_url to use `_SERVER["HTTP_HOST"]`

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#419]
- [x] Check on Lagoon via HTTP
- [x] Check on Lagoon in Drush (drush uli)
- [x] Check locally via HTTP
- [x] check locally via Drush (drush uli)

**Comment by Schnitzel** [comment]
@twardnw 
maybe this would actually be better than using `LAGOON_ROUTE`?

**Comment by twardnw** [comment]
took a couple iterations to get there @Schnitzel , but the sum is:
```
if (getenv('LAGOON_ROUTE')) {
  $proto = isset($_SERVER["HTTP_X_FORWARDED_PROTO"]) ? $_SERVER["HTTP_X_FORWARDED_PROTO"] : 'http';
  $base_url = $proto . "://" . $_SERVER["HTTP_HOST"];
}
```
I did deploy to drupal7-example-master on ch1, you can double check things there, passed all my test cases.
