### ISSUE TITLE
support ssh-ed25519 keys in Lagu 

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#423]
If the `ssh2` library cannot support Ed25519 keys at this time, we could fall back to commands such as the following executed over child processes:

```
ssh -p 2020 -i ./local-dev/cli_id_rsa lagoon@localhost token
```

**Comment by karlhorky** [comment]
It appears that a token is always being returned in my branch (branched off of 1e028bcd7f97477adef482c8fb3dfb4162510643, last commit of #536), regardless of the key that I pass.

I've opened #545 to track this.
