### ISSUE TITLE
error message for customer without private_key

### ISSUE THREAD

**Issue by rtprio** [uselagoon/lagoon#431]
currently it's 
master ERROR: TypeError: Cannot read property 'replace' of null

let's improve the error message, or update the schema so that it's not null.

**Comment by karlhorky** [comment]
You mean while using the CLI, right? I noticed this some time ago as well. I'd be up for helping out on this one. cc @Schnitzel

**Comment by rtprio** [comment]
No; Sorry I wasn't clear.
This is an error message from `openshiftbuilddeploy`

**Comment by smlx** [comment]
`openshiftbuilddeploy` is deprecated
