### ISSUE TITLE
Implement issue (and possibly) PR templates

### ISSUE THREAD

**Issue by dan2k3k4** [uselagoon/lagoon#434]
Github has supported Issue and PR templates since over 2 years. It is quite nice to be able to create a new issue and already have a template pre-filled for other open-source projects.

It would be nice to implement one for `lagoon`, here's a few examples: [awesome-github-templates](https://github.com/devspace/awesome-github-templates)

* [Creating an issue template for your repository](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)
* [Creating a pull request template for your repository](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

**Comment by dasrecht** [comment]
https://github.com/amazeeio/lagoon/pull/455

**Comment by dan2k3k4** [comment]
Approved @dasrecht
