### ISSUE TITLE
ERROR: pull access denied for lagoon/api-db,

### ISSUE THREAD

**Issue by aldibier** [uselagoon/lagoon#442]
Executing make lagoon-kickstart I get this error.

```
IMAGE_REPO=lagoon CI_USE_OPENSHIFT_REGISTRY=false docker-compose -p lagoon up -d rabbitmq openshiftremove openshiftbuilddeploy openshiftbuilddeploymonitor logs2slack api ssh auth-server local-git local-api-data-watcher-pusher local-es-kibana-watcher-pusher tests rest2tasks
Pulling api-db (lagoon/api-db:latest)...
ERROR: pull access denied for lagoon/api-db, repository does not exist or may require 'docker login'
```
The solution was add it at the end of deployment-test-services-main definition in Makefile

**Comment by dasrecht** [comment]
Hi @aldibier thanks for the bugreport. Can you create a pull request with that change. That would be fabulous!

**Comment by fubarhouse** [comment]
+1

```
Pulling api-db (lagoon/api-db:)...
ERROR: pull access denied for lagoon/api-db, repository does not exist or may require 'docker login'
```

Would love to help here, but it's clearly not something I'm physically allowed to help with...

**Comment by twardnw** [comment]
did you build the images locally first?

**Comment by fubarhouse** [comment]
I didn't actually, but I don't know where I can find the dockerfile for it.

Perhaps you could tell me - I'm simply using the kickstart process.

**Comment by twardnw** [comment]
`make build` will kick off the build process for all the images

**Comment by fubarhouse** [comment]
Excellent - I'll try that and get back to you. Thank you.

**Comment by twardnw** [comment]
you can also always get to us at https://amazeeio.rocket.chat

**Comment by fubarhouse** [comment]
I'm already there :P

I did assume this issue was linked to the OP, so that was my mistake.
