### ISSUE TITLE
Add possibility to skip deployment with commit message token

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#45]
https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build

**Comment by back-2-95** [comment]
Yeah, so something like `my documentation changes [skip deploy]`

**Comment by rtprio** [comment]
#308

**Comment by Schnitzel** [comment]
https://github.com/amazeeio/lagoon/pull/308

**Comment by rtprio** [comment]
Found a bug last week; reopening.

**Comment by rtprio** [comment]
I wasn't able to duplicate the issue.
