### ISSUE TITLE
Lagoon-Tug Remote deployments don't use the .lagoon.env.* files 

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#454]
During testing we observed that during the Lagoon-tug rollout on the remote Openshift fails to connect to the database as the environment variables overwritten in the `.lagoon.env.<branch>` will not be used.

The environment variables are present when the container is entered directy via the openshift console.

**Workaround:**

Defining the environment variables in the deployconfig which will make sure that every container run has the variables set.

**Comment by tobybellwood** [comment]
Tug is deprecated in Lagoon 2
