### ISSUE TITLE
Pod Idling - Don't idle mysql pods and only idle projects that didn't receive traffic for more than 4 hours

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#465]
Currently we idle projects pretty fast after not receiving traffic.

We discussed that we should not idle the mysql pods as they take the most time to start back up again.

Also the idling might be happening to fast so we can idle projects after 4 hours after the last traffic occured.

To control the idling further (i.e. not just running it with --all) we could put a label in place on the services `allow-idler` which would be overrideable via a label.

This way we could use `allow-idler: yes` for service that may be idled and `allow-idler:no` for services that should not be idled automatically.

**Comment by rtprio** [comment]
this was closed in #473.
