### ISSUE TITLE
allow intra-service api communication via `JWTSECRET` directly

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#47]
Currently requests to the API are allowed via JWT tokens. For intra-service communication we create an `admin` token that is used then by every service to talk to the api.
Unfortunately this makes bootstrapping of a new Lagoon very hard, as you need the Lagoon system running in order to create a new JWT token, but in the very first stages we don't have Lagoon running yet :)

So my idea would be to also allow communication to the API via `JWTSECRET` directly. As we distribute the `JWTSECRET` to all Services already, they could just use that to talk to the API.

**Comment by ryyppy** [comment]
**Ideal solution:**
- HTTPS / TLS signature check -> If okay, accept requests without JWTSecret

**Quick solution:**

- [x] Extract `/services/auth-server/src/jwt.js` in the common packages
- [x] Inject JWTAUDIENCE / JWTSECRET in given common package (q`n`d for now)
- [x] Adapt the auth-ssh service to be able to generate the admin token for itself (for api communication)

**Comment by Schnitzel** [comment]
implemented and tested, works perfectly :)
