### ISSUE TITLE
drush commands against remote fail due to incorrect working directory when not used in local containers

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#485]
Drush attempts to locate the drupal root directory for commands, and failing that simply uses the current directory. When using drush commands against a remote environment from _outside_ the containers, this results in a path like `/Users/twardnw/Sites/twardnw_com/`, which does not exist on the remote environment, causing the drush command to fail.

**Comment by Leksat** [comment]
Checked this with @Schnitzel. It seems like for now the only way is to fix this on the project level: correct `root` for all aliases in the end of `aliases.drushrc.php` after the stub code is executed.

```
if (!getenv('LAGOON')) {
  // When running Drush outside the container, it is not possible to determine
  // the web root. Just set the root manually.
  foreach ($aliases as $key => $alias) {
    $aliases[$key]['root'] = '/app/web';
  }
}
```

**Comment by vincenzodnp** [comment]
Hello there
the `root` folder is defined here: https://github.com/amazeeio/lagoon/blob/master/services/drush-alias/web/aliases.drushrc.php.stub#L281 and we might need to test if this is still needed.

**Comment by rocketeerbkw** [comment]
There have been a lot of changes in new versions of Drush and the way we handle aliases is different. Closing this assuming it's not a problem anymore.
