### ISSUE TITLE
Add Pull Request Support for BitBucket

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#49]
With https://github.com/amazeeio/lagoon/commit/5cee6b71e29bfea3c26c53c8ea9f93fac6c3d3ba and https://github.com/amazeeio/lagoon/commit/def96065f51c4b92e6dcd22a9cb4afc47b02ea76 we have pull request support for GitHub.
Now we would also need it for BitBucket.

**Comment by luksak** [comment]
This would be nice!

**Comment by erikrs** [comment]
We definitely like this to be implemented ! (since our company wide versioning system is only bitbucket)

**Comment by dasrecht** [comment]
Closing this was released in - https://github.com/amazeeio/lagoon/pull/539
