### ISSUE TITLE
make LAGOON_ROUTE and LAGOON_ROUTES smarter

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#491]
Especially for D7 sites which utilize `LAGOON_ROUTE` as the `$base_url`, the `LAGOON_ROUTE` should change to http if `insecure` is set to `Allow`

**Comment by twardnw** [comment]
@Schnitzel , after considering this off-and-on for a bit, I think perhaps introducing LAGOON_HOST and LAGOON_HOSTS might be a better way to handle this? From there we can have the flexibility of having the site/app to construct it's own reference to the route.

**Comment by Schnitzel** [comment]
technically we can just do that on the fly:

```
str_replace(['https://', 'http://'], ['', ''], getenv('LAGOON_ROUTE'));
```

**Comment by twardnw** [comment]
we also need to make sure LAGOON_ROUTE is set to be the first route in `.lagoon.yml`
