### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#502]
- [x] How to work with pull requests
- [x] Environment Types (production vs development)
- [x] Routes in .lagoon.yml (also auto generated routes)
- [x] full .lagoon.yml overview : http://lagoon.readthedocs.io/en/latest/using_lagoon/lagoon_yml/
- [x] docker-compose yaml
- [x] logging access
- [ ] Drupal: How to revert, backups before deployments
- [x] Promotion Workflow
- [x] MySQL Galera
- [x] Backups (short term), mid term (how to access, etc)
- [x] GraphQL API https://github.com/amazeeio/lagoon/blob/master/docs/administering_lagoon/graphql_api.md

**Comment by ejimz** [comment]
FYI, It looks like there is a broken link in https://lagoon.readthedocs.io/en/latest/developing_lagoon/ page, 
The "Makefile" link in "Start services" section doesn't exist.

Also there are broken links in https://lagoon.readthedocs.io/en/latest/using_lagoon/docker_images/php-fpm/ page, under the "amazee.io & OpenShift adaptions" section

**Comment by dasrecht** [comment]
Hi @ejimz thanks for pointing out i'll fix that in https://github.com/amazeeio/lagoon/pull/779
