### ISSUE TITLE
Allow to disable auto generated routes

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#505]
There should be the possibility to disable the creation of automatically created routes

**Comment by erikrs** [comment]
Additionally, you should be able to specify that no route at all should be generated, eg. when the relevant service is a back-end µ-service which shouldn't be reachable by ingress traffic.

Also take into account existing Lagoon services,eg. node or node-persistent, which have a route.yml defined in their openshift-templates dir: this route definition should additionally be ignored and therefore not created.

(if developers still want to reach that backend µ-service, something like an oc port-forward on the openshift CLI would be a go to solution, hence authentication is covered and a only a non public route is available through the port-forward. Ops and sec teams would be thankful ;-)
