### ISSUE TITLE
Lagu: Output mode settings

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#513]
Besides the fancy table output we could use some others, like:

- text
- CSV
- JSON

**Comment by karlhorky** [comment]
Maybe for this we can introduce an `output` or `format` option with possible values of:

- `table` (default?)
- `text` or `plain` or `simple` (see https://github.com/facebook/jest/issues/2471) - maybe just headings with values after a colon on newlines?
- `csv`
- `json`

Another thing to consider would be an `outputFile` or `outputPath` option to allow saving directly to a file, possibly useful for the CSV and JSON options.

There is some precedent for all of this in Jest's [`--json`](https://jestjs.io/docs/en/cli#json) and [`--outputFile`](https://jestjs.io/docs/en/cli#outputfile-filename) options.
