### ISSUE TITLE
Can't get xdebug to work

### ISSUE THREAD

**Issue by rafatwork** [uselagoon/lagoon#519]
**Describe the bug**
I can't get xdebug to work on my local machine. Everything looks correct + using the chrome debug extension (and I can see that the cookie is being set).
In phpinfo() I notice that "xdebug.remote_host" is set to 192.168.0.1. Is this correct? If not, how do you change this value?

**phpStorm configuration**
![phpstorm_servers](https://user-images.githubusercontent.com/8710999/42999012-86c2d12a-8c1c-11e8-8be3-39480a07913a.JPG)

![phpstorm_debug](https://user-images.githubusercontent.com/8710999/42999017-8920d980-8c1c-11e8-9ffa-566d1317a6dc.JPG)

**docker-compose.yml**
[docker-compose.txt](https://github.com/amazeeio/lagoon/files/2213576/docker-compose.txt)

**phpinfo**
[phpinfo.html.txt](https://github.com/amazeeio/lagoon/files/2213580/phpinfo.html.txt)

**Additional info**
Running Windows 10 - 1803 OS Build 17134.165
Running Docker CE 17.12.0-ce-win47 (15139)

**Comment by rafatwork** [comment]
Friendly reminder.

**Comment by gugalamaciek** [comment]
I have very similar problem. For one project xDebug works good, for second one - only from console.
As I compared setup, the only things which differs is xdebug.remote_host value. For working project it is set to:

`xdebug.remote_host => docker.for.win.localhost`

When value is set by docker (in my case) to:

`xdebug.remote_host => 172.20.0.1`

it doesn't work.

What is strange - remote host value is different when checking via cli (`php -i`) and via browser (phpinfo()).

Php setup (when checking in cli via `php -i`):
[test.txt](https://github.com/amazeeio/lagoon/files/2309553/test.txt)

Php setup (when checking via browser):
[phpinfo.html.txt](https://github.com/amazeeio/lagoon/files/2309566/phpinfo.html.txt)

Docker setup:
[docker-compose.yml.txt](https://github.com/amazeeio/lagoon/files/2309554/docker-compose.yml.txt)

I've checked  /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini, it contains:
`xdebug.remote_host=docker.for.win.localhost`

Also tried to setup loopback interface as described here: https://docs.amazee.io/tools/xdebug.html#xdebug-in-windows, but still not working.

I'm using Win10 with docker:
![image](https://user-images.githubusercontent.com/13976979/44453872-6afa5d80-a5fa-11e8-83b0-d61eb5aa5db8.png)

**Comment by twerthmueller** [comment]
@gugalamaciek just remove this line and the debugger (xdebug) should work again after a restart of the containers.

![docker-compose yml 2018-09-13 14-43-01](https://user-images.githubusercontent.com/6920143/45490325-16fd1780-b767-11e8-8328-db8db4586e2b.png)

After that change xdebug worked again. But we use Mac and not Windows.... hope this helps.

**Comment by rafatwork** [comment]
I've updated my Docker installation to version 18.06.1-ce-win73 (19507).

`xdebug.remote_host` now has `docker.for.mac.localhost` as value.

```
Pinging docker.for.mac.localhost [62.138.238.45] with 32 bytes of data:
Reply from 62.138.238.45: bytes=32 time=27ms TTL=250
Reply from 62.138.238.45: bytes=32 time=27ms TTL=250
Reply from 62.138.238.45: bytes=32 time=26ms TTL=250
```

Assistance greatly appreciated. This is hindering me quite a lot & I have to resort to different local development environments for the time being.

**Comment by rafatwork** [comment]
After digging this into myself, I finally found the issue. My initial suspicions were right: the `xdebug.remote_host` setting is incorrect on my installation.

Executing `ipconfig /all` in the command prompt I see the following:
```
Ethernet adapter vEthernet (DockerNAT):
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #2
   Physical Address. . . . . . . . . : 00-15-5D-F4-68-2F
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 10.0.75.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                             fec0:0:0:ffff::2%1
                                             fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled
```

Meaning my docker host is running on the `10.0.75.1` IP address.

When testing in a container, `docker.for.mac.localhost` however resolves to `62.138.238.45`. Actually, everything resolves to that IP address (`*.*`, such as `whatever.whatever`). This means xdebug isn't able to connect to my host.

In https://github.com/amazeeio/lagoon/blob/master/images/php/fpm/entrypoints/60-php-xdebug.sh I found out you can set the `xdebug.remote_host` setting by configuring a DOCKERHOST environment variable, which is what I did:
```
x-environment:
  ...
  &default-environment
    ...
    DOCKERHOST: 10.0.75.1
  ...
```

... et voila, xdebug is working again.

I'm not a Docker expert, so any help as to why DNS resolving on my docker installation seems to be broken is more then welcome...

**Comment by VladBo** [comment]
The same issue on MacOS. After setting DOCKERHOST: 172.16.172.16 xdebug is working agian.

**Comment by gugalamaciek** [comment]
@twerthmueller thank you very much! :) That works for me.

**Comment by Schnitzel** [comment]
seems like this has been solved, thanks everybody!

**Comment by rafatwork** [comment]
@Schnitzel 
Unless I'm missing something, but I think this hasn't been solved. We only have a workaround.

**Comment by luksak** [comment]
Yes, I still have this issue as well.

**Comment by alexdesignworks** [comment]
This issues does not specify the version of images used. Try to update to the latest images.

I can confirm that `0.22.1` has improvements on discovering the value of `xdebug.remote_host`. 
On MacOS it is correctly set to `docker.for.mac.localhost` for both CLI and FPM.

**Comment by tamasd** [comment]
Instead of the current logic, it should try `host.docker.internal`. That will take care of macOS and Windows. If that host cannot be resolved, then the script should get the gateway for Linux.

**Comment by AlexSkrypnyk** [comment]
@tamasd The logic works correctly - it tries its best to resolve the host, but times out.
 see https://github.com/amazeeio/lagoon/issues/1088

**Comment by iijiang** [comment]
@VladBo  same here, 172.16.172.16 works.
@AlexSkrypnyk 
@Schnitzel 

I am not sure I understand this issue.  https://github.com/amazeeio/pygmy/blob/267ba143158548628f190f05ecb5cb2c19212038/lib/pygmy/resolv_osx.rb#L26

I still have this issue https://github.com/uselagoon/lagoon/pull/2002

host.docker.internal doesnt resolve.

`nslookup host.docker.internal
Server:         192.168.0.1
Address:        192.168.0.1#53

** server can't find host.docker.internal: NXDOMAIN`

docker desktop: 4.0.0 (67817)
macOs: 11.5.2 (20G95) Big Sur

**Comment by rocketeerbkw** [comment]
@iijiang I've recently tested xdebug in our latest images and they are working correctly. Can you please follow our [setup instructions](https://docs.lagoon.sh/lagoon/using-lagoon-advanced/setting-up-xdebug-with-lagoon) and go through all the [troubleshooting steps](https://docs.lagoon.sh/lagoon/using-lagoon-advanced/setting-up-xdebug-with-lagoon#troubleshooting)? If it still doesn't work, please open a new issue or discussion (a lot of people turn off notifications for already closed issues).
