### ISSUE TITLE
drush 8.1.17 throws warning and ends abruptly

### ISSUE THREAD

**Issue by rvaddeman** [uselagoon/lagoon#521]
when accessing aliases with drush 8.1.17 version, drush throws the below warning and ends abruptly:

Could not load API JWT Token, error was: 'Load key "/home/.ssh/lagoon_cli.key": Permission denied,Permission denied (publickey).                                                               [warning]
A site alias is required. The way you call ssh command has changed to `drush @alias ssh`.                                                                                                        [error]
command terminated with exit code 1

Tested with drush 8.1.16 version, works fine!

**Comment by WICHEwebDev** [comment]
I am having the same problem on my Windows 10 machine with Drush 8.1.15. Strangely, it _was_ working, then the _@develop_ alias weirdly went missing and it started throwing this error:

Could not load API JWT Token, error was: 'Permission denied (publickey).                                                            [warning]Error: no alias record could be found for target @develop                                                                             [error][ut_pic_org]cli-drupal:/app$ drush sa
Could not load API JWT Token, error was: 'Permission denied (publickey).                                                            [warning]Could not load API JWT Token, error was: 'Permission denied (publickey).                                                            [warning]@none
@self
default

**Comment by rocketeerbkw** [comment]
I have an upstream PR open to fix this drush-ops/drush#3777

**Comment by rocketeerbkw** [comment]
Drush 8.2.0 was released today which fixes this issue. Upgrade by `composer update --with-dependencies drush/drush`
