### ISSUE TITLE
change solr deployment to recreate

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#533]
If solr is writing data at the time when a deployment happens, the new solr pod, though it appears to start correctly to OpenShift, will refuse to save data as it thinks the datadir is being shared by multiple servers, and thus not be accessible. Changing the deploy strategy to a `recreate` will prevent this.

**Comment by Schnitzel** [comment]
mhh but this is already the case?
https://github.com/amazeeio/lagoon/blob/2b4e03dbebd8bb716f6a6a677cb3ec9db81f05bd/images/oc-build-deploy-dind/openshift-templates/solr/deployment.yml#L34-L36

https://github.com/amazeeio/lagoon/blob/2b4e03dbebd8bb716f6a6a677cb3ec9db81f05bd/images/oc-build-deploy-dind/openshift-templates/solr/deployment.yml#L57-L58

**Comment by twardnw** [comment]
huh, the issue which presented itself today bahaved exactly like it used a rolling deployment 😒

**Comment by twardnw** [comment]
see #537
