### ISSUE TITLE
Nginx: Move $lagoon_environment_type into its own helper

### ISSUE THREAD

**Issue by ocean90** [uselagoon/lagoon#547]
Currently [`x-robots-header-development.conf`](https://github.com/amazeeio/lagoon/blob/eb2ed5a/images/nginx/helpers/x-robots-header-development.conf#L1-L2) defines `$lagoon_environment_type`. This makes the variable also available for other configs.
To make this more clear I suggest to move the variable declaration to its own file like `_lagoon_environment_type.conf`. I'm using an underscore here to ensure that file is loaded first via the current include rules ( `include /etc/nginx/helpers/*.conf;`). An alternative would be to use numbered prefixes like `00_lagoon_environment_type.conf`, `10_x-robots-header-development.conf`, ….

**Comment by Schnitzel** [comment]
we actually refactored nginx to use openresty which provides LUA, with this we can now use actual LUA scripts which are superior to the nginx ifs.
With that we're also setting the variable here via LUA: https://github.com/amazeeio/lagoon/pull/748

I do agree though that the order of the helpers are important, so I have another PR which changes them to be prefixed with numbers: https://github.com/amazeeio/lagoon/pull/760
