### ISSUE TITLE
Send `X-Robots-Tag: noindex, nofollow` also for autogenerated urls

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#609]
currently we add `X-Robots-Tag: noindex, nofollow` headers to all development environment, it would be good to also add these headers to autogenerated domains (like https://varnish-drupal-example-master.ch.amazee.io)

In order for this to work, the webserver (nginx) needs to know which domains are the autogenerated domains or which URL patterns are used for the auto generated domains

**Comment by twardnw** [comment]
@Schnitzel , any argument against carrying https://github.com/amazeeio/lagoon/blob/master/services/openshiftbuilddeploy/src/index.js#L170-L171 forward into the nginx container as an env var?

**Comment by twardnw** [comment]
After discussion, we will add the automatically generated routes to the configmap ( #688 ), then nginx can use that list to set the headers appropriately
