### ISSUE TITLE
Create MariaDB Alpine Base Image

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#61]

**Comment by Schnitzel** [comment]
must found: https://github.com/wodby/mariadb

**Comment by rtprio** [comment]
btw, wodby/mariadb compiles mariadb, which makes galera / cluster support troublesome.

**Comment by Schnitzel** [comment]
discussed with @rtprio 
we will fork the wodby/mariadb to create the lagoon/mariadb and try to add galera support to that (based on https://mariadb.com/kb/en/library/installating-galera-from-source/)

**Comment by Schnitzel** [comment]
moving to 0.8 as this actually does not prevent us from having beta sites launched

**Comment by Schnitzel** [comment]
this is done, thanks @rtprio for your hard work.
