### ISSUE TITLE
nginx-debug missing in new openresty 

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#615]
looks like the `nginx-debug` command is missing in the new openresty upstream nginx image that we're using.

would be great to get that back :)

**Comment by rtprio** [comment]
That _might_ be a problem; `nginx-debug` requires debug build options;   openresty doesn't seem to have a docker image with this, but they do have rpm/debs for it. They do not recommend using it in production. 

Do we want to copy openresty into our image, or create a openresty-alpine-debug image and create an image from that?

**Comment by tobybellwood** [comment]
Given the time past, closing this - can reopen if we ever need to re-create openresty-debug images
