### ISSUE TITLE
Alert from ElasticSearch entries?

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#618]
We would like to send some alerts from specific entries in ElasticSearch, do we use https://github.com/Yelp/elastalert or maybe we can forward specific entries to Prometheus and Alertmanager?

**Comment by Schnitzel** [comment]
Current plan:
We switched to OpenDistro with Lagoon 1.1.0, which includes an alerting feature that we would like to use. Unfortunately it is not integrated with the OpenDistro Security feature, which means each alert can be seen by everybody that has access to the Kibana. There is a ticket within OpenDistro that checks the working of this: https://github.com/opendistro-for-elasticsearch/alerting/issues/6

**Comment by rodrigoaguilera** [comment]
I am not familiar with what an "alert" would mean. Would it be possible to add the ability to notify on slack when a cronjob returns a non-zero exit code with this feature?

**Comment by tobybellwood** [comment]
As elasticsearch is no longer bundled into Lagoon, closing the issue here. Integrating Alerting with OpenSearch/ODFE would be a platform-specific implementation
