### ISSUE TITLE
Speed up cloning of Git submodules

### ISSUE THREAD

**Issue by Leksat** [uselagoon/lagoon#621]
We can use `--jobs` parameter with `git submodule update --init --recursive` to set the number of parallel git clone jobs. This can speed up the deployments.

Not sure which value is safe though. On my local I use `--jobs=6` and I never had an issue.

I can make a PR if this proposal sounds good to you.

**Comment by dasrecht** [comment]
Hi @Leksat 

Good idea, came across the issue of slow submodule checkouts too. Can you create a PR. We'll be happily review that!

**Comment by Leksat** [comment]
PR is ready. Test is green, but I have no idea if it tests the cloning of git submodules.

**Comment by Schnitzel** [comment]
yea, there is no real possibility to test this, so all good! merged, thanks a lot.
