### ISSUE TITLE
Custom Build Arguments definable via Lagoon API

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#640]
specifically for npm tokens

**Comment by erikrs** [comment]
Would this work: https://docs.openshift.com/container-platform/3.7/dev_guide/builds/build_inputs.html#using-secrets-during-build and adding it to the Lagoon BuildConfig

**Comment by Schnitzel** [comment]
Unfortunately it's a bit more complex as the Secrets are mounted into the Build Config and the Build Config is overwritten by Lagoon on every deploy so we would need to find a way to have the Build Config more persistent. I'm researching how we could do this.

**Comment by Schnitzel** [comment]
this will be solved by https://github.com/amazeeio/lagoon/issues/694
