### ISSUE TITLE
Store secrets inside git projects

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#65]
- Provide clients possibility to save secrets encrypted inside their git repository

Current idea:
- create for each Lagoon Project an OpenShift Project which has a TLS Private Key
- Allow clients via the ssh wrapper and cli container to encrypt environments with that TLS private key
- decrypt secret during buildtime and inject it into openshift project as regular secrets

**Comment by derpaschi** [comment]
@Schnitzel Would love to have the possibility of encrypted secrets. We don't like to store keys/secrets in plain in our git repositories. 👌🏻

**Comment by tobybellwood** [comment]
https://github.com/bitnami-labs/sealed-secrets can store encrypted secrets in git, and only the controller can decrypt

**Comment by smlx** [comment]
I believe Hashicorp Vault implements the system described in this issue:
https://learn.hashicorp.com/vault/encryption-as-a-service/eaas-transit

**Comment by tobybellwood** [comment]
I think we've got better ways to handle secrets now?
