### ISSUE TITLE
check if the HorizontalAutoscaler could kill running nodejs/nginx requests

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#653]

**Comment by christophasam** [comment]
Maybe its a similar issue what happens on kubernetes while stating the pods: https://github.com/kubernetes/kubernetes/issues/33674

**Comment by smlx** [comment]
Is this issue related to Lagoon user workloads? Or Lagoon Core/Remote service components?

**Comment by tobybellwood** [comment]
CLosing - unsure if it's still an issue

**Comment by smlx** [comment]
I think this issue is the nodejs version of https://github.com/uselagoon/lagoon-images/pull/445

Not sure what nodejs does when it receives a SIGTERM. It might gracefully drain in-flight requests before exiting by default?

**Comment by smlx** [comment]
Looks like [node doesn't exit gracefully](https://stackoverflow.com/a/65679246) by default, but you [can exit gracefully at the application level](https://stackoverflow.com/a/40321400).
