### ISSUE TITLE
PR Titles are not properly escaped

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#661]
```
"LAGOON_PR_BASE_BRANCH":"develop", "LAGOON_PR_TITLE":"Revert "Merge branch '\''feature/66-dpc_db_sync_bug'\'' into '\''develop'\''""}}'
Error from server: invalid character 'M' after object key:value pair
```

Basically the PR title having an `"` in it causes the deploy to fail.

**Comment by Leksat** [comment]
For the record, and to make this issue searchable: I encountered this bug when made a git commit with double quotes in its message.

UPD: Double checked, and, yeah, a commit message with double quotes works fine. It's only about the PR title.
