### ISSUE TITLE
logstash haproxy grok templates do not define any types

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#674]
We are using the logstash haproxy parsing templates which are bundled with logstash:
https://github.com/logstash-plugins/logstash-patterns-core/blob/master/patterns/haproxy

unfortunately they do not define any types, so every field is indexed as a string, which is not good for dashbaords and stuff.

There is an issue in logstash: https://github.com/logstash-plugins/logstash-patterns-core/issues/83

and an example file that would fix this.
https://gist.github.com/SamSaffron/0bcbcdcf16e84accd4d0

Idea is to replace the default grok template with a custom one like in the gist

**Comment by smlx** [comment]
Closing this as it's fixed in the lagoon-logging chart.

https://github.com/amazeeio/lagoon/blob/master/charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml#L66
