### ISSUE TITLE
Figure out a way on how to run the auth-ssh on Port 22

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#68]
With OpenShift we cannot expose the Port 22, it would need to be something at 30000+
It would be awesome to have some way to run the auth-ssh server on port 22

**Comment by dasrecht** [comment]
Cleaning up issues:
@Schnitzel currently we go with 32222 as default. Ok to close?

**Comment by Schnitzel** [comment]
yes 3222 works
