### ISSUE TITLE
Set up Jenkins to run Jest tests

### ISSUE THREAD

**Issue by karlhorky** [uselagoon/lagoon#680]
Often the Jest tests break, because they are not automatically run anywhere right now.

Let's integrate the Jest tests in  into our Jenkins CI pipeline, so that the failing statuses show in pull requests and commits:

- `cli`
- `node-packages/commons`
- `services/api`
- `services/webhook-handler`

**Comment by karlhorky** [comment]
Additionally, we could consider checking Flow (and maybe even ESLint) errors in the pipeline to further ensure quality and avoid bugs.

**Comment by tobybellwood** [comment]
needs a rethink
