### ISSUE TITLE
Versioning for docker images

### ISSUE THREAD

**Issue by Leksat** [uselagoon/lagoon#681]
As a particular example, https://hub.docker.com/r/amazeeio/elasticsearch/ has only the `latest` tag. If I use it in `docker-compose.yml`, the Elasticsearch version can suddenly change on one day, and something can break. Would be good to stick at least to the major version.

As a possible versioning system, here are @Schnitzel's thoughts:
> probably more like `amazeeio/elasticsearch:6`
> and then also `amazeeio/elasticsearch:latest`
> and when there is a 7 we do `amazeeio/elasticsearch:7`
> and `amazeeio/elasticsearch:latest` is the same as `amazeeio/elasticsearch:7`

**Comment by rocketeerbkw** [comment]
@Leksat is this addressed with the recent image version additions in https://github.com/amazeeio/lagoon/releases/tag/v0.21.0?

**Comment by dasrecht** [comment]
closed due to inactivity
