### ISSUE TITLE
Varnish looses backend connection if service ip changes

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#682]
**Describe the bug**
As soon as the service ip of nginx (or any service running behind varnish) is changed varnish looses the connection as the dns lookup is done just once during vcl load (https://varnish-cache.org/lists/pipermail/varnish-misc/2016-May/024952.html)

🎉 props to M. Hutter from VSHN for finding this issue.

**To Reproduce**
1. Visit site behind varnish
2. recreate nginx service (this will trigger an ip change)
3. visit a non-cached site
4. you should get a backend-error from varnish

**Expected behavior**
Varnish does not loose connection

**Comment by Schnitzel** [comment]
looks like https://github.com/nigoroll/libvmod-dynamic would solve that

**Comment by Schnitzel** [comment]
learn more https://info.varnish-software.com/blog/truly-dynamic-backend-definition-varnish
