### ISSUE TITLE
Lagoon Tug exposes URLs of deployments not belonging to the project

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#683]
**Describe the bug**

Sucessful Tug deployments display urls of the last deployment that was run. This should not happen as it has the possibility to expose other projects to customers using Lagoon Tug

**To Reproduce**
Trigger Lagoon Tug Deployment

**Expected behavior**
No URLs are shown for tug deployments.

**Screenshots**
<img width="594" alt="slack_-_amazee_io" src="https://user-images.githubusercontent.com/391732/46873719-8a15ae80-ce37-11e8-92d6-00806fe5b410.png">

**Additional context**

**Comment by dasrecht** [comment]
That issue lead me straight trough the whole deploy stack.

The URLs seem to come from here:
https://github.com/amazeeio/lagoon/blob/master/services/openshiftbuilddeploymonitor/src/index.js#L181-L191

In the environments above there was no `lagoon-env` available because there were no domains defined yet.

As we're already exiting early due to a tug deployment (https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L169-L178) we don't reach the condition that creates the `lagoon-env` (https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L360-L373) 

**Mitigation**
It can and has been mitigated for affected customers by creating a config-map with the name `lagoon-env`

```
apiVersion: v1
data:
  LAGOON_ROUTE: 'https://not-for-your-eyes.com'
  LAGOON_ROUTES: 'https://not-for-your-eyes.com'
kind: ConfigMap
metadata:
  name: lagoon-env
```

This has been applied to all affected customers.

**Todo**

- [ ] Make sure if there's no lagoon-env defined we don't send out the result of the last promise in `openshiftbuilddeploymonitor`

**Comment by tobybellwood** [comment]
Lagoon Tug is deprecated in Lagoon 2
