### ISSUE TITLE
Documentation - example repo strategy

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#684]
Currently we have a several places where example code is stored. This is hard to maintain and causes also a lot of confusion to developers who want to use lagoon.

- Drupal Example https://github.com/amazeeio/drupal-example
- Wordpress Example https://github.com/amazeeio/wordpress-example
- Drupal Examples in the Lagoon Repository https://github.com/amazeeio/lagoon/tree/master/docs/using_lagoon/drupal

Let's discuss a strategy how we move forward with this.

**Comment by dasrecht** [comment]
My take on it:

Move the Drupal Example into seperate github repositories and remove the code from the lagoon repository (as lagoon should not care too much about what's actually hosted on it).

Having a Documentation page which shows where Example code lives - This also enables us to list third party repos as they become available.

As for the wordpress-example repository I keep it updated and make sure it deploys. We also have customers contributing back to it.

I believe that having the seperate github repositories helps a lot as we keep the foundation of it updated at all times as we also use it to demo the platform sometimes. (this is not possible with the code stored in the lagoon repo)

**Comment by ChandeepKhosa** [comment]
Great idea 👏

**Comment by tobybellwood** [comment]
all under https://www.github.com/lagoon-examples org now
