### ISSUE TITLE
Blackfire integration

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#69]
- install blackfire php module by default into the php-fpm image, disabled by default and enable as soon as `BLACKFIRE_SERVER_ID` and `BLACKFIRE_SERVER_TOKEN` env variables are existing
- documentation

**Comment by twerthmueller** [comment]
Some plans to support that soon, because we will profiling some projects to optimize the performance?

**Comment by twerthmueller** [comment]
How to install it https://github.com/amazeeio/lagoon/wiki/Blackfire-integration

**Comment by dasrecht** [comment]
Blackfire Integration for containers is implemented as comment of @twerthmueller . Supporting blackfire for the cli will be tricky. 

As the issue has been sitting around for a while feel free to reopen it if the cli tracing is still a pressing issue.
