### ISSUE TITLE
Allow ENV variables to be defined for Projects and Enviornments

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#694]
The idea of this is, that via the Lagoon API there is the possibility to define an arbitrary amount of ENV variables either per Project or per Environment.

AC;
- [x] Env Variables are filled in the `lagoon-env` configmap of the environment.
- [x] If the same env variable is defined in the project and the environment, the one from the environment is used.
- [x] Additionally all defined Env variables are also exposed as `build-arg` during a Docker Build and can be consumed by the Docker Build

**Comment by Schnitzel** [comment]
I tried to work on this, but realized that I struggle with the concept of arbitrary data within the GraphQL API.

There is a JSON Scalar type for GraphQL: https://github.com/taion/graphql-type-json which we could use, but this means that the client is responsible that if you update the env variables that current existing env variables are sent as well, or they are deleted.

Then I thought about the possibility of just a EnvKeyValue store like: 

```
type Environment {
  envVariables: [EnvKeyValue]
}

type EnvKeyValue {
  name: String
  value: String
}
```

and just serialize all the defined envVariables as a JSON string within MySQL.
But then the question of getting and setting these env variables came up, maybe via

```
mutation addEnv {
  addEnvVariableToProject(input:{id:6, variable:{key:"variablekey", value:"variablevalue"}}) {
    id
  }
}
```

**Comment by rocketeerbkw** [comment]
PR #699 is ready for review to fix this issue
