### ISSUE TITLE
Trying to run Make tests on VirtualBox getting below error

### ISSUE THREAD

**Issue by siva2krish** [uselagoon/lagoon#702]
**Describe the bug**
Trying to install Lagoon in a Cloud VM based on Centos7 installed VirtualBox on top of it and running minishift  to run lagoon by using lagoon commands 

https://lagoon.readthedocs.io/en/latest/developing_lagoon/

**issue**

snpadmin@AmazeeHelm-CentOSVM lagoon]$make minishift && make tests 
[snpadmin@AmazeeHelm-CentOSVM lagoon]$ make tests
eval $(./local-dev/minishift/minishift --profile lagoon oc-env); \
oc login --insecure-skip-tls-verify -u developer -p developer $(cat minishift):8443; \
oc whoami -t | docker login --username developer --password-stdin $(cat minishift):30000
Cannot find the OpenShift client binary.
Make sure that OpenShift was provisioned successfully.
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-public
    kube-system
  * myproject
    openshift
    openshift-infra
    openshift-node

Using project "myproject".
Error response from daemon: Get https://192.168.99.100:30000/v2/: http: server gave HTTP response to HTTPS client
make: *** [minishift/login-docker-registry] Error 1

**Comment by siva2krish** [comment]
After Adding insecure docker registry able to resolve the above error  

After executing make tests again  all the required images are building at the end deployment failing showing the below error in my console 

-----Issue log--------

TASK [REMOTE SHELL - POST rest2task /remove with project ci-features and branch remoteshell to http://rest2tasks:3000] ***
ok: [localhost]

PLAY [REMOTE SHELL - check if site for ci-features does not exist anymore] *****

TASK [REMOTE SHELL - Check if URL http://ci-features.remoteshell.192.168.99.100.xip.io returns with resturn code 503] ***


after failing multiple times ci-features-remoteshell build is deleting in open-shift console.

fatal: [localhost]: FAILED! => {"attempts": 20, "changed": false, "content": "", "msg": "Status code was -1 and not [503]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://ci-features.remoteshell.192.168.99.100.xip.io"}

**Comment by ccjjmartin** [comment]
I got the same error and decided to run a different test which also failed.  Eventually came across a log that seems to indicate this is a certificate issue:

`time="2019-01-28T06:59:17Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get https://docker-registry.default.svc:5000/v2/:  http: server gave HTTP response to HTTPS client"`

When I access the console I get a warning from the browser about the certificate being untrusted.

Went back and accessed the failing build for the features test which also showed:
```
time="2019-01-28T06:53:03Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get https://docker-registry.default.svc:5000/v2/:  http: server gave HTTP response to HTTPS client"
--
  | time="2019-01-28T06:53:03Z" level=info msg="Error logging in to v1 endpoint, trying next endpoint: Get https://docker-registry.default.svc:5000/v1/users/:  http: server gave HTTP response to HTTPS client"
  | Get https://docker-registry.default.svc:5000/v1/users/:  http: server gave HTTP response to HTTPS client
```

The log file starts with:
```
could not connect to docker-host.lagoon.svc, trying fallback of docker-host.default.svc
--
  | could not connect to docker-host.default.svc

```

**Comment by ccjjmartin** [comment]
Actually, this looks like an upstream issue: https://github.com/openshift/origin/issues/16097

Something to do with /etc/resolv.conf not being set right within the containers.

Looks like this is mentioned in the troubleshooting section of the docs: https://lagoon.readthedocs.io/en/latest/developing_lagoon/#troubleshooting

**Comment by ccjjmartin** [comment]
Following the directions in the troubleshooting section of the docs and looking over the makefile I was able to get my docker-host running (wasn't before).  The executables you will need are found in ~/.minishift/cache/oc/v3.9.0/<os>/oc and <lagoon path>/local-dev/minishift/minishift

Once my docker-host was actually running with the recommended search settings in /etc/resolv.conf I was able to see that the pod is now running as opposed to failed to build but the test is still failing.

**Comment by tobybellwood** [comment]
make minishift is deprecated in Lagoon 2
