### ISSUE TITLE
Alerting from Lagoon Monitoring

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#73]
In https://github.com/amazeeio/lagoon/issues/72 we send service logs to elasticsearch, find a way on how to alert from that

**Comment by Schnitzel** [comment]
x-pack trial here: https://www.elastic.co/downloads/x-pack

**Comment by twardnw** [comment]
Currently our primary concern is monitoring the connection between any service and rabbitmq. As each service does some internal queueing of message, it is tolerable for an individual service to be missing it's connection for a few minutes, and then trigger an alert. In the event of multiple services missing their connection, an alert should be triggered as soon as that condition is seen.
