### ISSUE TITLE
API: Loading users for a project does not show them if they have no ssh key

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#745]
**Describe the bug**
When displaying the users for a project via 

```
query singleProject {
  projectByName(name: "drupal-example") {
    users {
      id
    }
  }
}
```

the user is not shown if the user has no ssh key assigned

**Expected behavior**
users are shown no matter if they have an ssh key or not

**Comment by rocketeerbkw** [comment]
Found the same bug when querying users from a Customer type, so fixed both cases.

```graphql
query allCustomers {
  allCustomers {
    users {
      id
    }
  }
}
```
