### ISSUE TITLE
Users with only access to Projects and no Customers cannot use Remote Shell (SSH)

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#746]
**Describe the bug**
Probably because of 
https://github.com/amazeeio/lagoon/blob/44f356fd6958bfc3b540bc11b95d896c47597a0a/services/api/src/routes/keys.js#L34
only ssh keys of customers are loaded and not just all users.
So if a user has only access to projects directly but not any customer access via SSH is not allowed

**Expected behavior**
Users with just projects assigned should also be able to use SSH

**Comment by rocketeerbkw** [comment]
I was able to reproduce and fix/test this locally
