### ISSUE TITLE
Save logs of Cronjobs

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#75]
Find system to save logs of Cronjobs implemented in https://github.com/amazeeio/lagoon/issues/74

**Comment by rtprio** [comment]
@Schnitzel go-cron seems to only log to standard out. 

Does it make sense to use some means to redirect the job output, and then post that to a lagoon service which posts it to S3?

**Comment by Schnitzel** [comment]
yes, my idea would be to output the logs of the cronjobs via the https://github.com/amazeeio/lagoon/blob/master/images/commons/lagoon/cronjob.sh file and send it to lagoon somehow, while on lagoon side there is a service that catches the cronjob and puts the cronjob logs into elasticsearch.
hint: we are gonna save the build logs in the future in elasticsearch and not s3 anymore, Brandon implemented that here already: https://github.com/amazeeio/lagoon/blob/develop/services/openshiftbuilddeploymonitor/src/index.js#L246
(basically it saves the build log as a `lagoon-log` and at the same time also uploads them to s3, the s3 part will be removed as soon as the logs can be visited via the lagoon ui)
