### ISSUE TITLE
Implement modular nginx config overrides

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#76]
Instead of telling developers to overwrite the whole nginx config if they just need to change a small piece of the config (like blocking IPs, special redirects, etc.), the main nginx config should include some files in a known directory.

**Comment by twardnw** [comment]
How many places in the config files should we have this set up for? So far thinking:
- server_first
- server_last
- location_first
- location_last

Should this just be limited to the drupal image, making the assumption that folks who use the base nginx image are going to be doing custom things anyway and won't need a helper like this?

**Comment by rtprio** [comment]
how does location_pre and location_post sound?

**Comment by twardnw** [comment]
mmm, that would make me expect the include to come before or after the location directive, currently it is the first and last lines inside the directive

**Comment by twardnw** [comment]
PR #105 opened

**Comment by Schnitzel** [comment]
mhh also not sure about the `first` and `last`.
nginx puppet uses `append` and `prepend`: https://github.com/voxpupuli/puppet-nginx
maybe thats more common? What do you think @rtprio @twardnw ?

**Comment by twardnw** [comment]
I feel ok about `append` and `prepend`
