### ISSUE TITLE
UI: Ability to delete environments from UI

### ISSUE THREAD

**Issue by thom8** [uselagoon/lagoon#770]
Due to being restrictions in place for the number of environments a project can have it would be useful to be able to delete an environment via the UI without having to close a PR or remove a branch.

It would also be be a good idea to include a confirmation step to ensure environments aren't accidentally removed and require a restore from backup to retrieve any environment specific data.

**Comment by Schnitzel** [comment]
currently it is only possible to delete environments via rest2tasks, this is a bit insecure and also we want to get rid of `rest2tasks` anyway.

Therefore 
- refactor the GraphQL method `deleteEnvironment()` to actually create the deleteTask for OpenShiftRemove (like rest2tasks currently does).
- remove the `/delete` endpoint of rest2tasks
- add a UI system to delete environments (something where you have to enter the environment name again)
