### ISSUE TITLE
Implement drush role for api

### ISSUE THREAD

**Issue by ryyppy** [uselagoon/lagoon#8]
For Drush we need to find a new role that allows READ access to graphql queries like this one:

```
{
  siteGroup:siteGroupByName(name: "amazee_io") {
  gitUrl
    slack {
      webhook
      channel
      informStart
      informChannel
    }
    sites {
      siteName
      siteBranch
      siteEnvironment
      siteHost
      serverInfrastructure
      serverIdentifier
      serverNames
      deployStrategy
      webRoot
      domains
      jumpHost
    }
  }
}
```

I'm perfectly fine with generating one token with a long lifetime which is then hardcoded in here: https://github.com/amazeeio/lagoon/blob/master/helpers/drush-alias/web/aliases.drushrc.php.stub, we will over time slowly convert drush calls to real authed calls via the cli, so it's just a temporary solution.

UPDATE:

For now, our credential system is not capable of attribute-based read permissions... so we will limit the `drush` role to only access Site / SiteGroup information. Access Client information will be denied.

**Comment by ryyppy** [comment]
Ready for testing

**Comment by Schnitzel** [comment]
tested, deployed, launched. thanks!
