### ISSUE TITLE
foreign key need to be added

### ISSUE THREAD

**Issue by markxtji** [uselagoon/lagoon#802]
in table `user_ssh_key`, `project_user`,`customer_user`, foreign keys need to be created so that relationship can be created correctly.

otherwise the sshkey/project/customer can be mapped to an un-existing user.

And triggers may also need to be created if they haven't been created.

**Comment by Schnitzel** [comment]
@rocketeerbkw can you have a look at this?

**Comment by seanhamlin** [comment]
I believe with the introduction of Keycloak, these SQL tables are no longer relevant.
