### ISSUE TITLE
Add ability for tasks to store artifacts long-term

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon#805]
When a user runs a task that results in some kind of artifact (e.g., sql dump), we need some way for the user to have access to said artifact.

Tasks are run on ephemeral pods, so the current way to "save" files is to put in in a path mounted to a PV. But this still doesn't give non-technical users the ability to access the files.

We need a system to store artifacts that meets at least the following criteria:

- Flexible enough to store anything (a file, multiple files, etc)
- Doesn't leak storage credentials to task pod
- Tracks where the artifact was saved, how to retrieve it, and what task it was created from
- Ultimately allows access to artifacts from the UI

**Comment by Schnitzel** [comment]
all our Lagoons have currently access to an S3 compatible storage system, so we could save the files in S3 and have Lagoon just play broker between them (allow for services to upload files and then server the files from S3 with an S3 proxy which will handle the authentication)
