### ISSUE TITLE
Prometheus/Grafana with Lagoon

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#817]
We have a Prometheus/Grafana running for some of our customers. This ticket is to bring the code from these installations into Lagoon:

Things to define:
- How do we run the Prometheus Operator? Some clusters maybe already have a prometheus operator running, so we probably should from a Lagoon point of view expect that the Prometheus Operator is already there?
- If a cluster has no Prometheus Operator yet, we should write a short documentation on how to get the Operator running (maybe even have a Repo for it)

**Comment by eskp** [comment]
Hey @Schnitzel, some docs already exist in our `prometheus-chart` repo. Happy to talk on where we can take them from here.

**Comment by Schnitzel** [comment]
discussed in the sync meeting:
- Split up the documentation of the installation into 3 Parts:
1. Prerequisite: Tiller
2. Prerequisite: prometheus operator
3. Installation of Prometheus/Grafana
- document how to actually `Configure Prometheus to scrape the above`
- copy over all sensible things from https://github.com/amazeeio/govcms-ops/blob/master/prod/values.yaml to https://github.com/amazeeio/prometheus-chart/blob/master/values.yaml (do not copy custom dashboards)
- add basic auth in front of prometheus/alertmanager via nginx
- grafana disable anonymous access

**Comment by eskp** [comment]
> - [x] Split up the documentation of the installation into 3 Parts:
> - [x] 1. Prerequisite: Tiller
> - [x] 2. Prerequisite: prometheus operator
> - [x] 3. Installation of Prometheus/Grafana
> - [x] document how to actually `Configure Prometheus to scrape the above`
> - [x] copy over all sensible things from https://github.com/amazeeio/govcms-ops/blob/master/prod/values.yaml to https://github.com/amazeeio/prometheus-chart/blob/master/values.yaml (do not copy custom dashboards)
> - [x] add basic auth in front of prometheus/alertmanager via nginx
> - [x] Grafana disable anonymous access

**Comment by eskp** [comment]
Added nginx proxy with basic auth docs.

**Comment by tobybellwood** [comment]
Lagoon won't be including prometheus/grafana - this is in the scope of the cluster management.
