### ISSUE TITLE
environment-specific env vars in API are not added to environment

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#831]
After adding env vars to an environment via the API, those env vars are not actually being made available for use.

steps to reproduce:
use addEnvVariable mutation to add a env var to an environment
```
mutation{
  addEnvVariable(input:{
    type:ENVIRONMENT
    typeId:390
    scope:RUNTIME
		name:"SECRET"
    value:"mysecret"
  }){
    id
  }
}
```
redploy that environment
check environment variables

**Comment by bryangruneberg** [comment]
Can confirm for project "alba" as well
