### ISSUE TITLE
UI/API to check if newest Images are running

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#844]
Services deployed into Lagoon are only using the newest upstream images if they actually trigger a redeployment. This could lead to situations where the services use quite an old version of the image and with that also security issues.

We already have a system in the Lagoon API which adds a list of all service names that are deployed to each environment.
We could enrich this information during the deployment with the version number of the services (probably from a new label of the image that is deployed? or somehow different) and then compare that with the newest published lagoon version, if it is different we can show that in the UI
Also add a system that can figure out if the customer changed something of the Docker Images or uses custom yaml templates.

**Comment by tobybellwood** [comment]
Collecting the upstream image version is now part of the `facts` subsystem
