### ISSUE TITLE
No Releasenotes for the past few versions

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#854]
**Describe the bug**
There seem to be no release notes after version 0.16.1

**Expected behavior**
Every release has a release note

**Comment by dasrecht** [comment]
As discussed during our Workshop we'll implement a PR Template which needs a ChangelogEntry that can be aggregated for the future releases

**Comment by Schnitzel** [comment]
wrote release nodes for v0.19.1: https://github.com/amazeeio/lagoon/releases/tag/v0.19.1

**Comment by dasrecht** [comment]
Fabulous! Thanks a lot. I'll also work on adding the PR template to make creating the releasenotes easier.
