### ISSUE TITLE
Development Environment Nginx Headers

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#86]
Development Environments should have some special headers (x-robots, etc.)
we need a system that automatically injects them (probably via LUA?)

**Comment by Schnitzel** [comment]
Infortunately there is no nginx:alpine with LUA, so I needed to do it without it, will check with maintainer if they are interested in a LUA version

**Comment by twardnw** [comment]
https://github.com/nginxinc/docker-nginx/issues/213

**Comment by Schnitzel** [comment]
so I found a way to implement this without the need of LUA.
But also in case we ever want LUA, we could use openresty, which is basically nginx bundled with lua (and a couple of other things, which is the reason that we don't wanna switch to it completely as it is probably too much)
