### ISSUE TITLE
Xdebug entrypoints does not have rights to use `ping` and therefore fails

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#863]
we start the local environment with a non-root user now:
https://github.com/amazeeio/drupal-example/blob/d4705750de8c583b5b620bb79e964ddb352f8d02/docker-compose.yml#L23-L26

which causes:
https://github.com/amazeeio/lagoon/blob/a7eb61cf42e4fe460fe694d3149e66b794e32feb/images/php/fpm/entrypoints/60-php-xdebug.sh#L6
to not work:
```
$ ping docker.for.mac.localhost                                                                                                                                                      
PING docker.for.mac.localhost (192.168.65.2): 56 data bytes                                                                                                                                                 
ping: permission denied (are you root?)
```

**Comment by smlx** [comment]
This was fixed in 69aff04ffa15f851fd7ac5bebb4ca97f5de8673e.
