### ISSUE TITLE
Raise timeouts for project removal

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#877]
**Describe the bug**
When a branch or PR is removed there are a lot of error messages currently. 
This is because our expectation is that we only terminate containers (which is pretty fast) as we also have databases that are provisioned via service catalog the decomission can take longer - even up to a few minutes

**To Reproduce**
1. create branch
2. wait till environment is fully started and database has been provisioned
3. remove branch

**Expected behavior**
Timeouts are set to accomodate slow removals - which will lead to less errors casted towards the ci channels.

**Screenshots**
<img width="697" alt="screenshot 2019-02-01 15 29 43" src="https://user-images.githubusercontent.com/391732/52128978-a9c72180-2636-11e9-9b2c-a5c1d72d1ada.png">

**Comment by dasrecht** [comment]
This also happens for environments which don't have pullrequests enabled

**Comment by twardnw** [comment]
Per discussion, rather than raising the timeouts, we don't need to announce the retry, just failure.
