### ISSUE TITLE
Docker image source is hard to track down

### ISSUE THREAD

**Issue by fago** [uselagoon/lagoon#881]
**Describe the bug**
- It's hard to track down how docker images are built.
- Besides that it would aid transparency.

**To Reproduce**
1. When you have some docker issues and you want to track down the source of the problem, inspecting how the docker image works and which customizations it has is very helpful.

**Expected behavior**
I go to the docker hub, e.g. https://hub.docker.com/r/amazeeio/mariadb-drupal and I get some pointer to your build scripts.

**Comment by twardnw** [comment]
All the dockerfiles for each image are linked in our docs : https://lagoon.readthedocs.io/en/stable/using_lagoon/#dockerfiles

Will evaluate if there is a way the build process can send a link during updates/pushes

**Comment by AlexSkrypnyk** [comment]
I'll add to this - there is no versioning of the images. If there is an issue after release - it is not possible neither to download the old images nor to even know what that image had. And tracking changes in the build files of images is pretty hard.

**Comment by tobybellwood** [comment]
(what @alexdesignworks said) - at least if they could be tied to Lagoon releases (and version documented in the dockerfile build) we can better understand where they are coming from!

**Comment by Schnitzel** [comment]
@tobybellwood @alexdesignworks 
the next version of Lagoon (probably tomorrow) will start to have version numbers with the images!
see: https://github.com/amazeeio/lagoon/pull/930

**Comment by tobybellwood** [comment]
Closing - all images now have a `LAGOON_VERSION` env var which ties them to the published tags at Docker Hub
