### ISSUE TITLE
Make redis max memory usage configurable

### ISSUE THREAD

**Issue by fago** [uselagoon/lagoon#882]
It would be nice to have an environment variable for adjusting redis max memory usage.

**Comment by dasrecht** [comment]
This is already implemented via the environment variable `MAXMEMORY`

https://github.com/amazeeio/lagoon/blob/master/images/redis/conf/redis.conf#L7

**Comment by fago** [comment]
ha, thanks - that's working! I'll better track down your build files in future ;)
would be nice to have pointers to support variables in docs!

**Comment by dasrecht** [comment]
Will add that to the documentation near-time
