### ISSUE TITLE
Document best practices for using CloudFlare

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#907]
- Cloudflare Setup is documented
- Best Practices are documented
- Drupal Modules are published and documented

**Comment by ChandeepKhosa** [comment]
This would be awesome 👍

**Comment by tobybellwood** [comment]
Given we're now in the process of rolling out a fully integrated CDN+WAF solution ourselves :wink:, we won't be spending time on documenting Cloudflare - but community contributions :1st_place_medal: are welcome though?
