### ISSUE TITLE
Lagoon audit log - include user ID in logs of any actions preformed (via the AdminUI or GraphQL)

### ISSUE THREAD

**Issue by thom8** [uselagoon/lagoon#911]
To assist with debugging issues around the Admin UI it would be helpful to understand and filter on actions by a specific user ID.

Change request:
Update any logs of the Admin UI to include the user ID of the authenticated user.

**Comment by rocketeerbkw** [comment]
@thom8 the UI can only make changes via the API, if we add user meta info to all the lagoon logs (which show up in elasticsearch) is that enough? I don't think it would be possible right now to differentiate logs between someone using the UI to do something and someone using the API directly (GraphiQL, etc).

**Comment by Schnitzel** [comment]
could we add some meta information to the logs to safe where the request is coming from? It could just be a Header that is added by the Lagoon UI and that is then saved (of course that could be spoofed via using the GraphQL API directly, but I think that's ok)

**Comment by rocketeerbkw** [comment]
The api already knows the difference between a keycloak token and a lagoon generated one, so would could use that (currently only the UI uses keycloak tokens correct?). And keycloak even keeps track of which client requested the token, so we could use that info too. But currently, a user could take the token from the browser console and put it in graphiql directly, so it wouldn't be a secure way to differentiate.

**Comment by Schnitzel** [comment]
ok, yes let's do that then. 
In the end the most important thing is the Lagoon UID that did the request, the client is interesting, but not security related.

**Comment by seanhamlin** [comment]
Having the API (via GraphQL) logged in an audit trail would be great. In this particular case, we wanted to work out who deleted an environment variable in the API.

**Comment by bomoko** [comment]
This should have been addressed by https://github.com/uselagoon/lagoon/pull/2690

I think we can close this
