### ISSUE TITLE
Add the ability to override environment.type for all environments in .lagoon.yml

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon#912]
In https://github.com/amazeeio/lagoon/blob/077416462a08d38ed92c3069aad96cb864df0503/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L54 we can specify an override environment type per-environment - is there value in adding a catch all `*` or `all` to override for all environments, instead of listing each?

This would allow us to central control a single docker.compose.yml and allow variations to .lagoon.yml to override when needed?

**Comment by tobybellwood** [comment]
(i'm going to bump this as a reminder to talk about it again)

**Comment by tobybellwood** [comment]
Order of preference:
Env specific > default > docker_compose.yml

**Comment by simesy** [comment]
Yeah i've just noticed if I create a new environment definition, i have to repeat a bunch of stuff. .lagoon.yml looks really flexible at first but it wants to be kept simple. It would be crazy cool if you could do some yaml anchors or `extends` stuff like gitlab-ci.yml

**Comment by grahamethompson** [comment]
I would also like to see this!

**Comment by bomoko** [comment]
@tobybellwood I'm going to close this for now. If you would like us to reopen this, could we chat about both whether it's still relevant and what the rationale for it is?
