### ISSUE TITLE
Missing patches/.gitkeep for drupal8-composer-mariadb

### ISSUE THREAD

**Issue by dan2k3k4** [uselagoon/lagoon#934]
As the `Dockerfile.cli` in the `drupal8-composer-mariadb/` folder relies on copying a `patches/` folder, we need to ensure this folder exists to prevent failed deployments for missing folder.

**Comment by rocketeerbkw** [comment]
It looks like this was addressed by commenting out the patches folder copy by default https://github.com/amazeeio/lagoon/commit/f936f07f53f318a2e5d45202f67a2c247124383b

@dan2k3k4 do you think #935 is still needed?

**Comment by Schnitzel** [comment]
I would remove the `patches/.gitkeep` from the PR as we updated the `Dockerfile.cli`.
I would keep the removal of the documentation, as it's too detailed

**Comment by dan2k3k4** [comment]
@rocketeerbkw yeah, I think commenting out the patches line closes #935. As you can also reference patches by URL and therefore skip the patches directory entirely.
