### ISSUE TITLE
Add Kubernetes services

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#944]
There is currently:
- [x] openshiftbuilddeploy
- [x] openshiftbuilddeployQueue
- [x] openshiftbuilddeploymonitor
- [x] openshiftjobs
- [x] openshiftjobsmonitor
- [x] openshiftmisc
- [x] openshiftremove

which are the main services that has Lagoon to talk to OpenShift

We need to find a way for the same to talk to Kubernetes with either:
- Make them generic for OpenShift and Kubernetes (if possible)
- Create them as well for Kuberenetes

**Comment by justinlevi** [comment]
Most of the work for these has been done here:
https://github.com/amazeeio/lagoon/tree/feature/kubernetes-services


I'm going to jump on creating `openshiftjobs` && `openshiftjobsmonitor`
kubernetesjobs branch (WIP) - https://github.com/amazeeio/lagoon/tree/feature/kubernetesjobs

**Comment by rocketeerbkw** [comment]
kubernetesjobs finished in #1665
