### ISSUE TITLE
Source link on PR environments is incorrect for GitLab

### ISSUE THREAD

**Issue by kmbremner** [uselagoon/lagoon#948]
**Describe the bug**
When pull requests are enabled in Lagoon, and the git repo is on GitLab the "source" link shown on the Lagoon PR environment overview page is incorrect. It gives a 404 from GitLab when clicked.

**To Reproduce**
1. Create a MR in GitLab
2. Go to the PR Environment Overview page in Lagoon
3. Click on the link under the Source heading 
4. Get 404 error page on GitLab

**Expected behavior**
Clicking the link should take you to the MR page on GitLab.

**Screenshots**
![image](https://user-images.githubusercontent.com/6079282/54023618-52fcbc80-418d-11e9-9285-7789dfea2465.png)

![image](https://user-images.githubusercontent.com/6079282/54023634-5abc6100-418d-11e9-8898-12cefd9e6e5a.png)

![image](https://user-images.githubusercontent.com/6079282/54023643-61e36f00-418d-11e9-9520-14f2b30e36f5.png)

**Additional context**
The link in the CI channel of Rocket Chat is correct and does not give a 404.

**Comment by rocketeerbkw** [comment]
@kmbremner for your example can you provide what the correct gitlab link is?

**Comment by kmbremner** [comment]
@rocketeerbkw sure! The (working) link in rocket chat was https://gitlab.com/one_young_world/oyw-website-d8/merge_requests/34

**Comment by klonos** [comment]
After the recent update to 0.22.1, we see a `:` added before the GitLab group name in the source link. For example:

https://projects.govcms.gov.au/:sandbox/someproject/tree/master

...when it should have been:

https://projects.govcms.gov.au/sandbox/someproject/tree/master

**Comment by shreddedbacon** [comment]
@klonos I have raised #1066 to address the problem you are seeing

**Comment by tobybellwood** [comment]
fixed in #1066
