### ISSUE TITLE
Don't idle cli pods that have cronjobs 

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#949]
**Describe the bug**
currently cli pods of dev projects are idled - which leads to cronjobs not being ran

**To Reproduce**
1. create a project with a cronjob
2. wait for idler to idle cli pod
**Expected behavior**
cli pods that have cronjobs defined should not be idled which ensures crons run  correctly on development sites.

**Comment by kehh** [comment]
Or possibly use the cronjob entries to 'wake' them from idle?

**Comment by dasrecht** [comment]
We're thinking about moving to other means of running the cronjobs (we used the jobs of openshift earlier but had issues with it as 1 minute cronjobs were putting a lot of load onto the kubernetes cluster). Not idling the cli containers would be a intermediate step. As the cronjob is ran only when the container is running we can't wake them up easily.

**Comment by Schnitzel** [comment]
this will be fixed/implemented with https://github.com/amazeeio/lagoon/issues/1001
