### ISSUE TITLE
Investigate automatic dependency updates with dependencies.io

### ISSUE THREAD

**Issue by thom8** [uselagoon/lagoon#95]
dependencies.io is a way for automating the update of project dependencies.

For lagoon it could include [npm packages](https://github.com/amazeeio/lagoon/blob/master/package.json) --> https://www.dependencies.io/docs/collectors/js-npm/
& base images of a Dockerfiles --> https://www.dependencies.io/docs/collectors/dockerfile/

You can choose the action when updates are found - https://www.dependencies.io/docs/configuration/ this can be pinging a slack channel or actually creating a PR.

https://www.dependencies.io/

**Comment by tobybellwood** [comment]
This is already in place in https://github.com/uselagoon/lagoon-images and soon here
