### ISSUE TITLE
Curl broken again

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#962]
upstream php images have been updated and so they now include curl `7.64.0` which causes the issue in https://github.com/amazeeio/lagoon/issues/923 to happen again

**Comment by Schnitzel** [comment]
https://github.com/amazeeio/lagoon/commit/9f6a1308421ae4486c76bbbf19a7b39a3c47cfd8 installs a specific older version of curl, to prevent the issue from happening

**Comment by Schnitzel** [comment]
for people affected:
change the `FROM` in your `Dockerfile.cli` to:
`amazeeio/php:7.x-cli-drupal-v0.21.0`

replace the `7.x` with your php version already in `Dockerfile.cli`

**Comment by Schnitzel** [comment]
this is released: https://github.com/amazeeio/lagoon/releases/tag/v0.21.3

**Comment by Schnitzel** [comment]
Unfortunately just downgrading `curl` wasn't enough, we also need to downgrade `libcurl`:
https://github.com/amazeeio/lagoon/commit/38a3efa5242d606e715a8984b77fa99599884268

**Comment by dasrecht** [comment]
closing has been released in  https://github.com/amazeeio/lagoon/releases/tag/v0.22.0
