### ISSUE TITLE
When some tasks finish there is no signal back that the job is done

### ISSUE THREAD

**Issue by fjgarlin** [uselagoon/lagoon#965]
**Describe the bug**
When creating a DB backup using the task `drush sql-dump` the task never reports as finished in the task overview. When clicking on the task, there are no logs available but the file to be downloaded is there. It appears as `Active` everywhere.

**To Reproduce**
1. Go to a project. Select `prod` environment.
2. Click on `Tasks` and select `Generate database backup` and click on `Add task`
3. Then wait, and wait... after a few minutes if you click on the task the file will be available for downloading, but the task will appear as active

**Expected behavior**
When the backup is done, the task appears as active.

**Screenshots**
![Screenshot 2019-03-12 at 11 20 49](https://user-images.githubusercontent.com/898540/54192781-0977de80-44b9-11e9-86fd-2263f4b26687.png)

**Comment by tobybellwood** [comment]
This should no longer be an issue
