### ISSUE TITLE
do not require logs-db, logs2logs-db and logs-db-ui to run locally

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#968]
our nodejs services are not happy when the ELK stack is not running and is throwing errors constantly, this is coming from https://github.com/amazeeio/lagoon/blob/master/node-packages/commons/src/local-logging.js#L42-L48

Let's implement an env variable switch where locally we either:
- not try to connect to the ELK stack at all
- not throw any errors if we cannot talk to ELK

**Comment by tobybellwood** [comment]
In Lagoon 2, this is all optional for local-dev
