### ISSUE TITLE
Dashboard stuck in redirect loop in IE 11

### ISSUE THREAD

**Issue by Ahmedjabar** [uselagoon/lagoon#969]
**Describe the bug**
The dashboard UI gets stuck in a redirect loop when using IE 11. The console reports this error:
`IE 11Unhandled promise rejection TypeError: Object doesn't support property or method 'success'`

**To Reproduce**
1. Open the dashboard using IE11
2. Login to the dashboard
3. The page gets stuck in a redirect loop

**Expected behavior**
Either:
1. The dashboard loads as normal.
2. If a decision is made to not support IE 11, display a message.

**Comment by rocketeerbkw** [comment]
Confirmed errors in IE11. The error is thrown in all browsers but it looks like only IE11 stops processing altogether.

A number of other polyfills and the inifnite loop have been added in https://github.com/amazeeio/lagoon/pull/976 to fix IE11 errors, but this bug will have to wait for an upstream fix it looks like: https://github.com/keycloak/keycloak/pull/5946
