### ISSUE TITLE
Support for KVM on linux

### ISSUE THREAD

**Issue by ccjjmartin** [uselagoon/lagoon#983]
## Purpose:
- Support for KVM on linux

## Description:
- Currently through the makefile minishift is designed to work with virtualbox

## Performance notes:
- I am experiencing big improvements to performance by switching to KVM.  Running `make minishift` used to take about 20 minutes on virtualbox and it is now taking closer to 2-4 minutes on KVM (this may be a linux only thing)

## Issues:
- The main blocker from keeping this from going out right now is networking changes which are breaking tests.

**Comment by smlx** [comment]
This was fixed a while ago now :smile:
