### ISSUE TITLE
Tasks page unable to load: environmentByOpenshiftProjectName is undefined

### ISSUE THREAD

**Issue by HurricaneInteractive** [uselagoon/lagoon#987]
**Describe the bug**
I am trying to load the _tasks_ page for a project, but I am running into this error repeatedly, making it impossible to create backups.

**Expected behavior**
Error being displayed:
```
An unexpected error has occurred
TypeError: Cannot read property 'environmentByOpenshiftProjectName' of undefined
```

**Screenshots**
![Screen Shot 2019-03-25 at 4 11 59 pm](https://user-images.githubusercontent.com/25698413/54896728-a60a9980-4f19-11e9-9e2a-dad468d0a95a.png)

**Edit**
It seems to that the request is timing out constantly
![Screen Shot 2019-03-25 at 4 37 23 pm](https://user-images.githubusercontent.com/25698413/54897383-59748d80-4f1c-11e9-9125-9de922a50694.png)

**Comment by Schnitzel** [comment]
Discussed with @rocketeerbkw we will implement a better error handling, as the current error is rather confusing.
Also see https://github.com/amazeeio/lagoon/issues/961 which will make the overview logs task loading better.
