### ISSUE TITLE
Variable interpolation in CMD

### ISSUE THREAD

**Issue by AlexSkrypnyk** [uselagoon/lagoon#997]
**Describe the bug**
Running a `CMD` with a command that uses an environment variable does not interpolate it.
In `package.json`:
```
"scripts": {
  "storybook": "start-storybook -p ${STORYBOOK_PORT:-9001}",
}
```

In `Dockerfile`:
```
ENV STORYBOOK_PORT=300

CMD [ "/bin/sh", "-c", "npm run storybook" ]
```

OR
 
```
ENV STORYBOOK_PORT=3000

CMD [ "/bin/sh", "-c", "npm", "run", "storybook" ]
```

Results in `$STORYBOOK_PORT` always be an empty string.

**Comment by Schnitzel** [comment]
I think that would be a feature of `npm`/`nodejs` and not Lagoon.
I searched through the documentation of `package.json` and could not find anything that you can use the format `${}` to use env variables.

**Comment by AlexSkrypnyk** [comment]
@Schnitzel thank you for looking into this.

I noticed that this image has a custom entrypoint - could it be that it does not evaluate variables?

Interestingly that variables interpolation does work locally and in CI, but not in Lagoon.

**Comment by Schnitzel** [comment]
> I noticed that this image has a custom entrypoint - could it be that it does not evaluate variables?

the entrypoint is just a call to `exec` in a shell: https://github.com/amazeeio/lagoon/blob/master/images/commons/lagoon/entrypoints.sh#L15

> Interestingly that variables interpolation does work locally and in CI, but not in Lagoon.

Can you show me which command you run in CI and locally?
Because it might be the case that in CI and locally you are running in `bash`, while here you are running in `sh` which is not the same.

**Comment by AlexSkrypnyk** [comment]
so if `sh` is a POSIX, the this applies
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02

but then "double-quoting" results in literal interpretation 
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_02_03

So, it looks to me that
```
"scripts": {
  "storybook": "start-storybook -p ${STORYBOOK_PORT:-9001}",
}
```
is interpreted as literal `start-storybook -p ${STORYBOOK_PORT}`

I've tried to get an output of this specific case (tried to see this string in the output) but was not able to do so.

If it is indeed a matter POSIX `sh` - is it possible to replace it with `bash` for the entrypoint? (and it feels like a big ask, but I'm wondering what is the reason not to use `bash`)

**Comment by Schnitzel** [comment]
@alexdesignworks 
You can just change the CMD:
```
CMD [ "/bin/bash", "-c", "npm run storybook" ]
```
and then it's running is `bash`

**Comment by Schnitzel** [comment]
plus the reason to now use bash by default is that bash is not by default in the alpine upstream images and we want to keep the images as small and as upstreamy as possible.
